/*******************************************************************************
 * Copyright (c) 2020, 2020 IBM Corp. and others
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which accompanies this
 * distribution and is available at http://eclipse.org/legal/epl-2.0
 * or the Apache License, Version 2.0 which accompanies this distribution
 * and is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License, v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception [1] and GNU General Public
 * License, version 2 with the OpenJDK Assembly Exception [2].
 *
 * [1] https://www.gnu.org/software/classpath/license.html
 * [2] http://openjdk.java.net/legal/assembly-exception.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
 *******************************************************************************/
/*
 * This table is #included in a static table.
 * Only Function Pointers are allowed.
 */


#define BadILOpRVEvaluator unImpOpEvaluator 
#define aconstRVEvaluator aconstEvaluator
#define iconstRVEvaluator iconstEvaluator
#define lconstRVEvaluator lconstEvaluator
#define fconstRVEvaluator fconstEvaluator
#define dconstRVEvaluator dconstEvaluator
#define bconstRVEvaluator bconstEvaluator
#define sconstRVEvaluator sconstEvaluator
#define iloadRVEvaluator iloadEvaluator
#define floadRVEvaluator floadEvaluator
#define dloadRVEvaluator dloadEvaluator
#define aloadRVEvaluator aloadEvaluator
#define bloadRVEvaluator bloadEvaluator
#define sloadRVEvaluator sloadEvaluator
#define lloadRVEvaluator lloadEvaluator
#define irdbarRVEvaluator unImpOpEvaluator
#define frdbarRVEvaluator unImpOpEvaluator
#define drdbarRVEvaluator unImpOpEvaluator
#define ardbarRVEvaluator unImpOpEvaluator
#define brdbarRVEvaluator unImpOpEvaluator
#define srdbarRVEvaluator unImpOpEvaluator
#define lrdbarRVEvaluator unImpOpEvaluator
#define iloadiRVEvaluator iloadEvaluator
#define floadiRVEvaluator floadEvaluator
#define dloadiRVEvaluator dloadEvaluator
#define aloadiRVEvaluator aloadEvaluator
#define bloadiRVEvaluator bloadEvaluator
#define sloadiRVEvaluator sloadEvaluator
#define lloadiRVEvaluator lloadEvaluator
#define irdbariRVEvaluator unImpOpEvaluator
#define frdbariRVEvaluator unImpOpEvaluator
#define drdbariRVEvaluator unImpOpEvaluator
#define ardbariRVEvaluator unImpOpEvaluator
#define brdbariRVEvaluator unImpOpEvaluator
#define srdbariRVEvaluator unImpOpEvaluator
#define lrdbariRVEvaluator unImpOpEvaluator
#define istoreRVEvaluator istoreEvaluator
#define lstoreRVEvaluator lstoreEvaluator
#define fstoreRVEvaluator fstoreEvaluator
#define dstoreRVEvaluator dstoreEvaluator
#define astoreRVEvaluator lstoreEvaluator
#define bstoreRVEvaluator bstoreEvaluator
#define sstoreRVEvaluator sstoreEvaluator
#define iwrtbarRVEvaluator unImpOpEvaluator
#define lwrtbarRVEvaluator unImpOpEvaluator
#define fwrtbarRVEvaluator unImpOpEvaluator
#define dwrtbarRVEvaluator unImpOpEvaluator
#define awrtbarRVEvaluator unImpOpEvaluator
#define bwrtbarRVEvaluator unImpOpEvaluator
#define swrtbarRVEvaluator unImpOpEvaluator
#define lstoreiRVEvaluator lstoreEvaluator
#define fstoreiRVEvaluator fstoreEvaluator
#define dstoreiRVEvaluator dstoreEvaluator
#define astoreiRVEvaluator lstoreEvaluator
#define bstoreiRVEvaluator bstoreEvaluator
#define sstoreiRVEvaluator sstoreEvaluator
#define istoreiRVEvaluator istoreEvaluator
#define lwrtbariRVEvaluator unImpOpEvaluator 
#define fwrtbariRVEvaluator unImpOpEvaluator 
#define dwrtbariRVEvaluator unImpOpEvaluator 
#define awrtbariRVEvaluator unImpOpEvaluator 
#define bwrtbariRVEvaluator unImpOpEvaluator 
#define swrtbariRVEvaluator unImpOpEvaluator 
#define iwrtbariRVEvaluator unImpOpEvaluator 
#define GotoRVEvaluator gotoEvaluator
#define ireturnRVEvaluator ireturnEvaluator
#define lreturnRVEvaluator lreturnEvaluator
#define freturnRVEvaluator freturnEvaluator
#define dreturnRVEvaluator dreturnEvaluator
#define areturnRVEvaluator lreturnEvaluator
#define ReturnRVEvaluator returnEvaluator
#define asynccheckRVEvaluator unImpOpEvaluator 
#define athrowRVEvaluator unImpOpEvaluator 
#define icallRVEvaluator directCallEvaluator
#define lcallRVEvaluator directCallEvaluator
#define fcallRVEvaluator directCallEvaluator
#define dcallRVEvaluator directCallEvaluator
#define acallRVEvaluator directCallEvaluator
#define callRVEvaluator directCallEvaluator
#define iaddRVEvaluator iaddEvaluator
#define laddRVEvaluator laddEvaluator 
#define faddRVEvaluator faddEvaluator
#define daddRVEvaluator daddEvaluator
#define baddRVEvaluator iaddEvaluator 
#define saddRVEvaluator iaddEvaluator 
#define isubRVEvaluator isubEvaluator
#define lsubRVEvaluator lsubEvaluator 
#define fsubRVEvaluator fsubEvaluator
#define dsubRVEvaluator dsubEvaluator
#define bsubRVEvaluator isubEvaluator 
#define ssubRVEvaluator isubEvaluator 
#define asubRVEvaluator unImpOpEvaluator 
#define imulRVEvaluator imulEvaluator
#define lmulRVEvaluator imulEvaluator 
#define fmulRVEvaluator fmulEvaluator
#define dmulRVEvaluator dmulEvaluator
#define bmulRVEvaluator imulEvaluator 
#define smulRVEvaluator imulEvaluator 
#define idivRVEvaluator idivEvaluator
#define ldivRVEvaluator ldivEvaluator
#define fdivRVEvaluator fdivEvaluator
#define ddivRVEvaluator ddivEvaluator
#define bdivRVEvaluator idivEvaluator 
#define sdivRVEvaluator idivEvaluator 
#define iudivRVEvaluator iudivEvaluator 
#define ludivRVEvaluator ludivEvaluator 
#define iremRVEvaluator iremEvaluator
#define lremRVEvaluator lremEvaluator
#define fremRVEvaluator unImpOpEvaluator 
#define dremRVEvaluator unImpOpEvaluator 
#define bremRVEvaluator iremEvaluator 
#define sremRVEvaluator iremEvaluator 
#define iuremRVEvaluator iuremEvaluator 
#define inegRVEvaluator inegEvaluator
#define lnegRVEvaluator inegEvaluator
#define fnegRVEvaluator fnegEvaluator
#define dnegRVEvaluator dnegEvaluator
#define bnegRVEvaluator unImpOpEvaluator 
#define snegRVEvaluator unImpOpEvaluator 
#define iabsRVEvaluator iabsEvaluator
#define labsRVEvaluator labsEvaluator
#define fabsRVEvaluator fabsEvaluator
#define dabsRVEvaluator dabsEvaluator
#define ishlRVEvaluator ishlEvaluator
#define lshlRVEvaluator ishlEvaluator
#define bshlRVEvaluator ishlEvaluator 
#define sshlRVEvaluator ishlEvaluator 
#define ishrRVEvaluator ishrEvaluator
#define lshrRVEvaluator ishrEvaluator
#define bshrRVEvaluator ishrEvaluator 
#define sshrRVEvaluator ishrEvaluator 
#define iushrRVEvaluator iushrEvaluator
#define lushrRVEvaluator iushrEvaluator
#define bushrRVEvaluator iushrEvaluator 
#define sushrRVEvaluator iushrEvaluator 
#define irolRVEvaluator irolEvaluator
#define lrolRVEvaluator irolEvaluator
#define iandRVEvaluator iandEvaluator 
#define landRVEvaluator iandEvaluator 
#define bandRVEvaluator iandEvaluator 
#define sandRVEvaluator iandEvaluator 
#define iorRVEvaluator iorEvaluator 
#define lorRVEvaluator iorEvaluator 
#define borRVEvaluator iorEvaluator 
#define sorRVEvaluator iorEvaluator 
#define ixorRVEvaluator ixorEvaluator 
#define lxorRVEvaluator ixorEvaluator 
#define bxorRVEvaluator ixorEvaluator 
#define sxorRVEvaluator ixorEvaluator 
#define i2lRVEvaluator i2lEvaluator
#define i2fRVEvaluator i2fEvaluator 
#define i2dRVEvaluator i2dEvaluator 
#define i2bRVEvaluator l2iEvaluator
#define i2sRVEvaluator l2iEvaluator
#define i2aRVEvaluator unImpOpEvaluator 
#define iu2lRVEvaluator iu2lEvaluator
#define iu2fRVEvaluator unImpOpEvaluator 
#define iu2dRVEvaluator unImpOpEvaluator 
#define iu2aRVEvaluator unImpOpEvaluator 
#define l2iRVEvaluator l2iEvaluator
#define l2fRVEvaluator l2fEvaluator 
#define l2dRVEvaluator l2dEvaluator 
#define l2bRVEvaluator l2iEvaluator
#define l2sRVEvaluator l2iEvaluator
#define l2aRVEvaluator passThroughEvaluator
#define lu2fRVEvaluator unImpOpEvaluator 
#define lu2dRVEvaluator unImpOpEvaluator 
#define lu2aRVEvaluator passThroughEvaluator
#define f2iRVEvaluator f2iEvaluator 
#define f2lRVEvaluator f2lEvaluator 
#define f2dRVEvaluator f2dEvaluator 
#define f2bRVEvaluator unImpOpEvaluator 
#define f2sRVEvaluator unImpOpEvaluator 
#define d2iRVEvaluator d2iEvaluator 
#define d2lRVEvaluator d2lEvaluator 
#define d2fRVEvaluator d2fEvaluator 
#define d2bRVEvaluator unImpOpEvaluator 
#define d2sRVEvaluator unImpOpEvaluator 
#define b2iRVEvaluator b2iEvaluator
#define b2lRVEvaluator b2lEvaluator
#define b2fRVEvaluator unImpOpEvaluator 
#define b2dRVEvaluator unImpOpEvaluator 
#define b2sRVEvaluator unImpOpEvaluator 
#define b2aRVEvaluator unImpOpEvaluator 
#define bu2iRVEvaluator bu2iEvaluator
#define bu2lRVEvaluator bu2lEvaluator
#define bu2fRVEvaluator unImpOpEvaluator 
#define bu2dRVEvaluator unImpOpEvaluator 
#define bu2sRVEvaluator unImpOpEvaluator 
#define bu2aRVEvaluator unImpOpEvaluator 
#define s2iRVEvaluator s2iEvaluator
#define s2lRVEvaluator s2lEvaluator
#define s2fRVEvaluator unImpOpEvaluator 
#define s2dRVEvaluator unImpOpEvaluator 
#define s2bRVEvaluator unImpOpEvaluator 
#define s2aRVEvaluator unImpOpEvaluator 
#define su2iRVEvaluator su2iEvaluator
#define su2lRVEvaluator su2lEvaluator
#define su2fRVEvaluator unImpOpEvaluator 
#define su2dRVEvaluator unImpOpEvaluator 
#define su2aRVEvaluator unImpOpEvaluator 
#define a2iRVEvaluator unImpOpEvaluator 
#define a2lRVEvaluator passThroughEvaluator
#define a2bRVEvaluator unImpOpEvaluator 
#define a2sRVEvaluator unImpOpEvaluator 
#define icmpeqRVEvaluator icmpeqEvaluator
#define icmpneRVEvaluator icmpneEvaluator
#define icmpltRVEvaluator icmpltEvaluator
#define icmpgeRVEvaluator icmpgeEvaluator
#define icmpgtRVEvaluator icmpgtEvaluator
#define icmpleRVEvaluator icmpleEvaluator
#define iucmpltRVEvaluator iucmpltEvaluator
#define iucmpgeRVEvaluator iucmpgeEvaluator
#define iucmpgtRVEvaluator iucmpgtEvaluator
#define iucmpleRVEvaluator iucmpleEvaluator
#define lcmpeqRVEvaluator lcmpeqEvaluator
#define lcmpneRVEvaluator lcmpneEvaluator
#define lcmpltRVEvaluator lcmpltEvaluator
#define lcmpgeRVEvaluator lcmpgeEvaluator
#define lcmpgtRVEvaluator lcmpgtEvaluator
#define lcmpleRVEvaluator lcmpleEvaluator
#define lucmpltRVEvaluator lucmpltEvaluator
#define lucmpgeRVEvaluator lucmpgeEvaluator
#define lucmpgtRVEvaluator lucmpgtEvaluator
#define lucmpleRVEvaluator lucmpleEvaluator
#define fcmpeqRVEvaluator fcmpeqEvaluator 
#define fcmpneRVEvaluator fcmpneEvaluator 
#define fcmpltRVEvaluator fcmpltEvaluator 
#define fcmpgeRVEvaluator fcmpgeEvaluator 
#define fcmpgtRVEvaluator fcmpgtEvaluator 
#define fcmpleRVEvaluator fcmpleEvaluator 
#define fcmpequRVEvaluator fcmpequEvaluator 
#define fcmpneuRVEvaluator fcmpneuEvaluator 
#define fcmpltuRVEvaluator fcmpltuEvaluator 
#define fcmpgeuRVEvaluator fcmpgeuEvaluator 
#define fcmpgtuRVEvaluator fcmpgtuEvaluator 
#define fcmpleuRVEvaluator fcmpleuEvaluator 
#define dcmpeqRVEvaluator dcmpeqEvaluator 
#define dcmpneRVEvaluator dcmpneEvaluator 
#define dcmpltRVEvaluator dcmpltEvaluator 
#define dcmpgeRVEvaluator dcmpgeEvaluator 
#define dcmpgtRVEvaluator dcmpgtEvaluator 
#define dcmpleRVEvaluator dcmpleEvaluator 
#define dcmpequRVEvaluator dcmpequEvaluator 
#define dcmpneuRVEvaluator dcmpneuEvaluator 
#define dcmpltuRVEvaluator dcmpltuEvaluator 
#define dcmpgeuRVEvaluator dcmpgeuEvaluator 
#define dcmpgtuRVEvaluator dcmpgtuEvaluator 
#define dcmpleuRVEvaluator dcmpleuEvaluator 
#define acmpeqRVEvaluator unImpOpEvaluator 
#define acmpneRVEvaluator unImpOpEvaluator 
#define acmpltRVEvaluator unImpOpEvaluator 
#define acmpgeRVEvaluator unImpOpEvaluator 
#define acmpgtRVEvaluator unImpOpEvaluator 
#define acmpleRVEvaluator unImpOpEvaluator 
#define bcmpeqRVEvaluator unImpOpEvaluator 
#define bcmpneRVEvaluator unImpOpEvaluator 
#define bcmpltRVEvaluator unImpOpEvaluator 
#define bcmpgeRVEvaluator unImpOpEvaluator 
#define bcmpgtRVEvaluator unImpOpEvaluator 
#define bcmpleRVEvaluator unImpOpEvaluator 
#define bucmpltRVEvaluator unImpOpEvaluator 
#define bucmpgeRVEvaluator unImpOpEvaluator 
#define bucmpgtRVEvaluator unImpOpEvaluator 
#define bucmpleRVEvaluator unImpOpEvaluator 
#define scmpeqRVEvaluator unImpOpEvaluator 
#define scmpneRVEvaluator unImpOpEvaluator 
#define scmpltRVEvaluator unImpOpEvaluator 
#define scmpgeRVEvaluator unImpOpEvaluator 
#define scmpgtRVEvaluator unImpOpEvaluator 
#define scmpleRVEvaluator unImpOpEvaluator 
#define sucmpltRVEvaluator unImpOpEvaluator 
#define sucmpgeRVEvaluator unImpOpEvaluator 
#define sucmpgtRVEvaluator unImpOpEvaluator 
#define sucmpleRVEvaluator unImpOpEvaluator 
#define lcmpRVEvaluator lcmpEvaluator
#define fcmplRVEvaluator dcmplEvaluator 
#define fcmpgRVEvaluator dcmpgEvaluator 
#define dcmplRVEvaluator dcmplEvaluator 
#define dcmpgRVEvaluator dcmpgEvaluator 
#define ificmpeqRVEvaluator ificmpeqEvaluator
#define ificmpneRVEvaluator ificmpneEvaluator
#define ificmpltRVEvaluator ificmpltEvaluator
#define ificmpgeRVEvaluator ificmpgeEvaluator
#define ificmpgtRVEvaluator ificmpgtEvaluator
#define ificmpleRVEvaluator ificmpleEvaluator
#define ifiucmpltRVEvaluator ifiucmpltEvaluator
#define ifiucmpgeRVEvaluator ifiucmpgeEvaluator
#define ifiucmpgtRVEvaluator ifiucmpgtEvaluator
#define ifiucmpleRVEvaluator ifiucmpleEvaluator
#define iflcmpeqRVEvaluator iflcmpeqEvaluator
#define iflcmpneRVEvaluator iflcmpneEvaluator
#define iflcmpltRVEvaluator iflcmpltEvaluator
#define iflcmpgeRVEvaluator iflcmpgeEvaluator
#define iflcmpgtRVEvaluator iflcmpgtEvaluator
#define iflcmpleRVEvaluator iflcmpleEvaluator
#define iflucmpltRVEvaluator iflucmpltEvaluator
#define iflucmpgeRVEvaluator iflucmpgeEvaluator
#define iflucmpgtRVEvaluator iflucmpgtEvaluator
#define iflucmpleRVEvaluator iflucmpleEvaluator
#define iffcmpeqRVEvaluator unImpOpEvaluator 
#define iffcmpneRVEvaluator unImpOpEvaluator 
#define iffcmpltRVEvaluator unImpOpEvaluator 
#define iffcmpgeRVEvaluator unImpOpEvaluator 
#define iffcmpgtRVEvaluator unImpOpEvaluator 
#define iffcmpleRVEvaluator unImpOpEvaluator 
#define iffcmpequRVEvaluator unImpOpEvaluator 
#define iffcmpneuRVEvaluator unImpOpEvaluator 
#define iffcmpltuRVEvaluator unImpOpEvaluator 
#define iffcmpgeuRVEvaluator unImpOpEvaluator 
#define iffcmpgtuRVEvaluator unImpOpEvaluator 
#define iffcmpleuRVEvaluator unImpOpEvaluator 
#define ifdcmpeqRVEvaluator unImpOpEvaluator 
#define ifdcmpneRVEvaluator unImpOpEvaluator 
#define ifdcmpltRVEvaluator unImpOpEvaluator 
#define ifdcmpgeRVEvaluator unImpOpEvaluator 
#define ifdcmpgtRVEvaluator unImpOpEvaluator 
#define ifdcmpleRVEvaluator unImpOpEvaluator 
#define ifdcmpequRVEvaluator unImpOpEvaluator 
#define ifdcmpneuRVEvaluator unImpOpEvaluator 
#define ifdcmpltuRVEvaluator unImpOpEvaluator 
#define ifdcmpgeuRVEvaluator unImpOpEvaluator 
#define ifdcmpgtuRVEvaluator unImpOpEvaluator 
#define ifdcmpleuRVEvaluator unImpOpEvaluator 
#define ifacmpeqRVEvaluator iflcmpeqEvaluator
#define ifacmpneRVEvaluator iflcmpneEvaluator
#define ifacmpltRVEvaluator iflucmpltEvaluator
#define ifacmpgeRVEvaluator iflucmpgeEvaluator
#define ifacmpgtRVEvaluator iflucmpgtEvaluator
#define ifacmpleRVEvaluator iflucmpleEvaluator
#define ifbcmpeqRVEvaluator unImpOpEvaluator 
#define ifbcmpneRVEvaluator unImpOpEvaluator 
#define ifbcmpltRVEvaluator unImpOpEvaluator 
#define ifbcmpgeRVEvaluator unImpOpEvaluator 
#define ifbcmpgtRVEvaluator unImpOpEvaluator 
#define ifbcmpleRVEvaluator unImpOpEvaluator 
#define ifbucmpltRVEvaluator unImpOpEvaluator 
#define ifbucmpgeRVEvaluator unImpOpEvaluator 
#define ifbucmpgtRVEvaluator unImpOpEvaluator 
#define ifbucmpleRVEvaluator unImpOpEvaluator 
#define ifscmpeqRVEvaluator unImpOpEvaluator 
#define ifscmpneRVEvaluator unImpOpEvaluator 
#define ifscmpltRVEvaluator unImpOpEvaluator 
#define ifscmpgeRVEvaluator unImpOpEvaluator 
#define ifscmpgtRVEvaluator unImpOpEvaluator 
#define ifscmpleRVEvaluator unImpOpEvaluator 
#define ifsucmpltRVEvaluator unImpOpEvaluator 
#define ifsucmpgeRVEvaluator unImpOpEvaluator 
#define ifsucmpgtRVEvaluator unImpOpEvaluator 
#define ifsucmpleRVEvaluator unImpOpEvaluator 
#define loadaddrRVEvaluator unImpOpEvaluator 
#define ZEROCHKRVEvaluator unImpOpEvaluator 
#define callIfRVEvaluator unImpOpEvaluator 
#define iRegLoadRVEvaluator iRegLoadEvaluator
#define aRegLoadRVEvaluator aRegLoadEvaluator
#define lRegLoadRVEvaluator iRegLoadEvaluator
#define fRegLoadRVEvaluator fRegLoadEvaluator
#define dRegLoadRVEvaluator fRegLoadEvaluator
#define sRegLoadRVEvaluator iRegLoadEvaluator
#define bRegLoadRVEvaluator iRegLoadEvaluator
#define iRegStoreRVEvaluator iRegStoreEvaluator
#define aRegStoreRVEvaluator iRegStoreEvaluator
#define lRegStoreRVEvaluator iRegStoreEvaluator
#define fRegStoreRVEvaluator iRegStoreEvaluator
#define dRegStoreRVEvaluator iRegStoreEvaluator
#define sRegStoreRVEvaluator iRegStoreEvaluator
#define bRegStoreRVEvaluator iRegStoreEvaluator
#define GlRegDepsRVEvaluator GlRegDepsEvaluator
#define iselectRVEvaluator iselectEvaluator 
#define lselectRVEvaluator iselectEvaluator 
#define bselectRVEvaluator iselectEvaluator 
#define sselectRVEvaluator iselectEvaluator 
#define aselectRVEvaluator iselectEvaluator 
#define fselectRVEvaluator fselectEvaluator 
#define dselectRVEvaluator dselectEvaluator 
#define treetopRVEvaluator treetopEvaluator
#define MethodEnterHookRVEvaluator unImpOpEvaluator 
#define MethodExitHookRVEvaluator unImpOpEvaluator 
#define PassThroughRVEvaluator passThroughEvaluator
#define compressedRefsRVEvaluator unImpOpEvaluator 
#define BBStartRVEvaluator BBStartEvaluator
#define BBEndRVEvaluator BBEndEvaluator
#define viremRVEvaluator unImpOpEvaluator 
#define viminRVEvaluator unImpOpEvaluator 
#define vimaxRVEvaluator unImpOpEvaluator 
#define vigetelemRVEvaluator unImpOpEvaluator 
#define visetelemRVEvaluator unImpOpEvaluator 
#define vimergelRVEvaluator unImpOpEvaluator 
#define vimergehRVEvaluator unImpOpEvaluator 
#define vicmpeqRVEvaluator unImpOpEvaluator 
#define vicmpgtRVEvaluator unImpOpEvaluator 
#define vicmpgeRVEvaluator unImpOpEvaluator 
#define vicmpltRVEvaluator unImpOpEvaluator 
#define vicmpleRVEvaluator unImpOpEvaluator 
#define vicmpalleqRVEvaluator unImpOpEvaluator 
#define vicmpallneRVEvaluator unImpOpEvaluator 
#define vicmpallgtRVEvaluator unImpOpEvaluator 
#define vicmpallgeRVEvaluator unImpOpEvaluator 
#define vicmpallltRVEvaluator unImpOpEvaluator 
#define vicmpallleRVEvaluator unImpOpEvaluator 
#define vicmpanyeqRVEvaluator unImpOpEvaluator 
#define vicmpanyneRVEvaluator unImpOpEvaluator 
#define vicmpanygtRVEvaluator unImpOpEvaluator 
#define vicmpanygeRVEvaluator unImpOpEvaluator 
#define vicmpanyltRVEvaluator unImpOpEvaluator 
#define vicmpanyleRVEvaluator unImpOpEvaluator 
#define vnotRVEvaluator unImpOpEvaluator 
#define vbitselectRVEvaluator unImpOpEvaluator 
#define vpermRVEvaluator unImpOpEvaluator 
#define vsplatsRVEvaluator unImpOpEvaluator 
#define vdmergelRVEvaluator unImpOpEvaluator 
#define vdmergehRVEvaluator unImpOpEvaluator 
#define vdsetelemRVEvaluator unImpOpEvaluator 
#define vdgetelemRVEvaluator unImpOpEvaluator 
#define vdselRVEvaluator unImpOpEvaluator 
#define vdremRVEvaluator unImpOpEvaluator 
#define vdmaddRVEvaluator unImpOpEvaluator 
#define vdnmsubRVEvaluator unImpOpEvaluator 
#define vdmsubRVEvaluator unImpOpEvaluator 
#define vdmaxRVEvaluator unImpOpEvaluator 
#define vdminRVEvaluator unImpOpEvaluator 
#define vdcmpeqRVEvaluator unImpOpEvaluator 
#define vdcmpneRVEvaluator unImpOpEvaluator 
#define vdcmpgtRVEvaluator unImpOpEvaluator 
#define vdcmpgeRVEvaluator unImpOpEvaluator 
#define vdcmpltRVEvaluator unImpOpEvaluator 
#define vdcmpleRVEvaluator unImpOpEvaluator 
#define vdcmpalleqRVEvaluator unImpOpEvaluator 
#define vdcmpallneRVEvaluator unImpOpEvaluator 
#define vdcmpallgtRVEvaluator unImpOpEvaluator 
#define vdcmpallgeRVEvaluator unImpOpEvaluator 
#define vdcmpallltRVEvaluator unImpOpEvaluator 
#define vdcmpallleRVEvaluator unImpOpEvaluator 
#define vdcmpanyeqRVEvaluator unImpOpEvaluator 
#define vdcmpanyneRVEvaluator unImpOpEvaluator 
#define vdcmpanygtRVEvaluator unImpOpEvaluator 
#define vdcmpanygeRVEvaluator unImpOpEvaluator 
#define vdcmpanyltRVEvaluator unImpOpEvaluator 
#define vdcmpanyleRVEvaluator unImpOpEvaluator 
#define vdsqrtRVEvaluator unImpOpEvaluator 
#define vdlogRVEvaluator unImpOpEvaluator 
#define vincRVEvaluator unImpOpEvaluator 
#define vdecRVEvaluator unImpOpEvaluator 
#define vnegRVEvaluator unImpOpEvaluator 
#define vcomRVEvaluator unImpOpEvaluator 
#define vaddRVEvaluator unImpOpEvaluator 
#define vsubRVEvaluator unImpOpEvaluator 
#define vmulRVEvaluator unImpOpEvaluator 
#define vdivRVEvaluator unImpOpEvaluator 
#define vremRVEvaluator unImpOpEvaluator 
#define vandRVEvaluator unImpOpEvaluator 
#define vorRVEvaluator unImpOpEvaluator 
#define vxorRVEvaluator unImpOpEvaluator 
#define vshlRVEvaluator unImpOpEvaluator 
#define vushrRVEvaluator unImpOpEvaluator 
#define vshrRVEvaluator unImpOpEvaluator 
#define vcmpeqRVEvaluator unImpOpEvaluator 
#define vcmpneRVEvaluator unImpOpEvaluator 
#define vcmpltRVEvaluator unImpOpEvaluator 
#define vucmpltRVEvaluator unImpOpEvaluator 
#define vcmpgtRVEvaluator unImpOpEvaluator 
#define vucmpgtRVEvaluator unImpOpEvaluator 
#define vcmpleRVEvaluator unImpOpEvaluator 
#define vucmpleRVEvaluator unImpOpEvaluator 
#define vcmpgeRVEvaluator unImpOpEvaluator 
#define vucmpgeRVEvaluator unImpOpEvaluator 
#define vloadRVEvaluator unImpOpEvaluator 
#define vloadiRVEvaluator unImpOpEvaluator 
#define vstoreRVEvaluator unImpOpEvaluator 
#define vstoreiRVEvaluator unImpOpEvaluator 
#define vrandRVEvaluator unImpOpEvaluator 
#define vreturnRVEvaluator unImpOpEvaluator 
#define vcallRVEvaluator unImpOpEvaluator 
#define vcalliRVEvaluator unImpOpEvaluator 
#define vselectRVEvaluator unImpOpEvaluator 
#define v2vRVEvaluator unImpOpEvaluator 
#define vl2vdRVEvaluator unImpOpEvaluator 
#define vconstRVEvaluator unImpOpEvaluator 
#define getvelemRVEvaluator unImpOpEvaluator 
#define vsetelemRVEvaluator unImpOpEvaluator 
#define vbRegLoadRVEvaluator unImpOpEvaluator 
#define vsRegLoadRVEvaluator unImpOpEvaluator 
#define viRegLoadRVEvaluator unImpOpEvaluator 
#define vlRegLoadRVEvaluator unImpOpEvaluator 
#define vfRegLoadRVEvaluator unImpOpEvaluator 
#define vdRegLoadRVEvaluator unImpOpEvaluator 
#define vbRegStoreRVEvaluator unImpOpEvaluator 
#define vsRegStoreRVEvaluator unImpOpEvaluator 
#define viRegStoreRVEvaluator unImpOpEvaluator 
#define vlRegStoreRVEvaluator unImpOpEvaluator 
#define vfRegStoreRVEvaluator unImpOpEvaluator 
#define vdRegStoreRVEvaluator unImpOpEvaluator 
#define iuloadRVEvaluator unImpOpEvaluator 
#define luloadRVEvaluator unImpOpEvaluator 
#define buloadRVEvaluator unImpOpEvaluator 
#define iuloadiRVEvaluator unImpOpEvaluator 
#define luloadiRVEvaluator unImpOpEvaluator 
#define buloadiRVEvaluator unImpOpEvaluator 
#define iustoreRVEvaluator unImpOpEvaluator 
#define lustoreRVEvaluator unImpOpEvaluator 
#define bustoreRVEvaluator unImpOpEvaluator 
#define iustoreiRVEvaluator unImpOpEvaluator 
#define lustoreiRVEvaluator unImpOpEvaluator 
#define bustoreiRVEvaluator unImpOpEvaluator 
#define iuaddRVEvaluator unImpOpEvaluator 
#define luaddRVEvaluator unImpOpEvaluator 
#define buaddRVEvaluator unImpOpEvaluator 
#define iusubRVEvaluator unImpOpEvaluator 
#define lusubRVEvaluator unImpOpEvaluator 
#define busubRVEvaluator unImpOpEvaluator 
#define iunegRVEvaluator unImpOpEvaluator 
#define lunegRVEvaluator unImpOpEvaluator 
#define f2iuRVEvaluator unImpOpEvaluator 
#define f2luRVEvaluator unImpOpEvaluator 
#define f2buRVEvaluator unImpOpEvaluator 
#define f2cRVEvaluator unImpOpEvaluator 
#define d2iuRVEvaluator unImpOpEvaluator 
#define d2luRVEvaluator unImpOpEvaluator 
#define d2buRVEvaluator unImpOpEvaluator 
#define d2cRVEvaluator unImpOpEvaluator 
#define iuRegLoadRVEvaluator unImpOpEvaluator 
#define luRegLoadRVEvaluator unImpOpEvaluator 
#define iuRegStoreRVEvaluator unImpOpEvaluator 
#define luRegStoreRVEvaluator unImpOpEvaluator 
#define cloadRVEvaluator cloadEvaluator
#define cloadiRVEvaluator cloadEvaluator
#define cstoreRVEvaluator sstoreEvaluator
#define cstoreiRVEvaluator sstoreEvaluator
#define monentRVEvaluator unImpOpEvaluator 
#define monexitRVEvaluator unImpOpEvaluator 
#define monexitfenceRVEvaluator unImpOpEvaluator 
#define tstartRVEvaluator unImpOpEvaluator 
#define tfinishRVEvaluator unImpOpEvaluator 
#define tabortRVEvaluator unImpOpEvaluator 
#define instanceofRVEvaluator unImpOpEvaluator 
#define checkcastRVEvaluator unImpOpEvaluator 
#define checkcastAndNULLCHKRVEvaluator unImpOpEvaluator 
#define NewRVEvaluator unImpOpEvaluator 
#define newvalueRVEvaluator unImpOpEvaluator 
#define newarrayRVEvaluator unImpOpEvaluator 
#define anewarrayRVEvaluator unImpOpEvaluator 
#define variableNewRVEvaluator unImpOpEvaluator 
#define variableNewArrayRVEvaluator unImpOpEvaluator 
#define multianewarrayRVEvaluator unImpOpEvaluator 
#define arraylengthRVEvaluator unImpOpEvaluator 
#define contigarraylengthRVEvaluator unImpOpEvaluator 
#define discontigarraylengthRVEvaluator unImpOpEvaluator 
#define icalliRVEvaluator indirectCallEvaluator 
#define lcalliRVEvaluator indirectCallEvaluator 
#define fcalliRVEvaluator indirectCallEvaluator 
#define dcalliRVEvaluator indirectCallEvaluator 
#define acalliRVEvaluator indirectCallEvaluator 
#define calliRVEvaluator indirectCallEvaluator 
#define fenceRVEvaluator unImpOpEvaluator 
#define luaddhRVEvaluator unImpOpEvaluator 
#define caddRVEvaluator unImpOpEvaluator 
#define aiaddRVEvaluator laddEvaluator 
#define aiuaddRVEvaluator unImpOpEvaluator 
#define aladdRVEvaluator laddEvaluator 
#define aluaddRVEvaluator unImpOpEvaluator 
#define lusubhRVEvaluator unImpOpEvaluator 
#define csubRVEvaluator unImpOpEvaluator 
#define imulhRVEvaluator imulhEvaluator 
#define iumulhRVEvaluator unImpOpEvaluator 
#define lmulhRVEvaluator unImpOpEvaluator 
#define lumulhRVEvaluator unImpOpEvaluator 
#define ibits2fRVEvaluator ibits2fEvaluator
#define fbits2iRVEvaluator fbits2iEvaluator
#define lbits2dRVEvaluator lbits2dEvaluator
#define dbits2lRVEvaluator dbits2lEvaluator
#define lookupRVEvaluator unImpOpEvaluator 
#define trtLookupRVEvaluator unImpOpEvaluator 
#define CaseRVEvaluator unImpOpEvaluator 
#define tableRVEvaluator unImpOpEvaluator 
#define exceptionRangeFenceRVEvaluator unImpOpEvaluator 
#define dbgFenceRVEvaluator unImpOpEvaluator 
#define NULLCHKRVEvaluator unImpOpEvaluator 
#define ResolveCHKRVEvaluator unImpOpEvaluator 
#define ResolveAndNULLCHKRVEvaluator unImpOpEvaluator 
#define DIVCHKRVEvaluator unImpOpEvaluator 
#define OverflowCHKRVEvaluator unImpOpEvaluator 
#define UnsignedOverflowCHKRVEvaluator unImpOpEvaluator 
#define BNDCHKRVEvaluator unImpOpEvaluator 
#define ArrayCopyBNDCHKRVEvaluator unImpOpEvaluator 
#define BNDCHKwithSpineCHKRVEvaluator unImpOpEvaluator 
#define SpineCHKRVEvaluator unImpOpEvaluator 
#define ArrayStoreCHKRVEvaluator unImpOpEvaluator 
#define ArrayCHKRVEvaluator unImpOpEvaluator 
#define RetRVEvaluator unImpOpEvaluator 
#define arraycopyRVEvaluator unImpOpEvaluator 
#define arraysetRVEvaluator unImpOpEvaluator 
#define arraytranslateRVEvaluator unImpOpEvaluator 
#define arraytranslateAndTestRVEvaluator unImpOpEvaluator 
#define long2StringRVEvaluator unImpOpEvaluator 
#define bitOpMemRVEvaluator unImpOpEvaluator 
#define bitOpMemNDRVEvaluator unImpOpEvaluator 
#define arraycmpRVEvaluator unImpOpEvaluator 
#define arraycmpWithPadRVEvaluator unImpOpEvaluator 
#define allocationFenceRVEvaluator unImpOpEvaluator 
#define loadFenceRVEvaluator unImpOpEvaluator 
#define storeFenceRVEvaluator unImpOpEvaluator 
#define fullFenceRVEvaluator unImpOpEvaluator 
#define MergeNewRVEvaluator unImpOpEvaluator 
#define computeCCRVEvaluator unImpOpEvaluator 
#define butestRVEvaluator unImpOpEvaluator 
#define sutestRVEvaluator unImpOpEvaluator 
#define bucmpRVEvaluator unImpOpEvaluator 
#define bcmpRVEvaluator unImpOpEvaluator 
#define sucmpRVEvaluator unImpOpEvaluator 
#define scmpRVEvaluator unImpOpEvaluator 
#define iucmpRVEvaluator unImpOpEvaluator 
#define icmpRVEvaluator unImpOpEvaluator 
#define lucmpRVEvaluator unImpOpEvaluator 
#define ificmpoRVEvaluator unImpOpEvaluator 
#define ificmpnoRVEvaluator unImpOpEvaluator 
#define iflcmpoRVEvaluator unImpOpEvaluator 
#define iflcmpnoRVEvaluator unImpOpEvaluator 
#define ificmnoRVEvaluator unImpOpEvaluator 
#define ificmnnoRVEvaluator unImpOpEvaluator 
#define iflcmnoRVEvaluator unImpOpEvaluator 
#define iflcmnnoRVEvaluator unImpOpEvaluator 
#define iuaddcRVEvaluator unImpOpEvaluator 
#define luaddcRVEvaluator unImpOpEvaluator 
#define iusubbRVEvaluator unImpOpEvaluator 
#define lusubbRVEvaluator unImpOpEvaluator 
#define icmpsetRVEvaluator unImpOpEvaluator 
#define lcmpsetRVEvaluator unImpOpEvaluator 
#define bztestnsetRVEvaluator unImpOpEvaluator 
#define ibatomicorRVEvaluator unImpOpEvaluator 
#define isatomicorRVEvaluator unImpOpEvaluator 
#define iiatomicorRVEvaluator unImpOpEvaluator 
#define ilatomicorRVEvaluator unImpOpEvaluator 
#define dexpRVEvaluator unImpOpEvaluator 
#define branchRVEvaluator unImpOpEvaluator 
#define igotoRVEvaluator unImpOpEvaluator 
#define bexpRVEvaluator unImpOpEvaluator 
#define buexpRVEvaluator unImpOpEvaluator 
#define sexpRVEvaluator unImpOpEvaluator 
#define cexpRVEvaluator unImpOpEvaluator 
#define iexpRVEvaluator unImpOpEvaluator 
#define iuexpRVEvaluator unImpOpEvaluator 
#define lexpRVEvaluator unImpOpEvaluator 
#define luexpRVEvaluator unImpOpEvaluator 
#define fexpRVEvaluator unImpOpEvaluator 
#define fuexpRVEvaluator unImpOpEvaluator 
#define duexpRVEvaluator unImpOpEvaluator 
#define ixfrsRVEvaluator unImpOpEvaluator 
#define lxfrsRVEvaluator unImpOpEvaluator 
#define fxfrsRVEvaluator unImpOpEvaluator 
#define dxfrsRVEvaluator unImpOpEvaluator 
#define fintRVEvaluator unImpOpEvaluator 
#define dintRVEvaluator unImpOpEvaluator 
#define fnintRVEvaluator unImpOpEvaluator 
#define dnintRVEvaluator unImpOpEvaluator 
#define fsqrtRVEvaluator unImpOpEvaluator 
#define dsqrtRVEvaluator unImpOpEvaluator 
#define getstackRVEvaluator unImpOpEvaluator 
#define deallocaRVEvaluator unImpOpEvaluator 
#define idozRVEvaluator unImpOpEvaluator 
#define dcosRVEvaluator unImpOpEvaluator 
#define dsinRVEvaluator unImpOpEvaluator 
#define dtanRVEvaluator unImpOpEvaluator 
#define dcoshRVEvaluator unImpOpEvaluator 
#define dsinhRVEvaluator unImpOpEvaluator 
#define dtanhRVEvaluator unImpOpEvaluator 
#define dacosRVEvaluator unImpOpEvaluator 
#define dasinRVEvaluator unImpOpEvaluator 
#define datanRVEvaluator unImpOpEvaluator 
#define datan2RVEvaluator unImpOpEvaluator 
#define dlogRVEvaluator unImpOpEvaluator 
#define dfloorRVEvaluator unImpOpEvaluator 
#define ffloorRVEvaluator unImpOpEvaluator 
#define dceilRVEvaluator unImpOpEvaluator 
#define fceilRVEvaluator unImpOpEvaluator 
#define ibranchRVEvaluator unImpOpEvaluator 
#define mbranchRVEvaluator unImpOpEvaluator 
#define getpmRVEvaluator unImpOpEvaluator 
#define setpmRVEvaluator unImpOpEvaluator 
#define loadAutoOffsetRVEvaluator unImpOpEvaluator 
#define imaxRVEvaluator imaxEvaluator 
#define iumaxRVEvaluator iumaxEvaluator 
#define lmaxRVEvaluator imaxEvaluator 
#define lumaxRVEvaluator iumaxEvaluator 
#define fmaxRVEvaluator fmaxEvaluator 
#define dmaxRVEvaluator dmaxEvaluator 
#define iminRVEvaluator iminEvaluator 
#define iuminRVEvaluator iuminEvaluator 
#define lminRVEvaluator iminEvaluator 
#define luminRVEvaluator iuminEvaluator 
#define fminRVEvaluator fminEvaluator 
#define dminRVEvaluator dminEvaluator 
#define trtRVEvaluator unImpOpEvaluator 
#define trtSimpleRVEvaluator unImpOpEvaluator 
#define ihbitRVEvaluator unImpOpEvaluator 
#define ilbitRVEvaluator unImpOpEvaluator 
#define inolzRVEvaluator unImpOpEvaluator 
#define inotzRVEvaluator unImpOpEvaluator 
#define ipopcntRVEvaluator unImpOpEvaluator 
#define lhbitRVEvaluator unImpOpEvaluator 
#define llbitRVEvaluator unImpOpEvaluator 
#define lnolzRVEvaluator unImpOpEvaluator 
#define lnotzRVEvaluator unImpOpEvaluator 
#define lpopcntRVEvaluator unImpOpEvaluator 
#define sbyteswapRVEvaluator unImpOpEvaluator 
#define ibyteswapRVEvaluator unImpOpEvaluator 
#define lbyteswapRVEvaluator unImpOpEvaluator 
#define bbitpermuteRVEvaluator unImpOpEvaluator 
#define sbitpermuteRVEvaluator unImpOpEvaluator 
#define ibitpermuteRVEvaluator unImpOpEvaluator 
#define lbitpermuteRVEvaluator unImpOpEvaluator 
#define PrefetchRVEvaluator unImpOpEvaluator 


#include "il/OMROpcodes.hpp"

#define GENERATE_TREE_EVAL_TABLE(\
   opcode, \
   name, \
   prop1, \
   prop2, \
   prop3, \
   prop4, \
   dataType, \
   typeProps, \
   childProps, \
   swapChildrenOpcode, \
   reverseBranchOpcode, \
   boolCompareOpcode, \
   ifCompareOpcode, \
   enumValue, \
   ...) enumValue ## RVEvaluator,

   FOR_EACH_OPCODE(GENERATE_TREE_EVAL_TABLE)

#undef GENERATE_TREE_EVAL_TABLE

