version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /buildenv/docker/x86_64/ubuntu20
    schedule:
      interval: daily
