/*******************************************************************************
 * Copyright (c) 2000, 2020 IBM Corp. and others
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which accompanies this
 * distribution and is available at http://eclipse.org/legal/epl-2.0
 * or the Apache License, Version 2.0 which accompanies this distribution
 * and is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License, v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception [1] and GNU General Public
 * License, version 2 with the OpenJDK Assembly Exception [2].
 *
 * [1] https://www.gnu.org/software/classpath/license.html
 * [2] http://openjdk.java.net/legal/assembly-exception.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
 *******************************************************************************/

/*
 * This table is #included in a static table.
 * Only Function Pointers are allowed.
 */

#define BadILOpPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define aconstPowerEvaluator TR::TreeEvaluator::aconstEvaluator
#define iconstPowerEvaluator TR::TreeEvaluator::iconstEvaluator
#define lconstPowerEvaluator TR::TreeEvaluator::lconstEvaluator
#define fconstPowerEvaluator TR::TreeEvaluator::fconstEvaluator
#define dconstPowerEvaluator TR::TreeEvaluator::dconstEvaluator
#define bconstPowerEvaluator TR::TreeEvaluator::iconstEvaluator
#define sconstPowerEvaluator TR::TreeEvaluator::iconstEvaluator
#define iloadPowerEvaluator TR::TreeEvaluator::iloadEvaluator
#define floadPowerEvaluator TR::TreeEvaluator::floadEvaluator
#define dloadPowerEvaluator TR::TreeEvaluator::dloadEvaluator
#define aloadPowerEvaluator TR::TreeEvaluator::aloadEvaluator
#define bloadPowerEvaluator TR::TreeEvaluator::bloadEvaluator
#define sloadPowerEvaluator TR::TreeEvaluator::sloadEvaluator
#define lloadPowerEvaluator TR::TreeEvaluator::lloadEvaluator
#define irdbarPowerEvaluator TR::TreeEvaluator::irdbarEvaluator
#define frdbarPowerEvaluator TR::TreeEvaluator::frdbarEvaluator
#define drdbarPowerEvaluator TR::TreeEvaluator::drdbarEvaluator
#define ardbarPowerEvaluator TR::TreeEvaluator::ardbarEvaluator
#define brdbarPowerEvaluator TR::TreeEvaluator::brdbarEvaluator
#define srdbarPowerEvaluator TR::TreeEvaluator::srdbarEvaluator
#define lrdbarPowerEvaluator TR::TreeEvaluator::lrdbarEvaluator
#define iloadiPowerEvaluator TR::TreeEvaluator::iloadEvaluator
#define floadiPowerEvaluator TR::TreeEvaluator::floadEvaluator
#define dloadiPowerEvaluator TR::TreeEvaluator::dloadEvaluator
#define aloadiPowerEvaluator TR::TreeEvaluator::aloadEvaluator
#define bloadiPowerEvaluator TR::TreeEvaluator::bloadEvaluator
#define sloadiPowerEvaluator TR::TreeEvaluator::sloadEvaluator
#define lloadiPowerEvaluator TR::TreeEvaluator::lloadEvaluator
#define irdbariPowerEvaluator TR::TreeEvaluator::irdbariEvaluator
#define frdbariPowerEvaluator TR::TreeEvaluator::frdbariEvaluator
#define drdbariPowerEvaluator TR::TreeEvaluator::drdbariEvaluator
#define ardbariPowerEvaluator TR::TreeEvaluator::ardbariEvaluator
#define brdbariPowerEvaluator TR::TreeEvaluator::brdbariEvaluator
#define srdbariPowerEvaluator TR::TreeEvaluator::srdbariEvaluator
#define lrdbariPowerEvaluator TR::TreeEvaluator::lrdbariEvaluator
#define istorePowerEvaluator TR::TreeEvaluator::istoreEvaluator
#define lstorePowerEvaluator TR::TreeEvaluator::lstoreEvaluator
#define fstorePowerEvaluator TR::TreeEvaluator::fstoreEvaluator
#define dstorePowerEvaluator TR::TreeEvaluator::dstoreEvaluator
#define astorePowerEvaluator TR::TreeEvaluator::astoreEvaluator
#define bstorePowerEvaluator TR::TreeEvaluator::bstoreEvaluator
#define sstorePowerEvaluator TR::TreeEvaluator::sstoreEvaluator
#define iwrtbarPowerEvaluator TR::TreeEvaluator::iwrtbarEvaluator
#define lwrtbarPowerEvaluator TR::TreeEvaluator::lwrtbarEvaluator
#define fwrtbarPowerEvaluator TR::TreeEvaluator::fwrtbarEvaluator
#define dwrtbarPowerEvaluator TR::TreeEvaluator::dwrtbarEvaluator
#define awrtbarPowerEvaluator TR::TreeEvaluator::awrtbarEvaluator
#define bwrtbarPowerEvaluator TR::TreeEvaluator::bwrtbarEvaluator
#define swrtbarPowerEvaluator TR::TreeEvaluator::swrtbarEvaluator
#define lstoreiPowerEvaluator TR::TreeEvaluator::lstoreEvaluator
#define fstoreiPowerEvaluator TR::TreeEvaluator::fstoreEvaluator
#define dstoreiPowerEvaluator TR::TreeEvaluator::dstoreEvaluator
#define astoreiPowerEvaluator TR::TreeEvaluator::astoreEvaluator
#define bstoreiPowerEvaluator TR::TreeEvaluator::bstoreEvaluator
#define sstoreiPowerEvaluator TR::TreeEvaluator::sstoreEvaluator
#define istoreiPowerEvaluator TR::TreeEvaluator::istoreEvaluator
#define lwrtbariPowerEvaluator TR::TreeEvaluator::lwrtbariEvaluator
#define fwrtbariPowerEvaluator TR::TreeEvaluator::fwrtbariEvaluator
#define dwrtbariPowerEvaluator TR::TreeEvaluator::dwrtbariEvaluator
#define awrtbariPowerEvaluator TR::TreeEvaluator::awrtbariEvaluator
#define bwrtbariPowerEvaluator TR::TreeEvaluator::bwrtbariEvaluator
#define swrtbariPowerEvaluator TR::TreeEvaluator::swrtbariEvaluator
#define iwrtbariPowerEvaluator TR::TreeEvaluator::iwrtbariEvaluator
#define GotoPowerEvaluator TR::TreeEvaluator::gotoEvaluator
#define ireturnPowerEvaluator TR::TreeEvaluator::ireturnEvaluator
#define lreturnPowerEvaluator TR::TreeEvaluator::lreturnEvaluator
#define freturnPowerEvaluator TR::TreeEvaluator::freturnEvaluator
#define dreturnPowerEvaluator TR::TreeEvaluator::freturnEvaluator
#define areturnPowerEvaluator TR::TreeEvaluator::ireturnEvaluator
#define ReturnPowerEvaluator TR::TreeEvaluator::returnEvaluator
#define asynccheckPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define athrowPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define icallPowerEvaluator TR::TreeEvaluator::directCallEvaluator
#define lcallPowerEvaluator TR::TreeEvaluator::directCallEvaluator
#define fcallPowerEvaluator TR::TreeEvaluator::directCallEvaluator
#define dcallPowerEvaluator TR::TreeEvaluator::directCallEvaluator
#define acallPowerEvaluator TR::TreeEvaluator::directCallEvaluator
#define callPowerEvaluator TR::TreeEvaluator::directCallEvaluator
#define iaddPowerEvaluator TR::TreeEvaluator::iaddEvaluator
#define laddPowerEvaluator TR::TreeEvaluator::laddEvaluator
#define faddPowerEvaluator TR::TreeEvaluator::faddEvaluator
#define daddPowerEvaluator TR::TreeEvaluator::daddEvaluator
#define baddPowerEvaluator TR::TreeEvaluator::iaddEvaluator
#define saddPowerEvaluator TR::TreeEvaluator::iaddEvaluator
#define isubPowerEvaluator TR::TreeEvaluator::isubEvaluator
#define lsubPowerEvaluator TR::TreeEvaluator::lsubEvaluator
#define fsubPowerEvaluator TR::TreeEvaluator::fsubEvaluator
#define dsubPowerEvaluator TR::TreeEvaluator::dsubEvaluator
#define bsubPowerEvaluator TR::TreeEvaluator::isubEvaluator
#define ssubPowerEvaluator TR::TreeEvaluator::isubEvaluator
#define asubPowerEvaluator TR::TreeEvaluator::asubEvaluator
#define imulPowerEvaluator TR::TreeEvaluator::imulEvaluator
#define lmulPowerEvaluator TR::TreeEvaluator::lmulEvaluator
#define fmulPowerEvaluator TR::TreeEvaluator::fmulEvaluator
#define dmulPowerEvaluator TR::TreeEvaluator::dmulEvaluator
#define bmulPowerEvaluator TR::TreeEvaluator::imulEvaluator
#define smulPowerEvaluator TR::TreeEvaluator::imulEvaluator
#define idivPowerEvaluator TR::TreeEvaluator::idivEvaluator
#define ldivPowerEvaluator TR::TreeEvaluator::ldivEvaluator
#define fdivPowerEvaluator TR::TreeEvaluator::fdivEvaluator
#define ddivPowerEvaluator TR::TreeEvaluator::ddivEvaluator
#define bdivPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define sdivPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iudivPowerEvaluator TR::TreeEvaluator::idivEvaluator
#define ludivPowerEvaluator TR::TreeEvaluator::ldivEvaluator
#define iremPowerEvaluator TR::TreeEvaluator::iremEvaluator
#define lremPowerEvaluator TR::TreeEvaluator::lremEvaluator
#define fremPowerEvaluator TR::TreeEvaluator::fremEvaluator
#define dremPowerEvaluator TR::TreeEvaluator::dremEvaluator
#define bremPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define sremPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iuremPowerEvaluator TR::TreeEvaluator::iremEvaluator
#define inegPowerEvaluator TR::TreeEvaluator::inegEvaluator
#define lnegPowerEvaluator TR::TreeEvaluator::lnegEvaluator
#define fnegPowerEvaluator TR::TreeEvaluator::fnegEvaluator
#define dnegPowerEvaluator TR::TreeEvaluator::fnegEvaluator
#define bnegPowerEvaluator TR::TreeEvaluator::inegEvaluator
#define snegPowerEvaluator TR::TreeEvaluator::inegEvaluator
#define iabsPowerEvaluator TR::TreeEvaluator::iabsEvaluator
#define labsPowerEvaluator TR::TreeEvaluator::labsEvaluator
#define fabsPowerEvaluator TR::TreeEvaluator::fabsEvaluator
#define dabsPowerEvaluator TR::TreeEvaluator::dabsEvaluator
#define ishlPowerEvaluator TR::TreeEvaluator::ishlEvaluator
#define lshlPowerEvaluator TR::TreeEvaluator::lshlEvaluator
#define bshlPowerEvaluator TR::TreeEvaluator::bshlEvaluator
#define sshlPowerEvaluator TR::TreeEvaluator::sshlEvaluator
#define ishrPowerEvaluator TR::TreeEvaluator::ishrEvaluator
#define lshrPowerEvaluator TR::TreeEvaluator::lshrEvaluator
#define bshrPowerEvaluator TR::TreeEvaluator::bshrEvaluator
#define sshrPowerEvaluator TR::TreeEvaluator::sshrEvaluator
#define iushrPowerEvaluator TR::TreeEvaluator::iushrEvaluator
#define lushrPowerEvaluator TR::TreeEvaluator::lushrEvaluator
#define bushrPowerEvaluator TR::TreeEvaluator::bushrEvaluator
#define sushrPowerEvaluator TR::TreeEvaluator::sushrEvaluator
#define irolPowerEvaluator TR::TreeEvaluator::irolEvaluator
#define lrolPowerEvaluator TR::TreeEvaluator::lrolEvaluator
#define iandPowerEvaluator TR::TreeEvaluator::iandEvaluator
#define landPowerEvaluator TR::TreeEvaluator::landEvaluator
#define bandPowerEvaluator TR::TreeEvaluator::iandEvaluator
#define sandPowerEvaluator TR::TreeEvaluator::iandEvaluator
#define iorPowerEvaluator TR::TreeEvaluator::iorEvaluator
#define lorPowerEvaluator TR::TreeEvaluator::lorEvaluator
#define borPowerEvaluator TR::TreeEvaluator::iorEvaluator
#define sorPowerEvaluator TR::TreeEvaluator::iorEvaluator
#define ixorPowerEvaluator TR::TreeEvaluator::ixorEvaluator
#define lxorPowerEvaluator TR::TreeEvaluator::lxorEvaluator
#define bxorPowerEvaluator TR::TreeEvaluator::ixorEvaluator
#define sxorPowerEvaluator TR::TreeEvaluator::ixorEvaluator
#define i2lPowerEvaluator TR::TreeEvaluator::s2lEvaluator
#define i2fPowerEvaluator TR::TreeEvaluator::i2fEvaluator
#define i2dPowerEvaluator TR::TreeEvaluator::i2dEvaluator
#define i2bPowerEvaluator TR::TreeEvaluator::i2bEvaluator
#define i2sPowerEvaluator TR::TreeEvaluator::i2sEvaluator
#define i2aPowerEvaluator TR::TreeEvaluator::i2aEvaluator
#define iu2lPowerEvaluator TR::TreeEvaluator::iu2lEvaluator
#define iu2fPowerEvaluator TR::TreeEvaluator::i2fEvaluator
#define iu2dPowerEvaluator TR::TreeEvaluator::i2dEvaluator
#define iu2aPowerEvaluator TR::TreeEvaluator::iu2aEvaluator
#define l2iPowerEvaluator TR::TreeEvaluator::l2iEvaluator
#define l2fPowerEvaluator TR::TreeEvaluator::l2fEvaluator
#define l2dPowerEvaluator TR::TreeEvaluator::l2dEvaluator
#define l2bPowerEvaluator TR::TreeEvaluator::l2bEvaluator
#define l2sPowerEvaluator TR::TreeEvaluator::l2sEvaluator
#define l2aPowerEvaluator TR::TreeEvaluator::l2aEvaluator
#define lu2fPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define lu2dPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define lu2aPowerEvaluator TR::TreeEvaluator::l2aEvaluator
#define f2iPowerEvaluator TR::TreeEvaluator::d2iEvaluator
#define f2lPowerEvaluator TR::TreeEvaluator::d2lEvaluator
#define f2dPowerEvaluator TR::TreeEvaluator::f2dEvaluator
#define f2bPowerEvaluator TR::TreeEvaluator::d2iEvaluator
#define f2sPowerEvaluator TR::TreeEvaluator::d2iEvaluator
#define d2iPowerEvaluator TR::TreeEvaluator::d2iEvaluator
#define d2lPowerEvaluator TR::TreeEvaluator::d2lEvaluator
#define d2fPowerEvaluator TR::TreeEvaluator::d2fEvaluator
#define d2bPowerEvaluator TR::TreeEvaluator::d2iEvaluator
#define d2sPowerEvaluator TR::TreeEvaluator::d2iEvaluator
#define b2iPowerEvaluator TR::TreeEvaluator::b2iEvaluator
#define b2lPowerEvaluator TR::TreeEvaluator::b2lEvaluator
#define b2fPowerEvaluator TR::TreeEvaluator::i2dEvaluator
#define b2dPowerEvaluator TR::TreeEvaluator::i2dEvaluator
#define b2sPowerEvaluator TR::TreeEvaluator::b2iEvaluator
#define b2aPowerEvaluator TR::TreeEvaluator::b2aEvaluator
#define bu2iPowerEvaluator TR::TreeEvaluator::bu2iEvaluator
#define bu2lPowerEvaluator TR::TreeEvaluator::bu2lEvaluator
#define bu2fPowerEvaluator TR::TreeEvaluator::i2dEvaluator
#define bu2dPowerEvaluator TR::TreeEvaluator::i2dEvaluator
#define bu2sPowerEvaluator TR::TreeEvaluator::bu2iEvaluator
#define bu2aPowerEvaluator TR::TreeEvaluator::bu2aEvaluator
#define s2iPowerEvaluator TR::TreeEvaluator::s2iEvaluator
#define s2lPowerEvaluator TR::TreeEvaluator::s2lEvaluator
#define s2fPowerEvaluator TR::TreeEvaluator::i2dEvaluator
#define s2dPowerEvaluator TR::TreeEvaluator::i2dEvaluator
#define s2bPowerEvaluator TR::TreeEvaluator::i2bEvaluator
#define s2aPowerEvaluator TR::TreeEvaluator::s2aEvaluator
#define su2iPowerEvaluator TR::TreeEvaluator::su2iEvaluator
#define su2lPowerEvaluator TR::TreeEvaluator::su2lEvaluator
#define su2fPowerEvaluator TR::TreeEvaluator::i2dEvaluator
#define su2dPowerEvaluator TR::TreeEvaluator::i2dEvaluator
#define su2aPowerEvaluator TR::TreeEvaluator::su2aEvaluator
#define a2iPowerEvaluator TR::TreeEvaluator::a2iEvaluator
#define a2lPowerEvaluator TR::TreeEvaluator::a2lEvaluator
#define a2bPowerEvaluator TR::TreeEvaluator::a2bEvaluator
#define a2sPowerEvaluator TR::TreeEvaluator::a2sEvaluator
#define icmpeqPowerEvaluator TR::TreeEvaluator::icmpeqEvaluator
#define icmpnePowerEvaluator TR::TreeEvaluator::icmpneEvaluator
#define icmpltPowerEvaluator TR::TreeEvaluator::icmpltEvaluator
#define icmpgePowerEvaluator TR::TreeEvaluator::icmpgeEvaluator
#define icmpgtPowerEvaluator TR::TreeEvaluator::icmpgtEvaluator
#define icmplePowerEvaluator TR::TreeEvaluator::icmpleEvaluator
#define iucmpltPowerEvaluator TR::TreeEvaluator::iucmpltEvaluator
#define iucmpgePowerEvaluator TR::TreeEvaluator::iucmpgeEvaluator
#define iucmpgtPowerEvaluator TR::TreeEvaluator::iucmpgtEvaluator
#define iucmplePowerEvaluator TR::TreeEvaluator::iucmpleEvaluator
#define lcmpeqPowerEvaluator TR::TreeEvaluator::lcmpeqEvaluator
#define lcmpnePowerEvaluator TR::TreeEvaluator::lcmpneEvaluator
#define lcmpltPowerEvaluator TR::TreeEvaluator::lcmpltEvaluator
#define lcmpgePowerEvaluator TR::TreeEvaluator::lcmpgeEvaluator
#define lcmpgtPowerEvaluator TR::TreeEvaluator::lcmpgtEvaluator
#define lcmplePowerEvaluator TR::TreeEvaluator::lcmpleEvaluator
#define lucmpltPowerEvaluator TR::TreeEvaluator::lucmpltEvaluator
#define lucmpgePowerEvaluator TR::TreeEvaluator::lucmpgeEvaluator
#define lucmpgtPowerEvaluator TR::TreeEvaluator::lucmpgtEvaluator
#define lucmplePowerEvaluator TR::TreeEvaluator::lucmpleEvaluator
#define fcmpeqPowerEvaluator TR::TreeEvaluator::fcmpeqPowerEvaluator
#define fcmpnePowerEvaluator TR::TreeEvaluator::fcmpnePowerEvaluator
#define fcmpltPowerEvaluator TR::TreeEvaluator::fcmpltPowerEvaluator
#define fcmpgePowerEvaluator TR::TreeEvaluator::fcmpgePowerEvaluator
#define fcmpgtPowerEvaluator TR::TreeEvaluator::fcmpgtPowerEvaluator
#define fcmplePowerEvaluator TR::TreeEvaluator::fcmplePowerEvaluator
#define fcmpequPowerEvaluator TR::TreeEvaluator::fcmpequPowerEvaluator
#define fcmpneuPowerEvaluator TR::TreeEvaluator::fcmpneuPowerEvaluator
#define fcmpltuPowerEvaluator TR::TreeEvaluator::fcmpltuPowerEvaluator
#define fcmpgeuPowerEvaluator TR::TreeEvaluator::fcmpgeuPowerEvaluator
#define fcmpgtuPowerEvaluator TR::TreeEvaluator::fcmpgtuPowerEvaluator
#define fcmpleuPowerEvaluator TR::TreeEvaluator::fcmpleuPowerEvaluator
#define dcmpeqPowerEvaluator TR::TreeEvaluator::dcmpeqEvaluator
#define dcmpnePowerEvaluator TR::TreeEvaluator::dcmpneEvaluator
#define dcmpltPowerEvaluator TR::TreeEvaluator::dcmpltEvaluator
#define dcmpgePowerEvaluator TR::TreeEvaluator::dcmpgeEvaluator
#define dcmpgtPowerEvaluator TR::TreeEvaluator::dcmpgtEvaluator
#define dcmplePowerEvaluator TR::TreeEvaluator::dcmpleEvaluator
#define dcmpequPowerEvaluator TR::TreeEvaluator::dcmpequEvaluator
#define dcmpneuPowerEvaluator TR::TreeEvaluator::dcmpneuEvaluator
#define dcmpltuPowerEvaluator TR::TreeEvaluator::dcmpltuEvaluator
#define dcmpgeuPowerEvaluator TR::TreeEvaluator::dcmpgeuEvaluator
#define dcmpgtuPowerEvaluator TR::TreeEvaluator::dcmpgtuEvaluator
#define dcmpleuPowerEvaluator TR::TreeEvaluator::dcmpleuEvaluator
#define acmpeqPowerEvaluator TR::TreeEvaluator::acmpeqEvaluator
#define acmpnePowerEvaluator TR::TreeEvaluator::acmpneEvaluator
#define acmpltPowerEvaluator TR::TreeEvaluator::acmpltEvaluator
#define acmpgePowerEvaluator TR::TreeEvaluator::acmpgeEvaluator
#define acmpgtPowerEvaluator TR::TreeEvaluator::acmpgtEvaluator
#define acmplePowerEvaluator TR::TreeEvaluator::acmpleEvaluator
#define bcmpeqPowerEvaluator TR::TreeEvaluator::bcmpeqEvaluator
#define bcmpnePowerEvaluator TR::TreeEvaluator::bcmpneEvaluator
#define bcmpltPowerEvaluator TR::TreeEvaluator::bcmpltEvaluator
#define bcmpgePowerEvaluator TR::TreeEvaluator::bcmpgeEvaluator
#define bcmpgtPowerEvaluator TR::TreeEvaluator::bcmpgtEvaluator
#define bcmplePowerEvaluator TR::TreeEvaluator::bcmpleEvaluator
#define bucmpltPowerEvaluator TR::TreeEvaluator::bucmpltEvaluator
#define bucmpgePowerEvaluator TR::TreeEvaluator::bucmpgeEvaluator
#define bucmpgtPowerEvaluator TR::TreeEvaluator::bucmpgtEvaluator
#define bucmplePowerEvaluator TR::TreeEvaluator::bucmpleEvaluator
#define scmpeqPowerEvaluator TR::TreeEvaluator::scmpeqEvaluator
#define scmpnePowerEvaluator TR::TreeEvaluator::scmpneEvaluator
#define scmpltPowerEvaluator TR::TreeEvaluator::scmpltEvaluator
#define scmpgePowerEvaluator TR::TreeEvaluator::scmpgeEvaluator
#define scmpgtPowerEvaluator TR::TreeEvaluator::scmpgtEvaluator
#define scmplePowerEvaluator TR::TreeEvaluator::scmpleEvaluator
#define sucmpltPowerEvaluator TR::TreeEvaluator::sucmpltEvaluator
#define sucmpgePowerEvaluator TR::TreeEvaluator::sucmpgeEvaluator
#define sucmpgtPowerEvaluator TR::TreeEvaluator::sucmpgtEvaluator
#define sucmplePowerEvaluator TR::TreeEvaluator::sucmpleEvaluator
#define lcmpPowerEvaluator TR::TreeEvaluator::lcmpEvaluator
#define fcmplPowerEvaluator TR::TreeEvaluator::dcmplEvaluator
#define fcmpgPowerEvaluator TR::TreeEvaluator::dcmpgEvaluator
#define dcmplPowerEvaluator TR::TreeEvaluator::dcmplEvaluator
#define dcmpgPowerEvaluator TR::TreeEvaluator::dcmpgEvaluator
#define ificmpeqPowerEvaluator TR::TreeEvaluator::ificmpeqEvaluator
#define ificmpnePowerEvaluator TR::TreeEvaluator::ificmpeqEvaluator
#define ificmpltPowerEvaluator TR::TreeEvaluator::ificmpltEvaluator
#define ificmpgePowerEvaluator TR::TreeEvaluator::ificmpgeEvaluator
#define ificmpgtPowerEvaluator TR::TreeEvaluator::ificmpgtEvaluator
#define ificmplePowerEvaluator TR::TreeEvaluator::ificmpleEvaluator
#define ifiucmpltPowerEvaluator TR::TreeEvaluator::ifiucmpltEvaluator
#define ifiucmpgePowerEvaluator TR::TreeEvaluator::ifiucmpgeEvaluator
#define ifiucmpgtPowerEvaluator TR::TreeEvaluator::ifiucmpgtEvaluator
#define ifiucmplePowerEvaluator TR::TreeEvaluator::ifiucmpleEvaluator
#define iflcmpeqPowerEvaluator TR::TreeEvaluator::iflcmpeqEvaluator
#define iflcmpnePowerEvaluator TR::TreeEvaluator::iflcmpeqEvaluator
#define iflcmpltPowerEvaluator TR::TreeEvaluator::iflcmpltEvaluator
#define iflcmpgePowerEvaluator TR::TreeEvaluator::iflcmpgeEvaluator
#define iflcmpgtPowerEvaluator TR::TreeEvaluator::iflcmpgtEvaluator
#define iflcmplePowerEvaluator TR::TreeEvaluator::iflcmpleEvaluator
#define iflucmpltPowerEvaluator TR::TreeEvaluator::iflucmpltEvaluator
#define iflucmpgePowerEvaluator TR::TreeEvaluator::iflucmpgeEvaluator
#define iflucmpgtPowerEvaluator TR::TreeEvaluator::iflucmpgtEvaluator
#define iflucmplePowerEvaluator TR::TreeEvaluator::iflucmpleEvaluator
#define iffcmpeqPowerEvaluator TR::TreeEvaluator::ifdcmpeqEvaluator
#define iffcmpnePowerEvaluator TR::TreeEvaluator::ifdcmpneEvaluator
#define iffcmpltPowerEvaluator TR::TreeEvaluator::ifdcmpltEvaluator
#define iffcmpgePowerEvaluator TR::TreeEvaluator::ifdcmpgeEvaluator
#define iffcmpgtPowerEvaluator TR::TreeEvaluator::ifdcmpgtEvaluator
#define iffcmplePowerEvaluator TR::TreeEvaluator::ifdcmpleEvaluator
#define iffcmpequPowerEvaluator TR::TreeEvaluator::ifdcmpequEvaluator
#define iffcmpneuPowerEvaluator TR::TreeEvaluator::ifdcmpneEvaluator
#define iffcmpltuPowerEvaluator TR::TreeEvaluator::ifdcmpltuEvaluator
#define iffcmpgeuPowerEvaluator TR::TreeEvaluator::ifdcmpgeuEvaluator
#define iffcmpgtuPowerEvaluator TR::TreeEvaluator::ifdcmpgtuEvaluator
#define iffcmpleuPowerEvaluator TR::TreeEvaluator::ifdcmpleuEvaluator
#define ifdcmpeqPowerEvaluator TR::TreeEvaluator::ifdcmpeqEvaluator
#define ifdcmpnePowerEvaluator TR::TreeEvaluator::ifdcmpneEvaluator
#define ifdcmpltPowerEvaluator TR::TreeEvaluator::ifdcmpltEvaluator
#define ifdcmpgePowerEvaluator TR::TreeEvaluator::ifdcmpgeEvaluator
#define ifdcmpgtPowerEvaluator TR::TreeEvaluator::ifdcmpgtEvaluator
#define ifdcmplePowerEvaluator TR::TreeEvaluator::ifdcmpleEvaluator
#define ifdcmpequPowerEvaluator TR::TreeEvaluator::ifdcmpequEvaluator
#define ifdcmpneuPowerEvaluator TR::TreeEvaluator::ifdcmpneEvaluator
#define ifdcmpltuPowerEvaluator TR::TreeEvaluator::ifdcmpltuEvaluator
#define ifdcmpgeuPowerEvaluator TR::TreeEvaluator::ifdcmpgeuEvaluator
#define ifdcmpgtuPowerEvaluator TR::TreeEvaluator::ifdcmpgtuEvaluator
#define ifdcmpleuPowerEvaluator TR::TreeEvaluator::ifdcmpleuEvaluator
#define ifacmpeqPowerEvaluator TR::TreeEvaluator::ifacmpeqEvaluator
#define ifacmpnePowerEvaluator TR::TreeEvaluator::ifacmpneEvaluator
#define ifacmpltPowerEvaluator TR::TreeEvaluator::ifacmpltEvaluator
#define ifacmpgePowerEvaluator TR::TreeEvaluator::ifacmpgeEvaluator
#define ifacmpgtPowerEvaluator TR::TreeEvaluator::ifacmpgtEvaluator
#define ifacmplePowerEvaluator TR::TreeEvaluator::ifacmpleEvaluator
#define ifbcmpeqPowerEvaluator TR::TreeEvaluator::ificmpeqEvaluator
#define ifbcmpnePowerEvaluator TR::TreeEvaluator::ificmpeqEvaluator
#define ifbcmpltPowerEvaluator TR::TreeEvaluator::ificmpltEvaluator
#define ifbcmpgePowerEvaluator TR::TreeEvaluator::ificmpgeEvaluator
#define ifbcmpgtPowerEvaluator TR::TreeEvaluator::ificmpgtEvaluator
#define ifbcmplePowerEvaluator TR::TreeEvaluator::ificmpleEvaluator
#define ifbucmpltPowerEvaluator TR::TreeEvaluator::ifiucmpltEvaluator
#define ifbucmpgePowerEvaluator TR::TreeEvaluator::ifiucmpgeEvaluator
#define ifbucmpgtPowerEvaluator TR::TreeEvaluator::ifiucmpgtEvaluator
#define ifbucmplePowerEvaluator TR::TreeEvaluator::ifiucmpleEvaluator
#define ifscmpeqPowerEvaluator TR::TreeEvaluator::ificmpeqEvaluator
#define ifscmpnePowerEvaluator TR::TreeEvaluator::ificmpeqEvaluator
#define ifscmpltPowerEvaluator TR::TreeEvaluator::ificmpltEvaluator
#define ifscmpgePowerEvaluator TR::TreeEvaluator::ificmpgeEvaluator
#define ifscmpgtPowerEvaluator TR::TreeEvaluator::ificmpgtEvaluator
#define ifscmplePowerEvaluator TR::TreeEvaluator::ificmpleEvaluator
#define ifsucmpltPowerEvaluator TR::TreeEvaluator::ifiucmpltEvaluator
#define ifsucmpgePowerEvaluator TR::TreeEvaluator::ifiucmpgeEvaluator
#define ifsucmpgtPowerEvaluator TR::TreeEvaluator::ifiucmpgtEvaluator
#define ifsucmplePowerEvaluator TR::TreeEvaluator::ifiucmpleEvaluator
#define loadaddrPowerEvaluator TR::TreeEvaluator::loadaddrEvaluator
#define ZEROCHKPowerEvaluator TR::TreeEvaluator::ZEROCHKEvaluator
#define callIfPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iRegLoadPowerEvaluator TR::TreeEvaluator::gprRegLoadEvaluator
#define aRegLoadPowerEvaluator TR::TreeEvaluator::gprRegLoadEvaluator
#define lRegLoadPowerEvaluator TR::TreeEvaluator::gprRegLoadEvaluator
#define fRegLoadPowerEvaluator TR::TreeEvaluator::fRegLoadEvaluator
#define dRegLoadPowerEvaluator TR::TreeEvaluator::dRegLoadEvaluator
#define sRegLoadPowerEvaluator TR::TreeEvaluator::gprRegLoadEvaluator
#define bRegLoadPowerEvaluator TR::TreeEvaluator::gprRegLoadEvaluator
#define iRegStorePowerEvaluator TR::TreeEvaluator::gprRegStoreEvaluator
#define aRegStorePowerEvaluator TR::TreeEvaluator::gprRegStoreEvaluator
#define lRegStorePowerEvaluator TR::TreeEvaluator::gprRegStoreEvaluator
#define fRegStorePowerEvaluator TR::TreeEvaluator::fRegStoreEvaluator
#define dRegStorePowerEvaluator TR::TreeEvaluator::fRegStoreEvaluator
#define sRegStorePowerEvaluator TR::TreeEvaluator::gprRegStoreEvaluator
#define bRegStorePowerEvaluator TR::TreeEvaluator::gprRegStoreEvaluator
#define GlRegDepsPowerEvaluator TR::TreeEvaluator::GlRegDepsEvaluator
#define iselectPowerEvaluator TR::TreeEvaluator::iselectEvaluator
#define lselectPowerEvaluator TR::TreeEvaluator::iselectEvaluator
#define bselectPowerEvaluator TR::TreeEvaluator::iselectEvaluator
#define sselectPowerEvaluator TR::TreeEvaluator::iselectEvaluator
#define aselectPowerEvaluator TR::TreeEvaluator::iselectEvaluator
#define fselectPowerEvaluator TR::TreeEvaluator::iselectEvaluator
#define dselectPowerEvaluator TR::TreeEvaluator::iselectEvaluator
#define treetopPowerEvaluator TR::TreeEvaluator::treetopEvaluator
#define MethodEnterHookPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define MethodExitHookPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define PassThroughPowerEvaluator TR::TreeEvaluator::passThroughEvaluator
#define compressedRefsPowerEvaluator TR::TreeEvaluator::compressedRefsEvaluator
#define BBStartPowerEvaluator TR::TreeEvaluator::BBStartEvaluator
#define BBEndPowerEvaluator TR::TreeEvaluator::BBEndEvaluator
#define viremPowerEvaluator TR::TreeEvaluator::viremEvaluator
#define viminPowerEvaluator TR::TreeEvaluator::viminEvaluator
#define vimaxPowerEvaluator TR::TreeEvaluator::vimaxEvaluator
#define vigetelemPowerEvaluator TR::TreeEvaluator::vigetelemEvaluator
#define visetelemPowerEvaluator TR::TreeEvaluator::visetelemEvaluator
#define vimergelPowerEvaluator TR::TreeEvaluator::vimergeEvaluator
#define vimergehPowerEvaluator TR::TreeEvaluator::vimergeEvaluator
#define vicmpeqPowerEvaluator TR::TreeEvaluator::vicmpeqEvaluator
#define vicmpgtPowerEvaluator TR::TreeEvaluator::vicmpgtEvaluator
#define vicmpgePowerEvaluator TR::TreeEvaluator::vicmpgeEvaluator
#define vicmpltPowerEvaluator TR::TreeEvaluator::vicmpltEvaluator
#define vicmplePowerEvaluator TR::TreeEvaluator::vicmpleEvaluator
#define vicmpalleqPowerEvaluator TR::TreeEvaluator::vicmpalleqEvaluator
#define vicmpallnePowerEvaluator TR::TreeEvaluator::vicmpallneEvaluator
#define vicmpallgtPowerEvaluator TR::TreeEvaluator::vicmpallgtEvaluator
#define vicmpallgePowerEvaluator TR::TreeEvaluator::vicmpallgeEvaluator
#define vicmpallltPowerEvaluator TR::TreeEvaluator::vicmpallltEvaluator
#define vicmpalllePowerEvaluator TR::TreeEvaluator::vicmpallleEvaluator
#define vicmpanyeqPowerEvaluator TR::TreeEvaluator::vicmpanyeqEvaluator
#define vicmpanynePowerEvaluator TR::TreeEvaluator::vicmpanyneEvaluator
#define vicmpanygtPowerEvaluator TR::TreeEvaluator::vicmpanygtEvaluator
#define vicmpanygePowerEvaluator TR::TreeEvaluator::vicmpanygeEvaluator
#define vicmpanyltPowerEvaluator TR::TreeEvaluator::vicmpanyltEvaluator
#define vicmpanylePowerEvaluator TR::TreeEvaluator::vicmpanyleEvaluator
#define vnotPowerEvaluator TR::TreeEvaluator::vnotEvaluator
#define vbitselectPowerEvaluator TR::TreeEvaluator::vbitselectEvaluator
#define vpermPowerEvaluator TR::TreeEvaluator::vpermEvaluator
#define vsplatsPowerEvaluator TR::TreeEvaluator::vsplatsEvaluator
#define vdmergelPowerEvaluator TR::TreeEvaluator::vdmergeEvaluator
#define vdmergehPowerEvaluator TR::TreeEvaluator::vdmergeEvaluator
#define vdsetelemPowerEvaluator TR::TreeEvaluator::vdsetelemEvaluator
#define vdgetelemPowerEvaluator TR::TreeEvaluator::vdgetelemEvaluator
#define vdselPowerEvaluator TR::TreeEvaluator::vdselEvaluator
#define vdremPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdmaddPowerEvaluator TR::TreeEvaluator::vdmaddEvaluator
#define vdnmsubPowerEvaluator TR::TreeEvaluator::vdnmsubEvaluator
#define vdmsubPowerEvaluator TR::TreeEvaluator::vdmsubEvaluator
#define vdmaxPowerEvaluator TR::TreeEvaluator::vdmaxEvaluator
#define vdminPowerEvaluator TR::TreeEvaluator::vdminEvaluator
#define vdcmpeqPowerEvaluator TR::TreeEvaluator::vdcmpeqEvaluator
#define vdcmpnePowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpgtPowerEvaluator TR::TreeEvaluator::vdcmpgtEvaluator
#define vdcmpgePowerEvaluator TR::TreeEvaluator::vdcmpgeEvaluator
#define vdcmpltPowerEvaluator TR::TreeEvaluator::vdcmpltEvaluator
#define vdcmplePowerEvaluator TR::TreeEvaluator::vdcmpleEvaluator
#define vdcmpalleqPowerEvaluator TR::TreeEvaluator::vdcmpalleqEvaluator
#define vdcmpallnePowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallgtPowerEvaluator TR::TreeEvaluator::vdcmpallgtEvaluator
#define vdcmpallgePowerEvaluator TR::TreeEvaluator::vdcmpallgeEvaluator
#define vdcmpallltPowerEvaluator TR::TreeEvaluator::vdcmpallltEvaluator
#define vdcmpalllePowerEvaluator TR::TreeEvaluator::vdcmpallleEvaluator
#define vdcmpanyeqPowerEvaluator TR::TreeEvaluator::vdcmpanyeqEvaluator
#define vdcmpanynePowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanygtPowerEvaluator TR::TreeEvaluator::vdcmpanygtEvaluator
#define vdcmpanygePowerEvaluator TR::TreeEvaluator::vdcmpanygeEvaluator
#define vdcmpanyltPowerEvaluator TR::TreeEvaluator::vdcmpanyltEvaluator
#define vdcmpanylePowerEvaluator TR::TreeEvaluator::vdcmpanyleEvaluator
#define vdsqrtPowerEvaluator TR::TreeEvaluator::vdsqrtEvaluator
#define vdlogPowerEvaluator TR::TreeEvaluator::vdlogEvaluator
#define vincPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdecPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vnegPowerEvaluator TR::TreeEvaluator::vnegEvaluator
#define vcomPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vaddPowerEvaluator TR::TreeEvaluator::vaddEvaluator
#define vsubPowerEvaluator TR::TreeEvaluator::vsubEvaluator
#define vmulPowerEvaluator TR::TreeEvaluator::vmulEvaluator
#define vdivPowerEvaluator TR::TreeEvaluator::vdivEvaluator
#define vremPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vandPowerEvaluator TR::TreeEvaluator::vandEvaluator
#define vorPowerEvaluator TR::TreeEvaluator::vorEvaluator
#define vxorPowerEvaluator TR::TreeEvaluator::vxorEvaluator
#define vshlPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vushrPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vshrPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpeqPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpnePowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpltPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vucmpltPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpgtPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vucmpgtPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmplePowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vucmplePowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpgePowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vucmpgePowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vloadPowerEvaluator TR::TreeEvaluator::vloadEvaluator
#define vloadiPowerEvaluator TR::TreeEvaluator::vloadEvaluator
#define vstorePowerEvaluator TR::TreeEvaluator::vstoreEvaluator
#define vstoreiPowerEvaluator TR::TreeEvaluator::vstoreEvaluator
#define vrandPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vreturnPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcallPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcalliPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vselectPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define v2vPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vl2vdPowerEvaluator TR::TreeEvaluator::vl2vdEvaluator
#define vconstPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define getvelemPowerEvaluator TR::TreeEvaluator::getvelemEvaluator
#define vsetelemPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vbRegLoadPowerEvaluator TR::TreeEvaluator::vRegLoadEvaluator
#define vsRegLoadPowerEvaluator TR::TreeEvaluator::vRegLoadEvaluator
#define viRegLoadPowerEvaluator TR::TreeEvaluator::vRegLoadEvaluator
#define vlRegLoadPowerEvaluator TR::TreeEvaluator::vRegLoadEvaluator
#define vfRegLoadPowerEvaluator TR::TreeEvaluator::vRegLoadEvaluator
#define vdRegLoadPowerEvaluator TR::TreeEvaluator::vRegLoadEvaluator
#define vbRegStorePowerEvaluator TR::TreeEvaluator::fRegStoreEvaluator
#define vsRegStorePowerEvaluator TR::TreeEvaluator::fRegStoreEvaluator
#define viRegStorePowerEvaluator TR::TreeEvaluator::fRegStoreEvaluator
#define vlRegStorePowerEvaluator TR::TreeEvaluator::fRegStoreEvaluator
#define vfRegStorePowerEvaluator TR::TreeEvaluator::fRegStoreEvaluator
#define vdRegStorePowerEvaluator TR::TreeEvaluator::fRegStoreEvaluator
#define iuloadPowerEvaluator TR::TreeEvaluator::iloadEvaluator
#define luloadPowerEvaluator TR::TreeEvaluator::lloadEvaluator
#define buloadPowerEvaluator TR::TreeEvaluator::buloadEvaluator
#define iuloadiPowerEvaluator TR::TreeEvaluator::iloadEvaluator
#define luloadiPowerEvaluator TR::TreeEvaluator::lloadEvaluator
#define buloadiPowerEvaluator TR::TreeEvaluator::buloadEvaluator
#define iustorePowerEvaluator TR::TreeEvaluator::istoreEvaluator
#define lustorePowerEvaluator TR::TreeEvaluator::lstoreEvaluator
#define bustorePowerEvaluator TR::TreeEvaluator::bstoreEvaluator
#define iustoreiPowerEvaluator TR::TreeEvaluator::istoreEvaluator
#define lustoreiPowerEvaluator TR::TreeEvaluator::lstoreEvaluator
#define bustoreiPowerEvaluator TR::TreeEvaluator::bstoreEvaluator
#define iuaddPowerEvaluator TR::TreeEvaluator::iaddEvaluator
#define luaddPowerEvaluator TR::TreeEvaluator::laddEvaluator
#define buaddPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iusubPowerEvaluator TR::TreeEvaluator::isubEvaluator
#define lusubPowerEvaluator TR::TreeEvaluator::lsubEvaluator
#define busubPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iunegPowerEvaluator TR::TreeEvaluator::inegEvaluator
#define lunegPowerEvaluator TR::TreeEvaluator::lnegEvaluator
#define f2iuPowerEvaluator TR::TreeEvaluator::d2iuEvaluator
#define f2luPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define f2buPowerEvaluator TR::TreeEvaluator::d2iuEvaluator
#define f2cPowerEvaluator TR::TreeEvaluator::d2iEvaluator
#define d2iuPowerEvaluator TR::TreeEvaluator::d2iuEvaluator
#define d2luPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define d2buPowerEvaluator TR::TreeEvaluator::d2iuEvaluator
#define d2cPowerEvaluator TR::TreeEvaluator::d2iEvaluator
#define iuRegLoadPowerEvaluator TR::TreeEvaluator::gprRegLoadEvaluator
#define luRegLoadPowerEvaluator TR::TreeEvaluator::gprRegLoadEvaluator
#define iuRegStorePowerEvaluator TR::TreeEvaluator::gprRegStoreEvaluator
#define luRegStorePowerEvaluator TR::TreeEvaluator::gprRegStoreEvaluator
#define cloadPowerEvaluator TR::TreeEvaluator::cloadEvaluator
#define cloadiPowerEvaluator TR::TreeEvaluator::cloadEvaluator
#define cstorePowerEvaluator TR::TreeEvaluator::cstoreEvaluator
#define cstoreiPowerEvaluator TR::TreeEvaluator::cstoreEvaluator
#define monentPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define monexitPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define monexitfencePowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define tstartPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define tfinishPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define tabortPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define instanceofPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define checkcastPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define checkcastAndNULLCHKPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define NewPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define newvaluePowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define newarrayPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define anewarrayPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define variableNewPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define variableNewArrayPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define multianewarrayPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define arraylengthPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define contigarraylengthPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define discontigarraylengthPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define icalliPowerEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define lcalliPowerEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define fcalliPowerEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define dcalliPowerEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define acalliPowerEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define calliPowerEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define fencePowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define luaddhPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define caddPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define aiaddPowerEvaluator TR::TreeEvaluator::iaddEvaluator
#define aiuaddPowerEvaluator TR::TreeEvaluator::iaddEvaluator
#define aladdPowerEvaluator TR::TreeEvaluator::laddEvaluator
#define aluaddPowerEvaluator TR::TreeEvaluator::laddEvaluator
#define lusubhPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define csubPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define imulhPowerEvaluator TR::TreeEvaluator::imulhEvaluator
#define iumulhPowerEvaluator TR::TreeEvaluator::imulhEvaluator
#define lmulhPowerEvaluator TR::TreeEvaluator::lmulhEvaluator
#define lumulhPowerEvaluator TR::TreeEvaluator::lmulhEvaluator
#define ibits2fPowerEvaluator TR::TreeEvaluator::ibits2fEvaluator
#define fbits2iPowerEvaluator TR::TreeEvaluator::fbits2iEvaluator
#define lbits2dPowerEvaluator TR::TreeEvaluator::lbits2dEvaluator
#define dbits2lPowerEvaluator TR::TreeEvaluator::dbits2lEvaluator
#define lookupPowerEvaluator TR::TreeEvaluator::lookupEvaluator
#define trtLookupPowerEvaluator TR::TreeEvaluator::NOPEvaluator
#define CasePowerEvaluator TR::TreeEvaluator::NOPEvaluator
#define tablePowerEvaluator TR::TreeEvaluator::tableEvaluator
#define exceptionRangeFencePowerEvaluator TR::TreeEvaluator::exceptionRangeFenceEvaluator
#define dbgFencePowerEvaluator TR::TreeEvaluator::exceptionRangeFenceEvaluator
#define NULLCHKPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ResolveCHKPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ResolveAndNULLCHKPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define DIVCHKPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define OverflowCHKPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define UnsignedOverflowCHKPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define BNDCHKPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ArrayCopyBNDCHKPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define BNDCHKwithSpineCHKPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define SpineCHKPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ArrayStoreCHKPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ArrayCHKPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define RetPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define arraycopyPowerEvaluator TR::TreeEvaluator::arraycopyEvaluator
#define arraysetPowerEvaluator TR::TreeEvaluator::arraysetEvaluator
#define arraytranslatePowerEvaluator TR::TreeEvaluator::arraytranslateEvaluator
#define arraytranslateAndTestPowerEvaluator TR::TreeEvaluator::arraytranslateAndTestEvaluator
#define long2StringPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define bitOpMemPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define bitOpMemNDPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define arraycmpPowerEvaluator TR::TreeEvaluator::arraycmpEvaluator
#define arraycmpWithPadPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define allocationFencePowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define loadFencePowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define storeFencePowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define fullFencePowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define MergeNewPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define computeCCPowerEvaluator TR::TreeEvaluator::computeCCEvaluator
#define butestPowerEvaluator TR::TreeEvaluator::butestEvaluator
#define sutestPowerEvaluator TR::TreeEvaluator::sutestEvaluator
#define bucmpPowerEvaluator TR::TreeEvaluator::iucmpEvaluator
#define bcmpPowerEvaluator TR::TreeEvaluator::icmpEvaluator
#define sucmpPowerEvaluator TR::TreeEvaluator::iucmpEvaluator
#define scmpPowerEvaluator TR::TreeEvaluator::icmpEvaluator
#define iucmpPowerEvaluator TR::TreeEvaluator::iucmpEvaluator
#define icmpPowerEvaluator TR::TreeEvaluator::icmpEvaluator
#define lucmpPowerEvaluator TR::TreeEvaluator::iucmpEvaluator
#define ificmpoPowerEvaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define ificmpnoPowerEvaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define iflcmpoPowerEvaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define iflcmpnoPowerEvaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define ificmnoPowerEvaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define ificmnnoPowerEvaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define iflcmnoPowerEvaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define iflcmnnoPowerEvaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define iuaddcPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define luaddcPowerEvaluator TR::TreeEvaluator::laddEvaluator
#define iusubbPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define lusubbPowerEvaluator TR::TreeEvaluator::lsubEvaluator
#define icmpsetPowerEvaluator TR::TreeEvaluator::cmpsetEvaluator
#define lcmpsetPowerEvaluator TR::TreeEvaluator::cmpsetEvaluator
#define bztestnsetPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ibatomicorPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define isatomicorPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define iiatomicorPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ilatomicorPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define dexpPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define branchPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define igotoPowerEvaluator TR::TreeEvaluator::igotoEvaluator
#define bexpPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define buexpPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define sexpPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define cexpPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iexpPowerEvaluator TR::TreeEvaluator::iexpEvaluator
#define iuexpPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define lexpPowerEvaluator TR::TreeEvaluator::lexpEvaluator
#define luexpPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fexpPowerEvaluator TR::TreeEvaluator::dexpEvaluator
#define fuexpPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define duexpPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define ixfrsPowerEvaluator TR::TreeEvaluator::ixfrsEvaluator
#define lxfrsPowerEvaluator TR::TreeEvaluator::lxfrsEvaluator
#define fxfrsPowerEvaluator TR::TreeEvaluator::dxfrsEvaluator
#define dxfrsPowerEvaluator TR::TreeEvaluator::dxfrsEvaluator
#define fintPowerEvaluator TR::TreeEvaluator::dintEvaluator
#define dintPowerEvaluator TR::TreeEvaluator::dintEvaluator
#define fnintPowerEvaluator TR::TreeEvaluator::dnintEvaluator
#define dnintPowerEvaluator TR::TreeEvaluator::dnintEvaluator
#define fsqrtPowerEvaluator TR::TreeEvaluator::fsqrtEvaluator
#define dsqrtPowerEvaluator TR::TreeEvaluator::dsqrtEvaluator
#define getstackPowerEvaluator TR::TreeEvaluator::getstackEvaluator
#define deallocaPowerEvaluator TR::TreeEvaluator::deallocaEvaluator
#define idozPowerEvaluator TR::TreeEvaluator::idozEvaluator
#define dcosPowerEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define dsinPowerEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define dtanPowerEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define dcoshPowerEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define dsinhPowerEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define dtanhPowerEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define dacosPowerEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define dasinPowerEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define datanPowerEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define datan2PowerEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define dlogPowerEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define dfloorPowerEvaluator TR::TreeEvaluator::dfloorEvaluator
#define ffloorPowerEvaluator TR::TreeEvaluator::dfloorEvaluator
#define dceilPowerEvaluator TR::TreeEvaluator::dfloorEvaluator
#define fceilPowerEvaluator TR::TreeEvaluator::dfloorEvaluator
#define ibranchPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define mbranchPowerEvaluator TR::TreeEvaluator::badILOpEvaluator
#define getpmPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define setpmPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define loadAutoOffsetPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define imaxPowerEvaluator TR::TreeEvaluator::maxEvaluator
#define iumaxPowerEvaluator TR::TreeEvaluator::maxEvaluator
#define lmaxPowerEvaluator TR::TreeEvaluator::maxEvaluator
#define lumaxPowerEvaluator TR::TreeEvaluator::maxEvaluator
#define fmaxPowerEvaluator TR::TreeEvaluator::maxEvaluator
#define dmaxPowerEvaluator TR::TreeEvaluator::maxEvaluator
#define iminPowerEvaluator TR::TreeEvaluator::minEvaluator
#define iuminPowerEvaluator TR::TreeEvaluator::minEvaluator
#define lminPowerEvaluator TR::TreeEvaluator::minEvaluator
#define luminPowerEvaluator TR::TreeEvaluator::minEvaluator
#define fminPowerEvaluator TR::TreeEvaluator::minEvaluator
#define dminPowerEvaluator TR::TreeEvaluator::minEvaluator
#define trtPowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define trtSimplePowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define ihbitPowerEvaluator TR::TreeEvaluator::integerHighestOneBit
#define ilbitPowerEvaluator TR::TreeEvaluator::integerLowestOneBit
#define inolzPowerEvaluator TR::TreeEvaluator::integerNumberOfLeadingZeros
#define inotzPowerEvaluator TR::TreeEvaluator::integerNumberOfTrailingZeros
#define ipopcntPowerEvaluator TR::TreeEvaluator::integerBitCount
#define lhbitPowerEvaluator TR::TreeEvaluator::longHighestOneBit
#define llbitPowerEvaluator TR::TreeEvaluator::longLowestOneBit
#define lnolzPowerEvaluator TR::TreeEvaluator::longNumberOfLeadingZeros
#define lnotzPowerEvaluator TR::TreeEvaluator::longNumberOfTrailingZeros
#define lpopcntPowerEvaluator TR::TreeEvaluator::longBitCount
#define sbyteswapPowerEvaluator TR::TreeEvaluator::sbyteswapEvaluator
#define ibyteswapPowerEvaluator TR::TreeEvaluator::ibyteswapEvaluator
#define lbyteswapPowerEvaluator TR::TreeEvaluator::lbyteswapEvaluator
#define bbitpermutePowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define sbitpermutePowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define ibitpermutePowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define lbitpermutePowerEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define PrefetchPowerEvaluator TR::TreeEvaluator::PrefetchEvaluator


#include "il/OMROpcodes.hpp"

#define GENERATE_TREE_EVAL_TABLE(\
   opcode, \
   name, \
   prop1, \
   prop2, \
   prop3, \
   prop4, \
   dataType, \
   typeProps, \
   childProps, \
   swapChildrenOpcode, \
   reverseBranchOpcode, \
   boolCompareOpcode, \
   ifCompareOpcode, \
   enumValue, \
   ...) enumValue ## PowerEvaluator,

   BadILOpPowerEvaluator,
   FOR_EACH_OPCODE(GENERATE_TREE_EVAL_TABLE)

#undef GENERATE_TREE_EVAL_TABLE

