/*******************************************************************************
 * Copyright (c) 2000, 2016 IBM Corp. and others
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which accompanies this
 * distribution and is available at http://eclipse.org/legal/epl-2.0
 * or the Apache License, Version 2.0 which accompanies this distribution
 * and is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License, v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception [1] and GNU General Public
 * License, version 2 with the OpenJDK Assembly Exception [2].
 *
 * [1] https://www.gnu.org/software/classpath/license.html
 * [2] http://openjdk.java.net/legal/assembly-exception.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
 *******************************************************************************/

// DO NOT EDIT THIS FILE!!!
// This file was generated by 'ftops.pl'.
// In order to change the information in this
// file you must edit '$OMR/compiler/p/codegen/PPCOps.ops'
// and then run 'perl $OMR/tools/compiler/p/ftops.pl'.

#include <stdint.h>                     // for uint32_t
#include "codegen/InstOpCode.hpp"       // for InstOpCode, etc
#include "p/codegen/PPCOpsDefines.hpp"  // for PPCOpProp_SyncSideEffectFree, etc

const uint32_t OMR::Power::InstOpCode::properties[PPCNumOpCodes] =
   {
// bad
0,

// add
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// add_r
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// addc
PPCOpProp_SetsCarryFlag |
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// addc_r
PPCOpProp_SetsCarryFlag |
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// addco
PPCOpProp_SetsCarryFlag |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// addco_r
PPCOpProp_SetsCarryFlag |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// adde
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// adde_r
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// addeo
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// addeo_r
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// addi
PPCOpProp_SyncSideEffectFree,

// addic
PPCOpProp_SetsCarryFlag |
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// addic_r
PPCOpProp_SetsCarryFlag |
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// addi2
PPCOpProp_SetsCarryFlag |
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// addi2_r
PPCOpProp_SetsCarryFlag |
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// addis
PPCOpProp_SyncSideEffectFree,

// addme
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// addme_r
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// addmeo
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// addmeo_r
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// addo
PPCOpProp_SetsOverflowFlag |
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// addo_r
PPCOpProp_SetsOverflowFlag |
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// addpcis
PPCOpProp_SyncSideEffectFree,

// addze
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// addze_r
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// addzeo
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// addzeo_r
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// and
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// and_r
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// andc
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// andc_r
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// addex
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// addex_r
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// andi_r
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// andis_r
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// b
PPCOpProp_BranchOp,

// ba
PPCOpProp_BranchOp,

// bctr
PPCOpProp_BranchOp |
PPCOpProp_UsesCtr,

// bctrl
PPCOpProp_BranchOp |
PPCOpProp_UsesCtr,

// bdnz
PPCOpProp_BranchOp |
PPCOpProp_UsesCtr |
PPCOpProp_SetsCtr,

// bdz
PPCOpProp_BranchOp |
PPCOpProp_UsesCtr |
PPCOpProp_SetsCtr,

// beq
PPCOpProp_BranchOp,

// beql
PPCOpProp_BranchOp,

// bfctr
PPCOpProp_BranchOp |
PPCOpProp_UsesCtr,

// bge
PPCOpProp_BranchOp,

// bgel
PPCOpProp_BranchOp,

// bgt
PPCOpProp_BranchOp,

// bgtl
PPCOpProp_BranchOp,

// bl
PPCOpProp_BranchOp,

// ble
PPCOpProp_BranchOp,

// blel
PPCOpProp_BranchOp,

// blt
PPCOpProp_BranchOp,

// bltl
PPCOpProp_BranchOp,

// bla
PPCOpProp_BranchOp,

// blr
PPCOpProp_BranchOp,

// blrl
PPCOpProp_BranchOp,

// bne
PPCOpProp_BranchOp,

// bnel
PPCOpProp_BranchOp,

// bnun
PPCOpProp_BranchOp,

// btctr
PPCOpProp_BranchOp |
PPCOpProp_UsesCtr,

// bun
PPCOpProp_BranchOp,

// beqlr
PPCOpProp_BranchOp,

// bgelr
PPCOpProp_BranchOp,

// bgtlr
PPCOpProp_BranchOp,

// blelr
PPCOpProp_BranchOp,

// bltlr
PPCOpProp_BranchOp,

// bnelr
PPCOpProp_BranchOp,

// cmp4
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// cmp8
PPCOpProp_DWord |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// cmpi4
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// cmpi8
PPCOpProp_DWord |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// cmpl4
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// cmpl8
PPCOpProp_DWord |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// cmpli4
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// cmpli8
PPCOpProp_DWord |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// cmprb
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// cmpeqb
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// cntlzd
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// cntlzd_r
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// cntlzw
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// cntlzw_r
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// crand
PPCOpProp_CRLogical |
PPCOpProp_SyncSideEffectFree,

// crandc
PPCOpProp_CRLogical |
PPCOpProp_SyncSideEffectFree,

// creqv
PPCOpProp_CRLogical |
PPCOpProp_SyncSideEffectFree,

// crnand
PPCOpProp_CRLogical |
PPCOpProp_SyncSideEffectFree,

// crnor
PPCOpProp_CRLogical |
PPCOpProp_SyncSideEffectFree,

// cror
PPCOpProp_CRLogical |
PPCOpProp_SyncSideEffectFree,

// crorc
PPCOpProp_CRLogical |
PPCOpProp_SyncSideEffectFree,

// crxor
PPCOpProp_CRLogical |
PPCOpProp_SyncSideEffectFree,

// dadd
PPCOpProp_DoubleFP |
PPCOpProp_HasRecordForm |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SyncSideEffectFree,

// dadd_r
PPCOpProp_DoubleFP |
PPCOpProp_IsRecordForm |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SyncSideEffectFree,

// darn
PPCOpProp_SyncSideEffectFree,

// dcbt
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// dcbtst
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// dcbtstt
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// dcbtt
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// dcbz
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// dcffix
PPCOpProp_DoubleFP |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormat |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SyncSideEffectFree,

// dcffix_r
PPCOpProp_DoubleFP |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormat |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SyncSideEffectFree,

// dcffixq
PPCOpProp_DoubleFP |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormat |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SyncSideEffectFree,

// dcffixq_r
PPCOpProp_DoubleFP |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormat |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SyncSideEffectFree,

// dcmpu
PPCOpProp_DoubleFP |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// dctfix
PPCOpProp_DoubleFP |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormat |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SyncSideEffectFree,

// dctfix_r
PPCOpProp_DoubleFP |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormat |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SyncSideEffectFree,

// ddedpd
PPCOpProp_DoubleFP |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// ddedpd_r
PPCOpProp_DoubleFP |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// ddiv
PPCOpProp_DoubleFP |
PPCOpProp_HasRecordForm |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SetsFPSCR |
PPCOpProp_SyncSideEffectFree,

// ddiv_r
PPCOpProp_DoubleFP |
PPCOpProp_IsRecordForm |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SetsFPSCR |
PPCOpProp_SyncSideEffectFree,

// denbcdu
PPCOpProp_DoubleFP |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// denbcdu_r
PPCOpProp_DoubleFP |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// divd
PPCOpProp_HasRecordForm |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// divd_r
PPCOpProp_IsRecordForm |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// diex
PPCOpProp_DoubleFP |
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// diex_r
PPCOpProp_DoubleFP |
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// divdo
PPCOpProp_HasRecordForm |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// divdo_r
PPCOpProp_IsRecordForm |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// divdu
PPCOpProp_HasRecordForm |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// divdu_r
PPCOpProp_IsRecordForm |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// divduo
PPCOpProp_HasRecordForm |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// divduo_r
PPCOpProp_IsRecordForm |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// divw
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// divw_r
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// divwo
PPCOpProp_HasRecordForm |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_SyncSideEffectFree,

// divwo_r
PPCOpProp_IsRecordForm |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_SyncSideEffectFree,

// divwu
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// divwu_r
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// divwuo
PPCOpProp_HasRecordForm |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_SyncSideEffectFree,

// divwuo_r
PPCOpProp_IsRecordForm |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_SyncSideEffectFree,

// dmul
PPCOpProp_DoubleFP |
PPCOpProp_HasRecordForm |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SyncSideEffectFree,

// dmul_r
PPCOpProp_DoubleFP |
PPCOpProp_IsRecordForm |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SyncSideEffectFree,

// dqua
PPCOpProp_DoubleFP |
PPCOpProp_HasRecordForm |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SetsFPSCR |
PPCOpProp_SyncSideEffectFree,

// dqua_r
PPCOpProp_DoubleFP |
PPCOpProp_IsRecordForm |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SetsFPSCR |
PPCOpProp_SyncSideEffectFree,

// drrnd
PPCOpProp_DoubleFP |
PPCOpProp_HasRecordForm |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SyncSideEffectFree,

// drrnd_r
PPCOpProp_DoubleFP |
PPCOpProp_IsRecordForm |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SyncSideEffectFree,

// drdpq
PPCOpProp_DoubleFP |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormat |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SyncSideEffectFree,

// drdpq_r
PPCOpProp_DoubleFP |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormat |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SyncSideEffectFree,

// dsub
PPCOpProp_DoubleFP |
PPCOpProp_HasRecordForm |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SyncSideEffectFree,

// dsub_r
PPCOpProp_DoubleFP |
PPCOpProp_IsRecordForm |
PPCOpProp_ReadsFPSCR |
PPCOpProp_SyncSideEffectFree,

// dtstdc
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree,

// dtstdg
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree,

// dxex
PPCOpProp_DoubleFP |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// dxex_r
PPCOpProp_DoubleFP |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// eieio
0,

// eqv
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx,

// eqv_r
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx,

// extsb
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// extsb_r
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// extsh
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// extsh_r
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// extsw
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// extsw_r
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// extswsli
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// extswsli_r
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// fabs
PPCOpProp_DoubleFP |
PPCOpProp_SingleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// fadd
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree,

// fadds
PPCOpProp_SingleFP |
PPCOpProp_SyncSideEffectFree,

// fcfid
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// fcfidu
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// fcfids
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// fcfidus
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// fcmpo
PPCOpProp_DoubleFP |
PPCOpProp_SingleFP |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// fcmpu
PPCOpProp_DoubleFP |
PPCOpProp_SingleFP |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// fcpsgn
PPCOpProp_DoubleFP |
PPCOpProp_SingleFP |
PPCOpProp_SyncSideEffectFree,

// fctid
PPCOpProp_DoubleFP |
PPCOpProp_SingleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// fctidz
PPCOpProp_DoubleFP |
PPCOpProp_SingleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// fctiw
PPCOpProp_DoubleFP |
PPCOpProp_SingleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// fctiwz
PPCOpProp_DoubleFP |
PPCOpProp_SingleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// fdiv
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree,

// fdivs
PPCOpProp_SingleFP |
PPCOpProp_SyncSideEffectFree,

// fmadd
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree,

// fmadds
PPCOpProp_SingleFP |
PPCOpProp_SyncSideEffectFree,

// fmr
PPCOpProp_DoubleFP |
PPCOpProp_SingleFP |
PPCOpProp_AltFormat |
PPCOpProp_IsRegCopy |
PPCOpProp_SyncSideEffectFree,

// fmsub
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree,

// fmsubs
PPCOpProp_SingleFP |
PPCOpProp_SyncSideEffectFree,

// fmul
PPCOpProp_DoubleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// fmuls
PPCOpProp_SingleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// fnabs
PPCOpProp_DoubleFP |
PPCOpProp_SingleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// fneg
PPCOpProp_DoubleFP |
PPCOpProp_SingleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// fnmadd
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree,

// fnmadds
PPCOpProp_SingleFP |
PPCOpProp_SyncSideEffectFree,

// fnmsub
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree,

// fnmsubs
PPCOpProp_SingleFP |
PPCOpProp_SyncSideEffectFree,

// fres
PPCOpProp_DoubleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// frim
PPCOpProp_DoubleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// frin
PPCOpProp_DoubleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// frip
PPCOpProp_DoubleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// frsp
PPCOpProp_DoubleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// frsqrte
PPCOpProp_DoubleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// fsel
PPCOpProp_DoubleFP |
PPCOpProp_SingleFP |
PPCOpProp_SyncSideEffectFree,

// fsqrt
PPCOpProp_DoubleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// fsqrts
PPCOpProp_SingleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// fsub
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree,

// fsubs
PPCOpProp_SingleFP |
PPCOpProp_SyncSideEffectFree,

// isync
PPCOpProp_IsSync,

// lbz
PPCOpProp_IsLoad,

// lbzu
PPCOpProp_UpdateForm |
PPCOpProp_IsLoad,

// lbzux
PPCOpProp_UpdateForm |
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lbzx
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// ld
PPCOpProp_IsLoad |
PPCOpProp_OffsetRequiresWordAlignment,

// ldarx
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// ldmx
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lwzmx
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// ldu
PPCOpProp_UpdateForm |
PPCOpProp_IsLoad |
PPCOpProp_OffsetRequiresWordAlignment,

// ldux
PPCOpProp_UpdateForm |
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// ldx
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lfd
PPCOpProp_DoubleFP |
PPCOpProp_IsLoad,

// lfdp
PPCOpProp_DoubleFP |
PPCOpProp_IsLoad,

// lfdu
PPCOpProp_DoubleFP |
PPCOpProp_UpdateForm |
PPCOpProp_IsLoad,

// lfdux
PPCOpProp_DoubleFP |
PPCOpProp_UpdateForm |
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lfdx
PPCOpProp_DoubleFP |
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lfdpx
PPCOpProp_DoubleFP |
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lfiwax
PPCOpProp_DoubleFP |
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lfiwzx
PPCOpProp_DoubleFP |
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lfs
PPCOpProp_SingleFP |
PPCOpProp_IsLoad,

// lfsu
PPCOpProp_SingleFP |
PPCOpProp_UpdateForm |
PPCOpProp_IsLoad,

// lfsux
PPCOpProp_SingleFP |
PPCOpProp_UpdateForm |
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lfsx
PPCOpProp_SingleFP |
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lha
PPCOpProp_IsLoad,

// lhau
PPCOpProp_UpdateForm |
PPCOpProp_IsLoad,

// lhaux
PPCOpProp_UpdateForm |
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lhax
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lhbrx
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lhz
PPCOpProp_IsLoad,

// lhzu
PPCOpProp_UpdateForm |
PPCOpProp_IsLoad,

// lhzux
PPCOpProp_UpdateForm |
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lhzx
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// li
PPCOpProp_SyncSideEffectFree,

// lis
PPCOpProp_SyncSideEffectFree,

// lmw
PPCOpProp_IsLoad,

// lswi
PPCOpProp_IsLoad,

// lswx
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lwa
PPCOpProp_IsLoad |
PPCOpProp_OffsetRequiresWordAlignment,

// lwarx
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lwaux
PPCOpProp_UpdateForm |
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lwax
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lwbrx
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// ldbrx
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lwsync
PPCOpProp_IsSync,

// lwz
PPCOpProp_IsLoad,

// lwzu
PPCOpProp_UpdateForm |
PPCOpProp_IsLoad,

// lwzux
PPCOpProp_UpdateForm |
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// lwzx
PPCOpProp_IsLoad |
PPCOpProp_AltFormat,

// maddld
PPCOpProp_SyncSideEffectFree,

// mcrf
PPCOpProp_SyncSideEffectFree,

// mcrfs
PPCOpProp_ReadsFPSCR |
PPCOpProp_SyncSideEffectFree,

// mcrxr
PPCOpProp_SyncSideEffectFree,

// mfcr
PPCOpProp_SyncSideEffectFree,

// mfocrf
PPCOpProp_SyncSideEffectFree,

// mfctr
PPCOpProp_UsesCtr |
PPCOpProp_SyncSideEffectFree,

// mffgpr
PPCOpProp_DoubleFP |
PPCOpProp_SingleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// mffs
PPCOpProp_SyncSideEffectFree,

// mflr
PPCOpProp_SyncSideEffectFree,

// mfmsr
PPCOpProp_SyncSideEffectFree,

// mfspr
PPCOpProp_SyncSideEffectFree,

// mftexasr
PPCOpProp_SyncSideEffectFree,

// mftexasru
PPCOpProp_SyncSideEffectFree,

// mftgpr
PPCOpProp_DoubleFP |
PPCOpProp_SingleFP |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// modud
PPCOpProp_SyncSideEffectFree,

// modsd
PPCOpProp_SyncSideEffectFree,

// moduw
PPCOpProp_SyncSideEffectFree,

// modsw
PPCOpProp_SyncSideEffectFree,

// mr
PPCOpProp_AltFormatx |
PPCOpProp_IsRegCopy |
PPCOpProp_SyncSideEffectFree,

// mtcrf
PPCOpProp_SyncSideEffectFree,

// mtctr
PPCOpProp_AltFormat |
PPCOpProp_SetsCtr |
PPCOpProp_SyncSideEffectFree,

// mtfsb0
PPCOpProp_SetsFPSCR |
PPCOpProp_SyncSideEffectFree,

// mtfsb1
PPCOpProp_SetsFPSCR |
PPCOpProp_SyncSideEffectFree,

// mtfsfl
PPCOpProp_AltFormatx |
PPCOpProp_HasRecordForm |
PPCOpProp_SetsFPSCR |
PPCOpProp_SyncSideEffectFree,

// mtfsfl_r
PPCOpProp_AltFormatx |
PPCOpProp_IsRecordForm |
PPCOpProp_SetsFPSCR |
PPCOpProp_SyncSideEffectFree,

// mtfsf
PPCOpProp_AltFormatx |
PPCOpProp_HasRecordForm |
PPCOpProp_SetsFPSCR |
PPCOpProp_SyncSideEffectFree,

// mtfsf_r
PPCOpProp_AltFormatx |
PPCOpProp_IsRecordForm |
PPCOpProp_SetsFPSCR |
PPCOpProp_SyncSideEffectFree,

// mtfsfw
PPCOpProp_AltFormatx |
PPCOpProp_HasRecordForm |
PPCOpProp_SetsFPSCR |
PPCOpProp_SyncSideEffectFree,

// mtfsfw_r
PPCOpProp_AltFormatx |
PPCOpProp_IsRecordForm |
PPCOpProp_SetsFPSCR |
PPCOpProp_SyncSideEffectFree,

// mtfsfi
PPCOpProp_AltFormatx |
PPCOpProp_HasRecordForm |
PPCOpProp_SetsFPSCR |
PPCOpProp_SyncSideEffectFree,

// mtfsfi_r
PPCOpProp_AltFormatx |
PPCOpProp_IsRecordForm |
PPCOpProp_SetsFPSCR |
PPCOpProp_SyncSideEffectFree,

// mtlr
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// mtmsr
PPCOpProp_SyncSideEffectFree,

// mtspr
PPCOpProp_SyncSideEffectFree,

// mfvsrd
PPCOpProp_IsVSX |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// mfvsrwz
PPCOpProp_IsVSX |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// mtvsrd
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// mtvsrwz
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// mtvsrwa
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// mulhd
PPCOpProp_HasRecordForm |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// mulhd_r
PPCOpProp_IsRecordForm |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// mulhdu
PPCOpProp_HasRecordForm |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// mulhdu_r
PPCOpProp_IsRecordForm |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// mulhw
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// mulhw_r
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// mulhwu
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// mulhwu_r
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// mulld
PPCOpProp_HasRecordForm |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// mulld_r
PPCOpProp_IsRecordForm |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// mulldo
PPCOpProp_HasRecordForm |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// mulldo_r
PPCOpProp_IsRecordForm |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// mulli
PPCOpProp_SyncSideEffectFree,

// mullw
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// mullw_r
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// mullwo
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// mullwo_r
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// nand
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// nand_r
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// neg
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// neg_r
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// nego
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// nego_r
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// nor
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// nor_r
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// or
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// or_r
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// orc
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// orc_r
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// ori
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// oris
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// popcntd
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// popcntw
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// rfi
0,

// rldcl
PPCOpProp_IsRotateOrShift |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// rldcl_r
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// rldcr
PPCOpProp_IsRotateOrShift |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_UseMaskEnd |
PPCOpProp_SyncSideEffectFree,

// rldcr_r
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_UseMaskEnd |
PPCOpProp_SyncSideEffectFree,

// rldic
PPCOpProp_IsRotateOrShift |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// rldic_r
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// rldicl
PPCOpProp_IsRotateOrShift |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// rldicl_r
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// rldicr
PPCOpProp_IsRotateOrShift |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_UseMaskEnd |
PPCOpProp_SyncSideEffectFree,

// rldicr_r
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_UseMaskEnd |
PPCOpProp_SyncSideEffectFree,

// rldimi
PPCOpProp_IsRotateOrShift |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_UsesTarget,

// rldimi_r
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_UsesTarget,

// rlwimi
PPCOpProp_IsRotateOrShift |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_UsesTarget,

// rlwimi_r
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_UsesTarget,

// rlwinm
PPCOpProp_IsRotateOrShift |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// rlwinm_r
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// rlwnm
PPCOpProp_IsRotateOrShift |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// rlwnm_r
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// setb
PPCOpProp_SyncSideEffectFree,

// sld
PPCOpProp_IsRotateOrShift |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// sld_r
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// slw
PPCOpProp_IsRotateOrShift |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// slw_r
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// srad
PPCOpProp_IsRotateOrShift |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SetsCarryFlag |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// srad_r
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SetsCarryFlag |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// sradi
PPCOpProp_IsRotateOrShift |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SetsCarryFlag |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// sradi_r
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SetsCarryFlag |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// sraw
PPCOpProp_IsRotateOrShift |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// sraw_r
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// srawi
PPCOpProp_IsRotateOrShift |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// srawi_r
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// srd
PPCOpProp_IsRotateOrShift |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// srd_r
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_DWord |
PPCOpProp_SyncSideEffectFree,

// srw
PPCOpProp_IsRotateOrShift |
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// srw_r
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// stb
PPCOpProp_IsStore,

// stbu
PPCOpProp_UpdateForm |
PPCOpProp_IsStore,

// stbux
PPCOpProp_UpdateForm |
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// stbx
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// std
PPCOpProp_IsStore |
PPCOpProp_OffsetRequiresWordAlignment,

// stdcx_r
PPCOpProp_IsStore |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormat,

// stdu
PPCOpProp_UpdateForm |
PPCOpProp_IsStore |
PPCOpProp_OffsetRequiresWordAlignment,

// stdux
PPCOpProp_UpdateForm |
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// stdx
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// stfd
PPCOpProp_DoubleFP |
PPCOpProp_IsStore,

// stfdp
PPCOpProp_DoubleFP |
PPCOpProp_IsStore,

// stfdu
PPCOpProp_UpdateForm |
PPCOpProp_DoubleFP |
PPCOpProp_IsStore,

// stfdux
PPCOpProp_UpdateForm |
PPCOpProp_DoubleFP |
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// stfdx
PPCOpProp_DoubleFP |
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// stfdpx
PPCOpProp_DoubleFP |
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// stfiwx
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// stfs
PPCOpProp_SingleFP |
PPCOpProp_IsStore,

// stfsu
PPCOpProp_UpdateForm |
PPCOpProp_SingleFP |
PPCOpProp_IsStore,

// stfsux
PPCOpProp_UpdateForm |
PPCOpProp_SingleFP |
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// stfsx
PPCOpProp_SingleFP |
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// sth
PPCOpProp_IsStore,

// sthbrx
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// sthu
PPCOpProp_UpdateForm |
PPCOpProp_IsStore,

// sthux
PPCOpProp_UpdateForm |
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// sthx
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// stmw
PPCOpProp_IsStore,

// stswi
PPCOpProp_IsStore,

// stswx
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// stw
PPCOpProp_IsStore,

// stwbrx
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// stdbrx
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// stwcx_r
PPCOpProp_IsStore |
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormat,

// stwu
PPCOpProp_UpdateForm |
PPCOpProp_IsStore,

// stwux
PPCOpProp_UpdateForm |
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// stwx
PPCOpProp_IsStore |
PPCOpProp_AltFormat,

// subf
PPCOpProp_HasRecordForm |
PPCOpProp_SyncSideEffectFree,

// subf_r
PPCOpProp_IsRecordForm |
PPCOpProp_SyncSideEffectFree,

// subfc
PPCOpProp_HasRecordForm |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// subfc_r
PPCOpProp_IsRecordForm |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// subfco
PPCOpProp_HasRecordForm |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// subfco_r
PPCOpProp_IsRecordForm |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// subfe
PPCOpProp_HasRecordForm |
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// subfe_r
PPCOpProp_IsRecordForm |
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// subfeo
PPCOpProp_HasRecordForm |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// subfeo_r
PPCOpProp_IsRecordForm |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// subfic
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// subfme
PPCOpProp_HasRecordForm |
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// subfme_r
PPCOpProp_IsRecordForm |
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// subfmeo
PPCOpProp_HasRecordForm |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// subfmeo_r
PPCOpProp_IsRecordForm |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// subfze
PPCOpProp_HasRecordForm |
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// subfze_r
PPCOpProp_IsRecordForm |
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// subfzeo
PPCOpProp_HasRecordForm |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// subfzeo_r
PPCOpProp_IsRecordForm |
PPCOpProp_SetsOverflowFlag |
PPCOpProp_ReadsCarryFlag |
PPCOpProp_SetsCarryFlag |
PPCOpProp_SyncSideEffectFree,

// sync
PPCOpProp_IsSync,

// tabort_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortdeq_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdeqi_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdge_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdgei_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdgt_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdgti_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdle_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdlei_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdlge_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdlgei_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdlgt_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdlgti_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdlle_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdllei_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdllt_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdllti_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdlt_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdlti_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdneq_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortdneqi_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm |
PPCOpProp_DWord,

// tabortweq_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortweqi_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortwge_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortwgei_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortwgt_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortwgti_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortwle_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortwlei_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortwlge_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortwlgei_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortwlgt_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortwlgti_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortwlle_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortwllei_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortwllt_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortwllti_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortwlt_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortwlti_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortwneq_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tabortwneqi_r
PPCOpProp_TMAbort |
PPCOpProp_IsRecordForm,

// tbegin_r
PPCOpProp_IsRecordForm,

// tbeginro_r
PPCOpProp_IsRecordForm,

// tend_r
PPCOpProp_IsRecordForm,

// tendall_r
PPCOpProp_IsRecordForm,

// tdeq
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdeqi
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdge
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdgei
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdgt
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdgti
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdle
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdlei
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdlge
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdlgei
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdlgt
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdlgti
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdlle
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdllei
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdllt
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdllti
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdlt
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdlti
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdneq
PPCOpProp_Trap |
PPCOpProp_DWord,

// tdneqi
PPCOpProp_Trap |
PPCOpProp_DWord,

// trap
PPCOpProp_Trap,

// tweq
PPCOpProp_Trap,

// tweqi
PPCOpProp_Trap,

// twge
PPCOpProp_Trap,

// twgei
PPCOpProp_Trap,

// twgt
PPCOpProp_Trap,

// twgti
PPCOpProp_Trap,

// twle
PPCOpProp_Trap,

// twlei
PPCOpProp_Trap,

// twlge
PPCOpProp_Trap,

// twlgei
PPCOpProp_Trap,

// twlgt
PPCOpProp_Trap,

// twlgti
PPCOpProp_Trap,

// twlle
PPCOpProp_Trap,

// twllei
PPCOpProp_Trap,

// twllt
PPCOpProp_Trap,

// twllti
PPCOpProp_Trap,

// twlt
PPCOpProp_Trap,

// twlti
PPCOpProp_Trap,

// twneq
PPCOpProp_Trap,

// twneqi
PPCOpProp_Trap,

// xor
PPCOpProp_HasRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// xor_r
PPCOpProp_IsRecordForm |
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// xori
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// xoris
PPCOpProp_AltFormatx |
PPCOpProp_SyncSideEffectFree,

// nop
PPCOpProp_SyncSideEffectFree,

// genop
PPCOpProp_SyncSideEffectFree,

// fence
PPCOpProp_SyncSideEffectFree,

// shdfence
PPCOpProp_SyncSideEffectFree,

// ret
0,

// wrtbar
0,

// proc
0,

// dd
0,

// assocreg
PPCOpProp_SyncSideEffectFree,

// vgdnop
0,

// depend
0,

// probenop
PPCOpProp_SyncSideEffectFree,

// iflong
PPCOpProp_BranchOp,

// setblong
0,

// setbool
0,

// setbflt
0,

// lcmp
0,

// flcmpl
0,

// flcmpg
0,

// idiv
0,

// ldiv
0,

// irem
0,

// lrem
0,

// cdnan
0,

// cfnan
0,

// d2i
0,

// d2l
0,

// ifx
PPCOpProp_BranchOp,

// setbx
0,

// iternary
0,

// lvsl
PPCOpProp_IsLoad |
PPCOpProp_IsVMX,

// lvsr
PPCOpProp_IsLoad |
PPCOpProp_IsVMX,

// lvx
PPCOpProp_IsLoad |
PPCOpProp_IsVMX,

// lvebx
PPCOpProp_IsLoad |
PPCOpProp_IsVMX,

// lvehx
PPCOpProp_IsLoad |
PPCOpProp_IsVMX,

// lvewx
PPCOpProp_IsLoad |
PPCOpProp_IsVMX,

// stvx
PPCOpProp_IsStore |
PPCOpProp_IsVMX,

// stvebx
PPCOpProp_IsStore |
PPCOpProp_IsVMX,

// stvehx
PPCOpProp_IsStore |
PPCOpProp_IsVMX,

// stvewx
PPCOpProp_IsStore |
PPCOpProp_IsVMX,

// vand
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vandc
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vor
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vxor
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vnor
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vperm
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsel
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsumsws
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsum2sws
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsum4sbs
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsum4shs
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsum4ubs
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vspltb
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// vsplth
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// vspltw
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// vspltisb
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vspltish
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vspltisw
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsl
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vslb
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsldoi
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vslh
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vslo
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vslw
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsr
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsrab
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsrah
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsraw
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsrb
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsrh
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsro
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsrw
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vrlb
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vrlh
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vrlw
PPCOpProp_IsRotateOrShift |
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vaddsbs
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vaddshs
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vaddsws
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vaddubm
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vaddubs
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vaddudm
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vadduhm
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vadduhs
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vadduwm
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vadduws
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsubsbs
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsubshs
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsubsws
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsububm
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsububs
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsubudm
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsubuhm
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsubuhs
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsubuwm
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vsubuws
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vmulesh
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vmulosh
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vmulouh
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vmuluwm
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vminsb
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vminsh
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vminsw
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vminub
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vminuh
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vminuw
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vmaxsb
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vmaxsh
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vmaxsw
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vmaxub
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vmaxuh
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vmaxuw
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vmsumuhm
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vcmpequb
PPCOpProp_IsVMX |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// vcmpeubr
PPCOpProp_IsVMX |
PPCOpProp_IsRecordForm |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// vcmpequh
PPCOpProp_IsVMX |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// vcmpeuhr
PPCOpProp_IsVMX |
PPCOpProp_IsRecordForm |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// vcmpequw
PPCOpProp_IsVMX |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// vcmpeuwr
PPCOpProp_IsVMX |
PPCOpProp_IsRecordForm |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// vcmpgtsb
PPCOpProp_IsVMX |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// vcmpgsbr
PPCOpProp_IsVMX |
PPCOpProp_IsRecordForm |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// vcmpgtsh
PPCOpProp_IsVMX |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// vcmpgshr
PPCOpProp_IsVMX |
PPCOpProp_IsRecordForm |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// vcmpgtsw
PPCOpProp_IsVMX |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// vcmpgswr
PPCOpProp_IsVMX |
PPCOpProp_IsRecordForm |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// vcmpgtub
PPCOpProp_IsVMX |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// vcmpgubr
PPCOpProp_IsVMX |
PPCOpProp_IsRecordForm |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// vcmpgtuh
PPCOpProp_IsVMX |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// vcmpguhr
PPCOpProp_IsVMX |
PPCOpProp_IsRecordForm |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// vcmpgtuw
PPCOpProp_IsVMX |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// vcmpguwr
PPCOpProp_IsVMX |
PPCOpProp_IsRecordForm |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// vupkhsb
PPCOpProp_IsVMX |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// vupkhsh
PPCOpProp_IsVMX |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// vupklsb
PPCOpProp_IsVMX |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// vupklsh
PPCOpProp_IsVMX |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// vpkuhum
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vpkuwum
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vmrghb
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vmrghh
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vmrghw
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vmrglb
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vmrglh
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// vmrglw
PPCOpProp_IsVMX |
PPCOpProp_SyncSideEffectFree,

// lxsdx
PPCOpProp_DoubleFP |
PPCOpProp_IsLoad |
PPCOpProp_IsVSX |
PPCOpProp_AltFormat,

// lxsdux
PPCOpProp_DoubleFP |
PPCOpProp_IsLoad |
PPCOpProp_IsVSX |
PPCOpProp_UpdateForm |
PPCOpProp_AltFormat,

// stxsdx
PPCOpProp_DoubleFP |
PPCOpProp_IsStore |
PPCOpProp_IsVSX |
PPCOpProp_AltFormat,

// stxsdux
PPCOpProp_DoubleFP |
PPCOpProp_IsStore |
PPCOpProp_IsVSX |
PPCOpProp_UpdateForm |
PPCOpProp_AltFormat,

// lxvd2x
PPCOpProp_IsLoad |
PPCOpProp_IsVSX |
PPCOpProp_AltFormat,

// lxvd2ux
PPCOpProp_IsLoad |
PPCOpProp_IsVSX |
PPCOpProp_UpdateForm |
PPCOpProp_AltFormat,

// lxvdsx
PPCOpProp_IsLoad |
PPCOpProp_IsVSX |
PPCOpProp_AltFormat,

// lxvw4x
PPCOpProp_IsLoad |
PPCOpProp_IsVSX |
PPCOpProp_AltFormat,

// lxvw4ux
PPCOpProp_IsLoad |
PPCOpProp_IsVSX |
PPCOpProp_UpdateForm |
PPCOpProp_AltFormat,

// stxvd2x
PPCOpProp_IsStore |
PPCOpProp_IsVSX |
PPCOpProp_AltFormat,

// stxvd2ux
PPCOpProp_IsStore |
PPCOpProp_IsVSX |
PPCOpProp_UpdateForm |
PPCOpProp_AltFormat,

// stxvw4x
PPCOpProp_IsStore |
PPCOpProp_IsVSX |
PPCOpProp_AltFormat,

// stxvw4ux
PPCOpProp_IsStore |
PPCOpProp_IsVSX |
PPCOpProp_UpdateForm |
PPCOpProp_AltFormat,

// xsabsdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// xsadddp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xscmpodp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// xscmpudp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_CompareOp |
PPCOpProp_SyncSideEffectFree,

// xscpsgndp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_IsRegCopy |
PPCOpProp_SyncSideEffectFree,

// xscvdpsxds
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// xscvdpsxws
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// xsdivdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsmaddadp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsmaddmdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsmsubadp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsmsubmdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsmuldp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsnabsdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// xsnegdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// xsnmaddadp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsnmaddmdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsnmsubadp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsnmsubmdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsrdpic
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// xsredp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// xsrsqrtedp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// xxlor
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xxlnor
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xxsel
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xxsldwi
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xxspltw
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xxpermdi
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xssqrtdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// xssubdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xscvsxddp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// xscvdpsp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_AltFormat |
PPCOpProp_SyncSideEffectFree,

// xvadddp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvmindp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvmaxdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvcmpeqdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_CompareOp,

// xvcmpeqdp_r
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_CompareOp |
PPCOpProp_IsRecordForm,

// xvcmpgedp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_CompareOp,

// xvcmpgedp_r
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_CompareOp |
PPCOpProp_IsRecordForm,

// xvcmpgtdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_CompareOp,

// xvcmpgtdp_r
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_CompareOp |
PPCOpProp_IsRecordForm,

// xvdivdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvmuldp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvnegdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvnmsubadp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_UsesTarget,

// xvnmsubmdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_UsesTarget,

// xvsubdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvmaddadp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_UsesTarget,

// xvmaddmdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_UsesTarget,

// xvmsubadp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_UsesTarget,

// xvmsubmdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_UsesTarget,

// xvsqrtdp
PPCOpProp_DoubleFP |
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// fmrgew
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// fmrgow
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// lxsiwax
PPCOpProp_IsVSX |
PPCOpProp_IsLoad,

// lxsiwzx
PPCOpProp_IsVSX |
PPCOpProp_IsLoad,

// lxsspx
PPCOpProp_IsVSX |
PPCOpProp_IsLoad,

// stxsiwx
PPCOpProp_IsVSX |
PPCOpProp_IsStore,

// stxsspx
PPCOpProp_IsVSX |
PPCOpProp_IsStore,

// xsaddsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xscvdpspn
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xscvdpuxds
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xscvdpuxws
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xscvspdp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xscvspdpn
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xscvsxdsp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xscvuxddp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xscvuxdsp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xsdivsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsmaddasp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsmaddmsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsmaxdp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree,

// xsmindp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree,

// xsmsubasp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsmsubmsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsmulsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsnmaddasp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsnmaddmsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsnmsubasp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsnmsubmsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xsrdpi
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xsrdpim
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xsrdpip
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xsrdpiz
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xsresp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xsrsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xsrsqrtesp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xssqrtsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xssubsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xxland
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xxlandc
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xxleqv
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xxlnand
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xxlorc
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xxlxor
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xxmrghw
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xxmrglw
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// vmrgew
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// vmrgow
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvabsdp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvabssp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvaddsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvcmpeqsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_CompareOp,

// xvcmpeqsp_r
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_CompareOp |
PPCOpProp_IsRecordForm,

// xvcmpgesp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_CompareOp,

// xvcmpgesp_r
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_CompareOp |
PPCOpProp_IsRecordForm,

// xvcmpgtsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_CompareOp,

// xvcmpgtsp_r
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_CompareOp |
PPCOpProp_IsRecordForm,

// xvcpsgndp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree,

// xvcpsgnsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvcvdpsp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvcvdpsxds
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvcvdpsxws
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvcvdpuxds
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvcvdpuxws
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvcvspdp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvcvspsxds
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvcvspsxws
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvcvspuxds
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvcvspuxws
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvcvsxddp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvcvsxdsp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvcvsxwdp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvcvsxwsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvcvuxddp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvcvuxdsp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvcvuxwdp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvcvuxwsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvdivsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvmaddasp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvmaddmsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvmaxsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvminsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvmsubasp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvmsubmsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvmulsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvnabsdp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvnabssp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvnegsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvnmaddadp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree,

// xvnmaddasp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvnmaddmdp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree,

// xvnmaddmsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvnmsubasp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvnmsubmsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// xvrdpi
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvrdpic
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvrdpim
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvrdpip
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvrdpiz
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvredp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvresp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvrspi
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvrspic
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvrspim
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvrspip
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvrspiz
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvrsqrtedp
PPCOpProp_IsVSX |
PPCOpProp_DoubleFP |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvrsqrtesp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvsqrtsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree |
PPCOpProp_AltFormat,

// xvsubsp
PPCOpProp_IsVSX |
PPCOpProp_SyncSideEffectFree,

// label
0
};
