################################################################################
#
# (c) Copyright IBM Corp. 2016, 2016
#
#  This program and the accompanying materials are made available
#  under the terms of the Eclipse Public License v1.0 and
#  Apache License v2.0 which accompanies this distribution.
#
#      The Eclipse Public License is available at
#      http://www.eclipse.org/legal/epl-v10.html
#
#      The Apache License v2.0 is available at
#      http://www.opensource.org/licenses/apache2.0.php
#
# Contributors:
#    Multiple authors (IBM Corp.) - initial implementation and documentation
################################################################################

FROM ubuntu:14.04

MAINTAINER Mark Stoodley <mstoodle@ca.ibm.com> (@mstoodle)

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get update -y \
    && apt-get install -y apt-utils \
    && apt-get update -y \
    && apt-get install -y vim curl git gcc g++ make wget unzip man-db linux-tools-generic gdb \
    && apt-get update -y
RUN groupadd -r jitbuilder -g 433 \
    && useradd -m -u 431 -r -g jitbuilder -d /home/jitbuilder -c "JitBuilder user" jitbuilder
COPY jitbuilder.tgz /home/jitbuilder/jitbuilder.tgz
RUN chown -f jitbuilder:jitbuilder /home/jitbuilder/jitbuilder.tgz
USER jitbuilder
RUN cd /home/jitbuilder \
    && tar zxvf jitbuilder.tgz \
    && rm jitbuilder.tgz \
    && chown -fR jitbuilder:jitbuilder *
WORKDIR /home/jitbuilder

