/*******************************************************************************
 * Copyright (c) 2000, 2020 IBM Corp. and others
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which accompanies this
 * distribution and is available at http://eclipse.org/legal/epl-2.0
 * or the Apache License, Version 2.0 which accompanies this distribution
 * and is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License, v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception [1] and GNU General Public
 * License, version 2 with the OpenJDK Assembly Exception [2].
 *
 * [1] https://www.gnu.org/software/classpath/license.html
 * [2] http://openjdk.java.net/legal/assembly-exception.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
 *******************************************************************************/

/*
 * This table is #included in a static table.
 * Only Function Pointers are allowed.
 */

#define BadILOpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define aconstARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::aconstEvaluator
#define iconstARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iconstEvaluator
#define lconstARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lconstEvaluator
#define fconstARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::fconstEvaluator
#define dconstARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dconstEvaluator
#define bconstARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::bconstEvaluator
#define sconstARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::sconstEvaluator
#define iloadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iloadEvaluator
#define floadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::floadEvaluator
#define dloadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dloadEvaluator
#define aloadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::aloadEvaluator
#define bloadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::bloadEvaluator
#define sloadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::sloadEvaluator
#define lloadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lloadEvaluator
#define irdbarARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define frdbarARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define drdbarARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ardbarARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define brdbarARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define srdbarARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define lrdbarARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define iloadiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iloadEvaluator
#define floadiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::floadEvaluator
#define dloadiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dloadEvaluator
#define aloadiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::aloadEvaluator
#define bloadiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::bloadEvaluator
#define sloadiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::sloadEvaluator
#define lloadiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lloadEvaluator
#define irdbariARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define frdbariARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define drdbariARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ardbariARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define brdbariARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define srdbariARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define lrdbariARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define istoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::istoreEvaluator
#define lstoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lstoreEvaluator
#define fstoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::fstoreEvaluator
#define dstoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dstoreEvaluator
#define astoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::istoreEvaluator
#define bstoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::bstoreEvaluator
#define sstoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::sstoreEvaluator
#define iwrtbarARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define lwrtbarARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define fwrtbarARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define dwrtbarARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define awrtbarARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::awrtbarEvaluator
#define bwrtbarARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define swrtbarARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define lstoreiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lstoreEvaluator
#define fstoreiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifstoreEvaluator
#define dstoreiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::idstoreEvaluator
#define astoreiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::istoreEvaluator
#define bstoreiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::bstoreEvaluator
#define sstoreiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::sstoreEvaluator
#define istoreiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::istoreEvaluator
#define lwrtbariARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define fwrtbariARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define dwrtbariARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define awrtbariARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::awrtbariEvaluator
#define bwrtbariARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define swrtbariARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define iwrtbariARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define GotoARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::gotoEvaluator
#define ireturnARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ireturnEvaluator
#define lreturnARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lreturnEvaluator
#define freturnARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::freturnEvaluator
#define dreturnARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dreturnEvaluator
#define areturnARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ireturnEvaluator
#define ReturnARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::returnEvaluator
#define asynccheckARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::asynccheckEvaluator
#define athrowARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define icallARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::directCallEvaluator
#define lcallARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::directCallEvaluator
#define fcallARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::directCallEvaluator
#define dcallARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::directCallEvaluator
#define acallARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::directCallEvaluator
#define callARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::directCallEvaluator
#define iaddARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iaddEvaluator
#define laddARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::laddEvaluator
#define faddARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::faddEvaluator
#define daddARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::daddEvaluator
#define baddARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define saddARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define isubARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::isubEvaluator
#define lsubARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lsubEvaluator
#define fsubARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::fsubEvaluator
#define dsubARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dsubEvaluator
#define bsubARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ssubARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define asubARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define imulARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::imulEvaluator
#define lmulARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lmulEvaluator
#define fmulARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::fmulEvaluator
#define dmulARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dmulEvaluator
#define bmulARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define smulARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define idivARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::idivEvaluator
#define ldivARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ldivEvaluator
#define fdivARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::fdivEvaluator
#define ddivARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ddivEvaluator
#define bdivARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define sdivARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define iudivARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ludivARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define iremARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iremEvaluator
#define lremARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lremEvaluator
#define fremARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::fremEvaluator
#define dremARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dremEvaluator
#define bremARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define sremARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define iuremARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iremEvaluator
#define inegARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::inegEvaluator
#define lnegARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lnegEvaluator
#define fnegARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::fnegEvaluator
#define dnegARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dnegEvaluator
#define bnegARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define snegARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define iabsARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iabsEvaluator
#define labsARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::labsEvaluator
#define fabsARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::fabsEvaluator
#define dabsARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dabsEvaluator
#define ishlARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ishlEvaluator
#define lshlARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lshlEvaluator
#define bshlARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define sshlARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ishrARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ishrEvaluator
#define lshrARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lshrEvaluator
#define bshrARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define sshrARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define iushrARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iushrEvaluator
#define lushrARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lushrEvaluator
#define bushrARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define sushrARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define irolARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::irolEvaluator
#define lrolARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lrolEvaluator
#define iandARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iandEvaluator
#define landARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::landEvaluator
#define bandARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iandEvaluator
#define sandARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iandEvaluator
#define iorARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iorEvaluator
#define lorARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lorEvaluator
#define borARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iorEvaluator
#define sorARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iorEvaluator
#define ixorARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ixorEvaluator
#define lxorARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lxorEvaluator
#define bxorARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ixorEvaluator
#define sxorARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ixorEvaluator
#define i2lARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::b2lEvaluator
#define i2fARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::i2fEvaluator
#define i2dARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::i2dEvaluator
#define i2bARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::i2bEvaluator
#define i2sARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::i2sEvaluator
#define i2aARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::passThroughEvaluator
#define iu2lARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iu2lEvaluator
#define iu2fARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::i2fEvaluator
#define iu2dARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::i2dEvaluator
#define iu2aARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::passThroughEvaluator
#define l2iARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::l2iEvaluator
#define l2fARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::l2fEvaluator
#define l2dARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::l2dEvaluator
#define l2bARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::i2bEvaluator
#define l2sARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::i2sEvaluator
#define l2aARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::l2iEvaluator
#define lu2fARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define lu2dARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define lu2aARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::l2iEvaluator
#define f2iARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::f2iEvaluator
#define f2lARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::f2lEvaluator
#define f2dARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::f2dEvaluator
#define f2bARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::d2bEvaluator
#define f2sARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::d2sEvaluator
#define d2iARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::d2iEvaluator
#define d2lARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::d2lEvaluator
#define d2fARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::d2fEvaluator
#define d2bARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::d2bEvaluator
#define d2sARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::d2sEvaluator
#define b2iARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::b2iEvaluator
#define b2lARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::b2lEvaluator
#define b2fARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::i2fEvaluator
#define b2dARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::i2dEvaluator
#define b2sARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::b2iEvaluator
#define b2aARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define bu2iARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::bu2iEvaluator
#define bu2lARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::bu2lEvaluator
#define bu2fARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define bu2dARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define bu2sARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define bu2aARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define s2iARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::b2iEvaluator
#define s2lARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::b2lEvaluator
#define s2fARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::i2fEvaluator
#define s2dARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::i2dEvaluator
#define s2bARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::i2bEvaluator
#define s2aARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define su2iARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::i2cEvaluator
#define su2lARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::su2lEvaluator
#define su2fARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::i2fEvaluator
#define su2dARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::i2dEvaluator
#define su2aARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define a2iARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::passThroughEvaluator
#define a2lARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::passThroughEvaluator
#define a2bARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define a2sARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define icmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::icmpeqEvaluator
#define icmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::icmpneEvaluator
#define icmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::icmpltEvaluator
#define icmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::icmpgeEvaluator
#define icmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::icmpgtEvaluator
#define icmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::icmpleEvaluator
#define iucmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::icmpeqEvaluator
#define iucmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::icmpneEvaluator
#define iucmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iucmpltEvaluator
#define iucmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iucmpgeEvaluator
#define iucmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iucmpgtEvaluator
#define iucmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iucmpleEvaluator
#define lcmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lcmpeqEvaluator
#define lcmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lcmpneEvaluator
#define lcmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lcmpltEvaluator
#define lcmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lcmpgeEvaluator
#define lcmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lcmpgtEvaluator
#define lcmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lcmpleEvaluator
#define lucmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lcmpeqEvaluator
#define lucmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lcmpneEvaluator
#define lucmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lucmpltEvaluator
#define lucmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lucmpgeEvaluator
#define lucmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lucmpgtEvaluator
#define lucmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lucmpleEvaluator
#define fcmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpeqEvaluator
#define fcmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpneEvaluator
#define fcmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpltEvaluator
#define fcmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpgeEvaluator
#define fcmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpgtEvaluator
#define fcmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpleEvaluator
#define fcmpequARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpeqEvaluator
#define fcmpneuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpneEvaluator
#define fcmpltuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpltEvaluator
#define fcmpgeuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpgeEvaluator
#define fcmpgtuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpgtEvaluator
#define fcmpleuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpleEvaluator
#define dcmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpeqEvaluator
#define dcmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpneEvaluator
#define dcmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpltEvaluator
#define dcmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpgeEvaluator
#define dcmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpgtEvaluator
#define dcmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpleEvaluator
#define dcmpequARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpeqEvaluator
#define dcmpneuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpneEvaluator
#define dcmpltuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpltEvaluator
#define dcmpgeuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpgeEvaluator
#define dcmpgtuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpgtEvaluator
#define dcmpleuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmpleEvaluator
#define acmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::icmpeqEvaluator
#define acmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::icmpneEvaluator
#define acmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iucmpltEvaluator
#define acmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iucmpgeEvaluator
#define acmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iucmpgtEvaluator
#define acmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iucmpleEvaluator
#define bcmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define bcmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define bcmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define bcmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define bcmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define bcmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define bucmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define bucmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define bucmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define bucmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define bucmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define bucmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define scmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define scmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define scmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define scmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define scmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define scmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define sucmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define sucmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define sucmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define sucmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define sucmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define sucmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define lcmpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lcmpEvaluator
#define fcmplARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmplEvaluator
#define fcmpgARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmplEvaluator
#define dcmplARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmplEvaluator
#define dcmpgARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dcmplEvaluator
#define ificmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ificmpeqEvaluator
#define ificmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ificmpeqEvaluator
#define ificmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ificmpltEvaluator
#define ificmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ificmpgeEvaluator
#define ificmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ificmpgtEvaluator
#define ificmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ificmpleEvaluator
#define ifiucmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ificmpeqEvaluator
#define ifiucmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ificmpeqEvaluator
#define ifiucmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifiucmpltEvaluator
#define ifiucmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifiucmpgeEvaluator
#define ifiucmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifiucmpgtEvaluator
#define ifiucmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifiucmpleEvaluator
#define iflcmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iflcmpeqEvaluator
#define iflcmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iflcmpeqEvaluator
#define iflcmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iflcmpltEvaluator
#define iflcmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iflcmpgeEvaluator
#define iflcmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iflcmpgtEvaluator
#define iflcmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iflcmpleEvaluator
#define iflucmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iflcmpeqEvaluator
#define iflucmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iflcmpeqEvaluator
#define iflucmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iflucmpltEvaluator
#define iflucmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iflucmpgeEvaluator
#define iflucmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iflucmpgtEvaluator
#define iflucmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iflucmpleEvaluator
#define iffcmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpeqEvaluator
#define iffcmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpneEvaluator
#define iffcmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpltEvaluator
#define iffcmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpgeEvaluator
#define iffcmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpgtEvaluator
#define iffcmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpleEvaluator
#define iffcmpequARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpeqEvaluator
#define iffcmpneuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpneEvaluator
#define iffcmpltuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpltEvaluator
#define iffcmpgeuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpgeEvaluator
#define iffcmpgtuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpgtEvaluator
#define iffcmpleuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpleEvaluator
#define ifdcmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpeqEvaluator
#define ifdcmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpneEvaluator
#define ifdcmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpltEvaluator
#define ifdcmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpgeEvaluator
#define ifdcmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpgtEvaluator
#define ifdcmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpleEvaluator
#define ifdcmpequARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpeqEvaluator
#define ifdcmpneuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpneEvaluator
#define ifdcmpltuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpltEvaluator
#define ifdcmpgeuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpgeEvaluator
#define ifdcmpgtuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpgtEvaluator
#define ifdcmpleuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifdcmpleEvaluator
#define ifacmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ifacmpeqEvaluator
#define ifacmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ificmpeqEvaluator
#define ifacmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifacmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifacmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifacmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifbcmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifbcmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifbcmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifbcmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifbcmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifbcmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifbucmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifbucmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifbucmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifbucmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifbucmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifbucmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifscmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifscmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifscmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifscmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifscmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifscmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifsucmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifsucmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifsucmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifsucmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifsucmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ifsucmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define loadaddrARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::loadaddrEvaluator
#define ZEROCHKARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ZEROCHKEvaluator
#define callIfARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define iRegLoadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iRegLoadEvaluator
#define aRegLoadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::aRegLoadEvaluator
#define lRegLoadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lRegLoadEvaluator
#define fRegLoadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::fRegLoadEvaluator
#define dRegLoadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::fRegLoadEvaluator
#define sRegLoadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iRegLoadEvaluator
#define bRegLoadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iRegLoadEvaluator
#define iRegStoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iRegStoreEvaluator
#define aRegStoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iRegStoreEvaluator
#define lRegStoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lRegStoreEvaluator
#define fRegStoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::fRegStoreEvaluator
#define dRegStoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::fRegStoreEvaluator
#define sRegStoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iRegStoreEvaluator
#define bRegStoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iRegStoreEvaluator
#define GlRegDepsARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::GlRegDepsEvaluator
#define iselectARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define lselectARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define bselectARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define sselectARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define aselectARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define fselectARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define dselectARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define treetopARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::treetopEvaluator
#define MethodEnterHookARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define MethodExitHookARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define PassThroughARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::passThroughEvaluator
#define compressedRefsARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define BBStartARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::BBStartEvaluator
#define BBEndARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::BBEndEvaluator
#define viremARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define viminARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vimaxARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vigetelemARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define visetelemARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vimergelARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vimergehARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vicmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vicmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vicmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vicmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vicmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vicmpalleqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanygtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanygeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vnotARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vbitselectARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vpermARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vsplatsARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdmergelARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdmergehARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdsetelemARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdgetelemARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdselARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdremARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdmaddARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdnmsubARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdmsubARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdmaxARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdminARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpalleqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanygtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanygeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdsqrtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdlogARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vincARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdecARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vnegARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vcomARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vaddARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vsubARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vmulARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdivARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vremARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vandARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vorARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vxorARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vshlARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vushrARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vshrARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vcmpeqARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vcmpneARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vcmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vucmpltARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vcmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vucmpgtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vcmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vucmpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vcmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vucmpgeARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vloadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vloadiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vstoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vstoreiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vrandARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vreturnARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vcallARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vcalliARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vselectARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define v2vARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vl2vdARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vconstARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define getvelemARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vsetelemARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vbRegLoadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vsRegLoadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define viRegLoadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vlRegLoadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vfRegLoadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdRegLoadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vbRegStoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vsRegStoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define viRegStoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vlRegStoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vfRegStoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define vdRegStoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define iuconstARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iconstEvaluator
#define luconstARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lconstEvaluator
#define buconstARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::bconstEvaluator
#define iuloadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iloadEvaluator
#define luloadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lloadEvaluator
#define buloadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::bloadEvaluator
#define iuloadiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iloadEvaluator
#define luloadiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lloadEvaluator
#define buloadiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::bloadEvaluator
#define iustoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::istoreEvaluator
#define lustoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lstoreEvaluator
#define bustoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::bstoreEvaluator
#define iustoreiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::istoreEvaluator
#define lustoreiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lstoreEvaluator
#define bustoreiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::bstoreEvaluator
#define iureturnARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ireturnEvaluator
#define lureturnARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lreturnEvaluator
#define iucallARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::directCallEvaluator
#define lucallARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::directCallEvaluator
#define iuaddARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iaddEvaluator
#define luaddARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::laddEvaluator
#define buaddARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define iusubARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::isubEvaluator
#define lusubARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lsubEvaluator
#define busubARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define iunegARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::inegEvaluator
#define lunegARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lnegEvaluator
#define f2iuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::f2iEvaluator
#define f2luARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::f2lEvaluator
#define f2buARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::d2bEvaluator
#define f2cARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::d2cEvaluator
#define d2iuARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::d2iEvaluator
#define d2luARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::d2lEvaluator
#define d2buARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::d2bEvaluator
#define d2cARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::d2cEvaluator
#define iuRegLoadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iRegLoadEvaluator
#define luRegLoadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lRegLoadEvaluator
#define iuRegStoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iRegStoreEvaluator
#define luRegStoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lRegStoreEvaluator
#define cconstARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::cconstEvaluator
#define cloadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::cloadEvaluator
#define cloadiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::cloadEvaluator
#define cstoreARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::sstoreEvaluator
#define cstoreiARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::sstoreEvaluator
#define monentARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::monentEvaluator
#define monexitARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::monexitEvaluator
#define monexitfenceARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define tstartARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define tfinishARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define tabortARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define instanceofARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::instanceofEvaluator
#define checkcastARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::checkcastEvaluator
#define checkcastAndNULLCHKARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::checkcastAndNULLCHKEvaluator
#define NewARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::newObjectEvaluator
#define newvalueARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define newarrayARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::newArrayEvaluator
#define anewarrayARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::anewArrayEvaluator
#define variableNewARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::newObjectEvaluator
#define variableNewArrayARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::anewArrayEvaluator
#define multianewarrayARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::multianewArrayEvaluator
#define arraylengthARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define contigarraylengthARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define discontigarraylengthARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define icalliARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::indirectCallEvaluator
#define iucalliARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::indirectCallEvaluator
#define lcalliARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::indirectCallEvaluator
#define lucalliARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::indirectCallEvaluator
#define fcalliARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::indirectCallEvaluator
#define dcalliARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::indirectCallEvaluator
#define acalliARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::indirectCallEvaluator
#define calliARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::indirectCallEvaluator
#define fenceARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define luaddhARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define caddARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define aiaddARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iaddEvaluator
#define aiuaddARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iaddEvaluator
#define aladdARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iaddEvaluator
#define aluaddARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::iaddEvaluator
#define lusubhARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define csubARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define imulhARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::imulhEvaluator
#define iumulhARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define lmulhARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define lumulhARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ibits2fARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ibits2fEvaluator
#define fbits2iARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::fbits2iEvaluator
#define lbits2dARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lbits2dEvaluator
#define dbits2lARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::dbits2lEvaluator
#define lookupARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::lookupEvaluator
#define trtLookupARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::NOPEvaluator
#define CaseARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::NOPEvaluator
#define tableARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::tableEvaluator
#define exceptionRangeFenceARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::exceptionRangeFenceEvaluator
#define dbgFenceARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::exceptionRangeFenceEvaluator
#define NULLCHKARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define ResolveCHKARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ResolveAndNULLCHKARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define DIVCHKARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::DIVCHKEvaluator
#define OverflowCHKARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define UnsignedOverflowCHKARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define BNDCHKARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::BNDCHKEvaluator
#define ArrayCopyBNDCHKARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ArrayCopyBNDCHKEvaluator
#define BNDCHKwithSpineCHKARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define SpineCHKARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define ArrayStoreCHKARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ArrayStoreCHKEvaluator
#define ArrayCHKARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::ArrayCHKEvaluator
#define RetARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define arraycopyARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::arraycopyEvaluator
#define arraysetARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::arraysetEvaluator
#define arraytranslateARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::arraytranslateEvaluator
#define arraytranslateAndTestARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::arraytranslateAndTestEvaluator
#define long2StringARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define bitOpMemARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define bitOpMemNDARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define arraycmpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::arraycmpEvaluator
#define arraycmpWithPadARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define allocationFenceARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::NOPEvaluator
#define loadFenceARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::NOPEvaluator
#define storeFenceARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::NOPEvaluator
#define fullFenceARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::NOPEvaluator
#define MergeNewARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define computeCCARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define butestARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define sutestARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define bucmpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define bcmpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define sucmpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define scmpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define iucmpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define icmpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define lucmpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define ificmpoARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define ificmpnoARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define iflcmpoARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define iflcmpnoARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define ificmnoARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define ificmnnoARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define iflcmnoARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define iflcmnnoARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define iuaddcARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define luaddcARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define iusubbARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define lusubbARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::badILOpEvaluator
#define icmpsetARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define lcmpsetARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define bztestnsetARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ibatomicorARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define isatomicorARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define iiatomicorARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ilatomicorARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define dexpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define branchARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define igotoARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::igotoEvaluator
#define bexpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define buexpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define sexpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define cexpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define iexpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define iuexpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define lexpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define luexpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define fexpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define fuexpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define duexpARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ixfrsARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define lxfrsARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define fxfrsARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define dxfrsARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define fintARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define dintARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define fnintARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define dnintARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define fsqrtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define dsqrtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define getstackARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define deallocaARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define idozARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define dcosARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define dsinARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define dtanARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define dcoshARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define dsinhARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define dtanhARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define dacosARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define dasinARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define datanARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define datan2ARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define dlogARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define dfloorARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ffloorARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define dceilARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define fceilARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ibranchARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define mbranchARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define getpmARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define setpmARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define loadAutoOffsetARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define imaxARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::maxEvaluator
#define iumaxARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::maxEvaluator
#define lmaxARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::maxEvaluator
#define lumaxARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::maxEvaluator
#define fmaxARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::fmaxEvaluator
#define dmaxARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::fmaxEvaluator
#define iminARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::minEvaluator
#define iuminARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::minEvaluator
#define lminARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::minEvaluator
#define luminARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::minEvaluator
#define fminARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::fminEvaluator
#define dminARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::fminEvaluator
#define trtARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define trtSimpleARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ihbitARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::integerHighestOneBit
#define ilbitARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::integerLowestOneBit
#define inolzARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::integerNumberOfLeadingZeros
#define inotzARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::integerNumberOfTrailingZeros
#define ipopcntARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::integerBitCount
#define lhbitARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::longHighestOneBit
#define llbitARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::longLowestOneBit
#define lnolzARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::longNumberOfLeadingZeros
#define lnotzARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::longNumberOfTrailingZeros
#define lpopcntARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::longBitCount
#define ibyteswapARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define bbitpermuteARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define sbitpermuteARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define ibitpermuteARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define lbitpermuteARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::unImpOpEvaluator
#define PrefetchARMEvaluator TR::TreeEvaluator::TR::TreeEvaluator::NOPEvaluator


#include "il/OMROpcodes.hpp"

#define GENERATE_TREE_EVAL_TABLE(\
   opcode, \
   name, \
   prop1, \
   prop2, \
   prop3, \
   prop4, \
   dataType, \
   typeProps, \
   childProps, \
   swapChildrenOpcode, \
   reverseBranchOpcode, \
   boolCompareOpcode, \
   ifCompareOpcode, \
   enumValue, \
   ...) enumValue ## ARMEvaluator,

   FOR_EACH_OPCODE(GENERATE_TREE_EVAL_TABLE)

#undef GENERATE_TREE_EVAL_TABLE

