/*******************************************************************************
 * Copyright (c) 2000, 2020 IBM Corp. and others
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which accompanies this
 * distribution and is available at http://eclipse.org/legal/epl-2.0
 * or the Apache License, Version 2.0 which accompanies this distribution
 * and is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License, v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception [1] and GNU General Public
 * License, version 2 with the OpenJDK Assembly Exception [2].
 *
 * [1] https://www.gnu.org/software/classpath/license.html
 * [2] http://openjdk.java.net/legal/assembly-exception.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
 *******************************************************************************/

/**
 * IlOpCode to TR_TreeEvaluatorFunctionPointer map.
 * This table is #included in a static table.
 * Only Function Pointers are allowed.
 */


#define SIGNED true
#define UNSIGN false


#define BadILOpZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define aconstZEvaluator TR::TreeEvaluator::aconstEvaluator
#define iconstZEvaluator TR::TreeEvaluator::iconstEvaluator
#define lconstZEvaluator TR::TreeEvaluator::lconstEvaluator
#define fconstZEvaluator TR::TreeEvaluator::fconstEvaluator
#define dconstZEvaluator TR::TreeEvaluator::dconstEvaluator
#define bconstZEvaluator TR::TreeEvaluator::bconstEvaluator
#define sconstZEvaluator TR::TreeEvaluator::sconstEvaluator
#define iloadZEvaluator TR::TreeEvaluator::iloadEvaluator
#define floadZEvaluator TR::TreeEvaluator::floadEvaluator
#define dloadZEvaluator TR::TreeEvaluator::dloadEvaluator
#define aloadZEvaluator TR::TreeEvaluator::aloadEvaluator
#define bloadZEvaluator TR::TreeEvaluator::bloadEvaluator
#define sloadZEvaluator TR::TreeEvaluator::sloadEvaluator
#define lloadZEvaluator TR::TreeEvaluator::lloadEvaluator
#define irdbarZEvaluator TR::TreeEvaluator::irdbarEvaluator
#define frdbarZEvaluator TR::TreeEvaluator::frdbarEvaluator
#define drdbarZEvaluator TR::TreeEvaluator::drdbarEvaluator
#define ardbarZEvaluator TR::TreeEvaluator::ardbarEvaluator
#define brdbarZEvaluator TR::TreeEvaluator::brdbarEvaluator
#define srdbarZEvaluator TR::TreeEvaluator::srdbarEvaluator
#define lrdbarZEvaluator TR::TreeEvaluator::lrdbarEvaluator
#define iloadiZEvaluator TR::TreeEvaluator::iloadEvaluator
#define floadiZEvaluator TR::TreeEvaluator::floadEvaluator
#define dloadiZEvaluator TR::TreeEvaluator::dloadEvaluator
#define aloadiZEvaluator TR::TreeEvaluator::aloadEvaluator
#define bloadiZEvaluator TR::TreeEvaluator::bloadEvaluator
#define sloadiZEvaluator TR::TreeEvaluator::sloadEvaluator
#define lloadiZEvaluator TR::TreeEvaluator::lloadEvaluator
#define irdbariZEvaluator TR::TreeEvaluator::irdbariEvaluator
#define frdbariZEvaluator TR::TreeEvaluator::frdbariEvaluator
#define drdbariZEvaluator TR::TreeEvaluator::drdbariEvaluator
#define ardbariZEvaluator TR::TreeEvaluator::ardbariEvaluator
#define brdbariZEvaluator TR::TreeEvaluator::brdbariEvaluator
#define srdbariZEvaluator TR::TreeEvaluator::srdbariEvaluator
#define lrdbariZEvaluator TR::TreeEvaluator::lrdbariEvaluator
#define istoreZEvaluator TR::TreeEvaluator::istoreEvaluator
#define lstoreZEvaluator TR::TreeEvaluator::lstoreEvaluator
#define fstoreZEvaluator TR::TreeEvaluator::fstoreEvaluator
#define dstoreZEvaluator TR::TreeEvaluator::dstoreEvaluator
#define astoreZEvaluator TR::TreeEvaluator::astoreEvaluator
#define bstoreZEvaluator TR::TreeEvaluator::bstoreEvaluator
#define sstoreZEvaluator TR::TreeEvaluator::sstoreEvaluator
#define iwrtbarZEvaluator TR::TreeEvaluator::iwrtbarEvaluator
#define lwrtbarZEvaluator TR::TreeEvaluator::lwrtbarEvaluator
#define fwrtbarZEvaluator TR::TreeEvaluator::fwrtbarEvaluator
#define dwrtbarZEvaluator TR::TreeEvaluator::dwrtbarEvaluator
#define awrtbarZEvaluator TR::TreeEvaluator::awrtbarEvaluator
#define bwrtbarZEvaluator TR::TreeEvaluator::bwrtbarEvaluator
#define swrtbarZEvaluator TR::TreeEvaluator::swrtbarEvaluator
#define lstoreiZEvaluator TR::TreeEvaluator::lstoreEvaluator
#define fstoreiZEvaluator TR::TreeEvaluator::fstoreEvaluator
#define dstoreiZEvaluator TR::TreeEvaluator::dstoreEvaluator
#define astoreiZEvaluator TR::TreeEvaluator::astoreEvaluator
#define bstoreiZEvaluator TR::TreeEvaluator::bstoreEvaluator
#define sstoreiZEvaluator TR::TreeEvaluator::sstoreEvaluator
#define istoreiZEvaluator TR::TreeEvaluator::istoreEvaluator
#define lwrtbariZEvaluator TR::TreeEvaluator::lwrtbariEvaluator
#define fwrtbariZEvaluator TR::TreeEvaluator::fwrtbariEvaluator
#define dwrtbariZEvaluator TR::TreeEvaluator::dwrtbariEvaluator
#define awrtbariZEvaluator TR::TreeEvaluator::awrtbariEvaluator
#define bwrtbariZEvaluator TR::TreeEvaluator::bwrtbariEvaluator
#define swrtbariZEvaluator TR::TreeEvaluator::swrtbariEvaluator
#define iwrtbariZEvaluator TR::TreeEvaluator::iwrtbariEvaluator
#define GotoZEvaluator TR::TreeEvaluator::gotoEvaluator
#define ireturnZEvaluator TR::TreeEvaluator::returnEvaluator
#define lreturnZEvaluator TR::TreeEvaluator::returnEvaluator
#define freturnZEvaluator TR::TreeEvaluator::returnEvaluator
#define dreturnZEvaluator TR::TreeEvaluator::returnEvaluator
#define areturnZEvaluator TR::TreeEvaluator::returnEvaluator
#define ReturnZEvaluator TR::TreeEvaluator::returnEvaluator
#define asynccheckZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define athrowZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define icallZEvaluator TR::TreeEvaluator::directCallEvaluator
#define lcallZEvaluator TR::TreeEvaluator::directCallEvaluator
#define fcallZEvaluator TR::TreeEvaluator::directCallEvaluator
#define dcallZEvaluator TR::TreeEvaluator::directCallEvaluator
#define acallZEvaluator TR::TreeEvaluator::directCallEvaluator
#define callZEvaluator TR::TreeEvaluator::directCallEvaluator
#define iaddZEvaluator TR::TreeEvaluator::iaddEvaluator
#define laddZEvaluator TR::TreeEvaluator::laddEvaluator
#define faddZEvaluator TR::TreeEvaluator::faddEvaluator
#define daddZEvaluator TR::TreeEvaluator::daddEvaluator
#define baddZEvaluator TR::TreeEvaluator::baddEvaluator
#define saddZEvaluator TR::TreeEvaluator::saddEvaluator
#define isubZEvaluator TR::TreeEvaluator::isubEvaluator
#define lsubZEvaluator TR::TreeEvaluator::lsubEvaluator
#define fsubZEvaluator TR::TreeEvaluator::fsubEvaluator
#define dsubZEvaluator TR::TreeEvaluator::dsubEvaluator
#define bsubZEvaluator TR::TreeEvaluator::bsubEvaluator
#define ssubZEvaluator TR::TreeEvaluator::ssubEvaluator
#define asubZEvaluator TR::TreeEvaluator::isubEvaluator
#define imulZEvaluator TR::TreeEvaluator::imulEvaluator
#define lmulZEvaluator TR::TreeEvaluator::lmulEvaluator
#define fmulZEvaluator TR::TreeEvaluator::fmulEvaluator
#define dmulZEvaluator TR::TreeEvaluator::dmulEvaluator
#define bmulZEvaluator TR::TreeEvaluator::bmulEvaluator
#define smulZEvaluator TR::TreeEvaluator::smulEvaluator
#define idivZEvaluator TR::TreeEvaluator::idivEvaluator
#define ldivZEvaluator TR::TreeEvaluator::ldivEvaluator
#define fdivZEvaluator TR::TreeEvaluator::fdivEvaluator
#define ddivZEvaluator TR::TreeEvaluator::ddivEvaluator
#define bdivZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define sdivZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iudivZEvaluator TR::TreeEvaluator::idivEvaluator
#define ludivZEvaluator TR::TreeEvaluator::ldivEvaluator
#define iremZEvaluator TR::TreeEvaluator::iremEvaluator
#define lremZEvaluator TR::TreeEvaluator::lremEvaluator
#define fremZEvaluator TR::TreeEvaluator::fremEvaluator
#define dremZEvaluator TR::TreeEvaluator::dremEvaluator
#define bremZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define sremZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iuremZEvaluator TR::TreeEvaluator::iremEvaluator
#define inegZEvaluator TR::TreeEvaluator::inegEvaluator
#define lnegZEvaluator TR::TreeEvaluator::lnegEvaluator
#define fnegZEvaluator TR::TreeEvaluator::fnegEvaluator
#define dnegZEvaluator TR::TreeEvaluator::dnegEvaluator
#define bnegZEvaluator TR::TreeEvaluator::bnegEvaluator
#define snegZEvaluator TR::TreeEvaluator::snegEvaluator
#define iabsZEvaluator TR::TreeEvaluator::iabsEvaluator
#define labsZEvaluator TR::TreeEvaluator::labsEvaluator
#define fabsZEvaluator TR::TreeEvaluator::iabsEvaluator
#define dabsZEvaluator TR::TreeEvaluator::iabsEvaluator
#define ishlZEvaluator TR::TreeEvaluator::ishlEvaluator
#define lshlZEvaluator TR::TreeEvaluator::lshlEvaluator
#define bshlZEvaluator TR::TreeEvaluator::bshlEvaluator
#define sshlZEvaluator TR::TreeEvaluator::sshlEvaluator
#define ishrZEvaluator TR::TreeEvaluator::ishrEvaluator
#define lshrZEvaluator TR::TreeEvaluator::lshrEvaluator
#define bshrZEvaluator TR::TreeEvaluator::bshrEvaluator
#define sshrZEvaluator TR::TreeEvaluator::sshrEvaluator
#define iushrZEvaluator TR::TreeEvaluator::iushrEvaluator
#define lushrZEvaluator TR::TreeEvaluator::lushrEvaluator
#define bushrZEvaluator TR::TreeEvaluator::bushrEvaluator
#define sushrZEvaluator TR::TreeEvaluator::sushrEvaluator
#define irolZEvaluator TR::TreeEvaluator::integerRolEvaluator
#define lrolZEvaluator TR::TreeEvaluator::integerRolEvaluator
#define iandZEvaluator TR::TreeEvaluator::iandEvaluator
#define landZEvaluator TR::TreeEvaluator::landEvaluator
#define bandZEvaluator TR::TreeEvaluator::bandEvaluator
#define sandZEvaluator TR::TreeEvaluator::sandEvaluator
#define iorZEvaluator TR::TreeEvaluator::iorEvaluator
#define lorZEvaluator TR::TreeEvaluator::lorEvaluator
#define borZEvaluator TR::TreeEvaluator::borEvaluator
#define sorZEvaluator TR::TreeEvaluator::sorEvaluator
#define ixorZEvaluator TR::TreeEvaluator::ixorEvaluator
#define lxorZEvaluator TR::TreeEvaluator::lxorEvaluator
#define bxorZEvaluator TR::TreeEvaluator::bxorEvaluator
#define sxorZEvaluator TR::TreeEvaluator::sxorEvaluator
#define i2lZEvaluator TR::TreeEvaluator::extendCastEvaluator<SIGNED,32,64>
#define i2fZEvaluator TR::TreeEvaluator::i2fEvaluator
#define i2dZEvaluator TR::TreeEvaluator::i2dEvaluator
#define i2bZEvaluator TR::TreeEvaluator::narrowCastEvaluator<SIGNED,8>
#define i2sZEvaluator TR::TreeEvaluator::narrowCastEvaluator<SIGNED,16>
#define i2aZEvaluator TR::TreeEvaluator::addressCastEvaluator<32,true>
#define iu2lZEvaluator TR::TreeEvaluator::extendCastEvaluator<UNSIGN,32,64>
#define iu2fZEvaluator TR::TreeEvaluator::i2fEvaluator
#define iu2dZEvaluator TR::TreeEvaluator::i2dEvaluator
#define iu2aZEvaluator TR::TreeEvaluator::addressCastEvaluator<32,true>
#define l2iZEvaluator TR::TreeEvaluator::narrowCastEvaluator<SIGNED,32>
#define l2fZEvaluator TR::TreeEvaluator::l2fEvaluator
#define l2dZEvaluator TR::TreeEvaluator::l2dEvaluator
#define l2bZEvaluator TR::TreeEvaluator::narrowCastEvaluator<SIGNED,8>
#define l2sZEvaluator TR::TreeEvaluator::narrowCastEvaluator<SIGNED,16>
#define l2aZEvaluator TR::TreeEvaluator::l2aEvaluator
#define lu2fZEvaluator TR::TreeEvaluator::l2fEvaluator
#define lu2dZEvaluator TR::TreeEvaluator::l2dEvaluator
#define lu2aZEvaluator TR::TreeEvaluator::addressCastEvaluator<64,true>
#define f2iZEvaluator TR::TreeEvaluator::f2iEvaluator
#define f2lZEvaluator TR::TreeEvaluator::f2lEvaluator
#define f2dZEvaluator TR::TreeEvaluator::f2dEvaluator
#define f2bZEvaluator TR::TreeEvaluator::f2iEvaluator
#define f2sZEvaluator TR::TreeEvaluator::f2iEvaluator
#define d2iZEvaluator TR::TreeEvaluator::d2iEvaluator
#define d2lZEvaluator TR::TreeEvaluator::d2lEvaluator
#define d2fZEvaluator TR::TreeEvaluator::d2fEvaluator
#define d2bZEvaluator TR::TreeEvaluator::d2iEvaluator
#define d2sZEvaluator TR::TreeEvaluator::d2iEvaluator
#define b2iZEvaluator TR::TreeEvaluator::extendCastEvaluator<SIGNED,8,32>
#define b2lZEvaluator TR::TreeEvaluator::extendCastEvaluator<SIGNED,8,64>
#define b2fZEvaluator TR::TreeEvaluator::i2fEvaluator
#define b2dZEvaluator TR::TreeEvaluator::i2dEvaluator
#define b2sZEvaluator TR::TreeEvaluator::extendCastEvaluator<SIGNED,8,32>
#define b2aZEvaluator TR::TreeEvaluator::passThroughEvaluator
#define bu2iZEvaluator TR::TreeEvaluator::extendCastEvaluator<UNSIGN,8,32>
#define bu2lZEvaluator TR::TreeEvaluator::extendCastEvaluator<UNSIGN,8,64>
#define bu2fZEvaluator TR::TreeEvaluator::i2fEvaluator
#define bu2dZEvaluator TR::TreeEvaluator::i2dEvaluator
#define bu2sZEvaluator TR::TreeEvaluator::extendCastEvaluator<UNSIGN,8,32>
#define bu2aZEvaluator TR::TreeEvaluator::addressCastEvaluator<8,true>
#define s2iZEvaluator TR::TreeEvaluator::extendCastEvaluator<SIGNED,16,32>
#define s2lZEvaluator TR::TreeEvaluator::extendCastEvaluator<SIGNED,16,64>
#define s2fZEvaluator TR::TreeEvaluator::i2fEvaluator
#define s2dZEvaluator TR::TreeEvaluator::i2dEvaluator
#define s2bZEvaluator TR::TreeEvaluator::narrowCastEvaluator<SIGNED,8>
#define s2aZEvaluator TR::TreeEvaluator::addressCastEvaluator<16,true>
#define su2iZEvaluator TR::TreeEvaluator::extendCastEvaluator<UNSIGN,16,32>
#define su2lZEvaluator TR::TreeEvaluator::extendCastEvaluator<UNSIGN,16,64>
#define su2fZEvaluator TR::TreeEvaluator::i2fEvaluator
#define su2dZEvaluator TR::TreeEvaluator::i2dEvaluator
#define su2aZEvaluator TR::TreeEvaluator::addressCastEvaluator<16,true>
#define a2iZEvaluator TR::TreeEvaluator::addressCastEvaluator<32,false>
#define a2lZEvaluator TR::TreeEvaluator::addressCastEvaluator<64,false>
#define a2bZEvaluator TR::TreeEvaluator::addressCastEvaluator<8,false>
#define a2sZEvaluator TR::TreeEvaluator::addressCastEvaluator<16,false>
#define icmpeqZEvaluator TR::TreeEvaluator::icmpeqEvaluator
#define icmpneZEvaluator TR::TreeEvaluator::icmpeqEvaluator
#define icmpltZEvaluator TR::TreeEvaluator::icmpltEvaluator
#define icmpgeZEvaluator TR::TreeEvaluator::icmpgeEvaluator
#define icmpgtZEvaluator TR::TreeEvaluator::icmpgtEvaluator
#define icmpleZEvaluator TR::TreeEvaluator::icmpleEvaluator
#define iucmpltZEvaluator TR::TreeEvaluator::icmpltEvaluator
#define iucmpgeZEvaluator TR::TreeEvaluator::icmpgeEvaluator
#define iucmpgtZEvaluator TR::TreeEvaluator::icmpgtEvaluator
#define iucmpleZEvaluator TR::TreeEvaluator::icmpleEvaluator
#define lcmpeqZEvaluator TR::TreeEvaluator::lcmpeqEvaluator
#define lcmpneZEvaluator TR::TreeEvaluator::lcmpneEvaluator
#define lcmpltZEvaluator TR::TreeEvaluator::lcmpltEvaluator
#define lcmpgeZEvaluator TR::TreeEvaluator::lcmpgeEvaluator
#define lcmpgtZEvaluator TR::TreeEvaluator::lcmpgtEvaluator
#define lcmpleZEvaluator TR::TreeEvaluator::lcmpleEvaluator
#define lucmpltZEvaluator TR::TreeEvaluator::lcmpltEvaluator
#define lucmpgeZEvaluator TR::TreeEvaluator::lcmpgeEvaluator
#define lucmpgtZEvaluator TR::TreeEvaluator::lcmpgtEvaluator
#define lucmpleZEvaluator TR::TreeEvaluator::lcmpleEvaluator
#define fcmpeqZEvaluator TR::TreeEvaluator::fcmpeqEvaluator
#define fcmpneZEvaluator TR::TreeEvaluator::fcmpneEvaluator
#define fcmpltZEvaluator TR::TreeEvaluator::fcmpltEvaluator
#define fcmpgeZEvaluator TR::TreeEvaluator::fcmpgeEvaluator
#define fcmpgtZEvaluator TR::TreeEvaluator::fcmpgtEvaluator
#define fcmpleZEvaluator TR::TreeEvaluator::fcmpleEvaluator
#define fcmpequZEvaluator TR::TreeEvaluator::fcmpequEvaluator
#define fcmpneuZEvaluator TR::TreeEvaluator::fcmpneuEvaluator
#define fcmpltuZEvaluator TR::TreeEvaluator::fcmpltuEvaluator
#define fcmpgeuZEvaluator TR::TreeEvaluator::fcmpgeuEvaluator
#define fcmpgtuZEvaluator TR::TreeEvaluator::fcmpgtuEvaluator
#define fcmpleuZEvaluator TR::TreeEvaluator::fcmpleuEvaluator
#define dcmpeqZEvaluator TR::TreeEvaluator::fcmpeqEvaluator
#define dcmpneZEvaluator TR::TreeEvaluator::fcmpneEvaluator
#define dcmpltZEvaluator TR::TreeEvaluator::fcmpltEvaluator
#define dcmpgeZEvaluator TR::TreeEvaluator::fcmpgeEvaluator
#define dcmpgtZEvaluator TR::TreeEvaluator::fcmpgtEvaluator
#define dcmpleZEvaluator TR::TreeEvaluator::fcmpleEvaluator
#define dcmpequZEvaluator TR::TreeEvaluator::fcmpequEvaluator
#define dcmpneuZEvaluator TR::TreeEvaluator::fcmpneuEvaluator
#define dcmpltuZEvaluator TR::TreeEvaluator::fcmpltuEvaluator
#define dcmpgeuZEvaluator TR::TreeEvaluator::fcmpgeuEvaluator
#define dcmpgtuZEvaluator TR::TreeEvaluator::fcmpgtuEvaluator
#define dcmpleuZEvaluator TR::TreeEvaluator::fcmpleuEvaluator
#define acmpeqZEvaluator TR::TreeEvaluator::acmpeqEvaluator
#define acmpneZEvaluator TR::TreeEvaluator::icmpeqEvaluator
#define acmpltZEvaluator TR::TreeEvaluator::icmpltEvaluator
#define acmpgeZEvaluator TR::TreeEvaluator::icmpgeEvaluator
#define acmpgtZEvaluator TR::TreeEvaluator::icmpgtEvaluator
#define acmpleZEvaluator TR::TreeEvaluator::icmpleEvaluator
#define bcmpeqZEvaluator TR::TreeEvaluator::bcmpeqEvaluator
#define bcmpneZEvaluator TR::TreeEvaluator::bcmpeqEvaluator
#define bcmpltZEvaluator TR::TreeEvaluator::bcmpltEvaluator
#define bcmpgeZEvaluator TR::TreeEvaluator::bcmpgeEvaluator
#define bcmpgtZEvaluator TR::TreeEvaluator::bcmpgtEvaluator
#define bcmpleZEvaluator TR::TreeEvaluator::bcmpleEvaluator
#define bucmpltZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define bucmpgeZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define bucmpgtZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define bucmpleZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define scmpeqZEvaluator TR::TreeEvaluator::scmpeqEvaluator
#define scmpneZEvaluator TR::TreeEvaluator::scmpeqEvaluator
#define scmpltZEvaluator TR::TreeEvaluator::scmpltEvaluator
#define scmpgeZEvaluator TR::TreeEvaluator::scmpgeEvaluator
#define scmpgtZEvaluator TR::TreeEvaluator::scmpgtEvaluator
#define scmpleZEvaluator TR::TreeEvaluator::scmpleEvaluator
#define sucmpltZEvaluator TR::TreeEvaluator::sucmpltEvaluator
#define sucmpgeZEvaluator TR::TreeEvaluator::sucmpgeEvaluator
#define sucmpgtZEvaluator TR::TreeEvaluator::sucmpgtEvaluator
#define sucmpleZEvaluator TR::TreeEvaluator::sucmpleEvaluator
#define lcmpZEvaluator TR::TreeEvaluator::lcmpEvaluator
#define fcmplZEvaluator TR::TreeEvaluator::fcmplEvaluator
#define fcmpgZEvaluator TR::TreeEvaluator::fcmplEvaluator
#define dcmplZEvaluator TR::TreeEvaluator::fcmplEvaluator
#define dcmpgZEvaluator TR::TreeEvaluator::fcmplEvaluator
#define ificmpeqZEvaluator TR::TreeEvaluator::ificmpeqEvaluator
#define ificmpneZEvaluator TR::TreeEvaluator::ificmpeqEvaluator
#define ificmpltZEvaluator TR::TreeEvaluator::ificmpltEvaluator
#define ificmpgeZEvaluator TR::TreeEvaluator::ificmpgeEvaluator
#define ificmpgtZEvaluator TR::TreeEvaluator::ificmpgtEvaluator
#define ificmpleZEvaluator TR::TreeEvaluator::ificmpleEvaluator
#define ifiucmpltZEvaluator TR::TreeEvaluator::ificmpltEvaluator
#define ifiucmpgeZEvaluator TR::TreeEvaluator::ificmpgeEvaluator
#define ifiucmpgtZEvaluator TR::TreeEvaluator::ificmpgtEvaluator
#define ifiucmpleZEvaluator TR::TreeEvaluator::ificmpleEvaluator
#define iflcmpeqZEvaluator TR::TreeEvaluator::iflcmpeqEvaluator
#define iflcmpneZEvaluator TR::TreeEvaluator::iflcmpneEvaluator
#define iflcmpltZEvaluator TR::TreeEvaluator::iflcmpltEvaluator
#define iflcmpgeZEvaluator TR::TreeEvaluator::iflcmpgeEvaluator
#define iflcmpgtZEvaluator TR::TreeEvaluator::iflcmpgtEvaluator
#define iflcmpleZEvaluator TR::TreeEvaluator::iflcmpleEvaluator
#define iflucmpltZEvaluator TR::TreeEvaluator::iflcmpltEvaluator
#define iflucmpgeZEvaluator TR::TreeEvaluator::iflcmpgeEvaluator
#define iflucmpgtZEvaluator TR::TreeEvaluator::iflcmpgtEvaluator
#define iflucmpleZEvaluator TR::TreeEvaluator::iflcmpleEvaluator
#define iffcmpeqZEvaluator TR::TreeEvaluator::iffcmpeqEvaluator
#define iffcmpneZEvaluator TR::TreeEvaluator::iffcmpneEvaluator
#define iffcmpltZEvaluator TR::TreeEvaluator::iffcmpltEvaluator
#define iffcmpgeZEvaluator TR::TreeEvaluator::iffcmpgeEvaluator
#define iffcmpgtZEvaluator TR::TreeEvaluator::iffcmpgtEvaluator
#define iffcmpleZEvaluator TR::TreeEvaluator::iffcmpleEvaluator
#define iffcmpequZEvaluator TR::TreeEvaluator::iffcmpequEvaluator
#define iffcmpneuZEvaluator TR::TreeEvaluator::iffcmpneuEvaluator
#define iffcmpltuZEvaluator TR::TreeEvaluator::iffcmpltuEvaluator
#define iffcmpgeuZEvaluator TR::TreeEvaluator::iffcmpgeuEvaluator
#define iffcmpgtuZEvaluator TR::TreeEvaluator::iffcmpgtuEvaluator
#define iffcmpleuZEvaluator TR::TreeEvaluator::iffcmpleuEvaluator
#define ifdcmpeqZEvaluator TR::TreeEvaluator::iffcmpeqEvaluator
#define ifdcmpneZEvaluator TR::TreeEvaluator::iffcmpneEvaluator
#define ifdcmpltZEvaluator TR::TreeEvaluator::iffcmpltEvaluator
#define ifdcmpgeZEvaluator TR::TreeEvaluator::iffcmpgeEvaluator
#define ifdcmpgtZEvaluator TR::TreeEvaluator::iffcmpgtEvaluator
#define ifdcmpleZEvaluator TR::TreeEvaluator::iffcmpleEvaluator
#define ifdcmpequZEvaluator TR::TreeEvaluator::iffcmpequEvaluator
#define ifdcmpneuZEvaluator TR::TreeEvaluator::iffcmpneuEvaluator
#define ifdcmpltuZEvaluator TR::TreeEvaluator::iffcmpltuEvaluator
#define ifdcmpgeuZEvaluator TR::TreeEvaluator::iffcmpgeuEvaluator
#define ifdcmpgtuZEvaluator TR::TreeEvaluator::iffcmpgtuEvaluator
#define ifdcmpleuZEvaluator TR::TreeEvaluator::iffcmpleuEvaluator
#define ifacmpeqZEvaluator TR::TreeEvaluator::ifacmpeqEvaluator
#define ifacmpneZEvaluator TR::TreeEvaluator::ifacmpneEvaluator
#define ifacmpltZEvaluator TR::TreeEvaluator::ificmpltEvaluator
#define ifacmpgeZEvaluator TR::TreeEvaluator::ificmpgeEvaluator
#define ifacmpgtZEvaluator TR::TreeEvaluator::ificmpgtEvaluator
#define ifacmpleZEvaluator TR::TreeEvaluator::ificmpleEvaluator
#define ifbcmpeqZEvaluator TR::TreeEvaluator::ifbcmpeqEvaluator
#define ifbcmpneZEvaluator TR::TreeEvaluator::ifbcmpeqEvaluator
#define ifbcmpltZEvaluator TR::TreeEvaluator::ifbcmpltEvaluator
#define ifbcmpgeZEvaluator TR::TreeEvaluator::ifbcmpgeEvaluator
#define ifbcmpgtZEvaluator TR::TreeEvaluator::ifbcmpgtEvaluator
#define ifbcmpleZEvaluator TR::TreeEvaluator::ifbcmpleEvaluator
#define ifbucmpltZEvaluator TR::TreeEvaluator::ifbcmpltEvaluator
#define ifbucmpgeZEvaluator TR::TreeEvaluator::ifbcmpgeEvaluator
#define ifbucmpgtZEvaluator TR::TreeEvaluator::ifbcmpgtEvaluator
#define ifbucmpleZEvaluator TR::TreeEvaluator::ifbcmpleEvaluator
#define ifscmpeqZEvaluator TR::TreeEvaluator::ifscmpeqEvaluator
#define ifscmpneZEvaluator TR::TreeEvaluator::ifscmpeqEvaluator
#define ifscmpltZEvaluator TR::TreeEvaluator::ifscmpltEvaluator
#define ifscmpgeZEvaluator TR::TreeEvaluator::ifscmpgeEvaluator
#define ifscmpgtZEvaluator TR::TreeEvaluator::ifscmpgtEvaluator
#define ifscmpleZEvaluator TR::TreeEvaluator::ifscmpleEvaluator
#define ifsucmpltZEvaluator TR::TreeEvaluator::ifsucmpltEvaluator
#define ifsucmpgeZEvaluator TR::TreeEvaluator::ifsucmpgeEvaluator
#define ifsucmpgtZEvaluator TR::TreeEvaluator::ifsucmpgtEvaluator
#define ifsucmpleZEvaluator TR::TreeEvaluator::ifsucmpleEvaluator
#define loadaddrZEvaluator TR::TreeEvaluator::loadaddrEvaluator
#define ZEROCHKZEvaluator TR::TreeEvaluator::ZEROCHKEvaluator
#define callIfZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iRegLoadZEvaluator TR::TreeEvaluator::iRegLoadEvaluator
#define aRegLoadZEvaluator TR::TreeEvaluator::aRegLoadEvaluator
#define lRegLoadZEvaluator TR::TreeEvaluator::lRegLoadEvaluator
#define fRegLoadZEvaluator TR::TreeEvaluator::fRegLoadEvaluator
#define dRegLoadZEvaluator TR::TreeEvaluator::dRegLoadEvaluator
#define sRegLoadZEvaluator TR::TreeEvaluator::iRegLoadEvaluator
#define bRegLoadZEvaluator TR::TreeEvaluator::iRegLoadEvaluator
#define iRegStoreZEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define aRegStoreZEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define lRegStoreZEvaluator TR::TreeEvaluator::lRegStoreEvaluator
#define fRegStoreZEvaluator TR::TreeEvaluator::fRegStoreEvaluator
#define dRegStoreZEvaluator TR::TreeEvaluator::dRegStoreEvaluator
#define sRegStoreZEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define bRegStoreZEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define GlRegDepsZEvaluator TR::TreeEvaluator::GlRegDepsEvaluator
#define iselectZEvaluator TR::TreeEvaluator::selectEvaluator
#define lselectZEvaluator TR::TreeEvaluator::selectEvaluator
#define bselectZEvaluator TR::TreeEvaluator::selectEvaluator
#define sselectZEvaluator TR::TreeEvaluator::selectEvaluator
#define aselectZEvaluator TR::TreeEvaluator::selectEvaluator
#define fselectZEvaluator TR::TreeEvaluator::dselectEvaluator
#define dselectZEvaluator TR::TreeEvaluator::dselectEvaluator
#define treetopZEvaluator TR::TreeEvaluator::treetopEvaluator
#define MethodEnterHookZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define MethodExitHookZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define PassThroughZEvaluator TR::TreeEvaluator::passThroughEvaluator
#define compressedRefsZEvaluator TR::TreeEvaluator::compressedRefsEvaluator
#define BBStartZEvaluator TR::TreeEvaluator::BBStartEvaluator
#define BBEndZEvaluator TR::TreeEvaluator::BBEndEvaluator
#define viremZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define viminZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vimaxZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vigetelemZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define visetelemZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vimergelZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vimergehZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpeqZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpgtZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpgeZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpltZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpleZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpalleqZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallneZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallgtZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallgeZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallltZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallleZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyeqZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyneZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanygtZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanygeZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyltZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyleZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vnotZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vbitselectZEvaluator TR::TreeEvaluator::vselEvaluator
#define vpermZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vsplatsZEvaluator TR::TreeEvaluator::vsplatsEvaluator
#define vdmergelZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdmergehZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdsetelemZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdgetelemZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdselZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdremZEvaluator TR::TreeEvaluator::vdremEvaluator
#define vdmaddZEvaluator TR::TreeEvaluator::vdmaddEvaluator
#define vdnmsubZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdmsubZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdmaxZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdminZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpeqZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpneZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpgtZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpgeZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpltZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpleZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpalleqZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallneZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallgtZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallgeZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallltZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallleZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyeqZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyneZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanygtZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanygeZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyltZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyleZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdsqrtZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdlogZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vincZEvaluator TR::TreeEvaluator::vincEvaluator
#define vdecZEvaluator TR::TreeEvaluator::vdecEvaluator
#define vnegZEvaluator TR::TreeEvaluator::vnegEvaluator
#define vcomZEvaluator TR::TreeEvaluator::vcomEvaluator
#define vaddZEvaluator TR::TreeEvaluator::vaddEvaluator
#define vsubZEvaluator TR::TreeEvaluator::vsubEvaluator
#define vmulZEvaluator TR::TreeEvaluator::vmulEvaluator
#define vdivZEvaluator TR::TreeEvaluator::vdivEvaluator
#define vremZEvaluator TR::TreeEvaluator::vremEvaluator
#define vandZEvaluator TR::TreeEvaluator::vandEvaluator
#define vorZEvaluator TR::TreeEvaluator::vorEvaluator
#define vxorZEvaluator TR::TreeEvaluator::vxorEvaluator
#define vshlZEvaluator TR::TreeEvaluator::vectorElementShiftHelper
#define vushrZEvaluator TR::TreeEvaluator::vectorElementShiftHelper
#define vshrZEvaluator TR::TreeEvaluator::vectorElementShiftHelper
#define vcmpeqZEvaluator TR::TreeEvaluator::vcmpeqEvaluator
#define vcmpneZEvaluator TR::TreeEvaluator::vcmpneEvaluator
#define vcmpltZEvaluator TR::TreeEvaluator::vcmpltEvaluator
#define vucmpltZEvaluator TR::TreeEvaluator::vcmpltEvaluator
#define vcmpgtZEvaluator TR::TreeEvaluator::vcmpgtEvaluator
#define vucmpgtZEvaluator TR::TreeEvaluator::vcmpgtEvaluator
#define vcmpleZEvaluator TR::TreeEvaluator::vcmpleEvaluator
#define vucmpleZEvaluator TR::TreeEvaluator::vcmpleEvaluator
#define vcmpgeZEvaluator TR::TreeEvaluator::vcmpgeEvaluator
#define vucmpgeZEvaluator TR::TreeEvaluator::vcmpgeEvaluator
#define vloadZEvaluator TR::TreeEvaluator::vloadEvaluator
#define vloadiZEvaluator TR::TreeEvaluator::vloadEvaluator
#define vstoreZEvaluator TR::TreeEvaluator::vstoreEvaluator
#define vstoreiZEvaluator TR::TreeEvaluator::vstoreEvaluator
#define vrandZEvaluator TR::TreeEvaluator::vrandEvaluator
#define vreturnZEvaluator TR::TreeEvaluator::vreturnEvaluator
#define vcallZEvaluator TR::TreeEvaluator::directCallEvaluator
#define vcalliZEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define vselectZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define v2vZEvaluator TR::TreeEvaluator::passThroughEvaluator
#define vl2vdZEvaluator TR::TreeEvaluator::vl2vdEvaluator
#define vconstZEvaluator TR::TreeEvaluator::vconstEvaluator
#define getvelemZEvaluator TR::TreeEvaluator::getvelemEvaluator
#define vsetelemZEvaluator TR::TreeEvaluator::vsetelemEvaluator
#define vbRegLoadZEvaluator TR::TreeEvaluator::vRegLoadEvaluator
#define vsRegLoadZEvaluator TR::TreeEvaluator::vRegLoadEvaluator
#define viRegLoadZEvaluator TR::TreeEvaluator::vRegLoadEvaluator
#define vlRegLoadZEvaluator TR::TreeEvaluator::vRegLoadEvaluator
#define vfRegLoadZEvaluator TR::TreeEvaluator::vRegLoadEvaluator
#define vdRegLoadZEvaluator TR::TreeEvaluator::vRegLoadEvaluator
#define vbRegStoreZEvaluator TR::TreeEvaluator::vRegStoreEvaluator
#define vsRegStoreZEvaluator TR::TreeEvaluator::vRegStoreEvaluator
#define viRegStoreZEvaluator TR::TreeEvaluator::vRegStoreEvaluator
#define vlRegStoreZEvaluator TR::TreeEvaluator::vRegStoreEvaluator
#define vfRegStoreZEvaluator TR::TreeEvaluator::vRegStoreEvaluator
#define vdRegStoreZEvaluator TR::TreeEvaluator::vRegStoreEvaluator
#define iuconstZEvaluator TR::TreeEvaluator::iconstEvaluator
#define luconstZEvaluator TR::TreeEvaluator::lconstEvaluator
#define buconstZEvaluator TR::TreeEvaluator::bconstEvaluator
#define iuloadZEvaluator TR::TreeEvaluator::iloadEvaluator
#define luloadZEvaluator TR::TreeEvaluator::lloadEvaluator
#define buloadZEvaluator TR::TreeEvaluator::bloadEvaluator
#define iuloadiZEvaluator TR::TreeEvaluator::iloadEvaluator
#define luloadiZEvaluator TR::TreeEvaluator::lloadEvaluator
#define buloadiZEvaluator TR::TreeEvaluator::bloadEvaluator
#define iustoreZEvaluator TR::TreeEvaluator::istoreEvaluator
#define lustoreZEvaluator TR::TreeEvaluator::lstoreEvaluator
#define bustoreZEvaluator TR::TreeEvaluator::bstoreEvaluator
#define iustoreiZEvaluator TR::TreeEvaluator::istoreEvaluator
#define lustoreiZEvaluator TR::TreeEvaluator::lstoreEvaluator
#define bustoreiZEvaluator TR::TreeEvaluator::bstoreEvaluator
#define iureturnZEvaluator TR::TreeEvaluator::returnEvaluator
#define lureturnZEvaluator TR::TreeEvaluator::returnEvaluator
#define iucallZEvaluator TR::TreeEvaluator::directCallEvaluator
#define lucallZEvaluator TR::TreeEvaluator::directCallEvaluator
#define iuaddZEvaluator TR::TreeEvaluator::iaddEvaluator
#define luaddZEvaluator TR::TreeEvaluator::laddEvaluator
#define buaddZEvaluator TR::TreeEvaluator::baddEvaluator
#define iusubZEvaluator TR::TreeEvaluator::isubEvaluator
#define lusubZEvaluator TR::TreeEvaluator::lsubEvaluator
#define busubZEvaluator TR::TreeEvaluator::bsubEvaluator
#define iunegZEvaluator TR::TreeEvaluator::inegEvaluator
#define lunegZEvaluator TR::TreeEvaluator::lnegEvaluator
#define f2iuZEvaluator TR::TreeEvaluator::f2iEvaluator
#define f2luZEvaluator TR::TreeEvaluator::f2lEvaluator
#define f2buZEvaluator TR::TreeEvaluator::f2iEvaluator
#define f2cZEvaluator TR::TreeEvaluator::f2iEvaluator
#define d2iuZEvaluator TR::TreeEvaluator::d2iEvaluator
#define d2luZEvaluator TR::TreeEvaluator::d2lEvaluator
#define d2buZEvaluator TR::TreeEvaluator::d2iEvaluator
#define d2cZEvaluator TR::TreeEvaluator::d2iEvaluator
#define iuRegLoadZEvaluator TR::TreeEvaluator::iRegLoadEvaluator
#define luRegLoadZEvaluator TR::TreeEvaluator::lRegLoadEvaluator
#define iuRegStoreZEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define luRegStoreZEvaluator TR::TreeEvaluator::lRegStoreEvaluator
#define cconstZEvaluator TR::TreeEvaluator::cconstEvaluator
#define cloadZEvaluator TR::TreeEvaluator::sloadEvaluator
#define cloadiZEvaluator TR::TreeEvaluator::sloadEvaluator
#define cstoreZEvaluator TR::TreeEvaluator::cstoreEvaluator
#define cstoreiZEvaluator TR::TreeEvaluator::cstoreEvaluator
#define monentZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define monexitZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define monexitfenceZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define tstartZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define tfinishZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define tabortZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define instanceofZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define checkcastZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define checkcastAndNULLCHKZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define NewZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define newvalueZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define newarrayZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define anewarrayZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define variableNewZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define variableNewArrayZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define multianewarrayZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define arraylengthZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define contigarraylengthZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define discontigarraylengthZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define icalliZEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define iucalliZEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define lcalliZEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define lucalliZEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define fcalliZEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define dcalliZEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define acalliZEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define calliZEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define fenceZEvaluator TR::TreeEvaluator::fenceEvaluator
#define luaddhZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define caddZEvaluator TR::TreeEvaluator::caddEvaluator
#define aiaddZEvaluator TR::TreeEvaluator::aiaddEvaluator
#define aiuaddZEvaluator TR::TreeEvaluator::aiaddEvaluator
#define aladdZEvaluator TR::TreeEvaluator::aladdEvaluator
#define aluaddZEvaluator TR::TreeEvaluator::aladdEvaluator
#define lusubhZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define csubZEvaluator TR::TreeEvaluator::csubEvaluator
#define imulhZEvaluator TR::TreeEvaluator::mulhEvaluator
#define iumulhZEvaluator TR::TreeEvaluator::mulhEvaluator
#define lmulhZEvaluator TR::TreeEvaluator::lmulhEvaluator
#define lumulhZEvaluator TR::TreeEvaluator::lmulhEvaluator
#define ibits2fZEvaluator TR::TreeEvaluator::ibits2fEvaluator
#define fbits2iZEvaluator TR::TreeEvaluator::fbits2iEvaluator
#define lbits2dZEvaluator TR::TreeEvaluator::lbits2dEvaluator
#define dbits2lZEvaluator TR::TreeEvaluator::dbits2lEvaluator
#define lookupZEvaluator TR::TreeEvaluator::lookupEvaluator
#define trtLookupZEvaluator TR::TreeEvaluator::lookupEvaluator
#define CaseZEvaluator TR::TreeEvaluator::NOPEvaluator
#define tableZEvaluator TR::TreeEvaluator::tableEvaluator
#define exceptionRangeFenceZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dbgFenceZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define NULLCHKZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ResolveCHKZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ResolveAndNULLCHKZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define DIVCHKZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define OverflowCHKZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define UnsignedOverflowCHKZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define BNDCHKZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ArrayCopyBNDCHKZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define BNDCHKwithSpineCHKZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define SpineCHKZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ArrayStoreCHKZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ArrayCHKZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define RetZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define arraycopyZEvaluator TR::TreeEvaluator::arraycopyEvaluator
#define arraysetZEvaluator TR::TreeEvaluator::arraysetEvaluator
#define arraytranslateZEvaluator TR::TreeEvaluator::arraytranslateEvaluator
#define arraytranslateAndTestZEvaluator TR::TreeEvaluator::arraytranslateAndTestEvaluator
#define long2StringZEvaluator TR::TreeEvaluator::long2StringEvaluator
#define bitOpMemZEvaluator TR::TreeEvaluator::bitOpMemEvaluator
#define bitOpMemNDZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define arraycmpZEvaluator TR::TreeEvaluator::arraycmpEvaluator
#define arraycmpWithPadZEvaluator TR::TreeEvaluator::arraycmpEvaluatorWithPad
#define allocationFenceZEvaluator TR::TreeEvaluator::NOPEvaluator
#define loadFenceZEvaluator TR::TreeEvaluator::barrierFenceEvaluator
#define storeFenceZEvaluator TR::TreeEvaluator::barrierFenceEvaluator
#define fullFenceZEvaluator TR::TreeEvaluator::barrierFenceEvaluator
#define MergeNewZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define computeCCZEvaluator TR::TreeEvaluator::computeCCEvaluator
#define butestZEvaluator TR::TreeEvaluator::butestEvaluator
#define sutestZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define bucmpZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define bcmpZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define sucmpZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define scmpZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define iucmpZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define icmpZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define lucmpZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ificmpoZEvaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define ificmpnoZEvaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define iflcmpoZEvaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define iflcmpnoZEvaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define ificmnoZEvaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define ificmnnoZEvaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define iflcmnoZEvaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define iflcmnnoZEvaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define iuaddcZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define luaddcZEvaluator TR::TreeEvaluator::laddEvaluator
#define iusubbZEvaluator TR::TreeEvaluator::badILOpEvaluator
#define lusubbZEvaluator TR::TreeEvaluator::lsubEvaluator
#define icmpsetZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define lcmpsetZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define bztestnsetZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define ibatomicorZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define isatomicorZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iiatomicorZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define ilatomicorZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dexpZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define branchZEvaluator TR::TreeEvaluator::branchEvaluator
#define igotoZEvaluator TR::TreeEvaluator::igotoEvaluator
#define bexpZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define buexpZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define sexpZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define cexpZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iexpZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iuexpZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define lexpZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define luexpZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fexpZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fuexpZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define duexpZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define ixfrsZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define lxfrsZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fxfrsZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dxfrsZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fintZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dintZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fnintZEvaluator TR::TreeEvaluator::fnintEvaluator
#define dnintZEvaluator TR::TreeEvaluator::dnintEvaluator
#define fsqrtZEvaluator TR::TreeEvaluator::fsqrtEvaluator
#define dsqrtZEvaluator TR::TreeEvaluator::dsqrtEvaluator
#define getstackZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define deallocaZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define idozZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dcosZEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define dsinZEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define dtanZEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define dcoshZEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define dsinhZEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define dtanhZEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define dacosZEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define dasinZEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define datanZEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define datan2ZEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define dlogZEvaluator TR::TreeEvaluator::libmFuncEvaluator
#define dfloorZEvaluator TR::TreeEvaluator::dfloorEvaluator
#define ffloorZEvaluator TR::TreeEvaluator::ffloorEvaluator
#define dceilZEvaluator TR::TreeEvaluator::dceilEvaluator
#define fceilZEvaluator TR::TreeEvaluator::fceilEvaluator
#define ibranchZEvaluator TR::TreeEvaluator::ibranchEvaluator
#define mbranchZEvaluator TR::TreeEvaluator::mbranchEvaluator
#define getpmZEvaluator TR::TreeEvaluator::getpmEvaluator
#define setpmZEvaluator TR::TreeEvaluator::setpmEvaluator
#define loadAutoOffsetZEvaluator TR::TreeEvaluator::loadAutoOffsetEvaluator
#define imaxZEvaluator TR::TreeEvaluator::imaxEvaluator
#define iumaxZEvaluator TR::TreeEvaluator::imaxEvaluator
#define lmaxZEvaluator TR::TreeEvaluator::lmaxEvaluator
#define lumaxZEvaluator TR::TreeEvaluator::lmaxEvaluator
#define fmaxZEvaluator TR::TreeEvaluator::fmaxEvaluator
#define dmaxZEvaluator TR::TreeEvaluator::dmaxEvaluator
#define iminZEvaluator TR::TreeEvaluator::iminEvaluator
#define iuminZEvaluator TR::TreeEvaluator::iminEvaluator
#define lminZEvaluator TR::TreeEvaluator::lminEvaluator
#define luminZEvaluator TR::TreeEvaluator::lminEvaluator
#define fminZEvaluator TR::TreeEvaluator::fminEvaluator
#define dminZEvaluator TR::TreeEvaluator::dminEvaluator
#define trtZEvaluator TR::TreeEvaluator::trtEvaluator
#define trtSimpleZEvaluator TR::TreeEvaluator::trtEvaluator
#define ihbitZEvaluator TR::TreeEvaluator::integerHighestOneBit
#define ilbitZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define inolzZEvaluator TR::TreeEvaluator::integerNumberOfLeadingZeros
#define inotzZEvaluator TR::TreeEvaluator::integerNumberOfTrailingZeros
#define ipopcntZEvaluator TR::TreeEvaluator::integerBitCount
#define lhbitZEvaluator TR::TreeEvaluator::longHighestOneBit
#define llbitZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define lnolzZEvaluator TR::TreeEvaluator::longNumberOfLeadingZeros
#define lnotzZEvaluator TR::TreeEvaluator::longNumberOfTrailingZeros
#define lpopcntZEvaluator TR::TreeEvaluator::longBitCount
#define ibyteswapZEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define bbitpermuteZEvaluator TR::TreeEvaluator::bitpermuteEvaluator
#define sbitpermuteZEvaluator TR::TreeEvaluator::bitpermuteEvaluator
#define ibitpermuteZEvaluator TR::TreeEvaluator::bitpermuteEvaluator
#define lbitpermuteZEvaluator TR::TreeEvaluator::bitpermuteEvaluator
#define PrefetchZEvaluator TR::TreeEvaluator::PrefetchEvaluator



#include "il/OMROpcodes.hpp"

#define GENERATE_TREE_EVAL_TABLE(\
   opcode, \
   name, \
   prop1, \
   prop2, \
   prop3, \
   prop4, \
   dataType, \
   typeProps, \
   childProps, \
   swapChildrenOpcode, \
   reverseBranchOpcode, \
   boolCompareOpcode, \
   ifCompareOpcode, \
   enumValue, \
   ...) enumValue ## ZEvaluator,

   FOR_EACH_OPCODE(GENERATE_TREE_EVAL_TABLE)

#undef GENERATE_TREE_EVAL_TABLE


#undef SIGNED
#undef UNSIGN

