/*******************************************************************************
 * Copyright (c) 2018, 2020 IBM Corp. and others
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which accompanies this
 * distribution and is available at http://eclipse.org/legal/epl-2.0
 * or the Apache License, Version 2.0 which accompanies this distribution
 * and is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License, v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception [1] and GNU General Public
 * License, version 2 with the OpenJDK Assembly Exception [2].
 *
 * [1] https://www.gnu.org/software/classpath/license.html
 * [2] http://openjdk.java.net/legal/assembly-exception.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
 *******************************************************************************/
/*
 * This table is #included in a static table.
 * Only Function Pointers are allowed.
 */

#define BadILOpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define aconstARM64Evaluator TR::TreeEvaluator::aconstEvaluator
#define iconstARM64Evaluator TR::TreeEvaluator::iconstEvaluator
#define lconstARM64Evaluator TR::TreeEvaluator::lconstEvaluator
#define fconstARM64Evaluator TR::TreeEvaluator::fconstEvaluator
#define dconstARM64Evaluator TR::TreeEvaluator::dconstEvaluator
#define bconstARM64Evaluator TR::TreeEvaluator::bconstEvaluator
#define sconstARM64Evaluator TR::TreeEvaluator::sconstEvaluator
#define iloadARM64Evaluator TR::TreeEvaluator::iloadEvaluator
#define floadARM64Evaluator TR::TreeEvaluator::floadEvaluator
#define dloadARM64Evaluator TR::TreeEvaluator::dloadEvaluator
#define aloadARM64Evaluator TR::TreeEvaluator::aloadEvaluator
#define bloadARM64Evaluator TR::TreeEvaluator::bloadEvaluator
#define sloadARM64Evaluator TR::TreeEvaluator::sloadEvaluator
#define lloadARM64Evaluator TR::TreeEvaluator::lloadEvaluator
#define irdbarARM64Evaluator TR::TreeEvaluator::irdbarEvaluator
#define frdbarARM64Evaluator TR::TreeEvaluator::frdbarEvaluator
#define drdbarARM64Evaluator TR::TreeEvaluator::drdbarEvaluator
#define ardbarARM64Evaluator TR::TreeEvaluator::ardbarEvaluator
#define brdbarARM64Evaluator TR::TreeEvaluator::brdbarEvaluator
#define srdbarARM64Evaluator TR::TreeEvaluator::srdbarEvaluator
#define lrdbarARM64Evaluator TR::TreeEvaluator::lrdbarEvaluator
#define iloadiARM64Evaluator TR::TreeEvaluator::iloadEvaluator
#define floadiARM64Evaluator TR::TreeEvaluator::floadEvaluator
#define dloadiARM64Evaluator TR::TreeEvaluator::dloadEvaluator
#define aloadiARM64Evaluator TR::TreeEvaluator::aloadEvaluator
#define bloadiARM64Evaluator TR::TreeEvaluator::bloadEvaluator
#define sloadiARM64Evaluator TR::TreeEvaluator::sloadEvaluator
#define lloadiARM64Evaluator TR::TreeEvaluator::lloadEvaluator
#define irdbariARM64Evaluator TR::TreeEvaluator::irdbariEvaluator
#define frdbariARM64Evaluator TR::TreeEvaluator::frdbariEvaluator
#define drdbariARM64Evaluator TR::TreeEvaluator::drdbariEvaluator
#define ardbariARM64Evaluator TR::TreeEvaluator::ardbariEvaluator
#define brdbariARM64Evaluator TR::TreeEvaluator::brdbariEvaluator
#define srdbariARM64Evaluator TR::TreeEvaluator::srdbariEvaluator
#define lrdbariARM64Evaluator TR::TreeEvaluator::lrdbariEvaluator
#define istoreARM64Evaluator TR::TreeEvaluator::istoreEvaluator
#define lstoreARM64Evaluator TR::TreeEvaluator::lstoreEvaluator
#define fstoreARM64Evaluator TR::TreeEvaluator::fstoreEvaluator
#define dstoreARM64Evaluator TR::TreeEvaluator::dstoreEvaluator
#define astoreARM64Evaluator TR::TreeEvaluator::astoreEvaluator
#define bstoreARM64Evaluator TR::TreeEvaluator::bstoreEvaluator
#define sstoreARM64Evaluator TR::TreeEvaluator::sstoreEvaluator
#define iwrtbarARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define lwrtbarARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fwrtbarARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dwrtbarARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define awrtbarARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define bwrtbarARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define swrtbarARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define lstoreiARM64Evaluator TR::TreeEvaluator::lstoreEvaluator
#define fstoreiARM64Evaluator TR::TreeEvaluator::fstoreEvaluator
#define dstoreiARM64Evaluator TR::TreeEvaluator::dstoreEvaluator
#define astoreiARM64Evaluator TR::TreeEvaluator::astoreEvaluator
#define bstoreiARM64Evaluator TR::TreeEvaluator::bstoreEvaluator
#define sstoreiARM64Evaluator TR::TreeEvaluator::sstoreEvaluator
#define istoreiARM64Evaluator TR::TreeEvaluator::istoreEvaluator
#define lwrtbariARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fwrtbariARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dwrtbariARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define awrtbariARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define bwrtbariARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define swrtbariARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iwrtbariARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define GotoARM64Evaluator TR::TreeEvaluator::gotoEvaluator
#define ireturnARM64Evaluator TR::TreeEvaluator::ireturnEvaluator
#define lreturnARM64Evaluator TR::TreeEvaluator::lreturnEvaluator
#define freturnARM64Evaluator TR::TreeEvaluator::freturnEvaluator
#define dreturnARM64Evaluator TR::TreeEvaluator::dreturnEvaluator
#define areturnARM64Evaluator TR::TreeEvaluator::areturnEvaluator
#define ReturnARM64Evaluator TR::TreeEvaluator::returnEvaluator
#define asynccheckARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define athrowARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define icallARM64Evaluator TR::TreeEvaluator::directCallEvaluator
#define lcallARM64Evaluator TR::TreeEvaluator::directCallEvaluator
#define fcallARM64Evaluator TR::TreeEvaluator::directCallEvaluator
#define dcallARM64Evaluator TR::TreeEvaluator::directCallEvaluator
#define acallARM64Evaluator TR::TreeEvaluator::directCallEvaluator
#define callARM64Evaluator TR::TreeEvaluator::directCallEvaluator
#define iaddARM64Evaluator TR::TreeEvaluator::iaddEvaluator
#define laddARM64Evaluator TR::TreeEvaluator::laddEvaluator
#define faddARM64Evaluator TR::TreeEvaluator::faddEvaluator
#define daddARM64Evaluator TR::TreeEvaluator::daddEvaluator
#define baddARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define saddARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define isubARM64Evaluator TR::TreeEvaluator::isubEvaluator
#define lsubARM64Evaluator TR::TreeEvaluator::lsubEvaluator
#define fsubARM64Evaluator TR::TreeEvaluator::fsubEvaluator
#define dsubARM64Evaluator TR::TreeEvaluator::dsubEvaluator
#define bsubARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define ssubARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define asubARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define imulARM64Evaluator TR::TreeEvaluator::imulEvaluator
#define lmulARM64Evaluator TR::TreeEvaluator::lmulEvaluator
#define fmulARM64Evaluator TR::TreeEvaluator::fmulEvaluator
#define dmulARM64Evaluator TR::TreeEvaluator::dmulEvaluator
#define bmulARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define smulARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define idivARM64Evaluator TR::TreeEvaluator::idivEvaluator
#define ldivARM64Evaluator TR::TreeEvaluator::ldivEvaluator
#define fdivARM64Evaluator TR::TreeEvaluator::fdivEvaluator
#define ddivARM64Evaluator TR::TreeEvaluator::ddivEvaluator
#define bdivARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define sdivARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iudivARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define ludivARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iremARM64Evaluator TR::TreeEvaluator::iremEvaluator
#define lremARM64Evaluator TR::TreeEvaluator::lremEvaluator
#define fremARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dremARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define bremARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define sremARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iuremARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define inegARM64Evaluator TR::TreeEvaluator::inegEvaluator
#define lnegARM64Evaluator TR::TreeEvaluator::lnegEvaluator
#define fnegARM64Evaluator TR::TreeEvaluator::fnegEvaluator
#define dnegARM64Evaluator TR::TreeEvaluator::dnegEvaluator
#define bnegARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define snegARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iabsARM64Evaluator TR::TreeEvaluator::iabsEvaluator
#define labsARM64Evaluator TR::TreeEvaluator::labsEvaluator
#define fabsARM64Evaluator TR::TreeEvaluator::fabsEvaluator
#define dabsARM64Evaluator TR::TreeEvaluator::dabsEvaluator
#define ishlARM64Evaluator TR::TreeEvaluator::ishlEvaluator
#define lshlARM64Evaluator TR::TreeEvaluator::ishlEvaluator
#define bshlARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define sshlARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define ishrARM64Evaluator TR::TreeEvaluator::ishrEvaluator
#define lshrARM64Evaluator TR::TreeEvaluator::ishrEvaluator
#define bshrARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define sshrARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iushrARM64Evaluator TR::TreeEvaluator::iushrEvaluator
#define lushrARM64Evaluator TR::TreeEvaluator::iushrEvaluator
#define bushrARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define sushrARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define irolARM64Evaluator TR::TreeEvaluator::irolEvaluator
#define lrolARM64Evaluator TR::TreeEvaluator::irolEvaluator
#define iandARM64Evaluator TR::TreeEvaluator::iandEvaluator
#define landARM64Evaluator TR::TreeEvaluator::landEvaluator
#define bandARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define sandARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iorARM64Evaluator TR::TreeEvaluator::iorEvaluator
#define lorARM64Evaluator TR::TreeEvaluator::lorEvaluator
#define borARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define sorARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define ixorARM64Evaluator TR::TreeEvaluator::ixorEvaluator
#define lxorARM64Evaluator TR::TreeEvaluator::lxorEvaluator
#define bxorARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define sxorARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define i2lARM64Evaluator TR::TreeEvaluator::i2lEvaluator
#define i2fARM64Evaluator TR::TreeEvaluator::i2fEvaluator
#define i2dARM64Evaluator TR::TreeEvaluator::i2dEvaluator
#define i2bARM64Evaluator TR::TreeEvaluator::l2iEvaluator
#define i2sARM64Evaluator TR::TreeEvaluator::l2iEvaluator
#define i2aARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iu2lARM64Evaluator TR::TreeEvaluator::iu2lEvaluator
#define iu2fARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iu2dARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iu2aARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define l2iARM64Evaluator TR::TreeEvaluator::l2iEvaluator
#define l2fARM64Evaluator TR::TreeEvaluator::l2fEvaluator
#define l2dARM64Evaluator TR::TreeEvaluator::l2dEvaluator
#define l2bARM64Evaluator TR::TreeEvaluator::l2iEvaluator
#define l2sARM64Evaluator TR::TreeEvaluator::l2iEvaluator
#define l2aARM64Evaluator TR::TreeEvaluator::l2aEvaluator
#define lu2fARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lu2dARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lu2aARM64Evaluator TR::TreeEvaluator::passThroughEvaluator
#define f2iARM64Evaluator TR::TreeEvaluator::f2iEvaluator
#define f2lARM64Evaluator TR::TreeEvaluator::f2lEvaluator
#define f2dARM64Evaluator TR::TreeEvaluator::f2dEvaluator
#define f2bARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define f2sARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define d2iARM64Evaluator TR::TreeEvaluator::d2iEvaluator
#define d2lARM64Evaluator TR::TreeEvaluator::d2lEvaluator
#define d2fARM64Evaluator TR::TreeEvaluator::d2fEvaluator
#define d2bARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define d2sARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define b2iARM64Evaluator TR::TreeEvaluator::b2iEvaluator
#define b2lARM64Evaluator TR::TreeEvaluator::b2lEvaluator
#define b2fARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define b2dARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define b2sARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define b2aARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bu2iARM64Evaluator TR::TreeEvaluator::bu2iEvaluator
#define bu2lARM64Evaluator TR::TreeEvaluator::bu2lEvaluator
#define bu2fARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bu2dARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bu2sARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bu2aARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define s2iARM64Evaluator TR::TreeEvaluator::s2iEvaluator
#define s2lARM64Evaluator TR::TreeEvaluator::s2lEvaluator
#define s2fARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define s2dARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define s2bARM64Evaluator TR::TreeEvaluator::l2iEvaluator 
#define s2aARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define su2iARM64Evaluator TR::TreeEvaluator::su2iEvaluator
#define su2lARM64Evaluator TR::TreeEvaluator::su2lEvaluator
#define su2fARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define su2dARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define su2aARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define a2iARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define a2lARM64Evaluator TR::TreeEvaluator::passThroughEvaluator
#define a2bARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define a2sARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define icmpeqARM64Evaluator TR::TreeEvaluator::icmpeqEvaluator
#define icmpneARM64Evaluator TR::TreeEvaluator::icmpneEvaluator
#define icmpltARM64Evaluator TR::TreeEvaluator::icmpltEvaluator
#define icmpgeARM64Evaluator TR::TreeEvaluator::icmpgeEvaluator
#define icmpgtARM64Evaluator TR::TreeEvaluator::icmpgtEvaluator
#define icmpleARM64Evaluator TR::TreeEvaluator::icmpleEvaluator
#define iucmpeqARM64Evaluator TR::TreeEvaluator::icmpeqEvaluator
#define iucmpneARM64Evaluator TR::TreeEvaluator::icmpneEvaluator
#define iucmpltARM64Evaluator TR::TreeEvaluator::iucmpltEvaluator
#define iucmpgeARM64Evaluator TR::TreeEvaluator::iucmpgeEvaluator
#define iucmpgtARM64Evaluator TR::TreeEvaluator::iucmpgtEvaluator
#define iucmpleARM64Evaluator TR::TreeEvaluator::iucmpleEvaluator
#define lcmpeqARM64Evaluator TR::TreeEvaluator::lcmpeqEvaluator
#define lcmpneARM64Evaluator TR::TreeEvaluator::lcmpneEvaluator
#define lcmpltARM64Evaluator TR::TreeEvaluator::lcmpltEvaluator
#define lcmpgeARM64Evaluator TR::TreeEvaluator::lcmpgeEvaluator
#define lcmpgtARM64Evaluator TR::TreeEvaluator::lcmpgtEvaluator
#define lcmpleARM64Evaluator TR::TreeEvaluator::lcmpleEvaluator
#define lucmpeqARM64Evaluator TR::TreeEvaluator::lcmpeqEvaluator
#define lucmpneARM64Evaluator TR::TreeEvaluator::lcmpneEvaluator
#define lucmpltARM64Evaluator TR::TreeEvaluator::lucmpltEvaluator
#define lucmpgeARM64Evaluator TR::TreeEvaluator::lucmpgeEvaluator
#define lucmpgtARM64Evaluator TR::TreeEvaluator::lucmpgtEvaluator
#define lucmpleARM64Evaluator TR::TreeEvaluator::lucmpleEvaluator
#define fcmpeqARM64Evaluator TR::TreeEvaluator::fcmpeqEvaluator
#define fcmpneARM64Evaluator TR::TreeEvaluator::fcmpneEvaluator
#define fcmpltARM64Evaluator TR::TreeEvaluator::fcmpltEvaluator
#define fcmpgeARM64Evaluator TR::TreeEvaluator::fcmpgeEvaluator
#define fcmpgtARM64Evaluator TR::TreeEvaluator::fcmpgtEvaluator
#define fcmpleARM64Evaluator TR::TreeEvaluator::fcmpleEvaluator
#define fcmpequARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fcmpneuARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fcmpltuARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fcmpgeuARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fcmpgtuARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fcmpleuARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcmpeqARM64Evaluator TR::TreeEvaluator::dcmpeqEvaluator
#define dcmpneARM64Evaluator TR::TreeEvaluator::dcmpneEvaluator
#define dcmpltARM64Evaluator TR::TreeEvaluator::dcmpltEvaluator
#define dcmpgeARM64Evaluator TR::TreeEvaluator::dcmpgeEvaluator
#define dcmpgtARM64Evaluator TR::TreeEvaluator::dcmpgtEvaluator
#define dcmpleARM64Evaluator TR::TreeEvaluator::dcmpleEvaluator
#define dcmpequARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcmpneuARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcmpltuARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcmpgeuARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcmpgtuARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcmpleuARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define acmpeqARM64Evaluator TR::TreeEvaluator::lcmpeqEvaluator 
#define acmpneARM64Evaluator TR::TreeEvaluator::lcmpneEvaluator 
#define acmpltARM64Evaluator TR::TreeEvaluator::lucmpltEvaluator 
#define acmpgeARM64Evaluator TR::TreeEvaluator::lucmpgeEvaluator 
#define acmpgtARM64Evaluator TR::TreeEvaluator::lucmpgtEvaluator 
#define acmpleARM64Evaluator TR::TreeEvaluator::lucmpleEvaluator 
#define bcmpeqARM64Evaluator TR::TreeEvaluator::icmpeqEvaluator
#define bcmpneARM64Evaluator TR::TreeEvaluator::icmpneEvaluator
#define bcmpltARM64Evaluator TR::TreeEvaluator::icmpltEvaluator
#define bcmpgeARM64Evaluator TR::TreeEvaluator::icmpgeEvaluator
#define bcmpgtARM64Evaluator TR::TreeEvaluator::icmpgtEvaluator
#define bcmpleARM64Evaluator TR::TreeEvaluator::icmpleEvaluator
#define bucmpeqARM64Evaluator TR::TreeEvaluator::icmpeqEvaluator
#define bucmpneARM64Evaluator TR::TreeEvaluator::icmpneEvaluator
#define bucmpltARM64Evaluator TR::TreeEvaluator::iucmpltEvaluator
#define bucmpgeARM64Evaluator TR::TreeEvaluator::iucmpgeEvaluator
#define bucmpgtARM64Evaluator TR::TreeEvaluator::iucmpgtEvaluator
#define bucmpleARM64Evaluator TR::TreeEvaluator::iucmpleEvaluator
#define scmpeqARM64Evaluator TR::TreeEvaluator::icmpeqEvaluator
#define scmpneARM64Evaluator TR::TreeEvaluator::icmpneEvaluator
#define scmpltARM64Evaluator TR::TreeEvaluator::icmpltEvaluator
#define scmpgeARM64Evaluator TR::TreeEvaluator::icmpgeEvaluator
#define scmpgtARM64Evaluator TR::TreeEvaluator::icmpgtEvaluator
#define scmpleARM64Evaluator TR::TreeEvaluator::icmpleEvaluator
#define sucmpeqARM64Evaluator TR::TreeEvaluator::icmpeqEvaluator
#define sucmpneARM64Evaluator TR::TreeEvaluator::icmpneEvaluator
#define sucmpltARM64Evaluator TR::TreeEvaluator::iucmpltEvaluator
#define sucmpgeARM64Evaluator TR::TreeEvaluator::iucmpgeEvaluator
#define sucmpgtARM64Evaluator TR::TreeEvaluator::iucmpgtEvaluator
#define sucmpleARM64Evaluator TR::TreeEvaluator::iucmpleEvaluator
#define lcmpARM64Evaluator TR::TreeEvaluator::lcmpEvaluator
#define fcmplARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fcmpgARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcmplARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcmpgARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ificmpeqARM64Evaluator TR::TreeEvaluator::ificmpeqEvaluator
#define ificmpneARM64Evaluator TR::TreeEvaluator::ificmpneEvaluator
#define ificmpltARM64Evaluator TR::TreeEvaluator::ificmpltEvaluator
#define ificmpgeARM64Evaluator TR::TreeEvaluator::ificmpgeEvaluator
#define ificmpgtARM64Evaluator TR::TreeEvaluator::ificmpgtEvaluator
#define ificmpleARM64Evaluator TR::TreeEvaluator::ificmpleEvaluator
#define ifiucmpeqARM64Evaluator TR::TreeEvaluator::ificmpeqEvaluator
#define ifiucmpneARM64Evaluator TR::TreeEvaluator::ificmpneEvaluator
#define ifiucmpltARM64Evaluator TR::TreeEvaluator::ifiucmpltEvaluator
#define ifiucmpgeARM64Evaluator TR::TreeEvaluator::ifiucmpgeEvaluator
#define ifiucmpgtARM64Evaluator TR::TreeEvaluator::ifiucmpgtEvaluator
#define ifiucmpleARM64Evaluator TR::TreeEvaluator::ifiucmpleEvaluator
#define iflcmpeqARM64Evaluator TR::TreeEvaluator::iflcmpeqEvaluator
#define iflcmpneARM64Evaluator TR::TreeEvaluator::iflcmpneEvaluator
#define iflcmpltARM64Evaluator TR::TreeEvaluator::iflcmpltEvaluator
#define iflcmpgeARM64Evaluator TR::TreeEvaluator::iflcmpgeEvaluator
#define iflcmpgtARM64Evaluator TR::TreeEvaluator::iflcmpgtEvaluator
#define iflcmpleARM64Evaluator TR::TreeEvaluator::iflcmpleEvaluator
#define iflucmpeqARM64Evaluator TR::TreeEvaluator::iflcmpeqEvaluator
#define iflucmpneARM64Evaluator TR::TreeEvaluator::iflcmpneEvaluator
#define iflucmpltARM64Evaluator TR::TreeEvaluator::iflucmpltEvaluator
#define iflucmpgeARM64Evaluator TR::TreeEvaluator::iflucmpgeEvaluator
#define iflucmpgtARM64Evaluator TR::TreeEvaluator::iflucmpgtEvaluator
#define iflucmpleARM64Evaluator TR::TreeEvaluator::iflucmpleEvaluator
#define iffcmpeqARM64Evaluator TR::TreeEvaluator::iffcmpeqEvaluator
#define iffcmpneARM64Evaluator TR::TreeEvaluator::iffcmpneEvaluator
#define iffcmpltARM64Evaluator TR::TreeEvaluator::iffcmpltEvaluator
#define iffcmpgeARM64Evaluator TR::TreeEvaluator::iffcmpgeEvaluator
#define iffcmpgtARM64Evaluator TR::TreeEvaluator::iffcmpgtEvaluator
#define iffcmpleARM64Evaluator TR::TreeEvaluator::iffcmpleEvaluator
#define iffcmpequARM64Evaluator TR::TreeEvaluator::iffcmpequEvaluator
#define iffcmpneuARM64Evaluator TR::TreeEvaluator::iffcmpneuEvaluator
#define iffcmpltuARM64Evaluator TR::TreeEvaluator::iffcmpltuEvaluator
#define iffcmpgeuARM64Evaluator TR::TreeEvaluator::iffcmpgeuEvaluator
#define iffcmpgtuARM64Evaluator TR::TreeEvaluator::iffcmpgtuEvaluator
#define iffcmpleuARM64Evaluator TR::TreeEvaluator::iffcmpleuEvaluator
#define ifdcmpeqARM64Evaluator TR::TreeEvaluator::ifdcmpeqEvaluator
#define ifdcmpneARM64Evaluator TR::TreeEvaluator::ifdcmpneEvaluator
#define ifdcmpltARM64Evaluator TR::TreeEvaluator::ifdcmpltEvaluator
#define ifdcmpgeARM64Evaluator TR::TreeEvaluator::ifdcmpgeEvaluator
#define ifdcmpgtARM64Evaluator TR::TreeEvaluator::ifdcmpgtEvaluator
#define ifdcmpleARM64Evaluator TR::TreeEvaluator::ifdcmpleEvaluator
#define ifdcmpequARM64Evaluator TR::TreeEvaluator::ifdcmpequEvaluator
#define ifdcmpneuARM64Evaluator TR::TreeEvaluator::ifdcmpneuEvaluator
#define ifdcmpltuARM64Evaluator TR::TreeEvaluator::ifdcmpltuEvaluator
#define ifdcmpgeuARM64Evaluator TR::TreeEvaluator::ifdcmpgeuEvaluator
#define ifdcmpgtuARM64Evaluator TR::TreeEvaluator::ifdcmpgtuEvaluator
#define ifdcmpleuARM64Evaluator TR::TreeEvaluator::ifdcmpleuEvaluator
#define ifacmpeqARM64Evaluator TR::TreeEvaluator::iflcmpeqEvaluator
#define ifacmpneARM64Evaluator TR::TreeEvaluator::iflcmpneEvaluator
#define ifacmpltARM64Evaluator TR::TreeEvaluator::iflucmpltEvaluator
#define ifacmpgeARM64Evaluator TR::TreeEvaluator::iflucmpgeEvaluator
#define ifacmpgtARM64Evaluator TR::TreeEvaluator::iflucmpgtEvaluator
#define ifacmpleARM64Evaluator TR::TreeEvaluator::iflucmpleEvaluator
#define ifbcmpeqARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbcmpneARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbcmpltARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbcmpgeARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbcmpgtARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbcmpleARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbucmpeqARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbucmpneARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbucmpltARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbucmpgeARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbucmpgtARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbucmpleARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifscmpeqARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifscmpneARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifscmpltARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifscmpgeARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifscmpgtARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifscmpleARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifsucmpeqARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifsucmpneARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifsucmpltARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifsucmpgeARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifsucmpgtARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifsucmpleARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define loadaddrARM64Evaluator TR::TreeEvaluator::loadaddrEvaluator
#define ZEROCHKARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define callIfARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iRegLoadARM64Evaluator TR::TreeEvaluator::iRegLoadEvaluator
#define aRegLoadARM64Evaluator TR::TreeEvaluator::aRegLoadEvaluator
#define lRegLoadARM64Evaluator TR::TreeEvaluator::iRegLoadEvaluator
#define fRegLoadARM64Evaluator TR::TreeEvaluator::fRegLoadEvaluator
#define dRegLoadARM64Evaluator TR::TreeEvaluator::fRegLoadEvaluator
#define sRegLoadARM64Evaluator TR::TreeEvaluator::iRegLoadEvaluator
#define bRegLoadARM64Evaluator TR::TreeEvaluator::iRegLoadEvaluator
#define iRegStoreARM64Evaluator TR::TreeEvaluator::iRegStoreEvaluator
#define aRegStoreARM64Evaluator TR::TreeEvaluator::iRegStoreEvaluator
#define lRegStoreARM64Evaluator TR::TreeEvaluator::iRegStoreEvaluator
#define fRegStoreARM64Evaluator TR::TreeEvaluator::iRegStoreEvaluator
#define dRegStoreARM64Evaluator TR::TreeEvaluator::iRegStoreEvaluator
#define sRegStoreARM64Evaluator TR::TreeEvaluator::iRegStoreEvaluator
#define bRegStoreARM64Evaluator TR::TreeEvaluator::iRegStoreEvaluator
#define GlRegDepsARM64Evaluator TR::TreeEvaluator::GlRegDepsEvaluator
#define iselectARM64Evaluator TR::TreeEvaluator::iselectEvaluator
#define lselectARM64Evaluator TR::TreeEvaluator::iselectEvaluator
#define bselectARM64Evaluator TR::TreeEvaluator::iselectEvaluator
#define sselectARM64Evaluator TR::TreeEvaluator::iselectEvaluator
#define aselectARM64Evaluator TR::TreeEvaluator::iselectEvaluator
#define fselectARM64Evaluator TR::TreeEvaluator::fselectEvaluator
#define dselectARM64Evaluator TR::TreeEvaluator::fselectEvaluator
#define treetopARM64Evaluator TR::TreeEvaluator::treetopEvaluator
#define MethodEnterHookARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define MethodExitHookARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define PassThroughARM64Evaluator TR::TreeEvaluator::passThroughEvaluator
#define compressedRefsARM64Evaluator TR::TreeEvaluator::compressedRefsEvaluator
#define BBStartARM64Evaluator TR::TreeEvaluator::BBStartEvaluator
#define BBEndARM64Evaluator TR::TreeEvaluator::BBEndEvaluator
#define viremARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define viminARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vimaxARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vigetelemARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define visetelemARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vimergelARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vimergehARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpeqARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpgtARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpgeARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpltARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpleARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpalleqARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpallneARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpallgtARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpallgeARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpallltARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpallleARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpanyeqARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpanyneARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpanygtARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpanygeARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpanyltARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpanyleARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vnotARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vbitselectARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vpermARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vsplatsARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdmergelARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdmergehARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdsetelemARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdgetelemARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdselARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdremARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdmaddARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdnmsubARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdmsubARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdmaxARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdminARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpeqARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpneARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpgtARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpgeARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpltARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpleARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpalleqARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpallneARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpallgtARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpallgeARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpallltARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpallleARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpanyeqARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpanyneARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpanygtARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpanygeARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpanyltARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpanyleARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdsqrtARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdlogARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vincARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdecARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vnegARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vcomARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vaddARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vsubARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vmulARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdivARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vremARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vandARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vorARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vxorARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vshlARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vushrARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vshrARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vcmpeqARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vcmpneARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vcmpltARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vucmpltARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vcmpgtARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vucmpgtARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vcmpleARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vucmpleARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vcmpgeARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vucmpgeARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vloadARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vloadiARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vstoreARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vstoreiARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vrandARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vreturnARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vcallARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vcalliARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vselectARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define v2vARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vl2vdARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vconstARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define getvelemARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vsetelemARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vbRegLoadARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vsRegLoadARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define viRegLoadARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vlRegLoadARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vfRegLoadARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdRegLoadARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vbRegStoreARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vsRegStoreARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define viRegStoreARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vlRegStoreARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vfRegStoreARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdRegStoreARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iuconstARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define luconstARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define buconstARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iuloadARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define luloadARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define buloadARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iuloadiARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define luloadiARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define buloadiARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iustoreARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lustoreARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bustoreARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iustoreiARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lustoreiARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bustoreiARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iureturnARM64Evaluator TR::TreeEvaluator::ireturnEvaluator
#define lureturnARM64Evaluator TR::TreeEvaluator::lreturnEvaluator
#define iucallARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lucallARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iuaddARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define luaddARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define buaddARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iusubARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lusubARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define busubARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iunegARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lunegARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define f2iuARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define f2luARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define f2buARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define f2cARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define d2iuARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define d2luARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define d2buARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define d2cARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iuRegLoadARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define luRegLoadARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iuRegStoreARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define luRegStoreARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define cconstARM64Evaluator TR::TreeEvaluator::cconstEvaluator
#define cloadARM64Evaluator TR::TreeEvaluator::cloadEvaluator
#define cloadiARM64Evaluator TR::TreeEvaluator::cloadEvaluator
#define cstoreARM64Evaluator TR::TreeEvaluator::sstoreEvaluator
#define cstoreiARM64Evaluator TR::TreeEvaluator::sstoreEvaluator
#define monentARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define monexitARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define monexitfenceARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define tstartARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define tfinishARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define tabortARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define instanceofARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define checkcastARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define checkcastAndNULLCHKARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define NewARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define newvalueARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define newarrayARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define anewarrayARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define variableNewARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define variableNewArrayARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define multianewarrayARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define arraylengthARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define contigarraylengthARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define discontigarraylengthARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define icalliARM64Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define iucalliARM64Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define lcalliARM64Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define lucalliARM64Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define fcalliARM64Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define dcalliARM64Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define acalliARM64Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define calliARM64Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define fenceARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define luaddhARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define caddARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define aiaddARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define aiuaddARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define aladdARM64Evaluator TR::TreeEvaluator::aladdEvaluator
#define aluaddARM64Evaluator TR::TreeEvaluator::aladdEvaluator
#define lusubhARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define csubARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define imulhARM64Evaluator TR::TreeEvaluator::imulhEvaluator
#define iumulhARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lmulhARM64Evaluator TR::TreeEvaluator::lmulhEvaluator
#define lumulhARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ibits2fARM64Evaluator TR::TreeEvaluator::ibits2fEvaluator
#define fbits2iARM64Evaluator TR::TreeEvaluator::fbits2iEvaluator
#define lbits2dARM64Evaluator TR::TreeEvaluator::lbits2dEvaluator
#define dbits2lARM64Evaluator TR::TreeEvaluator::dbits2lEvaluator
#define lookupARM64Evaluator TR::TreeEvaluator::lookupEvaluator
#define trtLookupARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define CaseARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define tableARM64Evaluator TR::TreeEvaluator::tableEvaluator
#define exceptionRangeFenceARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dbgFenceARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define NULLCHKARM64Evaluator TR::TreeEvaluator::badILOpEvaluator 
#define ResolveCHKARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ResolveAndNULLCHKARM64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define DIVCHKARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define OverflowCHKARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define UnsignedOverflowCHKARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define BNDCHKARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ArrayCopyBNDCHKARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define BNDCHKwithSpineCHKARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define SpineCHKARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ArrayStoreCHKARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ArrayCHKARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define RetARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define arraycopyARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define arraysetARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define arraytranslateARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define arraytranslateAndTestARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define long2StringARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bitOpMemARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bitOpMemNDARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define arraycmpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define arraycmpWithPadARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define allocationFenceARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define loadFenceARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define storeFenceARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fullFenceARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define MergeNewARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define computeCCARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define butestARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define sutestARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bucmpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bcmpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define sucmpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define scmpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iucmpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define icmpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lucmpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ificmpoARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ificmpnoARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iflcmpoARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iflcmpnoARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ificmnoARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ificmnnoARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iflcmnoARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iflcmnnoARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iuaddcARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define luaddcARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iusubbARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lusubbARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define icmpsetARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lcmpsetARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bztestnsetARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ibatomicorARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define isatomicorARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iiatomicorARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ilatomicorARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dexpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define branchARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define igotoARM64Evaluator TR::TreeEvaluator::igotoEvaluator 
#define bexpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define buexpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define sexpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define cexpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iexpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iuexpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lexpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define luexpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fexpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fuexpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define duexpARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ixfrsARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lxfrsARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fxfrsARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dxfrsARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fintARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dintARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fnintARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dnintARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fsqrtARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dsqrtARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define getstackARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define deallocaARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define idozARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcosARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dsinARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dtanARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcoshARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dsinhARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dtanhARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dacosARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dasinARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define datanARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define datan2ARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dlogARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dfloorARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ffloorARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dceilARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fceilARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ibranchARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define mbranchARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define getpmARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define setpmARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define loadAutoOffsetARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define imaxARM64Evaluator TR::TreeEvaluator::imaxEvaluator
#define iumaxARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lmaxARM64Evaluator TR::TreeEvaluator::lmaxEvaluator
#define lumaxARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fmaxARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dmaxARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iminARM64Evaluator TR::TreeEvaluator::iminEvaluator
#define iuminARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lminARM64Evaluator TR::TreeEvaluator::lminEvaluator
#define luminARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fminARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dminARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define trtARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define trtSimpleARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ihbitARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ilbitARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define inolzARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define inotzARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ipopcntARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lhbitARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define llbitARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lnolzARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lnotzARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lpopcntARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ibyteswapARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bbitpermuteARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define sbitpermuteARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ibitpermuteARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lbitpermuteARM64Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define PrefetchARM64Evaluator TR::TreeEvaluator::PrefetchEvaluator


#include "il/OMROpcodes.hpp"

#define GENERATE_TREE_EVAL_TABLE(\
   opcode, \
   name, \
   prop1, \
   prop2, \
   prop3, \
   prop4, \
   dataType, \
   typeProps, \
   childProps, \
   swapChildrenOpcode, \
   reverseBranchOpcode, \
   boolCompareOpcode, \
   ifCompareOpcode, \
   enumValue, \
   ...) enumValue ## ARM64Evaluator,

   FOR_EACH_OPCODE(GENERATE_TREE_EVAL_TABLE)

#undef GENERATE_TREE_EVAL_TABLE

