/*******************************************************************************
 * Copyright (c) 2018, 2020 IBM Corp. and others
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which accompanies this
 * distribution and is available at http://eclipse.org/legal/epl-2.0
 * or the Apache License, Version 2.0 which accompanies this distribution
 * and is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License, v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception [1] and GNU General Public
 * License, version 2 with the OpenJDK Assembly Exception [2].
 *
 * [1] https://www.gnu.org/software/classpath/license.html
 * [2] http://openjdk.java.net/legal/assembly-exception.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
 *******************************************************************************/
/*
 * This table is #included in a static table.
 * Only Function Pointers are allowed.
 */

#define BadILOpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define aconstEvaluator TR::TreeEvaluator::aconstEvaluator
#define iconstEvaluator TR::TreeEvaluator::iconstEvaluator
#define lconstEvaluator TR::TreeEvaluator::lconstEvaluator
#define fconstEvaluator TR::TreeEvaluator::fconstEvaluator
#define dconstEvaluator TR::TreeEvaluator::dconstEvaluator
#define bconstEvaluator TR::TreeEvaluator::bconstEvaluator
#define sconstEvaluator TR::TreeEvaluator::sconstEvaluator
#define iloadEvaluator TR::TreeEvaluator::iloadEvaluator
#define floadEvaluator TR::TreeEvaluator::floadEvaluator
#define dloadEvaluator TR::TreeEvaluator::dloadEvaluator
#define aloadEvaluator TR::TreeEvaluator::aloadEvaluator
#define bloadEvaluator TR::TreeEvaluator::bloadEvaluator
#define sloadEvaluator TR::TreeEvaluator::sloadEvaluator
#define lloadEvaluator TR::TreeEvaluator::lloadEvaluator
#define irdbarEvaluator TR::TreeEvaluator::irdbarEvaluator
#define frdbarEvaluator TR::TreeEvaluator::frdbarEvaluator
#define drdbarEvaluator TR::TreeEvaluator::drdbarEvaluator
#define ardbarEvaluator TR::TreeEvaluator::ardbarEvaluator
#define brdbarEvaluator TR::TreeEvaluator::brdbarEvaluator
#define srdbarEvaluator TR::TreeEvaluator::srdbarEvaluator
#define lrdbarEvaluator TR::TreeEvaluator::lrdbarEvaluator
#define iloadiEvaluator TR::TreeEvaluator::iloadEvaluator
#define floadiEvaluator TR::TreeEvaluator::floadEvaluator
#define dloadiEvaluator TR::TreeEvaluator::dloadEvaluator
#define aloadiEvaluator TR::TreeEvaluator::aloadEvaluator
#define bloadiEvaluator TR::TreeEvaluator::bloadEvaluator
#define sloadiEvaluator TR::TreeEvaluator::sloadEvaluator
#define lloadiEvaluator TR::TreeEvaluator::lloadEvaluator
#define irdbariEvaluator TR::TreeEvaluator::irdbariEvaluator
#define frdbariEvaluator TR::TreeEvaluator::frdbariEvaluator
#define drdbariEvaluator TR::TreeEvaluator::drdbariEvaluator
#define ardbariEvaluator TR::TreeEvaluator::ardbariEvaluator
#define brdbariEvaluator TR::TreeEvaluator::brdbariEvaluator
#define srdbariEvaluator TR::TreeEvaluator::srdbariEvaluator
#define lrdbariEvaluator TR::TreeEvaluator::lrdbariEvaluator
#define istoreEvaluator TR::TreeEvaluator::istoreEvaluator
#define lstoreEvaluator TR::TreeEvaluator::lstoreEvaluator
#define fstoreEvaluator TR::TreeEvaluator::fstoreEvaluator
#define dstoreEvaluator TR::TreeEvaluator::dstoreEvaluator
#define astoreEvaluator TR::TreeEvaluator::astoreEvaluator
#define bstoreEvaluator TR::TreeEvaluator::bstoreEvaluator
#define sstoreEvaluator TR::TreeEvaluator::sstoreEvaluator
#define iwrtbarEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define lwrtbarEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fwrtbarEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dwrtbarEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define awrtbarEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define bwrtbarEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define swrtbarEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define lstoreiEvaluator TR::TreeEvaluator::lstoreEvaluator
#define fstoreiEvaluator TR::TreeEvaluator::fstoreEvaluator
#define dstoreiEvaluator TR::TreeEvaluator::dstoreEvaluator
#define astoreiEvaluator TR::TreeEvaluator::astoreEvaluator
#define bstoreiEvaluator TR::TreeEvaluator::bstoreEvaluator
#define sstoreiEvaluator TR::TreeEvaluator::sstoreEvaluator
#define istoreiEvaluator TR::TreeEvaluator::istoreEvaluator
#define lwrtbariEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fwrtbariEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dwrtbariEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define awrtbariEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define bwrtbariEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define swrtbariEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iwrtbariEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define GotoEvaluator TR::TreeEvaluator::gotoEvaluator
#define ireturnEvaluator TR::TreeEvaluator::ireturnEvaluator
#define lreturnEvaluator TR::TreeEvaluator::lreturnEvaluator
#define freturnEvaluator TR::TreeEvaluator::freturnEvaluator
#define dreturnEvaluator TR::TreeEvaluator::dreturnEvaluator
#define areturnEvaluator TR::TreeEvaluator::areturnEvaluator
#define ReturnEvaluator TR::TreeEvaluator::returnEvaluator
#define asynccheckEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define athrowEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define icallEvaluator TR::TreeEvaluator::directCallEvaluator
#define lcallEvaluator TR::TreeEvaluator::directCallEvaluator
#define fcallEvaluator TR::TreeEvaluator::directCallEvaluator
#define dcallEvaluator TR::TreeEvaluator::directCallEvaluator
#define acallEvaluator TR::TreeEvaluator::directCallEvaluator
#define callEvaluator TR::TreeEvaluator::directCallEvaluator
#define iaddEvaluator TR::TreeEvaluator::iaddEvaluator
#define laddEvaluator TR::TreeEvaluator::laddEvaluator
#define faddEvaluator TR::TreeEvaluator::faddEvaluator
#define daddEvaluator TR::TreeEvaluator::daddEvaluator
#define baddEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define saddEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define isubEvaluator TR::TreeEvaluator::isubEvaluator
#define lsubEvaluator TR::TreeEvaluator::lsubEvaluator
#define fsubEvaluator TR::TreeEvaluator::fsubEvaluator
#define dsubEvaluator TR::TreeEvaluator::dsubEvaluator
#define bsubEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define ssubEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define asubEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define imulEvaluator TR::TreeEvaluator::imulEvaluator
#define lmulEvaluator TR::TreeEvaluator::lmulEvaluator
#define fmulEvaluator TR::TreeEvaluator::fmulEvaluator
#define dmulEvaluator TR::TreeEvaluator::dmulEvaluator
#define bmulEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define smulEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define idivEvaluator TR::TreeEvaluator::idivEvaluator
#define ldivEvaluator TR::TreeEvaluator::ldivEvaluator
#define fdivEvaluator TR::TreeEvaluator::fdivEvaluator
#define ddivEvaluator TR::TreeEvaluator::ddivEvaluator
#define bdivEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define sdivEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iudivEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define ludivEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iremEvaluator TR::TreeEvaluator::iremEvaluator
#define lremEvaluator TR::TreeEvaluator::lremEvaluator
#define fremEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dremEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define bremEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define sremEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iuremEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define inegEvaluator TR::TreeEvaluator::inegEvaluator
#define lnegEvaluator TR::TreeEvaluator::lnegEvaluator
#define fnegEvaluator TR::TreeEvaluator::fnegEvaluator
#define dnegEvaluator TR::TreeEvaluator::dnegEvaluator
#define bnegEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define snegEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iabsEvaluator TR::TreeEvaluator::iabsEvaluator
#define labsEvaluator TR::TreeEvaluator::labsEvaluator
#define fabsEvaluator TR::TreeEvaluator::fabsEvaluator
#define dabsEvaluator TR::TreeEvaluator::dabsEvaluator
#define ishlEvaluator TR::TreeEvaluator::ishlEvaluator
#define lshlEvaluator TR::TreeEvaluator::ishlEvaluator
#define bshlEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define sshlEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define ishrEvaluator TR::TreeEvaluator::ishrEvaluator
#define lshrEvaluator TR::TreeEvaluator::ishrEvaluator
#define bshrEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define sshrEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iushrEvaluator TR::TreeEvaluator::iushrEvaluator
#define lushrEvaluator TR::TreeEvaluator::iushrEvaluator
#define bushrEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define sushrEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define irolEvaluator TR::TreeEvaluator::irolEvaluator
#define lrolEvaluator TR::TreeEvaluator::irolEvaluator
#define iandEvaluator TR::TreeEvaluator::iandEvaluator
#define landEvaluator TR::TreeEvaluator::landEvaluator
#define bandEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define sandEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iorEvaluator TR::TreeEvaluator::iorEvaluator
#define lorEvaluator TR::TreeEvaluator::lorEvaluator
#define borEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define sorEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define ixorEvaluator TR::TreeEvaluator::ixorEvaluator
#define lxorEvaluator TR::TreeEvaluator::lxorEvaluator
#define bxorEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define sxorEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define i2lEvaluator TR::TreeEvaluator::i2lEvaluator
#define i2fEvaluator TR::TreeEvaluator::i2fEvaluator
#define i2dEvaluator TR::TreeEvaluator::i2dEvaluator
#define i2bEvaluator TR::TreeEvaluator::l2iEvaluator
#define i2sEvaluator TR::TreeEvaluator::l2iEvaluator
#define i2aEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iu2lEvaluator TR::TreeEvaluator::iu2lEvaluator
#define iu2fEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iu2dEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iu2aEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define l2iEvaluator TR::TreeEvaluator::l2iEvaluator
#define l2fEvaluator TR::TreeEvaluator::l2fEvaluator
#define l2dEvaluator TR::TreeEvaluator::l2dEvaluator
#define l2bEvaluator TR::TreeEvaluator::l2iEvaluator
#define l2sEvaluator TR::TreeEvaluator::l2iEvaluator
#define l2aEvaluator TR::TreeEvaluator::l2aEvaluator
#define lu2fEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lu2dEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lu2aEvaluator TR::TreeEvaluator::passThroughEvaluator
#define f2iEvaluator TR::TreeEvaluator::f2iEvaluator
#define f2lEvaluator TR::TreeEvaluator::f2lEvaluator
#define f2dEvaluator TR::TreeEvaluator::f2dEvaluator
#define f2bEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define f2sEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define d2iEvaluator TR::TreeEvaluator::d2iEvaluator
#define d2lEvaluator TR::TreeEvaluator::d2lEvaluator
#define d2fEvaluator TR::TreeEvaluator::d2fEvaluator
#define d2bEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define d2sEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define b2iEvaluator TR::TreeEvaluator::b2iEvaluator
#define b2lEvaluator TR::TreeEvaluator::b2lEvaluator
#define b2fEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define b2dEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define b2sEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define b2aEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bu2iEvaluator TR::TreeEvaluator::bu2iEvaluator
#define bu2lEvaluator TR::TreeEvaluator::bu2lEvaluator
#define bu2fEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bu2dEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bu2sEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bu2aEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define s2iEvaluator TR::TreeEvaluator::s2iEvaluator
#define s2lEvaluator TR::TreeEvaluator::s2lEvaluator
#define s2fEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define s2dEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define s2bEvaluator TR::TreeEvaluator::l2iEvaluator 
#define s2aEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define su2iEvaluator TR::TreeEvaluator::su2iEvaluator
#define su2lEvaluator TR::TreeEvaluator::su2lEvaluator
#define su2fEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define su2dEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define su2aEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define a2iEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define a2lEvaluator TR::TreeEvaluator::passThroughEvaluator
#define a2bEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define a2sEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define icmpeqEvaluator TR::TreeEvaluator::icmpeqEvaluator
#define icmpneEvaluator TR::TreeEvaluator::icmpneEvaluator
#define icmpltEvaluator TR::TreeEvaluator::icmpltEvaluator
#define icmpgeEvaluator TR::TreeEvaluator::icmpgeEvaluator
#define icmpgtEvaluator TR::TreeEvaluator::icmpgtEvaluator
#define icmpleEvaluator TR::TreeEvaluator::icmpleEvaluator
#define iucmpltEvaluator TR::TreeEvaluator::iucmpltEvaluator
#define iucmpgeEvaluator TR::TreeEvaluator::iucmpgeEvaluator
#define iucmpgtEvaluator TR::TreeEvaluator::iucmpgtEvaluator
#define iucmpleEvaluator TR::TreeEvaluator::iucmpleEvaluator
#define lcmpeqEvaluator TR::TreeEvaluator::lcmpeqEvaluator
#define lcmpneEvaluator TR::TreeEvaluator::lcmpneEvaluator
#define lcmpltEvaluator TR::TreeEvaluator::lcmpltEvaluator
#define lcmpgeEvaluator TR::TreeEvaluator::lcmpgeEvaluator
#define lcmpgtEvaluator TR::TreeEvaluator::lcmpgtEvaluator
#define lcmpleEvaluator TR::TreeEvaluator::lcmpleEvaluator
#define lucmpltEvaluator TR::TreeEvaluator::lucmpltEvaluator
#define lucmpgeEvaluator TR::TreeEvaluator::lucmpgeEvaluator
#define lucmpgtEvaluator TR::TreeEvaluator::lucmpgtEvaluator
#define lucmpleEvaluator TR::TreeEvaluator::lucmpleEvaluator
#define fcmpeqEvaluator TR::TreeEvaluator::fcmpeqEvaluator
#define fcmpneEvaluator TR::TreeEvaluator::fcmpneEvaluator
#define fcmpltEvaluator TR::TreeEvaluator::fcmpltEvaluator
#define fcmpgeEvaluator TR::TreeEvaluator::fcmpgeEvaluator
#define fcmpgtEvaluator TR::TreeEvaluator::fcmpgtEvaluator
#define fcmpleEvaluator TR::TreeEvaluator::fcmpleEvaluator
#define fcmpequEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fcmpneuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fcmpltuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fcmpgeuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fcmpgtuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fcmpleuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcmpeqEvaluator TR::TreeEvaluator::dcmpeqEvaluator
#define dcmpneEvaluator TR::TreeEvaluator::dcmpneEvaluator
#define dcmpltEvaluator TR::TreeEvaluator::dcmpltEvaluator
#define dcmpgeEvaluator TR::TreeEvaluator::dcmpgeEvaluator
#define dcmpgtEvaluator TR::TreeEvaluator::dcmpgtEvaluator
#define dcmpleEvaluator TR::TreeEvaluator::dcmpleEvaluator
#define dcmpequEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcmpneuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcmpltuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcmpgeuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcmpgtuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcmpleuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define acmpeqEvaluator TR::TreeEvaluator::lcmpeqEvaluator 
#define acmpneEvaluator TR::TreeEvaluator::lcmpneEvaluator 
#define acmpltEvaluator TR::TreeEvaluator::lucmpltEvaluator 
#define acmpgeEvaluator TR::TreeEvaluator::lucmpgeEvaluator 
#define acmpgtEvaluator TR::TreeEvaluator::lucmpgtEvaluator 
#define acmpleEvaluator TR::TreeEvaluator::lucmpleEvaluator 
#define bcmpeqEvaluator TR::TreeEvaluator::icmpeqEvaluator
#define bcmpneEvaluator TR::TreeEvaluator::icmpneEvaluator
#define bcmpltEvaluator TR::TreeEvaluator::icmpltEvaluator
#define bcmpgeEvaluator TR::TreeEvaluator::icmpgeEvaluator
#define bcmpgtEvaluator TR::TreeEvaluator::icmpgtEvaluator
#define bcmpleEvaluator TR::TreeEvaluator::icmpleEvaluator
#define bucmpltEvaluator TR::TreeEvaluator::iucmpltEvaluator
#define bucmpgeEvaluator TR::TreeEvaluator::iucmpgeEvaluator
#define bucmpgtEvaluator TR::TreeEvaluator::iucmpgtEvaluator
#define bucmpleEvaluator TR::TreeEvaluator::iucmpleEvaluator
#define scmpeqEvaluator TR::TreeEvaluator::icmpeqEvaluator
#define scmpneEvaluator TR::TreeEvaluator::icmpneEvaluator
#define scmpltEvaluator TR::TreeEvaluator::icmpltEvaluator
#define scmpgeEvaluator TR::TreeEvaluator::icmpgeEvaluator
#define scmpgtEvaluator TR::TreeEvaluator::icmpgtEvaluator
#define scmpleEvaluator TR::TreeEvaluator::icmpleEvaluator
#define sucmpltEvaluator TR::TreeEvaluator::iucmpltEvaluator
#define sucmpgeEvaluator TR::TreeEvaluator::iucmpgeEvaluator
#define sucmpgtEvaluator TR::TreeEvaluator::iucmpgtEvaluator
#define sucmpleEvaluator TR::TreeEvaluator::iucmpleEvaluator
#define lcmpEvaluator TR::TreeEvaluator::lcmpEvaluator
#define fcmplEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fcmpgEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcmplEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcmpgEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ificmpeqEvaluator TR::TreeEvaluator::ificmpeqEvaluator
#define ificmpneEvaluator TR::TreeEvaluator::ificmpneEvaluator
#define ificmpltEvaluator TR::TreeEvaluator::ificmpltEvaluator
#define ificmpgeEvaluator TR::TreeEvaluator::ificmpgeEvaluator
#define ificmpgtEvaluator TR::TreeEvaluator::ificmpgtEvaluator
#define ificmpleEvaluator TR::TreeEvaluator::ificmpleEvaluator
#define ifiucmpltEvaluator TR::TreeEvaluator::ifiucmpltEvaluator
#define ifiucmpgeEvaluator TR::TreeEvaluator::ifiucmpgeEvaluator
#define ifiucmpgtEvaluator TR::TreeEvaluator::ifiucmpgtEvaluator
#define ifiucmpleEvaluator TR::TreeEvaluator::ifiucmpleEvaluator
#define iflcmpeqEvaluator TR::TreeEvaluator::iflcmpeqEvaluator
#define iflcmpneEvaluator TR::TreeEvaluator::iflcmpneEvaluator
#define iflcmpltEvaluator TR::TreeEvaluator::iflcmpltEvaluator
#define iflcmpgeEvaluator TR::TreeEvaluator::iflcmpgeEvaluator
#define iflcmpgtEvaluator TR::TreeEvaluator::iflcmpgtEvaluator
#define iflcmpleEvaluator TR::TreeEvaluator::iflcmpleEvaluator
#define iflucmpltEvaluator TR::TreeEvaluator::iflucmpltEvaluator
#define iflucmpgeEvaluator TR::TreeEvaluator::iflucmpgeEvaluator
#define iflucmpgtEvaluator TR::TreeEvaluator::iflucmpgtEvaluator
#define iflucmpleEvaluator TR::TreeEvaluator::iflucmpleEvaluator
#define iffcmpeqEvaluator TR::TreeEvaluator::iffcmpeqEvaluator
#define iffcmpneEvaluator TR::TreeEvaluator::iffcmpneEvaluator
#define iffcmpltEvaluator TR::TreeEvaluator::iffcmpltEvaluator
#define iffcmpgeEvaluator TR::TreeEvaluator::iffcmpgeEvaluator
#define iffcmpgtEvaluator TR::TreeEvaluator::iffcmpgtEvaluator
#define iffcmpleEvaluator TR::TreeEvaluator::iffcmpleEvaluator
#define iffcmpequEvaluator TR::TreeEvaluator::iffcmpequEvaluator
#define iffcmpneuEvaluator TR::TreeEvaluator::iffcmpneuEvaluator
#define iffcmpltuEvaluator TR::TreeEvaluator::iffcmpltuEvaluator
#define iffcmpgeuEvaluator TR::TreeEvaluator::iffcmpgeuEvaluator
#define iffcmpgtuEvaluator TR::TreeEvaluator::iffcmpgtuEvaluator
#define iffcmpleuEvaluator TR::TreeEvaluator::iffcmpleuEvaluator
#define ifdcmpeqEvaluator TR::TreeEvaluator::ifdcmpeqEvaluator
#define ifdcmpneEvaluator TR::TreeEvaluator::ifdcmpneEvaluator
#define ifdcmpltEvaluator TR::TreeEvaluator::ifdcmpltEvaluator
#define ifdcmpgeEvaluator TR::TreeEvaluator::ifdcmpgeEvaluator
#define ifdcmpgtEvaluator TR::TreeEvaluator::ifdcmpgtEvaluator
#define ifdcmpleEvaluator TR::TreeEvaluator::ifdcmpleEvaluator
#define ifdcmpequEvaluator TR::TreeEvaluator::ifdcmpequEvaluator
#define ifdcmpneuEvaluator TR::TreeEvaluator::ifdcmpneuEvaluator
#define ifdcmpltuEvaluator TR::TreeEvaluator::ifdcmpltuEvaluator
#define ifdcmpgeuEvaluator TR::TreeEvaluator::ifdcmpgeuEvaluator
#define ifdcmpgtuEvaluator TR::TreeEvaluator::ifdcmpgtuEvaluator
#define ifdcmpleuEvaluator TR::TreeEvaluator::ifdcmpleuEvaluator
#define ifacmpeqEvaluator TR::TreeEvaluator::iflcmpeqEvaluator
#define ifacmpneEvaluator TR::TreeEvaluator::iflcmpneEvaluator
#define ifacmpltEvaluator TR::TreeEvaluator::iflucmpltEvaluator
#define ifacmpgeEvaluator TR::TreeEvaluator::iflucmpgeEvaluator
#define ifacmpgtEvaluator TR::TreeEvaluator::iflucmpgtEvaluator
#define ifacmpleEvaluator TR::TreeEvaluator::iflucmpleEvaluator
#define ifbcmpeqEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbcmpneEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbcmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbcmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbcmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbcmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbucmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbucmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbucmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifbucmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifscmpeqEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifscmpneEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifscmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifscmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifscmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifscmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifsucmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifsucmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifsucmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ifsucmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define loadaddrEvaluator TR::TreeEvaluator::loadaddrEvaluator
#define ZEROCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define callIfEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iRegLoadEvaluator TR::TreeEvaluator::iRegLoadEvaluator
#define aRegLoadEvaluator TR::TreeEvaluator::aRegLoadEvaluator
#define lRegLoadEvaluator TR::TreeEvaluator::iRegLoadEvaluator
#define fRegLoadEvaluator TR::TreeEvaluator::fRegLoadEvaluator
#define dRegLoadEvaluator TR::TreeEvaluator::fRegLoadEvaluator
#define sRegLoadEvaluator TR::TreeEvaluator::iRegLoadEvaluator
#define bRegLoadEvaluator TR::TreeEvaluator::iRegLoadEvaluator
#define iRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define aRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define lRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define fRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define dRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define sRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define bRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define GlRegDepsEvaluator TR::TreeEvaluator::GlRegDepsEvaluator
#define iselectEvaluator TR::TreeEvaluator::iselectEvaluator
#define lselectEvaluator TR::TreeEvaluator::iselectEvaluator
#define bselectEvaluator TR::TreeEvaluator::iselectEvaluator
#define sselectEvaluator TR::TreeEvaluator::iselectEvaluator
#define aselectEvaluator TR::TreeEvaluator::iselectEvaluator
#define fselectEvaluator TR::TreeEvaluator::fselectEvaluator
#define dselectEvaluator TR::TreeEvaluator::fselectEvaluator
#define treetopEvaluator TR::TreeEvaluator::treetopEvaluator
#define MethodEnterHookEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define MethodExitHookEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define PassThroughEvaluator TR::TreeEvaluator::passThroughEvaluator
#define compressedRefsEvaluator TR::TreeEvaluator::compressedRefsEvaluator
#define BBStartEvaluator TR::TreeEvaluator::BBStartEvaluator
#define BBEndEvaluator TR::TreeEvaluator::BBEndEvaluator
#define viremEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define viminEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vimaxEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vigetelemEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define visetelemEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vimergelEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vimergehEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpeqEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpalleqEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpallneEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpallgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpallgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpallltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpallleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpanyeqEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpanyneEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpanygtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpanygeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpanyltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vicmpanyleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vnotEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vbitselectEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vpermEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vsplatsEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdmergelEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdmergehEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdsetelemEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdgetelemEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdselEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdremEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdmaddEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdnmsubEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdmsubEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdmaxEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdminEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpeqEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpneEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpalleqEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpallneEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpallgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpallgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpallltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpallleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpanyeqEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpanyneEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpanygtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpanygeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpanyltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdcmpanyleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdsqrtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdlogEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vincEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdecEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vnegEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vcomEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vaddEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vsubEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vmulEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdivEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vremEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vandEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vorEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vxorEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vshlEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vushrEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vshrEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vcmpeqEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vcmpneEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vcmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vucmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vcmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vucmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vcmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vucmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vcmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vucmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vloadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vloadiEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vstoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vstoreiEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vrandEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vreturnEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vcallEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vcalliEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vselectEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define v2vEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vl2vdEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vconstEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define getvelemEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vsetelemEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vbRegLoadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vsRegLoadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define viRegLoadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vlRegLoadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vfRegLoadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdRegLoadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vbRegStoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vsRegStoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define viRegStoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vlRegStoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vfRegStoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define vdRegStoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iuloadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define luloadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define buloadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iuloadiEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define luloadiEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define buloadiEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iustoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lustoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bustoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iustoreiEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lustoreiEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bustoreiEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iuaddEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define luaddEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define buaddEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iusubEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lusubEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define busubEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iunegEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lunegEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define f2iuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define f2luEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define f2buEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define f2cEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define d2iuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define d2luEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define d2buEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define d2cEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iuRegLoadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define luRegLoadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iuRegStoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define luRegStoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define cloadEvaluator TR::TreeEvaluator::cloadEvaluator
#define cloadiEvaluator TR::TreeEvaluator::cloadEvaluator
#define cstoreEvaluator TR::TreeEvaluator::sstoreEvaluator
#define cstoreiEvaluator TR::TreeEvaluator::sstoreEvaluator
#define monentEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define monexitEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define monexitfenceEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define tstartEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define tfinishEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define tabortEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define instanceofEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define checkcastEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define checkcastAndNULLCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define NewEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define newvalueEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define newarrayEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define anewarrayEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define variableNewEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define variableNewArrayEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define multianewarrayEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define arraylengthEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define contigarraylengthEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define discontigarraylengthEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define icalliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define lcalliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define fcalliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define dcalliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define acalliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define calliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define fenceEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define luaddhEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define caddEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define aiaddEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define aiuaddEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define aladdEvaluator TR::TreeEvaluator::aladdEvaluator
#define aluaddEvaluator TR::TreeEvaluator::aladdEvaluator
#define lusubhEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define csubEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define imulhEvaluator TR::TreeEvaluator::imulhEvaluator
#define iumulhEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lmulhEvaluator TR::TreeEvaluator::lmulhEvaluator
#define lumulhEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ibits2fEvaluator TR::TreeEvaluator::ibits2fEvaluator
#define fbits2iEvaluator TR::TreeEvaluator::fbits2iEvaluator
#define lbits2dEvaluator TR::TreeEvaluator::lbits2dEvaluator
#define dbits2lEvaluator TR::TreeEvaluator::dbits2lEvaluator
#define lookupEvaluator TR::TreeEvaluator::lookupEvaluator
#define trtLookupEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define CaseEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define tableEvaluator TR::TreeEvaluator::tableEvaluator
#define exceptionRangeFenceEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dbgFenceEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define NULLCHKEvaluator TR::TreeEvaluator::badILOpEvaluator 
#define ResolveCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ResolveAndNULLCHKEvaluator TR::TreeEvaluator::badILOpEvaluator
#define DIVCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define OverflowCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define UnsignedOverflowCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define BNDCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ArrayCopyBNDCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define BNDCHKwithSpineCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define SpineCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ArrayStoreCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ArrayCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define RetEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define arraycopyEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define arraysetEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define arraytranslateEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define arraytranslateAndTestEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define long2StringEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bitOpMemEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bitOpMemNDEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define arraycmpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define arraycmpWithPadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define allocationFenceEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define loadFenceEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define storeFenceEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fullFenceEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define MergeNewEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define computeCCEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define butestEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define sutestEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bucmpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bcmpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define sucmpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define scmpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iucmpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define icmpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lucmpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ificmpoEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ificmpnoEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iflcmpoEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iflcmpnoEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ificmnoEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ificmnnoEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iflcmnoEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iflcmnnoEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iuaddcEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define luaddcEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iusubbEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lusubbEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define icmpsetEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lcmpsetEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define bztestnsetEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ibatomicorEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define isatomicorEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iiatomicorEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ilatomicorEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define branchEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define igotoEvaluator TR::TreeEvaluator::igotoEvaluator 
#define bexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define buexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define sexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define cexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iuexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define luexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fuexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define duexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ixfrsEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lxfrsEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fxfrsEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dxfrsEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fintEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dintEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fnintEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dnintEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fsqrtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dsqrtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define getstackEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define deallocaEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define idozEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcosEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dsinEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dtanEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dcoshEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dsinhEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dtanhEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dacosEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dasinEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define datanEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define datan2Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dlogEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dfloorEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ffloorEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dceilEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fceilEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ibranchEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define mbranchEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define getpmEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define setpmEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define loadAutoOffsetEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define imaxEvaluator TR::TreeEvaluator::imaxEvaluator
#define iumaxEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lmaxEvaluator TR::TreeEvaluator::lmaxEvaluator
#define lumaxEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fmaxEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dmaxEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define iminEvaluator TR::TreeEvaluator::iminEvaluator
#define iuminEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lminEvaluator TR::TreeEvaluator::lminEvaluator
#define luminEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define fminEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define dminEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define trtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define trtSimpleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ihbitEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ilbitEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define inolzEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define inotzEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ipopcntEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lhbitEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define llbitEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lnolzEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lnotzEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lpopcntEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define sbyteswapEvaluator TR::TreeEvaluator::sbyteswapEvaluator 
#define ibyteswapEvaluator TR::TreeEvaluator::ibyteswapEvaluator 
#define lbyteswapEvaluator TR::TreeEvaluator::lbyteswapEvaluator 
#define bbitpermuteEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define sbitpermuteEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define ibitpermuteEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define lbitpermuteEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define PrefetchEvaluator TR::TreeEvaluator::PrefetchEvaluator


#include "il/OMROpcodes.hpp"

#define GENERATE_TREE_EVAL_TABLE(\
   opcode, \
   name, \
   prop1, \
   prop2, \
   prop3, \
   prop4, \
   dataType, \
   typeProps, \
   childProps, \
   swapChildrenOpcode, \
   reverseBranchOpcode, \
   boolCompareOpcode, \
   ifCompareOpcode, \
   enumValue, \
   ...) enumValue ## Evaluator,

   BadILOpEvaluator,
   FOR_EACH_OPCODE(GENERATE_TREE_EVAL_TABLE)

#undef GENERATE_TREE_EVAL_TABLE

