/*******************************************************************************
 * Copyright (c) 2018, 2021 IBM Corp. and others
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which accompanies this
 * distribution and is available at http://eclipse.org/legal/epl-2.0
 * or the Apache License, Version 2.0 which accompanies this distribution
 * and is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License, v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception [1] and GNU General Public
 * License, version 2 with the OpenJDK Assembly Exception [2].
 *
 * [1] https://www.gnu.org/software/classpath/license.html
 * [2] http://openjdk.java.net/legal/assembly-exception.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
 *******************************************************************************/
/*
 * This table is #included in a static table.
 * Only Function Pointers are allowed.
 */

#define _BadILOpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _aconstEvaluator TR::TreeEvaluator::aconstEvaluator
#define _iconstEvaluator TR::TreeEvaluator::iconstEvaluator
#define _lconstEvaluator TR::TreeEvaluator::lconstEvaluator
#define _fconstEvaluator TR::TreeEvaluator::fconstEvaluator
#define _dconstEvaluator TR::TreeEvaluator::dconstEvaluator
#define _bconstEvaluator TR::TreeEvaluator::bconstEvaluator
#define _sconstEvaluator TR::TreeEvaluator::sconstEvaluator
#define _iloadEvaluator TR::TreeEvaluator::iloadEvaluator
#define _floadEvaluator TR::TreeEvaluator::floadEvaluator
#define _dloadEvaluator TR::TreeEvaluator::dloadEvaluator
#define _aloadEvaluator TR::TreeEvaluator::aloadEvaluator
#define _bloadEvaluator TR::TreeEvaluator::bloadEvaluator
#define _sloadEvaluator TR::TreeEvaluator::sloadEvaluator
#define _lloadEvaluator TR::TreeEvaluator::lloadEvaluator
#define _irdbarEvaluator TR::TreeEvaluator::irdbarEvaluator
#define _frdbarEvaluator TR::TreeEvaluator::frdbarEvaluator
#define _drdbarEvaluator TR::TreeEvaluator::drdbarEvaluator
#define _ardbarEvaluator TR::TreeEvaluator::ardbarEvaluator
#define _brdbarEvaluator TR::TreeEvaluator::brdbarEvaluator
#define _srdbarEvaluator TR::TreeEvaluator::srdbarEvaluator
#define _lrdbarEvaluator TR::TreeEvaluator::lrdbarEvaluator
#define _iloadiEvaluator TR::TreeEvaluator::iloadEvaluator
#define _floadiEvaluator TR::TreeEvaluator::floadEvaluator
#define _dloadiEvaluator TR::TreeEvaluator::dloadEvaluator
#define _aloadiEvaluator TR::TreeEvaluator::aloadEvaluator
#define _bloadiEvaluator TR::TreeEvaluator::bloadEvaluator
#define _sloadiEvaluator TR::TreeEvaluator::sloadEvaluator
#define _lloadiEvaluator TR::TreeEvaluator::lloadEvaluator
#define _irdbariEvaluator TR::TreeEvaluator::irdbariEvaluator
#define _frdbariEvaluator TR::TreeEvaluator::frdbariEvaluator
#define _drdbariEvaluator TR::TreeEvaluator::drdbariEvaluator
#define _ardbariEvaluator TR::TreeEvaluator::ardbariEvaluator
#define _brdbariEvaluator TR::TreeEvaluator::brdbariEvaluator
#define _srdbariEvaluator TR::TreeEvaluator::srdbariEvaluator
#define _lrdbariEvaluator TR::TreeEvaluator::lrdbariEvaluator
#define _istoreEvaluator TR::TreeEvaluator::istoreEvaluator
#define _lstoreEvaluator TR::TreeEvaluator::lstoreEvaluator
#define _fstoreEvaluator TR::TreeEvaluator::fstoreEvaluator
#define _dstoreEvaluator TR::TreeEvaluator::dstoreEvaluator
#define _astoreEvaluator TR::TreeEvaluator::astoreEvaluator
#define _bstoreEvaluator TR::TreeEvaluator::bstoreEvaluator
#define _sstoreEvaluator TR::TreeEvaluator::sstoreEvaluator
#define _iwrtbarEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _lwrtbarEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _fwrtbarEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _dwrtbarEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _awrtbarEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _bwrtbarEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _swrtbarEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _lstoreiEvaluator TR::TreeEvaluator::lstoreEvaluator
#define _fstoreiEvaluator TR::TreeEvaluator::fstoreEvaluator
#define _dstoreiEvaluator TR::TreeEvaluator::dstoreEvaluator
#define _astoreiEvaluator TR::TreeEvaluator::astoreEvaluator
#define _bstoreiEvaluator TR::TreeEvaluator::bstoreEvaluator
#define _sstoreiEvaluator TR::TreeEvaluator::sstoreEvaluator
#define _istoreiEvaluator TR::TreeEvaluator::istoreEvaluator
#define _lwrtbariEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _fwrtbariEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _dwrtbariEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _awrtbariEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _bwrtbariEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _swrtbariEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _iwrtbariEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _GotoEvaluator TR::TreeEvaluator::gotoEvaluator
#define _ireturnEvaluator TR::TreeEvaluator::ireturnEvaluator
#define _lreturnEvaluator TR::TreeEvaluator::lreturnEvaluator
#define _freturnEvaluator TR::TreeEvaluator::freturnEvaluator
#define _dreturnEvaluator TR::TreeEvaluator::dreturnEvaluator
#define _areturnEvaluator TR::TreeEvaluator::areturnEvaluator
#define _ReturnEvaluator TR::TreeEvaluator::returnEvaluator
#define _asynccheckEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _athrowEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _icallEvaluator TR::TreeEvaluator::directCallEvaluator
#define _lcallEvaluator TR::TreeEvaluator::directCallEvaluator
#define _fcallEvaluator TR::TreeEvaluator::directCallEvaluator
#define _dcallEvaluator TR::TreeEvaluator::directCallEvaluator
#define _acallEvaluator TR::TreeEvaluator::directCallEvaluator
#define _callEvaluator TR::TreeEvaluator::directCallEvaluator
#define _iaddEvaluator TR::TreeEvaluator::iaddEvaluator
#define _laddEvaluator TR::TreeEvaluator::laddEvaluator
#define _faddEvaluator TR::TreeEvaluator::faddEvaluator
#define _daddEvaluator TR::TreeEvaluator::daddEvaluator
#define _baddEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _saddEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _isubEvaluator TR::TreeEvaluator::isubEvaluator
#define _lsubEvaluator TR::TreeEvaluator::lsubEvaluator
#define _fsubEvaluator TR::TreeEvaluator::fsubEvaluator
#define _dsubEvaluator TR::TreeEvaluator::dsubEvaluator
#define _bsubEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _ssubEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _asubEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _imulEvaluator TR::TreeEvaluator::imulEvaluator
#define _lmulEvaluator TR::TreeEvaluator::lmulEvaluator
#define _fmulEvaluator TR::TreeEvaluator::fmulEvaluator
#define _dmulEvaluator TR::TreeEvaluator::dmulEvaluator
#define _bmulEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _smulEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _idivEvaluator TR::TreeEvaluator::idivEvaluator
#define _ldivEvaluator TR::TreeEvaluator::ldivEvaluator
#define _fdivEvaluator TR::TreeEvaluator::fdivEvaluator
#define _ddivEvaluator TR::TreeEvaluator::ddivEvaluator
#define _bdivEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _sdivEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _iudivEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _ludivEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _iremEvaluator TR::TreeEvaluator::iremEvaluator
#define _lremEvaluator TR::TreeEvaluator::lremEvaluator
#define _fremEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _dremEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _bremEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _sremEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _iuremEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _inegEvaluator TR::TreeEvaluator::inegEvaluator
#define _lnegEvaluator TR::TreeEvaluator::lnegEvaluator
#define _fnegEvaluator TR::TreeEvaluator::fnegEvaluator
#define _dnegEvaluator TR::TreeEvaluator::dnegEvaluator
#define _bnegEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _snegEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iabsEvaluator TR::TreeEvaluator::iabsEvaluator
#define _labsEvaluator TR::TreeEvaluator::labsEvaluator
#define _fabsEvaluator TR::TreeEvaluator::fabsEvaluator
#define _dabsEvaluator TR::TreeEvaluator::dabsEvaluator
#define _ishlEvaluator TR::TreeEvaluator::ishlEvaluator
#define _lshlEvaluator TR::TreeEvaluator::ishlEvaluator
#define _bshlEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _sshlEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _ishrEvaluator TR::TreeEvaluator::ishrEvaluator
#define _lshrEvaluator TR::TreeEvaluator::ishrEvaluator
#define _bshrEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _sshrEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _iushrEvaluator TR::TreeEvaluator::iushrEvaluator
#define _lushrEvaluator TR::TreeEvaluator::iushrEvaluator
#define _bushrEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _sushrEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _irolEvaluator TR::TreeEvaluator::irolEvaluator
#define _lrolEvaluator TR::TreeEvaluator::irolEvaluator
#define _iandEvaluator TR::TreeEvaluator::iandEvaluator
#define _landEvaluator TR::TreeEvaluator::landEvaluator
#define _bandEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _sandEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _iorEvaluator TR::TreeEvaluator::iorEvaluator
#define _lorEvaluator TR::TreeEvaluator::lorEvaluator
#define _borEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _sorEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _ixorEvaluator TR::TreeEvaluator::ixorEvaluator
#define _lxorEvaluator TR::TreeEvaluator::lxorEvaluator
#define _bxorEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _sxorEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _i2lEvaluator TR::TreeEvaluator::i2lEvaluator
#define _i2fEvaluator TR::TreeEvaluator::i2fEvaluator
#define _i2dEvaluator TR::TreeEvaluator::i2dEvaluator
#define _i2bEvaluator TR::TreeEvaluator::l2iEvaluator
#define _i2sEvaluator TR::TreeEvaluator::l2iEvaluator
#define _i2aEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _iu2lEvaluator TR::TreeEvaluator::iu2lEvaluator
#define _iu2fEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _iu2dEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _iu2aEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define _l2iEvaluator TR::TreeEvaluator::l2iEvaluator
#define _l2fEvaluator TR::TreeEvaluator::l2fEvaluator
#define _l2dEvaluator TR::TreeEvaluator::l2dEvaluator
#define _l2bEvaluator TR::TreeEvaluator::l2iEvaluator
#define _l2sEvaluator TR::TreeEvaluator::l2iEvaluator
#define _l2aEvaluator TR::TreeEvaluator::l2aEvaluator
#define _lu2fEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _lu2dEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _lu2aEvaluator TR::TreeEvaluator::passThroughEvaluator
#define _f2iEvaluator TR::TreeEvaluator::f2iEvaluator
#define _f2lEvaluator TR::TreeEvaluator::f2lEvaluator
#define _f2dEvaluator TR::TreeEvaluator::f2dEvaluator
#define _f2bEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _f2sEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _d2iEvaluator TR::TreeEvaluator::d2iEvaluator
#define _d2lEvaluator TR::TreeEvaluator::d2lEvaluator
#define _d2fEvaluator TR::TreeEvaluator::d2fEvaluator
#define _d2bEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _d2sEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _b2iEvaluator TR::TreeEvaluator::b2iEvaluator
#define _b2lEvaluator TR::TreeEvaluator::b2lEvaluator
#define _b2fEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _b2dEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _b2sEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _b2aEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _bu2iEvaluator TR::TreeEvaluator::bu2iEvaluator
#define _bu2lEvaluator TR::TreeEvaluator::bu2lEvaluator
#define _bu2fEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _bu2dEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _bu2sEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _bu2aEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _s2iEvaluator TR::TreeEvaluator::s2iEvaluator
#define _s2lEvaluator TR::TreeEvaluator::s2lEvaluator
#define _s2fEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _s2dEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _s2bEvaluator TR::TreeEvaluator::l2iEvaluator 
#define _s2aEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _su2iEvaluator TR::TreeEvaluator::su2iEvaluator
#define _su2lEvaluator TR::TreeEvaluator::su2lEvaluator
#define _su2fEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _su2dEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _su2aEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _a2iEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _a2lEvaluator TR::TreeEvaluator::passThroughEvaluator
#define _a2bEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _a2sEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _icmpeqEvaluator TR::TreeEvaluator::icmpeqEvaluator
#define _icmpneEvaluator TR::TreeEvaluator::icmpneEvaluator
#define _icmpltEvaluator TR::TreeEvaluator::icmpltEvaluator
#define _icmpgeEvaluator TR::TreeEvaluator::icmpgeEvaluator
#define _icmpgtEvaluator TR::TreeEvaluator::icmpgtEvaluator
#define _icmpleEvaluator TR::TreeEvaluator::icmpleEvaluator
#define _iucmpltEvaluator TR::TreeEvaluator::iucmpltEvaluator
#define _iucmpgeEvaluator TR::TreeEvaluator::iucmpgeEvaluator
#define _iucmpgtEvaluator TR::TreeEvaluator::iucmpgtEvaluator
#define _iucmpleEvaluator TR::TreeEvaluator::iucmpleEvaluator
#define _lcmpeqEvaluator TR::TreeEvaluator::lcmpeqEvaluator
#define _lcmpneEvaluator TR::TreeEvaluator::lcmpneEvaluator
#define _lcmpltEvaluator TR::TreeEvaluator::lcmpltEvaluator
#define _lcmpgeEvaluator TR::TreeEvaluator::lcmpgeEvaluator
#define _lcmpgtEvaluator TR::TreeEvaluator::lcmpgtEvaluator
#define _lcmpleEvaluator TR::TreeEvaluator::lcmpleEvaluator
#define _lucmpltEvaluator TR::TreeEvaluator::lucmpltEvaluator
#define _lucmpgeEvaluator TR::TreeEvaluator::lucmpgeEvaluator
#define _lucmpgtEvaluator TR::TreeEvaluator::lucmpgtEvaluator
#define _lucmpleEvaluator TR::TreeEvaluator::lucmpleEvaluator
#define _fcmpeqEvaluator TR::TreeEvaluator::fcmpeqEvaluator
#define _fcmpneEvaluator TR::TreeEvaluator::fcmpneEvaluator
#define _fcmpltEvaluator TR::TreeEvaluator::fcmpltEvaluator
#define _fcmpgeEvaluator TR::TreeEvaluator::fcmpgeEvaluator
#define _fcmpgtEvaluator TR::TreeEvaluator::fcmpgtEvaluator
#define _fcmpleEvaluator TR::TreeEvaluator::fcmpleEvaluator
#define _fcmpequEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _fcmpneuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _fcmpltuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _fcmpgeuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _fcmpgtuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _fcmpleuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dcmpeqEvaluator TR::TreeEvaluator::dcmpeqEvaluator
#define _dcmpneEvaluator TR::TreeEvaluator::dcmpneEvaluator
#define _dcmpltEvaluator TR::TreeEvaluator::dcmpltEvaluator
#define _dcmpgeEvaluator TR::TreeEvaluator::dcmpgeEvaluator
#define _dcmpgtEvaluator TR::TreeEvaluator::dcmpgtEvaluator
#define _dcmpleEvaluator TR::TreeEvaluator::dcmpleEvaluator
#define _dcmpequEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dcmpneuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dcmpltuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dcmpgeuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dcmpgtuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dcmpleuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _acmpeqEvaluator TR::TreeEvaluator::lcmpeqEvaluator 
#define _acmpneEvaluator TR::TreeEvaluator::lcmpneEvaluator 
#define _acmpltEvaluator TR::TreeEvaluator::lucmpltEvaluator 
#define _acmpgeEvaluator TR::TreeEvaluator::lucmpgeEvaluator 
#define _acmpgtEvaluator TR::TreeEvaluator::lucmpgtEvaluator 
#define _acmpleEvaluator TR::TreeEvaluator::lucmpleEvaluator 
#define _bcmpeqEvaluator TR::TreeEvaluator::icmpeqEvaluator
#define _bcmpneEvaluator TR::TreeEvaluator::icmpneEvaluator
#define _bcmpltEvaluator TR::TreeEvaluator::icmpltEvaluator
#define _bcmpgeEvaluator TR::TreeEvaluator::icmpgeEvaluator
#define _bcmpgtEvaluator TR::TreeEvaluator::icmpgtEvaluator
#define _bcmpleEvaluator TR::TreeEvaluator::icmpleEvaluator
#define _bucmpltEvaluator TR::TreeEvaluator::iucmpltEvaluator
#define _bucmpgeEvaluator TR::TreeEvaluator::iucmpgeEvaluator
#define _bucmpgtEvaluator TR::TreeEvaluator::iucmpgtEvaluator
#define _bucmpleEvaluator TR::TreeEvaluator::iucmpleEvaluator
#define _scmpeqEvaluator TR::TreeEvaluator::icmpeqEvaluator
#define _scmpneEvaluator TR::TreeEvaluator::icmpneEvaluator
#define _scmpltEvaluator TR::TreeEvaluator::icmpltEvaluator
#define _scmpgeEvaluator TR::TreeEvaluator::icmpgeEvaluator
#define _scmpgtEvaluator TR::TreeEvaluator::icmpgtEvaluator
#define _scmpleEvaluator TR::TreeEvaluator::icmpleEvaluator
#define _sucmpltEvaluator TR::TreeEvaluator::iucmpltEvaluator
#define _sucmpgeEvaluator TR::TreeEvaluator::iucmpgeEvaluator
#define _sucmpgtEvaluator TR::TreeEvaluator::iucmpgtEvaluator
#define _sucmpleEvaluator TR::TreeEvaluator::iucmpleEvaluator
#define _lcmpEvaluator TR::TreeEvaluator::lcmpEvaluator
#define _fcmplEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _fcmpgEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dcmplEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dcmpgEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ificmpeqEvaluator TR::TreeEvaluator::ificmpeqEvaluator
#define _ificmpneEvaluator TR::TreeEvaluator::ificmpneEvaluator
#define _ificmpltEvaluator TR::TreeEvaluator::ificmpltEvaluator
#define _ificmpgeEvaluator TR::TreeEvaluator::ificmpgeEvaluator
#define _ificmpgtEvaluator TR::TreeEvaluator::ificmpgtEvaluator
#define _ificmpleEvaluator TR::TreeEvaluator::ificmpleEvaluator
#define _ifiucmpltEvaluator TR::TreeEvaluator::ifiucmpltEvaluator
#define _ifiucmpgeEvaluator TR::TreeEvaluator::ifiucmpgeEvaluator
#define _ifiucmpgtEvaluator TR::TreeEvaluator::ifiucmpgtEvaluator
#define _ifiucmpleEvaluator TR::TreeEvaluator::ifiucmpleEvaluator
#define _iflcmpeqEvaluator TR::TreeEvaluator::iflcmpeqEvaluator
#define _iflcmpneEvaluator TR::TreeEvaluator::iflcmpneEvaluator
#define _iflcmpltEvaluator TR::TreeEvaluator::iflcmpltEvaluator
#define _iflcmpgeEvaluator TR::TreeEvaluator::iflcmpgeEvaluator
#define _iflcmpgtEvaluator TR::TreeEvaluator::iflcmpgtEvaluator
#define _iflcmpleEvaluator TR::TreeEvaluator::iflcmpleEvaluator
#define _iflucmpltEvaluator TR::TreeEvaluator::iflucmpltEvaluator
#define _iflucmpgeEvaluator TR::TreeEvaluator::iflucmpgeEvaluator
#define _iflucmpgtEvaluator TR::TreeEvaluator::iflucmpgtEvaluator
#define _iflucmpleEvaluator TR::TreeEvaluator::iflucmpleEvaluator
#define _iffcmpeqEvaluator TR::TreeEvaluator::iffcmpeqEvaluator
#define _iffcmpneEvaluator TR::TreeEvaluator::iffcmpneEvaluator
#define _iffcmpltEvaluator TR::TreeEvaluator::iffcmpltEvaluator
#define _iffcmpgeEvaluator TR::TreeEvaluator::iffcmpgeEvaluator
#define _iffcmpgtEvaluator TR::TreeEvaluator::iffcmpgtEvaluator
#define _iffcmpleEvaluator TR::TreeEvaluator::iffcmpleEvaluator
#define _iffcmpequEvaluator TR::TreeEvaluator::iffcmpequEvaluator
#define _iffcmpneuEvaluator TR::TreeEvaluator::iffcmpneuEvaluator
#define _iffcmpltuEvaluator TR::TreeEvaluator::iffcmpltuEvaluator
#define _iffcmpgeuEvaluator TR::TreeEvaluator::iffcmpgeuEvaluator
#define _iffcmpgtuEvaluator TR::TreeEvaluator::iffcmpgtuEvaluator
#define _iffcmpleuEvaluator TR::TreeEvaluator::iffcmpleuEvaluator
#define _ifdcmpeqEvaluator TR::TreeEvaluator::ifdcmpeqEvaluator
#define _ifdcmpneEvaluator TR::TreeEvaluator::ifdcmpneEvaluator
#define _ifdcmpltEvaluator TR::TreeEvaluator::ifdcmpltEvaluator
#define _ifdcmpgeEvaluator TR::TreeEvaluator::ifdcmpgeEvaluator
#define _ifdcmpgtEvaluator TR::TreeEvaluator::ifdcmpgtEvaluator
#define _ifdcmpleEvaluator TR::TreeEvaluator::ifdcmpleEvaluator
#define _ifdcmpequEvaluator TR::TreeEvaluator::ifdcmpequEvaluator
#define _ifdcmpneuEvaluator TR::TreeEvaluator::ifdcmpneuEvaluator
#define _ifdcmpltuEvaluator TR::TreeEvaluator::ifdcmpltuEvaluator
#define _ifdcmpgeuEvaluator TR::TreeEvaluator::ifdcmpgeuEvaluator
#define _ifdcmpgtuEvaluator TR::TreeEvaluator::ifdcmpgtuEvaluator
#define _ifdcmpleuEvaluator TR::TreeEvaluator::ifdcmpleuEvaluator
#define _ifacmpeqEvaluator TR::TreeEvaluator::iflcmpeqEvaluator
#define _ifacmpneEvaluator TR::TreeEvaluator::iflcmpneEvaluator
#define _ifacmpltEvaluator TR::TreeEvaluator::iflucmpltEvaluator
#define _ifacmpgeEvaluator TR::TreeEvaluator::iflucmpgeEvaluator
#define _ifacmpgtEvaluator TR::TreeEvaluator::iflucmpgtEvaluator
#define _ifacmpleEvaluator TR::TreeEvaluator::iflucmpleEvaluator
#define _ifbcmpeqEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifbcmpneEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifbcmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifbcmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifbcmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifbcmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifbucmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifbucmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifbucmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifbucmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifscmpeqEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifscmpneEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifscmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifscmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifscmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifscmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifsucmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifsucmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifsucmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ifsucmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _loadaddrEvaluator TR::TreeEvaluator::loadaddrEvaluator
#define _ZEROCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _callIfEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iRegLoadEvaluator TR::TreeEvaluator::iRegLoadEvaluator
#define _aRegLoadEvaluator TR::TreeEvaluator::aRegLoadEvaluator
#define _lRegLoadEvaluator TR::TreeEvaluator::iRegLoadEvaluator
#define _fRegLoadEvaluator TR::TreeEvaluator::fRegLoadEvaluator
#define _dRegLoadEvaluator TR::TreeEvaluator::fRegLoadEvaluator
#define _sRegLoadEvaluator TR::TreeEvaluator::iRegLoadEvaluator
#define _bRegLoadEvaluator TR::TreeEvaluator::iRegLoadEvaluator
#define _iRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define _aRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define _lRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define _fRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define _dRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define _sRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define _bRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define _GlRegDepsEvaluator TR::TreeEvaluator::GlRegDepsEvaluator
#define _iselectEvaluator TR::TreeEvaluator::iselectEvaluator
#define _lselectEvaluator TR::TreeEvaluator::iselectEvaluator
#define _bselectEvaluator TR::TreeEvaluator::iselectEvaluator
#define _sselectEvaluator TR::TreeEvaluator::iselectEvaluator
#define _aselectEvaluator TR::TreeEvaluator::iselectEvaluator
#define _fselectEvaluator TR::TreeEvaluator::fselectEvaluator
#define _dselectEvaluator TR::TreeEvaluator::fselectEvaluator
#define _treetopEvaluator TR::TreeEvaluator::treetopEvaluator
#define _MethodEnterHookEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _MethodExitHookEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _PassThroughEvaluator TR::TreeEvaluator::passThroughEvaluator
#define _compressedRefsEvaluator TR::TreeEvaluator::compressedRefsEvaluator
#define _BBStartEvaluator TR::TreeEvaluator::BBStartEvaluator
#define _BBEndEvaluator TR::TreeEvaluator::BBEndEvaluator
#define _viremEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _viminEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vimaxEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vigetelemEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _visetelemEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vimergelEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vimergehEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vicmpeqEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vicmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vicmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vicmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vicmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vicmpalleqEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vicmpallneEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vicmpallgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vicmpallgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vicmpallltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vicmpallleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vicmpanyeqEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vicmpanyneEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vicmpanygtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vicmpanygeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vicmpanyltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vicmpanyleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vnotEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vbitselectEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vpermEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vsplatsEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdmergelEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdmergehEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdsetelemEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdgetelemEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdselEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdremEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdmaddEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdnmsubEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdmsubEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdmaxEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdminEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdcmpeqEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdcmpneEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdcmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdcmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdcmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdcmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdcmpalleqEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdcmpallneEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdcmpallgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdcmpallgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdcmpallltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdcmpallleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdcmpanyeqEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdcmpanyneEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdcmpanygtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdcmpanygeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdcmpanyltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdcmpanyleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdsqrtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdlogEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vincEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdecEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vnegEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vcomEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vaddEvaluator TR::TreeEvaluator::vaddEvaluator 
#define _vsubEvaluator TR::TreeEvaluator::vsubEvaluator 
#define _vmulEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdivEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vremEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vandEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vorEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vxorEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vshlEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vushrEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vshrEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vcmpeqEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vcmpneEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vcmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vucmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vcmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vucmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vcmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vucmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vcmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vucmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vloadEvaluator TR::TreeEvaluator::vloadEvaluator 
#define _vloadiEvaluator TR::TreeEvaluator::vloadEvaluator 
#define _vstoreEvaluator TR::TreeEvaluator::vstoreEvaluator 
#define _vstoreiEvaluator TR::TreeEvaluator::vstoreEvaluator 
#define _vrandEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vreturnEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vcallEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vcalliEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vselectEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _v2vEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vl2vdEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vconstEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _getvelemEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vsetelemEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vbRegLoadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vsRegLoadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _viRegLoadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vlRegLoadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vfRegLoadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdRegLoadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vbRegStoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vsRegStoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _viRegStoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vlRegStoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vfRegStoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _vdRegStoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iuloadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _luloadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _buloadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iuloadiEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _luloadiEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _buloadiEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iustoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _lustoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _bustoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iustoreiEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _lustoreiEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _bustoreiEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iuaddEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _luaddEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _buaddEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iusubEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _lusubEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _busubEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iunegEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _lunegEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _f2iuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _f2luEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _f2buEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _f2cEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _d2iuEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _d2luEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _d2buEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _d2cEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iuRegLoadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _luRegLoadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iuRegStoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _luRegStoreEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _cloadEvaluator TR::TreeEvaluator::cloadEvaluator
#define _cloadiEvaluator TR::TreeEvaluator::cloadEvaluator
#define _cstoreEvaluator TR::TreeEvaluator::sstoreEvaluator
#define _cstoreiEvaluator TR::TreeEvaluator::sstoreEvaluator
#define _monentEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _monexitEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _monexitfenceEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _tstartEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _tfinishEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _tabortEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _instanceofEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _checkcastEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _checkcastAndNULLCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _NewEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _newvalueEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _newarrayEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _anewarrayEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _variableNewEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _variableNewArrayEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _multianewarrayEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _arraylengthEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _contigarraylengthEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _discontigarraylengthEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _icalliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define _lcalliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define _fcalliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define _dcalliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define _acalliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define _calliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define _fenceEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _luaddhEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _caddEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _aiaddEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _aiuaddEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _aladdEvaluator TR::TreeEvaluator::aladdEvaluator
#define _aluaddEvaluator TR::TreeEvaluator::aladdEvaluator
#define _lusubhEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _csubEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _imulhEvaluator TR::TreeEvaluator::imulhEvaluator
#define _iumulhEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _lmulhEvaluator TR::TreeEvaluator::lmulhEvaluator
#define _lumulhEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ibits2fEvaluator TR::TreeEvaluator::ibits2fEvaluator
#define _fbits2iEvaluator TR::TreeEvaluator::fbits2iEvaluator
#define _lbits2dEvaluator TR::TreeEvaluator::lbits2dEvaluator
#define _dbits2lEvaluator TR::TreeEvaluator::dbits2lEvaluator
#define _lookupEvaluator TR::TreeEvaluator::lookupEvaluator
#define _trtLookupEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _CaseEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _tableEvaluator TR::TreeEvaluator::tableEvaluator
#define _exceptionRangeFenceEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dbgFenceEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _NULLCHKEvaluator TR::TreeEvaluator::badILOpEvaluator 
#define _ResolveCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ResolveAndNULLCHKEvaluator TR::TreeEvaluator::badILOpEvaluator
#define _DIVCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _OverflowCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _UnsignedOverflowCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _BNDCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ArrayCopyBNDCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _BNDCHKwithSpineCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _SpineCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ArrayStoreCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ArrayCHKEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _RetEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _arraycopyEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _arraysetEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _arraytranslateEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _arraytranslateAndTestEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _long2StringEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _bitOpMemEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _bitOpMemNDEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _arraycmpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _arraycmpWithPadEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _allocationFenceEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _loadFenceEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _storeFenceEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _fullFenceEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _MergeNewEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _computeCCEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _butestEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _sutestEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _bucmpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _bcmpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _sucmpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _scmpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iucmpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _icmpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _lucmpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ificmpoEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ificmpnoEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iflcmpoEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iflcmpnoEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ificmnoEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ificmnnoEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iflcmnoEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iflcmnnoEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iuaddcEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _luaddcEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iusubbEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _lusubbEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _icmpsetEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _lcmpsetEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _bztestnsetEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ibatomicorEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _isatomicorEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iiatomicorEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ilatomicorEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _branchEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _igotoEvaluator TR::TreeEvaluator::igotoEvaluator 
#define _bexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _buexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _sexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _cexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iuexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _lexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _luexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _fexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _fuexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _duexpEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ixfrsEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _lxfrsEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _fxfrsEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dxfrsEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _fintEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dintEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _fnintEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dnintEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _fsqrtEvaluator TR::TreeEvaluator::fsqrtEvaluator
#define _dsqrtEvaluator TR::TreeEvaluator::dsqrtEvaluator
#define _getstackEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _deallocaEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _idozEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dcosEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dsinEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dtanEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dcoshEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dsinhEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dtanhEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dacosEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dasinEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _datanEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _datan2Evaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dlogEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dfloorEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ffloorEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dceilEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _fceilEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ibranchEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _mbranchEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _getpmEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _setpmEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _loadAutoOffsetEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _imaxEvaluator TR::TreeEvaluator::imaxEvaluator
#define _iumaxEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _lmaxEvaluator TR::TreeEvaluator::lmaxEvaluator
#define _lumaxEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _fmaxEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dmaxEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _iminEvaluator TR::TreeEvaluator::iminEvaluator
#define _iuminEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _lminEvaluator TR::TreeEvaluator::lminEvaluator
#define _luminEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _fminEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _dminEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _trtEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _trtSimpleEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ihbitEvaluator TR::TreeEvaluator::ihbitEvaluator
#define _ilbitEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _inolzEvaluator TR::TreeEvaluator::inolzEvaluator
#define _inotzEvaluator TR::TreeEvaluator::inotzEvaluator
#define _ipopcntEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _lhbitEvaluator TR::TreeEvaluator::lhbitEvaluator
#define _llbitEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _lnolzEvaluator TR::TreeEvaluator::lnolzEvaluator
#define _lnotzEvaluator TR::TreeEvaluator::lnotzEvaluator
#define _lpopcntEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _sbyteswapEvaluator TR::TreeEvaluator::sbyteswapEvaluator 
#define _ibyteswapEvaluator TR::TreeEvaluator::ibyteswapEvaluator 
#define _lbyteswapEvaluator TR::TreeEvaluator::lbyteswapEvaluator 
#define _bbitpermuteEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _sbitpermuteEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _ibitpermuteEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _lbitpermuteEvaluator TR::TreeEvaluator::unImpOpEvaluator 
#define _PrefetchEvaluator TR::TreeEvaluator::PrefetchEvaluator

#define OPCODE_MACRO(\
   opcode, \
   name, \
   prop1, \
   prop2, \
   prop3, \
   prop4, \
   dataType, \
   typeProps, \
   childProps, \
   swapChildrenOpcode, \
   reverseBranchOpcode, \
   boolCompareOpcode, \
   ifCompareOpcode, \
   ...) _ ## opcode ## Evaluator,

   _BadILOpEvaluator,

#include "il/Opcodes.enum"
#undef OPCODE_MACRO

