find_package(LibElf)

find_path(LIBDWARF_INCLUDE_DIR "libdwarf/libdwarf.h")

if(LIBDWARF_INCLUDE_DIR)
	set(LIBDWARF_DEFINITIONS
		-DHAVE_LIBDWARF_DWARF_H=1
		-DHAVE_LIBDWARF_LIBDWARF_H=1
	)
endif()

find_library(LIBDWARF_LIBRARY dwarf)

set(LIBDWARF_INCLUDE_DIRS
	${LIBDWARF_INCLUDE_DIR}
	${LIBELF_INCLUDE_DIRS}
)

set(LIBDWARF_LIBRARIES
	${LIBDWARF_LIBRARY}
	${LIBELF_LIBRARIES}
)

include (FindPackageHandleStandardArgs)

message("LIBDWARF_INCLUDE_DIR=${LIBDWARF_INCLUDE_DIR}")
message("LIBDWARF_LIBRARY=${LIBDWARF_LIBRARY}")

find_package_handle_standard_args(LibDwarf
	DEFAULT_MSG
	LIBELF_FOUND
	LIBDWARF_LIBRARY
	LIBDWARF_INCLUDE_DIR
)
