# Find libdwarf.
# Requires:
#   LibElf
# Will set:
#   LIBDWARF_FOUND
#   LIBDWARF_INCLUDE_DIRS
#   LIBDWARF_LIBRARIES
#   LIBDWARF_DEFINITIONS

find_package(LibElf)

find_path(DWARF_H_INCLUDE_DIR "dwarf.h")

if(DWARF_H_INCLUDE_DIR)
	set(DWARF_H_DEFINITIONS -DHAVE_DWARF_H=1)
endif()

find_path(LIBDWARF_H_INCLUDE_DIR "libdwarf/dwarf.h")

if(LIBDWARF_H_INCLUDE_DIR)
	set(LIBDWARF_H_DEFINITIONS -DHAVE_LIBDWARF_LIBDWARF_H=1)
else()
	find_path(LIBDWARF_H_INCLUDE_DIR "libdwarf.h")

	if(LIBDWARF_H_INCLUDE_DIR)
		set(LIBDWARF_H_DEFINITIONS -DHAVE_LIBDWARF_H=1)
	endif()
endif()

find_library(LIBDWARF_LIBRARY dwarf)

include (FindPackageHandleStandardArgs)

find_package_handle_standard_args(LibDwarf
	DEFAULT_MSG
	LIBDWARF_LIBRARY
	DWARF_H_INCLUDE_DIR
	LIBDWARF_H_INCLUDE_DIR
	LIBELF_FOUND
)

if(LIBDWARF_FOUND)
	set(LIBDWARF_INCLUDE_DIRS
		${DWARF_H_INCLUDE_DIR}
		${LIBDWARF_H_INCLUDE_DIR}
		${LIBELF_INCLUDE_DIRS}
	)
	set(LIBDWARF_LIBRARIES
		${LIBDWARF_LIBRARY}
		${LIBELF_LIBRARIES}
	)
	set(LIBDWARF_DEFINITIONS
		${DWARF_H_DEFINITIONS}
		${LIBDWARF_H_DEFINITIONS}
		${LIBELF_DEFINITIONS}
	)
endif(LIBDWARF_FOUND)
