/*******************************************************************************
 * Copyright (c) 2000, 2020 IBM Corp. and others
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which accompanies this
 * distribution and is available at http://eclipse.org/legal/epl-2.0
 * or the Apache License, Version 2.0 which accompanies this distribution
 * and is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License, v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception [1] and GNU General Public
 * License, version 2 with the OpenJDK Assembly Exception [2].
 *
 * [1] https://www.gnu.org/software/classpath/license.html
 * [2] http://openjdk.java.net/legal/assembly-exception.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
 *******************************************************************************/

/*
 * This table is #included in a static table.
 * Only Function Pointers are allowed.
 */

#define BadILOpX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define aconstX86Evaluator TR::TreeEvaluator::aconstEvaluator
#define iconstX86Evaluator TR::TreeEvaluator::iconstEvaluator
#define lconstX86Evaluator TR::TreeEvaluator::lconstEvaluator
#define fconstX86Evaluator TR::TreeEvaluator::fconstEvaluator
#define dconstX86Evaluator TR::TreeEvaluator::dconstEvaluator
#define bconstX86Evaluator TR::TreeEvaluator::bconstEvaluator
#define sconstX86Evaluator TR::TreeEvaluator::sconstEvaluator
#define iloadX86Evaluator TR::TreeEvaluator::iloadEvaluator
#define floadX86Evaluator TR::TreeEvaluator::floadEvaluator
#define dloadX86Evaluator TR::TreeEvaluator::dloadEvaluator
#define aloadX86Evaluator TR::TreeEvaluator::aloadEvaluator
#define bloadX86Evaluator TR::TreeEvaluator::bloadEvaluator
#define sloadX86Evaluator TR::TreeEvaluator::sloadEvaluator
#define lloadX86Evaluator TR::TreeEvaluator::lloadEvaluator
#define irdbarX86Evaluator TR::TreeEvaluator::irdbarEvaluator
#define frdbarX86Evaluator TR::TreeEvaluator::frdbarEvaluator
#define drdbarX86Evaluator TR::TreeEvaluator::drdbarEvaluator
#define ardbarX86Evaluator TR::TreeEvaluator::ardbarEvaluator
#define brdbarX86Evaluator TR::TreeEvaluator::brdbarEvaluator
#define srdbarX86Evaluator TR::TreeEvaluator::srdbarEvaluator
#define lrdbarX86Evaluator TR::TreeEvaluator::lrdbarEvaluator
#define iloadiX86Evaluator TR::TreeEvaluator::iloadEvaluator
#define floadiX86Evaluator TR::TreeEvaluator::floadEvaluator
#define dloadiX86Evaluator TR::TreeEvaluator::dloadEvaluator
#define aloadiX86Evaluator TR::TreeEvaluator::aloadEvaluator
#define bloadiX86Evaluator TR::TreeEvaluator::bloadEvaluator
#define sloadiX86Evaluator TR::TreeEvaluator::sloadEvaluator
#define lloadiX86Evaluator TR::TreeEvaluator::lloadEvaluator
#define irdbariX86Evaluator TR::TreeEvaluator::irdbariEvaluator
#define frdbariX86Evaluator TR::TreeEvaluator::frdbariEvaluator
#define drdbariX86Evaluator TR::TreeEvaluator::drdbariEvaluator
#define ardbariX86Evaluator TR::TreeEvaluator::ardbariEvaluator
#define brdbariX86Evaluator TR::TreeEvaluator::brdbariEvaluator
#define srdbariX86Evaluator TR::TreeEvaluator::srdbariEvaluator
#define lrdbariX86Evaluator TR::TreeEvaluator::lrdbariEvaluator
#define istoreX86Evaluator TR::TreeEvaluator::istoreEvaluator
#define lstoreX86Evaluator TR::TreeEvaluator::lstoreEvaluator
#define fstoreX86Evaluator TR::TreeEvaluator::floatingPointStoreEvaluator
#define dstoreX86Evaluator TR::TreeEvaluator::dstoreEvaluator
#define astoreX86Evaluator TR::TreeEvaluator::istoreEvaluator
#define bstoreX86Evaluator TR::TreeEvaluator::bstoreEvaluator
#define sstoreX86Evaluator TR::TreeEvaluator::sstoreEvaluator
#define iwrtbarX86Evaluator TR::TreeEvaluator::iwrtbarEvaluator
#define lwrtbarX86Evaluator TR::TreeEvaluator::lwrtbarEvaluator
#define fwrtbarX86Evaluator TR::TreeEvaluator::fwrtbarEvaluator
#define dwrtbarX86Evaluator TR::TreeEvaluator::dwrtbarEvaluator
#define awrtbarX86Evaluator TR::TreeEvaluator::awrtbarEvaluator
#define bwrtbarX86Evaluator TR::TreeEvaluator::bwrtbarEvaluator
#define swrtbarX86Evaluator TR::TreeEvaluator::swrtbarEvaluator
#define lstoreiX86Evaluator TR::TreeEvaluator::lstoreEvaluator
#define fstoreiX86Evaluator TR::TreeEvaluator::floatingPointStoreEvaluator
#define dstoreiX86Evaluator TR::TreeEvaluator::dstoreEvaluator
#define astoreiX86Evaluator TR::TreeEvaluator::istoreEvaluator
#define bstoreiX86Evaluator TR::TreeEvaluator::bstoreEvaluator
#define sstoreiX86Evaluator TR::TreeEvaluator::sstoreEvaluator
#define istoreiX86Evaluator TR::TreeEvaluator::istoreEvaluator
#define lwrtbariX86Evaluator TR::TreeEvaluator::lwrtbariEvaluator
#define fwrtbariX86Evaluator TR::TreeEvaluator::fwrtbariEvaluator
#define dwrtbariX86Evaluator TR::TreeEvaluator::dwrtbariEvaluator
#define awrtbariX86Evaluator TR::TreeEvaluator::awrtbariEvaluator
#define bwrtbariX86Evaluator TR::TreeEvaluator::bwrtbariEvaluator
#define swrtbariX86Evaluator TR::TreeEvaluator::swrtbariEvaluator
#define iwrtbariX86Evaluator TR::TreeEvaluator::iwrtbariEvaluator
#define GotoX86Evaluator TR::TreeEvaluator::gotoEvaluator
#define ireturnX86Evaluator TR::TreeEvaluator::integerReturnEvaluator
#define lreturnX86Evaluator TR::TreeEvaluator::integerPairReturnEvaluator
#define freturnX86Evaluator TR::TreeEvaluator::fpReturnEvaluator
#define dreturnX86Evaluator TR::TreeEvaluator::fpReturnEvaluator
#define areturnX86Evaluator TR::TreeEvaluator::integerReturnEvaluator
#define ReturnX86Evaluator TR::TreeEvaluator::returnEvaluator
#define asynccheckX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define athrowX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define icallX86Evaluator TR::TreeEvaluator::directCallEvaluator
#define lcallX86Evaluator TR::TreeEvaluator::directCallEvaluator
#define fcallX86Evaluator TR::TreeEvaluator::directCallEvaluator
#define dcallX86Evaluator TR::TreeEvaluator::directCallEvaluator
#define acallX86Evaluator TR::TreeEvaluator::directCallEvaluator
#define callX86Evaluator TR::TreeEvaluator::directCallEvaluator
#define iaddX86Evaluator TR::TreeEvaluator::integerAddEvaluator
#define laddX86Evaluator TR::TreeEvaluator::integerPairAddEvaluator
#define faddX86Evaluator TR::TreeEvaluator::faddEvaluator
#define daddX86Evaluator TR::TreeEvaluator::daddEvaluator
#define baddX86Evaluator TR::TreeEvaluator::baddEvaluator
#define saddX86Evaluator TR::TreeEvaluator::saddEvaluator
#define isubX86Evaluator TR::TreeEvaluator::integerSubEvaluator
#define lsubX86Evaluator TR::TreeEvaluator::integerPairSubEvaluator
#define fsubX86Evaluator TR::TreeEvaluator::fsubEvaluator
#define dsubX86Evaluator TR::TreeEvaluator::dsubEvaluator
#define bsubX86Evaluator TR::TreeEvaluator::bsubEvaluator
#define ssubX86Evaluator TR::TreeEvaluator::ssubEvaluator
#define asubX86Evaluator TR::TreeEvaluator::integerSubEvaluator
#define imulX86Evaluator TR::TreeEvaluator::integerMulEvaluator
#define lmulX86Evaluator TR::TreeEvaluator::integerPairMulEvaluator
#define fmulX86Evaluator TR::TreeEvaluator::fmulEvaluator
#define dmulX86Evaluator TR::TreeEvaluator::dmulEvaluator
#define bmulX86Evaluator TR::TreeEvaluator::integerMulEvaluator
#define smulX86Evaluator TR::TreeEvaluator::integerMulEvaluator
#define idivX86Evaluator TR::TreeEvaluator::integerDivOrRemEvaluator
#define ldivX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fdivX86Evaluator TR::TreeEvaluator::fdivEvaluator
#define ddivX86Evaluator TR::TreeEvaluator::ddivEvaluator
#define bdivX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define sdivX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iudivX86Evaluator TR::TreeEvaluator::integerDivOrRemEvaluator
#define ludivX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define iremX86Evaluator TR::TreeEvaluator::integerDivOrRemEvaluator
#define lremX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fremX86Evaluator TR::TreeEvaluator::fpRemEvaluator
#define dremX86Evaluator TR::TreeEvaluator::fpRemEvaluator
#define bremX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define sremX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iuremX86Evaluator TR::TreeEvaluator::integerDivOrRemEvaluator
#define inegX86Evaluator TR::TreeEvaluator::integerNegEvaluator
#define lnegX86Evaluator TR::TreeEvaluator::integerPairNegEvaluator
#define fnegX86Evaluator TR::TreeEvaluator::fpUnaryMaskEvaluator
#define dnegX86Evaluator TR::TreeEvaluator::fpUnaryMaskEvaluator
#define bnegX86Evaluator TR::TreeEvaluator::bnegEvaluator
#define snegX86Evaluator TR::TreeEvaluator::snegEvaluator
#define iabsX86Evaluator TR::TreeEvaluator::integerAbsEvaluator
#define labsX86Evaluator TR::TreeEvaluator::integerPairAbsEvaluator
#define fabsX86Evaluator TR::TreeEvaluator::fpUnaryMaskEvaluator
#define dabsX86Evaluator TR::TreeEvaluator::fpUnaryMaskEvaluator
#define ishlX86Evaluator TR::TreeEvaluator::integerShlEvaluator
#define lshlX86Evaluator TR::TreeEvaluator::integerPairShlEvaluator
#define bshlX86Evaluator TR::TreeEvaluator::bshlEvaluator
#define sshlX86Evaluator TR::TreeEvaluator::sshlEvaluator
#define ishrX86Evaluator TR::TreeEvaluator::integerShrEvaluator
#define lshrX86Evaluator TR::TreeEvaluator::integerPairShrEvaluator
#define bshrX86Evaluator TR::TreeEvaluator::bshrEvaluator
#define sshrX86Evaluator TR::TreeEvaluator::sshrEvaluator
#define iushrX86Evaluator TR::TreeEvaluator::integerUshrEvaluator
#define lushrX86Evaluator TR::TreeEvaluator::integerPairUshrEvaluator
#define bushrX86Evaluator TR::TreeEvaluator::bushrEvaluator
#define sushrX86Evaluator TR::TreeEvaluator::sushrEvaluator
#define irolX86Evaluator TR::TreeEvaluator::integerRolEvaluator
#define lrolX86Evaluator TR::TreeEvaluator::integerPairRolEvaluator
#define iandX86Evaluator TR::TreeEvaluator::iandEvaluator
#define landX86Evaluator TR::TreeEvaluator::landEvaluator
#define bandX86Evaluator TR::TreeEvaluator::bandEvaluator
#define sandX86Evaluator TR::TreeEvaluator::sandEvaluator
#define iorX86Evaluator TR::TreeEvaluator::iorEvaluator
#define lorX86Evaluator TR::TreeEvaluator::lorEvaluator
#define borX86Evaluator TR::TreeEvaluator::borEvaluator
#define sorX86Evaluator TR::TreeEvaluator::sorEvaluator
#define ixorX86Evaluator TR::TreeEvaluator::ixorEvaluator
#define lxorX86Evaluator TR::TreeEvaluator::lxorEvaluator
#define bxorX86Evaluator TR::TreeEvaluator::bxorEvaluator
#define sxorX86Evaluator TR::TreeEvaluator::sxorEvaluator
#define i2lX86Evaluator TR::TreeEvaluator::i2lEvaluator
#define i2fX86Evaluator TR::TreeEvaluator::i2fEvaluator
#define i2dX86Evaluator TR::TreeEvaluator::i2dEvaluator
#define i2bX86Evaluator TR::TreeEvaluator::i2bEvaluator
#define i2sX86Evaluator TR::TreeEvaluator::i2bEvaluator
#define i2aX86Evaluator TR::TreeEvaluator::i2aEvaluator
#define iu2lX86Evaluator TR::TreeEvaluator::iu2lEvaluator
#define iu2fX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define iu2dX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define iu2aX86Evaluator TR::TreeEvaluator::passThroughEvaluator
#define l2iX86Evaluator TR::TreeEvaluator::l2iEvaluator
#define l2fX86Evaluator TR::TreeEvaluator::l2fEvaluator
#define l2dX86Evaluator TR::TreeEvaluator::l2dEvaluator
#define l2bX86Evaluator TR::TreeEvaluator::l2iEvaluator
#define l2sX86Evaluator TR::TreeEvaluator::l2iEvaluator
#define l2aX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define lu2fX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define lu2dX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define lu2aX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define f2iX86Evaluator TR::TreeEvaluator::f2iEvaluator
#define f2lX86Evaluator TR::TreeEvaluator::f2lEvaluator
#define f2dX86Evaluator TR::TreeEvaluator::f2dEvaluator
#define f2bX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define f2sX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define d2iX86Evaluator TR::TreeEvaluator::f2iEvaluator
#define d2lX86Evaluator TR::TreeEvaluator::d2lEvaluator
#define d2fX86Evaluator TR::TreeEvaluator::d2fEvaluator
#define d2bX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define d2sX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define b2iX86Evaluator TR::TreeEvaluator::b2iEvaluator
#define b2lX86Evaluator TR::TreeEvaluator::b2lEvaluator
#define b2fX86Evaluator TR::TreeEvaluator::i2fEvaluator
#define b2dX86Evaluator TR::TreeEvaluator::i2dEvaluator
#define b2sX86Evaluator TR::TreeEvaluator::b2sEvaluator
#define b2aX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define bu2iX86Evaluator TR::TreeEvaluator::bu2iEvaluator
#define bu2lX86Evaluator TR::TreeEvaluator::bu2lEvaluator
#define bu2fX86Evaluator TR::TreeEvaluator::i2fEvaluator
#define bu2dX86Evaluator TR::TreeEvaluator::i2dEvaluator
#define bu2sX86Evaluator TR::TreeEvaluator::bu2sEvaluator
#define bu2aX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define s2iX86Evaluator TR::TreeEvaluator::s2iEvaluator
#define s2lX86Evaluator TR::TreeEvaluator::s2lEvaluator
#define s2fX86Evaluator TR::TreeEvaluator::i2fEvaluator
#define s2dX86Evaluator TR::TreeEvaluator::i2dEvaluator
#define s2bX86Evaluator TR::TreeEvaluator::i2bEvaluator
#define s2aX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define su2iX86Evaluator TR::TreeEvaluator::su2iEvaluator
#define su2lX86Evaluator TR::TreeEvaluator::su2lEvaluator
#define su2fX86Evaluator TR::TreeEvaluator::i2fEvaluator
#define su2dX86Evaluator TR::TreeEvaluator::i2dEvaluator
#define su2aX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define a2iX86Evaluator TR::TreeEvaluator::passThroughEvaluator
#define a2lX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define a2bX86Evaluator TR::TreeEvaluator::i2bEvaluator
#define a2sX86Evaluator TR::TreeEvaluator::i2bEvaluator
#define icmpeqX86Evaluator TR::TreeEvaluator::integerCmpeqEvaluator
#define icmpneX86Evaluator TR::TreeEvaluator::integerCmpneEvaluator
#define icmpltX86Evaluator TR::TreeEvaluator::integerCmpltEvaluator
#define icmpgeX86Evaluator TR::TreeEvaluator::integerCmpgeEvaluator
#define icmpgtX86Evaluator TR::TreeEvaluator::integerCmpgtEvaluator
#define icmpleX86Evaluator TR::TreeEvaluator::integerCmpleEvaluator
#define iucmpeqX86Evaluator TR::TreeEvaluator::integerCmpeqEvaluator
#define iucmpneX86Evaluator TR::TreeEvaluator::integerCmpneEvaluator
#define iucmpltX86Evaluator TR::TreeEvaluator::unsignedIntegerCmpltEvaluator
#define iucmpgeX86Evaluator TR::TreeEvaluator::unsignedIntegerCmpgeEvaluator
#define iucmpgtX86Evaluator TR::TreeEvaluator::unsignedIntegerCmpgtEvaluator
#define iucmpleX86Evaluator TR::TreeEvaluator::unsignedIntegerCmpleEvaluator
#define lcmpeqX86Evaluator TR::TreeEvaluator::lcmpeqEvaluator
#define lcmpneX86Evaluator TR::TreeEvaluator::lcmpneEvaluator
#define lcmpltX86Evaluator TR::TreeEvaluator::lcmpltEvaluator
#define lcmpgeX86Evaluator TR::TreeEvaluator::lcmpgeEvaluator
#define lcmpgtX86Evaluator TR::TreeEvaluator::lcmpgtEvaluator
#define lcmpleX86Evaluator TR::TreeEvaluator::lcmpleEvaluator
#define lucmpeqX86Evaluator TR::TreeEvaluator::lcmpeqEvaluator
#define lucmpneX86Evaluator TR::TreeEvaluator::lcmpneEvaluator
#define lucmpltX86Evaluator TR::TreeEvaluator::lucmpltEvaluator
#define lucmpgeX86Evaluator TR::TreeEvaluator::lucmpgeEvaluator
#define lucmpgtX86Evaluator TR::TreeEvaluator::lucmpgtEvaluator
#define lucmpleX86Evaluator TR::TreeEvaluator::lucmpleEvaluator
#define fcmpeqX86Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpneX86Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpltX86Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpgeX86Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpgtX86Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpleX86Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpequX86Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpneuX86Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpltuX86Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpgeuX86Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpgtuX86Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpleuX86Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define dcmpeqX86Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpneX86Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpltX86Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpgeX86Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpgtX86Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpleX86Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpequX86Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpneuX86Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpltuX86Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpgeuX86Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpgtuX86Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpleuX86Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define acmpeqX86Evaluator TR::TreeEvaluator::acmpeqEvaluator
#define acmpneX86Evaluator TR::TreeEvaluator::integerCmpneEvaluator
#define acmpltX86Evaluator TR::TreeEvaluator::unsignedIntegerCmpltEvaluator
#define acmpgeX86Evaluator TR::TreeEvaluator::unsignedIntegerCmpgeEvaluator
#define acmpgtX86Evaluator TR::TreeEvaluator::unsignedIntegerCmpgtEvaluator
#define acmpleX86Evaluator TR::TreeEvaluator::unsignedIntegerCmpleEvaluator
#define bcmpeqX86Evaluator TR::TreeEvaluator::bcmpeqEvaluator
#define bcmpneX86Evaluator TR::TreeEvaluator::bcmpeqEvaluator
#define bcmpltX86Evaluator TR::TreeEvaluator::bcmpltEvaluator
#define bcmpgeX86Evaluator TR::TreeEvaluator::bcmpgeEvaluator
#define bcmpgtX86Evaluator TR::TreeEvaluator::bcmpgtEvaluator
#define bcmpleX86Evaluator TR::TreeEvaluator::bcmpleEvaluator
#define bucmpeqX86Evaluator TR::TreeEvaluator::bcmpeqEvaluator
#define bucmpneX86Evaluator TR::TreeEvaluator::bcmpeqEvaluator
#define bucmpltX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define bucmpgeX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define bucmpgtX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define bucmpleX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define scmpeqX86Evaluator TR::TreeEvaluator::scmpeqEvaluator
#define scmpneX86Evaluator TR::TreeEvaluator::scmpeqEvaluator
#define scmpltX86Evaluator TR::TreeEvaluator::scmpltEvaluator
#define scmpgeX86Evaluator TR::TreeEvaluator::scmpgeEvaluator
#define scmpgtX86Evaluator TR::TreeEvaluator::scmpgtEvaluator
#define scmpleX86Evaluator TR::TreeEvaluator::scmpleEvaluator
#define sucmpeqX86Evaluator TR::TreeEvaluator::sucmpeqEvaluator
#define sucmpneX86Evaluator TR::TreeEvaluator::sucmpeqEvaluator
#define sucmpltX86Evaluator TR::TreeEvaluator::sucmpltEvaluator
#define sucmpgeX86Evaluator TR::TreeEvaluator::sucmpgeEvaluator
#define sucmpgtX86Evaluator TR::TreeEvaluator::sucmpgtEvaluator
#define sucmpleX86Evaluator TR::TreeEvaluator::sucmpleEvaluator
#define lcmpX86Evaluator TR::TreeEvaluator::lcmpEvaluator
#define fcmplX86Evaluator TR::TreeEvaluator::compareFloatEvaluator
#define fcmpgX86Evaluator TR::TreeEvaluator::compareFloatEvaluator
#define dcmplX86Evaluator TR::TreeEvaluator::compareDoubleEvaluator
#define dcmpgX86Evaluator TR::TreeEvaluator::compareDoubleEvaluator
#define ificmpeqX86Evaluator TR::TreeEvaluator::integerIfCmpeqEvaluator
#define ificmpneX86Evaluator TR::TreeEvaluator::integerIfCmpneEvaluator
#define ificmpltX86Evaluator TR::TreeEvaluator::integerIfCmpltEvaluator
#define ificmpgeX86Evaluator TR::TreeEvaluator::integerIfCmpgeEvaluator
#define ificmpgtX86Evaluator TR::TreeEvaluator::integerIfCmpgtEvaluator
#define ificmpleX86Evaluator TR::TreeEvaluator::integerIfCmpleEvaluator
#define ifiucmpeqX86Evaluator TR::TreeEvaluator::integerIfCmpeqEvaluator
#define ifiucmpneX86Evaluator TR::TreeEvaluator::integerIfCmpneEvaluator
#define ifiucmpltX86Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpltEvaluator
#define ifiucmpgeX86Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpgeEvaluator
#define ifiucmpgtX86Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpgtEvaluator
#define ifiucmpleX86Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpleEvaluator
#define iflcmpeqX86Evaluator TR::TreeEvaluator::iflcmpeqEvaluator
#define iflcmpneX86Evaluator TR::TreeEvaluator::iflcmpneEvaluator
#define iflcmpltX86Evaluator TR::TreeEvaluator::iflcmpltEvaluator
#define iflcmpgeX86Evaluator TR::TreeEvaluator::iflcmpgeEvaluator
#define iflcmpgtX86Evaluator TR::TreeEvaluator::iflcmpgtEvaluator
#define iflcmpleX86Evaluator TR::TreeEvaluator::iflcmpleEvaluator
#define iflucmpeqX86Evaluator TR::TreeEvaluator::iflcmpeqEvaluator
#define iflucmpneX86Evaluator TR::TreeEvaluator::iflcmpneEvaluator
#define iflucmpltX86Evaluator TR::TreeEvaluator::iflcmpltEvaluator
#define iflucmpgeX86Evaluator TR::TreeEvaluator::iflcmpgeEvaluator
#define iflucmpgtX86Evaluator TR::TreeEvaluator::iflcmpgtEvaluator
#define iflucmpleX86Evaluator TR::TreeEvaluator::iflcmpleEvaluator
#define iffcmpeqX86Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpneX86Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpltX86Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpgeX86Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpgtX86Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpleX86Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpequX86Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpneuX86Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpltuX86Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpgeuX86Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpgtuX86Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpleuX86Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define ifdcmpeqX86Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpneX86Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpltX86Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpgeX86Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpgtX86Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpleX86Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpequX86Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpneuX86Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpltuX86Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpgeuX86Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpgtuX86Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpleuX86Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifacmpeqX86Evaluator TR::TreeEvaluator::ifacmpeqEvaluator
#define ifacmpneX86Evaluator TR::TreeEvaluator::integerIfCmpneEvaluator
#define ifacmpltX86Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpltEvaluator
#define ifacmpgeX86Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpgeEvaluator
#define ifacmpgtX86Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpgtEvaluator
#define ifacmpleX86Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpleEvaluator
#define ifbcmpeqX86Evaluator TR::TreeEvaluator::ifbcmpeqEvaluator
#define ifbcmpneX86Evaluator TR::TreeEvaluator::ifbcmpeqEvaluator
#define ifbcmpltX86Evaluator TR::TreeEvaluator::ifbcmpltEvaluator
#define ifbcmpgeX86Evaluator TR::TreeEvaluator::ifbcmpgeEvaluator
#define ifbcmpgtX86Evaluator TR::TreeEvaluator::ifbcmpgtEvaluator
#define ifbcmpleX86Evaluator TR::TreeEvaluator::ifbcmpleEvaluator
#define ifbucmpeqX86Evaluator TR::TreeEvaluator::ifbcmpeqEvaluator
#define ifbucmpneX86Evaluator TR::TreeEvaluator::ifbcmpeqEvaluator
#define ifbucmpltX86Evaluator TR::TreeEvaluator::ifbucmpltEvaluator
#define ifbucmpgeX86Evaluator TR::TreeEvaluator::ifbucmpgeEvaluator
#define ifbucmpgtX86Evaluator TR::TreeEvaluator::ifbucmpgtEvaluator
#define ifbucmpleX86Evaluator TR::TreeEvaluator::ifbucmpleEvaluator
#define ifscmpeqX86Evaluator TR::TreeEvaluator::ifscmpeqEvaluator
#define ifscmpneX86Evaluator TR::TreeEvaluator::ifscmpeqEvaluator
#define ifscmpltX86Evaluator TR::TreeEvaluator::ifscmpltEvaluator
#define ifscmpgeX86Evaluator TR::TreeEvaluator::ifscmpgeEvaluator
#define ifscmpgtX86Evaluator TR::TreeEvaluator::ifscmpgtEvaluator
#define ifscmpleX86Evaluator TR::TreeEvaluator::ifscmpleEvaluator
#define ifsucmpeqX86Evaluator TR::TreeEvaluator::ifsucmpeqEvaluator
#define ifsucmpneX86Evaluator TR::TreeEvaluator::ifsucmpeqEvaluator
#define ifsucmpltX86Evaluator TR::TreeEvaluator::ifsucmpltEvaluator
#define ifsucmpgeX86Evaluator TR::TreeEvaluator::ifsucmpgeEvaluator
#define ifsucmpgtX86Evaluator TR::TreeEvaluator::ifsucmpgtEvaluator
#define ifsucmpleX86Evaluator TR::TreeEvaluator::ifsucmpleEvaluator
#define loadaddrX86Evaluator TR::TreeEvaluator::loadaddrEvaluator
#define ZEROCHKX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define callIfX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iRegLoadX86Evaluator TR::TreeEvaluator::integerRegLoadEvaluator
#define aRegLoadX86Evaluator TR::TreeEvaluator::aRegLoadEvaluator
#define lRegLoadX86Evaluator TR::TreeEvaluator::lRegLoadEvaluator
#define fRegLoadX86Evaluator TR::TreeEvaluator::fRegLoadEvaluator
#define dRegLoadX86Evaluator TR::TreeEvaluator::dRegLoadEvaluator
#define sRegLoadX86Evaluator TR::TreeEvaluator::integerRegLoadEvaluator
#define bRegLoadX86Evaluator TR::TreeEvaluator::integerRegLoadEvaluator
#define iRegStoreX86Evaluator TR::TreeEvaluator::iRegStoreEvaluator
#define aRegStoreX86Evaluator TR::TreeEvaluator::iRegStoreEvaluator
#define lRegStoreX86Evaluator TR::TreeEvaluator::lRegStoreEvaluator
#define fRegStoreX86Evaluator TR::TreeEvaluator::fRegStoreEvaluator
#define dRegStoreX86Evaluator TR::TreeEvaluator::dRegStoreEvaluator
#define sRegStoreX86Evaluator TR::TreeEvaluator::iRegStoreEvaluator
#define bRegStoreX86Evaluator TR::TreeEvaluator::iRegStoreEvaluator
#define GlRegDepsX86Evaluator TR::TreeEvaluator::GlRegDepsEvaluator
#define iselectX86Evaluator TR::TreeEvaluator::iselectEvaluator
#define lselectX86Evaluator TR::TreeEvaluator::lselectEvaluator
#define bselectX86Evaluator TR::TreeEvaluator::iselectEvaluator
#define sselectX86Evaluator TR::TreeEvaluator::iselectEvaluator
#define aselectX86Evaluator TR::TreeEvaluator::iselectEvaluator
#define fselectX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define dselectX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define treetopX86Evaluator TR::TreeEvaluator::treetopEvaluator
#define MethodEnterHookX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define MethodExitHookX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define PassThroughX86Evaluator TR::TreeEvaluator::passThroughEvaluator
#define compressedRefsX86Evaluator TR::TreeEvaluator::compressedRefsEvaluator
#define BBStartX86Evaluator TR::TreeEvaluator::BBStartEvaluator
#define BBEndX86Evaluator TR::TreeEvaluator::BBEndEvaluator
#define viremX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define viminX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vimaxX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vigetelemX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define visetelemX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vimergelX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vimergehX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpeqX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpgtX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpgeX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpltX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpleX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpalleqX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallneX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallgtX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallgeX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallltX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallleX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyeqX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyneX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanygtX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanygeX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyltX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyleX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vnotX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vbitselectX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vpermX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vsplatsX86Evaluator TR::TreeEvaluator::SIMDsplatsEvaluator
#define vdmergelX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdmergehX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdsetelemX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdgetelemX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdselX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdremX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdmaddX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdnmsubX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdmsubX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdmaxX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdminX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpeqX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpneX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpgtX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpgeX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpltX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpleX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpalleqX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallneX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallgtX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallgeX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallltX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallleX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyeqX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyneX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanygtX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanygeX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyltX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyleX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdsqrtX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdlogX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vincX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdecX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vnegX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcomX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vaddX86Evaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vsubX86Evaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vmulX86Evaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vdivX86Evaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vremX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vandX86Evaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vorX86Evaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vxorX86Evaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vshlX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vushrX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vshrX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpeqX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpneX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpltX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vucmpltX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpgtX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vucmpgtX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpleX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vucmpleX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpgeX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vucmpgeX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vloadX86Evaluator TR::TreeEvaluator::SIMDloadEvaluator
#define vloadiX86Evaluator TR::TreeEvaluator::SIMDloadEvaluator
#define vstoreX86Evaluator TR::TreeEvaluator::SIMDstoreEvaluator
#define vstoreiX86Evaluator TR::TreeEvaluator::SIMDstoreEvaluator
#define vrandX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vreturnX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcallX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcalliX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vselectX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define v2vX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vl2vdX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vconstX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define getvelemX86Evaluator TR::TreeEvaluator::SIMDgetvelemEvaluator
#define vsetelemX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vbRegLoadX86Evaluator TR::TreeEvaluator::SIMDRegLoadEvaluator
#define vsRegLoadX86Evaluator TR::TreeEvaluator::SIMDRegLoadEvaluator
#define viRegLoadX86Evaluator TR::TreeEvaluator::SIMDRegLoadEvaluator
#define vlRegLoadX86Evaluator TR::TreeEvaluator::SIMDRegLoadEvaluator
#define vfRegLoadX86Evaluator TR::TreeEvaluator::SIMDRegLoadEvaluator
#define vdRegLoadX86Evaluator TR::TreeEvaluator::SIMDRegLoadEvaluator
#define vbRegStoreX86Evaluator TR::TreeEvaluator::SIMDRegStoreEvaluator
#define vsRegStoreX86Evaluator TR::TreeEvaluator::SIMDRegStoreEvaluator
#define viRegStoreX86Evaluator TR::TreeEvaluator::SIMDRegStoreEvaluator
#define vlRegStoreX86Evaluator TR::TreeEvaluator::SIMDRegStoreEvaluator
#define vfRegStoreX86Evaluator TR::TreeEvaluator::SIMDRegStoreEvaluator
#define vdRegStoreX86Evaluator TR::TreeEvaluator::SIMDRegStoreEvaluator
#define iuconstX86Evaluator TR::TreeEvaluator::iconstEvaluator
#define luconstX86Evaluator TR::TreeEvaluator::lconstEvaluator
#define buconstX86Evaluator TR::TreeEvaluator::bconstEvaluator
#define iuloadX86Evaluator TR::TreeEvaluator::iloadEvaluator
#define luloadX86Evaluator TR::TreeEvaluator::lloadEvaluator
#define buloadX86Evaluator TR::TreeEvaluator::bloadEvaluator
#define iuloadiX86Evaluator TR::TreeEvaluator::iloadEvaluator
#define luloadiX86Evaluator TR::TreeEvaluator::lloadEvaluator
#define buloadiX86Evaluator TR::TreeEvaluator::bloadEvaluator
#define iustoreX86Evaluator TR::TreeEvaluator::istoreEvaluator
#define lustoreX86Evaluator TR::TreeEvaluator::lstoreEvaluator
#define bustoreX86Evaluator TR::TreeEvaluator::bstoreEvaluator
#define iustoreiX86Evaluator TR::TreeEvaluator::istoreEvaluator
#define lustoreiX86Evaluator TR::TreeEvaluator::lstoreEvaluator
#define bustoreiX86Evaluator TR::TreeEvaluator::bstoreEvaluator
#define iureturnX86Evaluator TR::TreeEvaluator::integerReturnEvaluator
#define lureturnX86Evaluator TR::TreeEvaluator::integerPairReturnEvaluator
#define iucallX86Evaluator TR::TreeEvaluator::directCallEvaluator
#define lucallX86Evaluator TR::TreeEvaluator::directCallEvaluator
#define iuaddX86Evaluator TR::TreeEvaluator::integerAddEvaluator
#define luaddX86Evaluator TR::TreeEvaluator::integerPairAddEvaluator
#define buaddX86Evaluator TR::TreeEvaluator::baddEvaluator
#define iusubX86Evaluator TR::TreeEvaluator::integerSubEvaluator
#define lusubX86Evaluator TR::TreeEvaluator::integerPairSubEvaluator
#define busubX86Evaluator TR::TreeEvaluator::bsubEvaluator
#define iunegX86Evaluator TR::TreeEvaluator::integerNegEvaluator
#define lunegX86Evaluator TR::TreeEvaluator::integerPairNegEvaluator
#define f2iuX86Evaluator TR::TreeEvaluator::f2iEvaluator
#define f2luX86Evaluator TR::TreeEvaluator::f2lEvaluator
#define f2buX86Evaluator TR::TreeEvaluator::f2bEvaluator
#define f2cX86Evaluator TR::TreeEvaluator::f2cEvaluator
#define d2iuX86Evaluator TR::TreeEvaluator::f2iEvaluator
#define d2luX86Evaluator TR::TreeEvaluator::d2lEvaluator
#define d2buX86Evaluator TR::TreeEvaluator::d2bEvaluator
#define d2cX86Evaluator TR::TreeEvaluator::d2cEvaluator
#define iuRegLoadX86Evaluator TR::TreeEvaluator::integerRegLoadEvaluator
#define luRegLoadX86Evaluator TR::TreeEvaluator::lRegLoadEvaluator
#define iuRegStoreX86Evaluator TR::TreeEvaluator::iRegStoreEvaluator
#define luRegStoreX86Evaluator TR::TreeEvaluator::lRegStoreEvaluator
#define cconstX86Evaluator TR::TreeEvaluator::cconstEvaluator
#define cloadX86Evaluator TR::TreeEvaluator::sloadEvaluator
#define cloadiX86Evaluator TR::TreeEvaluator::sloadEvaluator
#define cstoreX86Evaluator TR::TreeEvaluator::cstoreEvaluator
#define cstoreiX86Evaluator TR::TreeEvaluator::cstoreEvaluator
#define monentX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define monexitX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define monexitfenceX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define tstartX86Evaluator TR::TreeEvaluator::tstartEvaluator
#define tfinishX86Evaluator TR::TreeEvaluator::tfinishEvaluator
#define tabortX86Evaluator TR::TreeEvaluator::tabortEvaluator
#define instanceofX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define checkcastX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define checkcastAndNULLCHKX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define NewX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define newvalueX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define newarrayX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define anewarrayX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define variableNewX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define variableNewArrayX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define multianewarrayX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define arraylengthX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define contigarraylengthX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define discontigarraylengthX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define icalliX86Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define iucalliX86Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define lcalliX86Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define lucalliX86Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define fcalliX86Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define dcalliX86Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define acalliX86Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define calliX86Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define fenceX86Evaluator TR::TreeEvaluator::fenceEvaluator
#define luaddhX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define caddX86Evaluator TR::TreeEvaluator::caddEvaluator
#define aiaddX86Evaluator TR::TreeEvaluator::integerAddEvaluator
#define aiuaddX86Evaluator TR::TreeEvaluator::integerAddEvaluator
#define aladdX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define aluaddX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define lusubhX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define csubX86Evaluator TR::TreeEvaluator::csubEvaluator
#define imulhX86Evaluator TR::TreeEvaluator::integerMulhEvaluator
#define iumulhX86Evaluator TR::TreeEvaluator::integerMulhEvaluator
#define lmulhX86Evaluator TR::TreeEvaluator::integerPairMulEvaluator
#define lumulhX86Evaluator TR::TreeEvaluator::integerPairMulEvaluator
#define ibits2fX86Evaluator TR::TreeEvaluator::ibits2fEvaluator
#define fbits2iX86Evaluator TR::TreeEvaluator::fbits2iEvaluator
#define lbits2dX86Evaluator TR::TreeEvaluator::lbits2dEvaluator
#define dbits2lX86Evaluator TR::TreeEvaluator::dbits2lEvaluator
#define lookupX86Evaluator TR::TreeEvaluator::lookupEvaluator
#define trtLookupX86Evaluator TR::TreeEvaluator::NOPEvaluator
#define CaseX86Evaluator TR::TreeEvaluator::NOPEvaluator
#define tableX86Evaluator TR::TreeEvaluator::tableEvaluator
#define exceptionRangeFenceX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define dbgFenceX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define NULLCHKX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define ResolveCHKX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define ResolveAndNULLCHKX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define DIVCHKX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define OverflowCHKX86Evaluator TR::TreeEvaluator::overflowCHKEvaluator
#define UnsignedOverflowCHKX86Evaluator TR::TreeEvaluator::overflowCHKEvaluator
#define BNDCHKX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define ArrayCopyBNDCHKX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define BNDCHKwithSpineCHKX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define SpineCHKX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define ArrayStoreCHKX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define ArrayCHKX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define RetX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define arraycopyX86Evaluator TR::TreeEvaluator::arraycopyEvaluator
#define arraysetX86Evaluator TR::TreeEvaluator::arraysetEvaluator
#define arraytranslateX86Evaluator TR::TreeEvaluator::arraytranslateEvaluator
#define arraytranslateAndTestX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define long2StringX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define bitOpMemX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define bitOpMemNDX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define arraycmpX86Evaluator TR::TreeEvaluator::arraycmpEvaluator
#define arraycmpWithPadX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define allocationFenceX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define loadFenceX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define storeFenceX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define fullFenceX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define MergeNewX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define computeCCX86Evaluator TR::TreeEvaluator::computeCCEvaluator
#define butestX86Evaluator TR::TreeEvaluator::butestEvaluator
#define sutestX86Evaluator TR::TreeEvaluator::sutestEvaluator
#define bucmpX86Evaluator TR::TreeEvaluator::bucmpEvaluator
#define bcmpX86Evaluator TR::TreeEvaluator::bcmpEvaluator
#define sucmpX86Evaluator TR::TreeEvaluator::sucmpEvaluator
#define scmpX86Evaluator TR::TreeEvaluator::scmpEvaluator
#define iucmpX86Evaluator TR::TreeEvaluator::iucmpEvaluator
#define icmpX86Evaluator TR::TreeEvaluator::icmpEvaluator
#define lucmpX86Evaluator TR::TreeEvaluator::lcmpEvaluator
#define ificmpoX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define ificmpnoX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define iflcmpoX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define iflcmpnoX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define ificmnoX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define ificmnnoX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define iflcmnoX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define iflcmnnoX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define iuaddcX86Evaluator TR::TreeEvaluator::integerAddEvaluator
#define luaddcX86Evaluator TR::TreeEvaluator::integerPairAddEvaluator
#define iusubbX86Evaluator TR::TreeEvaluator::integerSubEvaluator
#define lusubbX86Evaluator TR::TreeEvaluator::integerPairSubEvaluator
#define icmpsetX86Evaluator TR::TreeEvaluator::icmpsetEvaluator
#define lcmpsetX86Evaluator TR::TreeEvaluator::lcmpsetEvaluator
#define bztestnsetX86Evaluator TR::TreeEvaluator::bztestnsetEvaluator
#define ibatomicorX86Evaluator TR::TreeEvaluator::atomicorEvaluator
#define isatomicorX86Evaluator TR::TreeEvaluator::atomicorEvaluator
#define iiatomicorX86Evaluator TR::TreeEvaluator::atomicorEvaluator
#define ilatomicorX86Evaluator TR::TreeEvaluator::atomicorEvaluator
#define dexpX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define branchX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define igotoX86Evaluator TR::TreeEvaluator::igotoEvaluator
#define bexpX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define buexpX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define sexpX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define cexpX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iexpX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iuexpX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define lexpX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define luexpX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fexpX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fuexpX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define duexpX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define ixfrsX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define lxfrsX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fxfrsX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dxfrsX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fintX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dintX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fnintX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dnintX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fsqrtX86Evaluator TR::TreeEvaluator::fpSqrtEvaluator
#define dsqrtX86Evaluator TR::TreeEvaluator::fpSqrtEvaluator
#define getstackX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define deallocaX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define idozX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dcosX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dsinX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dtanX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dcoshX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dsinhX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dtanhX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dacosX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dasinX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define datanX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define datan2X86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dlogX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dfloorX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define ffloorX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dceilX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fceilX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define ibranchX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define mbranchX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define getpmX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define setpmX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define loadAutoOffsetX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define imaxX86Evaluator TR::TreeEvaluator::minmaxEvaluator
#define iumaxX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define lmaxX86Evaluator TR::TreeEvaluator::integerPairMinMaxEvaluator
#define lumaxX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fmaxX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dmaxX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iminX86Evaluator TR::TreeEvaluator::minmaxEvaluator
#define iuminX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define lminX86Evaluator TR::TreeEvaluator::integerPairMinMaxEvaluator
#define luminX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fminX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dminX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define trtX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define trtSimpleX86Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define ihbitX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define ilbitX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define inolzX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define inotzX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define ipopcntX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define lhbitX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define llbitX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define lnolzX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define lnotzX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define lpopcntX86Evaluator TR::TreeEvaluator::badILOpEvaluator
#define ibyteswapX86Evaluator TR::TreeEvaluator::ibyteswapEvaluator
#define bbitpermuteX86Evaluator TR::TreeEvaluator::bitpermuteEvaluator
#define sbitpermuteX86Evaluator TR::TreeEvaluator::bitpermuteEvaluator
#define ibitpermuteX86Evaluator TR::TreeEvaluator::bitpermuteEvaluator
#define lbitpermuteX86Evaluator TR::TreeEvaluator::bitpermuteEvaluator
#define PrefetchX86Evaluator TR::TreeEvaluator::PrefetchEvaluator


#include "il/OMROpcodes.hpp"

#define GENERATE_TREE_EVAL_TABLE(\
   opcode, \
   name, \
   prop1, \
   prop2, \
   prop3, \
   prop4, \
   dataType, \
   typeProps, \
   childProps, \
   swapChildrenOpcode, \
   reverseBranchOpcode, \
   boolCompareOpcode, \
   ifCompareOpcode, \
   enumValue, \
   ...) enumValue ## X86Evaluator,

   FOR_EACH_OPCODE(GENERATE_TREE_EVAL_TABLE)

#undef GENERATE_TREE_EVAL_TABLE
