/*******************************************************************************
 * Copyright (c) 2000, 2020 IBM Corp. and others
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which accompanies this
 * distribution and is available at http://eclipse.org/legal/epl-2.0
 * or the Apache License, Version 2.0 which accompanies this distribution
 * and is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License, v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception [1] and GNU General Public
 * License, version 2 with the OpenJDK Assembly Exception [2].
 *
 * [1] https://www.gnu.org/software/classpath/license.html
 * [2] http://openjdk.java.net/legal/assembly-exception.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
 *******************************************************************************/

/*
 * This table is #included in a static table.
 * Only Function Pointers are allowed.
 */


#define BadILOpEvaluator TR::TreeEvaluator::badILOpEvaluator
#define aconstEvaluator TR::TreeEvaluator::aconstEvaluator
#define iconstEvaluator TR::TreeEvaluator::iconstEvaluator
#define lconstEvaluator TR::TreeEvaluator::lconstEvaluator
#define fconstEvaluator TR::TreeEvaluator::fconstEvaluator
#define dconstEvaluator TR::TreeEvaluator::dconstEvaluator
#define bconstEvaluator TR::TreeEvaluator::bconstEvaluator
#define sconstEvaluator TR::TreeEvaluator::sconstEvaluator
#define iloadEvaluator TR::TreeEvaluator::iloadEvaluator
#define floadEvaluator TR::TreeEvaluator::floadEvaluator
#define dloadEvaluator TR::TreeEvaluator::dloadEvaluator
#define aloadEvaluator TR::TreeEvaluator::aloadEvaluator
#define bloadEvaluator TR::TreeEvaluator::bloadEvaluator
#define sloadEvaluator TR::TreeEvaluator::sloadEvaluator
#define lloadEvaluator TR::TreeEvaluator::lloadEvaluator
#define irdbarEvaluator TR::TreeEvaluator::irdbarEvaluator
#define frdbarEvaluator TR::TreeEvaluator::frdbarEvaluator
#define drdbarEvaluator TR::TreeEvaluator::drdbarEvaluator
#define ardbarEvaluator TR::TreeEvaluator::ardbarEvaluator
#define brdbarEvaluator TR::TreeEvaluator::brdbarEvaluator
#define srdbarEvaluator TR::TreeEvaluator::srdbarEvaluator
#define lrdbarEvaluator TR::TreeEvaluator::lrdbarEvaluator
#define iloadiEvaluator TR::TreeEvaluator::iloadEvaluator
#define floadiEvaluator TR::TreeEvaluator::floadEvaluator
#define dloadiEvaluator TR::TreeEvaluator::dloadEvaluator
#define aloadiEvaluator TR::TreeEvaluator::aloadEvaluator
#define bloadiEvaluator TR::TreeEvaluator::bloadEvaluator
#define sloadiEvaluator TR::TreeEvaluator::sloadEvaluator
#define lloadiEvaluator TR::TreeEvaluator::lloadEvaluator
#define irdbariEvaluator TR::TreeEvaluator::irdbariEvaluator
#define frdbariEvaluator TR::TreeEvaluator::frdbariEvaluator
#define drdbariEvaluator TR::TreeEvaluator::drdbariEvaluator
#define ardbariEvaluator TR::TreeEvaluator::ardbariEvaluator
#define brdbariEvaluator TR::TreeEvaluator::brdbariEvaluator
#define srdbariEvaluator TR::TreeEvaluator::srdbariEvaluator
#define lrdbariEvaluator TR::TreeEvaluator::lrdbariEvaluator
#define istoreEvaluator TR::TreeEvaluator::istoreEvaluator
#define lstoreEvaluator TR::TreeEvaluator::lstoreEvaluator
#define fstoreEvaluator TR::TreeEvaluator::floatingPointStoreEvaluator
#define dstoreEvaluator TR::TreeEvaluator::dstoreEvaluator
#define astoreEvaluator TR::TreeEvaluator::istoreEvaluator
#define bstoreEvaluator TR::TreeEvaluator::bstoreEvaluator
#define sstoreEvaluator TR::TreeEvaluator::sstoreEvaluator
#define iwrtbarEvaluator TR::TreeEvaluator::iwrtbarEvaluator
#define lwrtbarEvaluator TR::TreeEvaluator::lwrtbarEvaluator
#define fwrtbarEvaluator TR::TreeEvaluator::fwrtbarEvaluator
#define dwrtbarEvaluator TR::TreeEvaluator::dwrtbarEvaluator
#define awrtbarEvaluator TR::TreeEvaluator::awrtbarEvaluator
#define bwrtbarEvaluator TR::TreeEvaluator::bwrtbarEvaluator
#define swrtbarEvaluator TR::TreeEvaluator::swrtbarEvaluator
#define lstoreiEvaluator TR::TreeEvaluator::lstoreEvaluator
#define fstoreiEvaluator TR::TreeEvaluator::floatingPointStoreEvaluator
#define dstoreiEvaluator TR::TreeEvaluator::dstoreEvaluator
#define astoreiEvaluator TR::TreeEvaluator::istoreEvaluator
#define bstoreiEvaluator TR::TreeEvaluator::bstoreEvaluator
#define sstoreiEvaluator TR::TreeEvaluator::sstoreEvaluator
#define istoreiEvaluator TR::TreeEvaluator::istoreEvaluator
#define lwrtbariEvaluator TR::TreeEvaluator::lwrtbariEvaluator
#define fwrtbariEvaluator TR::TreeEvaluator::fwrtbariEvaluator
#define dwrtbariEvaluator TR::TreeEvaluator::dwrtbariEvaluator
#define awrtbariEvaluator TR::TreeEvaluator::awrtbariEvaluator
#define bwrtbariEvaluator TR::TreeEvaluator::bwrtbariEvaluator
#define swrtbariEvaluator TR::TreeEvaluator::swrtbariEvaluator
#define iwrtbariEvaluator TR::TreeEvaluator::iwrtbariEvaluator
#define GotoEvaluator TR::TreeEvaluator::gotoEvaluator
#define ireturnEvaluator TR::TreeEvaluator::integerReturnEvaluator
#define lreturnEvaluator TR::TreeEvaluator::integerPairReturnEvaluator
#define freturnEvaluator TR::TreeEvaluator::fpReturnEvaluator
#define dreturnEvaluator TR::TreeEvaluator::fpReturnEvaluator
#define areturnEvaluator TR::TreeEvaluator::integerReturnEvaluator
#define ReturnEvaluator TR::TreeEvaluator::returnEvaluator
#define asynccheckEvaluator TR::TreeEvaluator::badILOpEvaluator
#define athrowEvaluator TR::TreeEvaluator::badILOpEvaluator
#define icallEvaluator TR::TreeEvaluator::directCallEvaluator
#define lcallEvaluator TR::TreeEvaluator::directCallEvaluator
#define fcallEvaluator TR::TreeEvaluator::directCallEvaluator
#define dcallEvaluator TR::TreeEvaluator::directCallEvaluator
#define acallEvaluator TR::TreeEvaluator::directCallEvaluator
#define callEvaluator TR::TreeEvaluator::directCallEvaluator
#define iaddEvaluator TR::TreeEvaluator::integerAddEvaluator
#define laddEvaluator TR::TreeEvaluator::integerPairAddEvaluator
#define faddEvaluator TR::TreeEvaluator::faddEvaluator
#define daddEvaluator TR::TreeEvaluator::daddEvaluator
#define baddEvaluator TR::TreeEvaluator::baddEvaluator
#define saddEvaluator TR::TreeEvaluator::saddEvaluator
#define isubEvaluator TR::TreeEvaluator::integerSubEvaluator
#define lsubEvaluator TR::TreeEvaluator::integerPairSubEvaluator
#define fsubEvaluator TR::TreeEvaluator::fsubEvaluator
#define dsubEvaluator TR::TreeEvaluator::dsubEvaluator
#define bsubEvaluator TR::TreeEvaluator::bsubEvaluator
#define ssubEvaluator TR::TreeEvaluator::ssubEvaluator
#define asubEvaluator TR::TreeEvaluator::integerSubEvaluator
#define imulEvaluator TR::TreeEvaluator::integerMulEvaluator
#define lmulEvaluator TR::TreeEvaluator::integerPairMulEvaluator
#define fmulEvaluator TR::TreeEvaluator::fmulEvaluator
#define dmulEvaluator TR::TreeEvaluator::dmulEvaluator
#define bmulEvaluator TR::TreeEvaluator::integerMulEvaluator
#define smulEvaluator TR::TreeEvaluator::integerMulEvaluator
#define idivEvaluator TR::TreeEvaluator::integerDivOrRemEvaluator
#define ldivEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fdivEvaluator TR::TreeEvaluator::fdivEvaluator
#define ddivEvaluator TR::TreeEvaluator::ddivEvaluator
#define bdivEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define sdivEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iudivEvaluator TR::TreeEvaluator::integerDivOrRemEvaluator
#define ludivEvaluator TR::TreeEvaluator::badILOpEvaluator
#define iremEvaluator TR::TreeEvaluator::integerDivOrRemEvaluator
#define lremEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fremEvaluator TR::TreeEvaluator::fpRemEvaluator
#define dremEvaluator TR::TreeEvaluator::fpRemEvaluator
#define bremEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define sremEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iuremEvaluator TR::TreeEvaluator::integerDivOrRemEvaluator
#define inegEvaluator TR::TreeEvaluator::integerNegEvaluator
#define lnegEvaluator TR::TreeEvaluator::integerPairNegEvaluator
#define fnegEvaluator TR::TreeEvaluator::fpUnaryMaskEvaluator
#define dnegEvaluator TR::TreeEvaluator::fpUnaryMaskEvaluator
#define bnegEvaluator TR::TreeEvaluator::bnegEvaluator
#define snegEvaluator TR::TreeEvaluator::snegEvaluator
#define iabsEvaluator TR::TreeEvaluator::integerAbsEvaluator
#define labsEvaluator TR::TreeEvaluator::integerPairAbsEvaluator
#define fabsEvaluator TR::TreeEvaluator::fpUnaryMaskEvaluator
#define dabsEvaluator TR::TreeEvaluator::fpUnaryMaskEvaluator
#define ishlEvaluator TR::TreeEvaluator::integerShlEvaluator
#define lshlEvaluator TR::TreeEvaluator::integerPairShlEvaluator
#define bshlEvaluator TR::TreeEvaluator::bshlEvaluator
#define sshlEvaluator TR::TreeEvaluator::sshlEvaluator
#define ishrEvaluator TR::TreeEvaluator::integerShrEvaluator
#define lshrEvaluator TR::TreeEvaluator::integerPairShrEvaluator
#define bshrEvaluator TR::TreeEvaluator::bshrEvaluator
#define sshrEvaluator TR::TreeEvaluator::sshrEvaluator
#define iushrEvaluator TR::TreeEvaluator::integerUshrEvaluator
#define lushrEvaluator TR::TreeEvaluator::integerPairUshrEvaluator
#define bushrEvaluator TR::TreeEvaluator::bushrEvaluator
#define sushrEvaluator TR::TreeEvaluator::sushrEvaluator
#define irolEvaluator TR::TreeEvaluator::integerRolEvaluator
#define lrolEvaluator TR::TreeEvaluator::integerPairRolEvaluator
#define iandEvaluator TR::TreeEvaluator::iandEvaluator
#define landEvaluator TR::TreeEvaluator::landEvaluator
#define bandEvaluator TR::TreeEvaluator::bandEvaluator
#define sandEvaluator TR::TreeEvaluator::sandEvaluator
#define iorEvaluator TR::TreeEvaluator::iorEvaluator
#define lorEvaluator TR::TreeEvaluator::lorEvaluator
#define borEvaluator TR::TreeEvaluator::borEvaluator
#define sorEvaluator TR::TreeEvaluator::sorEvaluator
#define ixorEvaluator TR::TreeEvaluator::ixorEvaluator
#define lxorEvaluator TR::TreeEvaluator::lxorEvaluator
#define bxorEvaluator TR::TreeEvaluator::bxorEvaluator
#define sxorEvaluator TR::TreeEvaluator::sxorEvaluator
#define i2lEvaluator TR::TreeEvaluator::i2lEvaluator
#define i2fEvaluator TR::TreeEvaluator::i2fEvaluator
#define i2dEvaluator TR::TreeEvaluator::i2dEvaluator
#define i2bEvaluator TR::TreeEvaluator::i2bEvaluator
#define i2sEvaluator TR::TreeEvaluator::i2bEvaluator
#define i2aEvaluator TR::TreeEvaluator::i2aEvaluator
#define iu2lEvaluator TR::TreeEvaluator::iu2lEvaluator
#define iu2fEvaluator TR::TreeEvaluator::badILOpEvaluator
#define iu2dEvaluator TR::TreeEvaluator::badILOpEvaluator
#define iu2aEvaluator TR::TreeEvaluator::passThroughEvaluator
#define l2iEvaluator TR::TreeEvaluator::l2iEvaluator
#define l2fEvaluator TR::TreeEvaluator::l2fEvaluator
#define l2dEvaluator TR::TreeEvaluator::l2dEvaluator
#define l2bEvaluator TR::TreeEvaluator::l2iEvaluator
#define l2sEvaluator TR::TreeEvaluator::l2iEvaluator
#define l2aEvaluator TR::TreeEvaluator::badILOpEvaluator
#define lu2fEvaluator TR::TreeEvaluator::badILOpEvaluator
#define lu2dEvaluator TR::TreeEvaluator::badILOpEvaluator
#define lu2aEvaluator TR::TreeEvaluator::badILOpEvaluator
#define f2iEvaluator TR::TreeEvaluator::f2iEvaluator
#define f2lEvaluator TR::TreeEvaluator::f2lEvaluator
#define f2dEvaluator TR::TreeEvaluator::f2dEvaluator
#define f2bEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define f2sEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define d2iEvaluator TR::TreeEvaluator::f2iEvaluator
#define d2lEvaluator TR::TreeEvaluator::d2lEvaluator
#define d2fEvaluator TR::TreeEvaluator::d2fEvaluator
#define d2bEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define d2sEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define b2iEvaluator TR::TreeEvaluator::b2iEvaluator
#define b2lEvaluator TR::TreeEvaluator::b2lEvaluator
#define b2fEvaluator TR::TreeEvaluator::i2fEvaluator
#define b2dEvaluator TR::TreeEvaluator::i2dEvaluator
#define b2sEvaluator TR::TreeEvaluator::b2sEvaluator
#define b2aEvaluator TR::TreeEvaluator::badILOpEvaluator
#define bu2iEvaluator TR::TreeEvaluator::bu2iEvaluator
#define bu2lEvaluator TR::TreeEvaluator::bu2lEvaluator
#define bu2fEvaluator TR::TreeEvaluator::i2fEvaluator
#define bu2dEvaluator TR::TreeEvaluator::i2dEvaluator
#define bu2sEvaluator TR::TreeEvaluator::bu2sEvaluator
#define bu2aEvaluator TR::TreeEvaluator::badILOpEvaluator
#define s2iEvaluator TR::TreeEvaluator::s2iEvaluator
#define s2lEvaluator TR::TreeEvaluator::s2lEvaluator
#define s2fEvaluator TR::TreeEvaluator::i2fEvaluator
#define s2dEvaluator TR::TreeEvaluator::i2dEvaluator
#define s2bEvaluator TR::TreeEvaluator::i2bEvaluator
#define s2aEvaluator TR::TreeEvaluator::badILOpEvaluator
#define su2iEvaluator TR::TreeEvaluator::su2iEvaluator
#define su2lEvaluator TR::TreeEvaluator::su2lEvaluator
#define su2fEvaluator TR::TreeEvaluator::i2fEvaluator
#define su2dEvaluator TR::TreeEvaluator::i2dEvaluator
#define su2aEvaluator TR::TreeEvaluator::badILOpEvaluator
#define a2iEvaluator TR::TreeEvaluator::passThroughEvaluator
#define a2lEvaluator TR::TreeEvaluator::badILOpEvaluator
#define a2bEvaluator TR::TreeEvaluator::i2bEvaluator
#define a2sEvaluator TR::TreeEvaluator::i2bEvaluator
#define icmpeqEvaluator TR::TreeEvaluator::integerCmpeqEvaluator
#define icmpneEvaluator TR::TreeEvaluator::integerCmpneEvaluator
#define icmpltEvaluator TR::TreeEvaluator::integerCmpltEvaluator
#define icmpgeEvaluator TR::TreeEvaluator::integerCmpgeEvaluator
#define icmpgtEvaluator TR::TreeEvaluator::integerCmpgtEvaluator
#define icmpleEvaluator TR::TreeEvaluator::integerCmpleEvaluator
#define iucmpeqEvaluator TR::TreeEvaluator::integerCmpeqEvaluator
#define iucmpneEvaluator TR::TreeEvaluator::integerCmpneEvaluator
#define iucmpltEvaluator TR::TreeEvaluator::unsignedIntegerCmpltEvaluator
#define iucmpgeEvaluator TR::TreeEvaluator::unsignedIntegerCmpgeEvaluator
#define iucmpgtEvaluator TR::TreeEvaluator::unsignedIntegerCmpgtEvaluator
#define iucmpleEvaluator TR::TreeEvaluator::unsignedIntegerCmpleEvaluator
#define lcmpeqEvaluator TR::TreeEvaluator::lcmpeqEvaluator
#define lcmpneEvaluator TR::TreeEvaluator::lcmpneEvaluator
#define lcmpltEvaluator TR::TreeEvaluator::lcmpltEvaluator
#define lcmpgeEvaluator TR::TreeEvaluator::lcmpgeEvaluator
#define lcmpgtEvaluator TR::TreeEvaluator::lcmpgtEvaluator
#define lcmpleEvaluator TR::TreeEvaluator::lcmpleEvaluator
#define lucmpeqEvaluator TR::TreeEvaluator::lcmpeqEvaluator
#define lucmpneEvaluator TR::TreeEvaluator::lcmpneEvaluator
#define lucmpltEvaluator TR::TreeEvaluator::lucmpltEvaluator
#define lucmpgeEvaluator TR::TreeEvaluator::lucmpgeEvaluator
#define lucmpgtEvaluator TR::TreeEvaluator::lucmpgtEvaluator
#define lucmpleEvaluator TR::TreeEvaluator::lucmpleEvaluator
#define fcmpeqEvaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpneEvaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpltEvaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpgeEvaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpgtEvaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpleEvaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpequEvaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpneuEvaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpltuEvaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpgeuEvaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpgtuEvaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpleuEvaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define dcmpeqEvaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpneEvaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpltEvaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpgeEvaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpgtEvaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpleEvaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpequEvaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpneuEvaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpltuEvaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpgeuEvaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpgtuEvaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpleuEvaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define acmpeqEvaluator TR::TreeEvaluator::acmpeqEvaluator
#define acmpneEvaluator TR::TreeEvaluator::integerCmpneEvaluator
#define acmpltEvaluator TR::TreeEvaluator::unsignedIntegerCmpltEvaluator
#define acmpgeEvaluator TR::TreeEvaluator::unsignedIntegerCmpgeEvaluator
#define acmpgtEvaluator TR::TreeEvaluator::unsignedIntegerCmpgtEvaluator
#define acmpleEvaluator TR::TreeEvaluator::unsignedIntegerCmpleEvaluator
#define bcmpeqEvaluator TR::TreeEvaluator::bcmpeqEvaluator
#define bcmpneEvaluator TR::TreeEvaluator::bcmpeqEvaluator
#define bcmpltEvaluator TR::TreeEvaluator::bcmpltEvaluator
#define bcmpgeEvaluator TR::TreeEvaluator::bcmpgeEvaluator
#define bcmpgtEvaluator TR::TreeEvaluator::bcmpgtEvaluator
#define bcmpleEvaluator TR::TreeEvaluator::bcmpleEvaluator
#define bucmpeqEvaluator TR::TreeEvaluator::bcmpeqEvaluator
#define bucmpneEvaluator TR::TreeEvaluator::bcmpeqEvaluator
#define bucmpltEvaluator TR::TreeEvaluator::badILOpEvaluator
#define bucmpgeEvaluator TR::TreeEvaluator::badILOpEvaluator
#define bucmpgtEvaluator TR::TreeEvaluator::badILOpEvaluator
#define bucmpleEvaluator TR::TreeEvaluator::badILOpEvaluator
#define scmpeqEvaluator TR::TreeEvaluator::scmpeqEvaluator
#define scmpneEvaluator TR::TreeEvaluator::scmpeqEvaluator
#define scmpltEvaluator TR::TreeEvaluator::scmpltEvaluator
#define scmpgeEvaluator TR::TreeEvaluator::scmpgeEvaluator
#define scmpgtEvaluator TR::TreeEvaluator::scmpgtEvaluator
#define scmpleEvaluator TR::TreeEvaluator::scmpleEvaluator
#define sucmpeqEvaluator TR::TreeEvaluator::sucmpeqEvaluator
#define sucmpneEvaluator TR::TreeEvaluator::sucmpeqEvaluator
#define sucmpltEvaluator TR::TreeEvaluator::sucmpltEvaluator
#define sucmpgeEvaluator TR::TreeEvaluator::sucmpgeEvaluator
#define sucmpgtEvaluator TR::TreeEvaluator::sucmpgtEvaluator
#define sucmpleEvaluator TR::TreeEvaluator::sucmpleEvaluator
#define lcmpEvaluator TR::TreeEvaluator::lcmpEvaluator
#define fcmplEvaluator TR::TreeEvaluator::compareFloatEvaluator
#define fcmpgEvaluator TR::TreeEvaluator::compareFloatEvaluator
#define dcmplEvaluator TR::TreeEvaluator::compareDoubleEvaluator
#define dcmpgEvaluator TR::TreeEvaluator::compareDoubleEvaluator
#define ificmpeqEvaluator TR::TreeEvaluator::integerIfCmpeqEvaluator
#define ificmpneEvaluator TR::TreeEvaluator::integerIfCmpneEvaluator
#define ificmpltEvaluator TR::TreeEvaluator::integerIfCmpltEvaluator
#define ificmpgeEvaluator TR::TreeEvaluator::integerIfCmpgeEvaluator
#define ificmpgtEvaluator TR::TreeEvaluator::integerIfCmpgtEvaluator
#define ificmpleEvaluator TR::TreeEvaluator::integerIfCmpleEvaluator
#define ifiucmpeqEvaluator TR::TreeEvaluator::integerIfCmpeqEvaluator
#define ifiucmpneEvaluator TR::TreeEvaluator::integerIfCmpneEvaluator
#define ifiucmpltEvaluator TR::TreeEvaluator::unsignedIntegerIfCmpltEvaluator
#define ifiucmpgeEvaluator TR::TreeEvaluator::unsignedIntegerIfCmpgeEvaluator
#define ifiucmpgtEvaluator TR::TreeEvaluator::unsignedIntegerIfCmpgtEvaluator
#define ifiucmpleEvaluator TR::TreeEvaluator::unsignedIntegerIfCmpleEvaluator
#define iflcmpeqEvaluator TR::TreeEvaluator::iflcmpeqEvaluator
#define iflcmpneEvaluator TR::TreeEvaluator::iflcmpneEvaluator
#define iflcmpltEvaluator TR::TreeEvaluator::iflcmpltEvaluator
#define iflcmpgeEvaluator TR::TreeEvaluator::iflcmpgeEvaluator
#define iflcmpgtEvaluator TR::TreeEvaluator::iflcmpgtEvaluator
#define iflcmpleEvaluator TR::TreeEvaluator::iflcmpleEvaluator
#define iflucmpeqEvaluator TR::TreeEvaluator::iflcmpeqEvaluator
#define iflucmpneEvaluator TR::TreeEvaluator::iflcmpneEvaluator
#define iflucmpltEvaluator TR::TreeEvaluator::iflcmpltEvaluator
#define iflucmpgeEvaluator TR::TreeEvaluator::iflcmpgeEvaluator
#define iflucmpgtEvaluator TR::TreeEvaluator::iflcmpgtEvaluator
#define iflucmpleEvaluator TR::TreeEvaluator::iflcmpleEvaluator
#define iffcmpeqEvaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpneEvaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpltEvaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpgeEvaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpgtEvaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpleEvaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpequEvaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpneuEvaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpltuEvaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpgeuEvaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpgtuEvaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpleuEvaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define ifdcmpeqEvaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpneEvaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpltEvaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpgeEvaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpgtEvaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpleEvaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpequEvaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpneuEvaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpltuEvaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpgeuEvaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpgtuEvaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpleuEvaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifacmpeqEvaluator TR::TreeEvaluator::ifacmpeqEvaluator
#define ifacmpneEvaluator TR::TreeEvaluator::integerIfCmpneEvaluator
#define ifacmpltEvaluator TR::TreeEvaluator::unsignedIntegerIfCmpltEvaluator
#define ifacmpgeEvaluator TR::TreeEvaluator::unsignedIntegerIfCmpgeEvaluator
#define ifacmpgtEvaluator TR::TreeEvaluator::unsignedIntegerIfCmpgtEvaluator
#define ifacmpleEvaluator TR::TreeEvaluator::unsignedIntegerIfCmpleEvaluator
#define ifbcmpeqEvaluator TR::TreeEvaluator::ifbcmpeqEvaluator
#define ifbcmpneEvaluator TR::TreeEvaluator::ifbcmpeqEvaluator
#define ifbcmpltEvaluator TR::TreeEvaluator::ifbcmpltEvaluator
#define ifbcmpgeEvaluator TR::TreeEvaluator::ifbcmpgeEvaluator
#define ifbcmpgtEvaluator TR::TreeEvaluator::ifbcmpgtEvaluator
#define ifbcmpleEvaluator TR::TreeEvaluator::ifbcmpleEvaluator
#define ifbucmpeqEvaluator TR::TreeEvaluator::ifbcmpeqEvaluator
#define ifbucmpneEvaluator TR::TreeEvaluator::ifbcmpeqEvaluator
#define ifbucmpltEvaluator TR::TreeEvaluator::ifbucmpltEvaluator
#define ifbucmpgeEvaluator TR::TreeEvaluator::ifbucmpgeEvaluator
#define ifbucmpgtEvaluator TR::TreeEvaluator::ifbucmpgtEvaluator
#define ifbucmpleEvaluator TR::TreeEvaluator::ifbucmpleEvaluator
#define ifscmpeqEvaluator TR::TreeEvaluator::ifscmpeqEvaluator
#define ifscmpneEvaluator TR::TreeEvaluator::ifscmpeqEvaluator
#define ifscmpltEvaluator TR::TreeEvaluator::ifscmpltEvaluator
#define ifscmpgeEvaluator TR::TreeEvaluator::ifscmpgeEvaluator
#define ifscmpgtEvaluator TR::TreeEvaluator::ifscmpgtEvaluator
#define ifscmpleEvaluator TR::TreeEvaluator::ifscmpleEvaluator
#define ifsucmpeqEvaluator TR::TreeEvaluator::ifsucmpeqEvaluator
#define ifsucmpneEvaluator TR::TreeEvaluator::ifsucmpeqEvaluator
#define ifsucmpltEvaluator TR::TreeEvaluator::ifsucmpltEvaluator
#define ifsucmpgeEvaluator TR::TreeEvaluator::ifsucmpgeEvaluator
#define ifsucmpgtEvaluator TR::TreeEvaluator::ifsucmpgtEvaluator
#define ifsucmpleEvaluator TR::TreeEvaluator::ifsucmpleEvaluator
#define loadaddrEvaluator TR::TreeEvaluator::loadaddrEvaluator
#define ZEROCHKEvaluator TR::TreeEvaluator::badILOpEvaluator
#define callIfEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iRegLoadEvaluator TR::TreeEvaluator::integerRegLoadEvaluator
#define aRegLoadEvaluator TR::TreeEvaluator::aRegLoadEvaluator
#define lRegLoadEvaluator TR::TreeEvaluator::lRegLoadEvaluator
#define fRegLoadEvaluator TR::TreeEvaluator::fRegLoadEvaluator
#define dRegLoadEvaluator TR::TreeEvaluator::dRegLoadEvaluator
#define sRegLoadEvaluator TR::TreeEvaluator::integerRegLoadEvaluator
#define bRegLoadEvaluator TR::TreeEvaluator::integerRegLoadEvaluator
#define iRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define aRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define lRegStoreEvaluator TR::TreeEvaluator::lRegStoreEvaluator
#define fRegStoreEvaluator TR::TreeEvaluator::fRegStoreEvaluator
#define dRegStoreEvaluator TR::TreeEvaluator::dRegStoreEvaluator
#define sRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define bRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define GlRegDepsEvaluator TR::TreeEvaluator::GlRegDepsEvaluator
#define iselectEvaluator TR::TreeEvaluator::iselectEvaluator
#define lselectEvaluator TR::TreeEvaluator::lselectEvaluator
#define bselectEvaluator TR::TreeEvaluator::iselectEvaluator
#define sselectEvaluator TR::TreeEvaluator::iselectEvaluator
#define aselectEvaluator TR::TreeEvaluator::iselectEvaluator
#define fselectEvaluator TR::TreeEvaluator::badILOpEvaluator
#define dselectEvaluator TR::TreeEvaluator::badILOpEvaluator
#define treetopEvaluator TR::TreeEvaluator::treetopEvaluator
#define MethodEnterHookEvaluator TR::TreeEvaluator::badILOpEvaluator
#define MethodExitHookEvaluator TR::TreeEvaluator::badILOpEvaluator
#define PassThroughEvaluator TR::TreeEvaluator::passThroughEvaluator
#define compressedRefsEvaluator TR::TreeEvaluator::compressedRefsEvaluator
#define BBStartEvaluator TR::TreeEvaluator::BBStartEvaluator
#define BBEndEvaluator TR::TreeEvaluator::BBEndEvaluator
#define viremEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define viminEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vimaxEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vigetelemEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define visetelemEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vimergelEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vimergehEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpeqEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpalleqEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallneEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallgtEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallgeEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallltEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallleEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyeqEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyneEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanygtEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanygeEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyltEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyleEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vnotEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vbitselectEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vpermEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vsplatsEvaluator TR::TreeEvaluator::SIMDsplatsEvaluator
#define vdmergelEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdmergehEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdsetelemEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdgetelemEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdselEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdremEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdmaddEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdnmsubEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdmsubEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdmaxEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdminEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpeqEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpneEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpalleqEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallneEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallgtEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallgeEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallltEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallleEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyeqEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyneEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanygtEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanygeEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyltEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyleEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdsqrtEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdlogEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vincEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdecEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vnegEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcomEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vaddEvaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vsubEvaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vmulEvaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vdivEvaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vremEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vandEvaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vorEvaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vxorEvaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vshlEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vushrEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vshrEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpeqEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpneEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vucmpltEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vucmpgtEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vucmpleEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vucmpgeEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vloadEvaluator TR::TreeEvaluator::SIMDloadEvaluator
#define vloadiEvaluator TR::TreeEvaluator::SIMDloadEvaluator
#define vstoreEvaluator TR::TreeEvaluator::SIMDstoreEvaluator
#define vstoreiEvaluator TR::TreeEvaluator::SIMDstoreEvaluator
#define vrandEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vreturnEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcallEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcalliEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vselectEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define v2vEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vl2vdEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vconstEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define getvelemEvaluator TR::TreeEvaluator::SIMDgetvelemEvaluator
#define vsetelemEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define vbRegLoadEvaluator TR::TreeEvaluator::SIMDRegLoadEvaluator
#define vsRegLoadEvaluator TR::TreeEvaluator::SIMDRegLoadEvaluator
#define viRegLoadEvaluator TR::TreeEvaluator::SIMDRegLoadEvaluator
#define vlRegLoadEvaluator TR::TreeEvaluator::SIMDRegLoadEvaluator
#define vfRegLoadEvaluator TR::TreeEvaluator::SIMDRegLoadEvaluator
#define vdRegLoadEvaluator TR::TreeEvaluator::SIMDRegLoadEvaluator
#define vbRegStoreEvaluator TR::TreeEvaluator::SIMDRegStoreEvaluator
#define vsRegStoreEvaluator TR::TreeEvaluator::SIMDRegStoreEvaluator
#define viRegStoreEvaluator TR::TreeEvaluator::SIMDRegStoreEvaluator
#define vlRegStoreEvaluator TR::TreeEvaluator::SIMDRegStoreEvaluator
#define vfRegStoreEvaluator TR::TreeEvaluator::SIMDRegStoreEvaluator
#define vdRegStoreEvaluator TR::TreeEvaluator::SIMDRegStoreEvaluator
#define iuconstEvaluator TR::TreeEvaluator::iconstEvaluator
#define luconstEvaluator TR::TreeEvaluator::lconstEvaluator
#define buconstEvaluator TR::TreeEvaluator::bconstEvaluator
#define iuloadEvaluator TR::TreeEvaluator::iloadEvaluator
#define luloadEvaluator TR::TreeEvaluator::lloadEvaluator
#define buloadEvaluator TR::TreeEvaluator::bloadEvaluator
#define iuloadiEvaluator TR::TreeEvaluator::iloadEvaluator
#define luloadiEvaluator TR::TreeEvaluator::lloadEvaluator
#define buloadiEvaluator TR::TreeEvaluator::bloadEvaluator
#define iustoreEvaluator TR::TreeEvaluator::istoreEvaluator
#define lustoreEvaluator TR::TreeEvaluator::lstoreEvaluator
#define bustoreEvaluator TR::TreeEvaluator::bstoreEvaluator
#define iustoreiEvaluator TR::TreeEvaluator::istoreEvaluator
#define lustoreiEvaluator TR::TreeEvaluator::lstoreEvaluator
#define bustoreiEvaluator TR::TreeEvaluator::bstoreEvaluator
#define iureturnEvaluator TR::TreeEvaluator::integerReturnEvaluator
#define lureturnEvaluator TR::TreeEvaluator::integerPairReturnEvaluator
#define iucallEvaluator TR::TreeEvaluator::directCallEvaluator
#define lucallEvaluator TR::TreeEvaluator::directCallEvaluator
#define iuaddEvaluator TR::TreeEvaluator::integerAddEvaluator
#define luaddEvaluator TR::TreeEvaluator::integerPairAddEvaluator
#define buaddEvaluator TR::TreeEvaluator::baddEvaluator
#define iusubEvaluator TR::TreeEvaluator::integerSubEvaluator
#define lusubEvaluator TR::TreeEvaluator::integerPairSubEvaluator
#define busubEvaluator TR::TreeEvaluator::bsubEvaluator
#define iunegEvaluator TR::TreeEvaluator::integerNegEvaluator
#define lunegEvaluator TR::TreeEvaluator::integerPairNegEvaluator
#define f2iuEvaluator TR::TreeEvaluator::f2iEvaluator
#define f2luEvaluator TR::TreeEvaluator::f2lEvaluator
#define f2buEvaluator TR::TreeEvaluator::f2bEvaluator
#define f2cEvaluator TR::TreeEvaluator::f2cEvaluator
#define d2iuEvaluator TR::TreeEvaluator::f2iEvaluator
#define d2luEvaluator TR::TreeEvaluator::d2lEvaluator
#define d2buEvaluator TR::TreeEvaluator::d2bEvaluator
#define d2cEvaluator TR::TreeEvaluator::d2cEvaluator
#define iuRegLoadEvaluator TR::TreeEvaluator::integerRegLoadEvaluator
#define luRegLoadEvaluator TR::TreeEvaluator::lRegLoadEvaluator
#define iuRegStoreEvaluator TR::TreeEvaluator::iRegStoreEvaluator
#define luRegStoreEvaluator TR::TreeEvaluator::lRegStoreEvaluator
#define cconstEvaluator TR::TreeEvaluator::cconstEvaluator
#define cloadEvaluator TR::TreeEvaluator::sloadEvaluator
#define cloadiEvaluator TR::TreeEvaluator::sloadEvaluator
#define cstoreEvaluator TR::TreeEvaluator::cstoreEvaluator
#define cstoreiEvaluator TR::TreeEvaluator::cstoreEvaluator
#define monentEvaluator TR::TreeEvaluator::badILOpEvaluator
#define monexitEvaluator TR::TreeEvaluator::badILOpEvaluator
#define monexitfenceEvaluator TR::TreeEvaluator::badILOpEvaluator
#define tstartEvaluator TR::TreeEvaluator::tstartEvaluator
#define tfinishEvaluator TR::TreeEvaluator::tfinishEvaluator
#define tabortEvaluator TR::TreeEvaluator::tabortEvaluator
#define instanceofEvaluator TR::TreeEvaluator::badILOpEvaluator
#define checkcastEvaluator TR::TreeEvaluator::badILOpEvaluator
#define checkcastAndNULLCHKEvaluator TR::TreeEvaluator::badILOpEvaluator
#define NewEvaluator TR::TreeEvaluator::badILOpEvaluator
#define newvalueEvaluator TR::TreeEvaluator::badILOpEvaluator
#define newarrayEvaluator TR::TreeEvaluator::badILOpEvaluator
#define anewarrayEvaluator TR::TreeEvaluator::badILOpEvaluator
#define variableNewEvaluator TR::TreeEvaluator::badILOpEvaluator
#define variableNewArrayEvaluator TR::TreeEvaluator::badILOpEvaluator
#define multianewarrayEvaluator TR::TreeEvaluator::badILOpEvaluator
#define arraylengthEvaluator TR::TreeEvaluator::badILOpEvaluator
#define contigarraylengthEvaluator TR::TreeEvaluator::badILOpEvaluator
#define discontigarraylengthEvaluator TR::TreeEvaluator::badILOpEvaluator
#define icalliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define iucalliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define lcalliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define lucalliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define fcalliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define dcalliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define acalliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define calliEvaluator TR::TreeEvaluator::indirectCallEvaluator
#define fenceEvaluator TR::TreeEvaluator::fenceEvaluator
#define luaddhEvaluator TR::TreeEvaluator::badILOpEvaluator
#define caddEvaluator TR::TreeEvaluator::caddEvaluator
#define aiaddEvaluator TR::TreeEvaluator::integerAddEvaluator
#define aiuaddEvaluator TR::TreeEvaluator::integerAddEvaluator
#define aladdEvaluator TR::TreeEvaluator::badILOpEvaluator
#define aluaddEvaluator TR::TreeEvaluator::badILOpEvaluator
#define lusubhEvaluator TR::TreeEvaluator::badILOpEvaluator
#define csubEvaluator TR::TreeEvaluator::csubEvaluator
#define imulhEvaluator TR::TreeEvaluator::integerMulhEvaluator
#define iumulhEvaluator TR::TreeEvaluator::integerMulhEvaluator
#define lmulhEvaluator TR::TreeEvaluator::integerPairMulEvaluator
#define lumulhEvaluator TR::TreeEvaluator::integerPairMulEvaluator
#define ibits2fEvaluator TR::TreeEvaluator::ibits2fEvaluator
#define fbits2iEvaluator TR::TreeEvaluator::fbits2iEvaluator
#define lbits2dEvaluator TR::TreeEvaluator::lbits2dEvaluator
#define dbits2lEvaluator TR::TreeEvaluator::dbits2lEvaluator
#define lookupEvaluator TR::TreeEvaluator::lookupEvaluator
#define trtLookupEvaluator TR::TreeEvaluator::NOPEvaluator
#define CaseEvaluator TR::TreeEvaluator::NOPEvaluator
#define tableEvaluator TR::TreeEvaluator::tableEvaluator
#define exceptionRangeFenceEvaluator TR::TreeEvaluator::badILOpEvaluator
#define dbgFenceEvaluator TR::TreeEvaluator::badILOpEvaluator
#define NULLCHKEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ResolveCHKEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ResolveAndNULLCHKEvaluator TR::TreeEvaluator::badILOpEvaluator
#define DIVCHKEvaluator TR::TreeEvaluator::badILOpEvaluator
#define OverflowCHKEvaluator TR::TreeEvaluator::overflowCHKEvaluator
#define UnsignedOverflowCHKEvaluator TR::TreeEvaluator::overflowCHKEvaluator
#define BNDCHKEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ArrayCopyBNDCHKEvaluator TR::TreeEvaluator::badILOpEvaluator
#define BNDCHKwithSpineCHKEvaluator TR::TreeEvaluator::badILOpEvaluator
#define SpineCHKEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ArrayStoreCHKEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ArrayCHKEvaluator TR::TreeEvaluator::badILOpEvaluator
#define RetEvaluator TR::TreeEvaluator::badILOpEvaluator
#define arraycopyEvaluator TR::TreeEvaluator::arraycopyEvaluator
#define arraysetEvaluator TR::TreeEvaluator::arraysetEvaluator
#define arraytranslateEvaluator TR::TreeEvaluator::arraytranslateEvaluator
#define arraytranslateAndTestEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define long2StringEvaluator TR::TreeEvaluator::badILOpEvaluator
#define bitOpMemEvaluator TR::TreeEvaluator::badILOpEvaluator
#define bitOpMemNDEvaluator TR::TreeEvaluator::badILOpEvaluator
#define arraycmpEvaluator TR::TreeEvaluator::arraycmpEvaluator
#define arraycmpWithPadEvaluator TR::TreeEvaluator::badILOpEvaluator
#define allocationFenceEvaluator TR::TreeEvaluator::badILOpEvaluator
#define loadFenceEvaluator TR::TreeEvaluator::badILOpEvaluator
#define storeFenceEvaluator TR::TreeEvaluator::badILOpEvaluator
#define fullFenceEvaluator TR::TreeEvaluator::badILOpEvaluator
#define MergeNewEvaluator TR::TreeEvaluator::badILOpEvaluator
#define computeCCEvaluator TR::TreeEvaluator::computeCCEvaluator
#define butestEvaluator TR::TreeEvaluator::butestEvaluator
#define sutestEvaluator TR::TreeEvaluator::sutestEvaluator
#define bucmpEvaluator TR::TreeEvaluator::bucmpEvaluator
#define bcmpEvaluator TR::TreeEvaluator::bcmpEvaluator
#define sucmpEvaluator TR::TreeEvaluator::sucmpEvaluator
#define scmpEvaluator TR::TreeEvaluator::scmpEvaluator
#define iucmpEvaluator TR::TreeEvaluator::iucmpEvaluator
#define icmpEvaluator TR::TreeEvaluator::icmpEvaluator
#define lucmpEvaluator TR::TreeEvaluator::lcmpEvaluator
#define ificmpoEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ificmpnoEvaluator TR::TreeEvaluator::badILOpEvaluator
#define iflcmpoEvaluator TR::TreeEvaluator::badILOpEvaluator
#define iflcmpnoEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ificmnoEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ificmnnoEvaluator TR::TreeEvaluator::badILOpEvaluator
#define iflcmnoEvaluator TR::TreeEvaluator::badILOpEvaluator
#define iflcmnnoEvaluator TR::TreeEvaluator::badILOpEvaluator
#define iuaddcEvaluator TR::TreeEvaluator::integerAddEvaluator
#define luaddcEvaluator TR::TreeEvaluator::integerPairAddEvaluator
#define iusubbEvaluator TR::TreeEvaluator::integerSubEvaluator
#define lusubbEvaluator TR::TreeEvaluator::integerPairSubEvaluator
#define icmpsetEvaluator TR::TreeEvaluator::icmpsetEvaluator
#define lcmpsetEvaluator TR::TreeEvaluator::lcmpsetEvaluator
#define bztestnsetEvaluator TR::TreeEvaluator::bztestnsetEvaluator
#define ibatomicorEvaluator TR::TreeEvaluator::atomicorEvaluator
#define isatomicorEvaluator TR::TreeEvaluator::atomicorEvaluator
#define iiatomicorEvaluator TR::TreeEvaluator::atomicorEvaluator
#define ilatomicorEvaluator TR::TreeEvaluator::atomicorEvaluator
#define dexpEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define branchEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define igotoEvaluator TR::TreeEvaluator::igotoEvaluator
#define bexpEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define buexpEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define sexpEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define cexpEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iexpEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iuexpEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define lexpEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define luexpEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fexpEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fuexpEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define duexpEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define ixfrsEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define lxfrsEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fxfrsEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dxfrsEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fintEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dintEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fnintEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dnintEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fsqrtEvaluator TR::TreeEvaluator::fpSqrtEvaluator
#define dsqrtEvaluator TR::TreeEvaluator::fpSqrtEvaluator
#define getstackEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define deallocaEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define idozEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dcosEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dsinEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dtanEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dcoshEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dsinhEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dtanhEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dacosEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dasinEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define datanEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define datan2Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dlogEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dfloorEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define ffloorEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dceilEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fceilEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define ibranchEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define mbranchEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define getpmEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define setpmEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define loadAutoOffsetEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define imaxEvaluator TR::TreeEvaluator::minmaxEvaluator
#define iumaxEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define lmaxEvaluator TR::TreeEvaluator::integerPairMinMaxEvaluator
#define lumaxEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fmaxEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dmaxEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define iminEvaluator TR::TreeEvaluator::minmaxEvaluator
#define iuminEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define lminEvaluator TR::TreeEvaluator::integerPairMinMaxEvaluator
#define luminEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define fminEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define dminEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define trtEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define trtSimpleEvaluator TR::TreeEvaluator::unImpOpEvaluator
#define ihbitEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ilbitEvaluator TR::TreeEvaluator::badILOpEvaluator
#define inolzEvaluator TR::TreeEvaluator::badILOpEvaluator
#define inotzEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ipopcntEvaluator TR::TreeEvaluator::badILOpEvaluator
#define lhbitEvaluator TR::TreeEvaluator::badILOpEvaluator
#define llbitEvaluator TR::TreeEvaluator::badILOpEvaluator
#define lnolzEvaluator TR::TreeEvaluator::badILOpEvaluator
#define lnotzEvaluator TR::TreeEvaluator::badILOpEvaluator
#define lpopcntEvaluator TR::TreeEvaluator::badILOpEvaluator
#define ibyteswapEvaluator TR::TreeEvaluator::ibyteswapEvaluator
#define bbitpermuteEvaluator TR::TreeEvaluator::bitpermuteEvaluator
#define sbitpermuteEvaluator TR::TreeEvaluator::bitpermuteEvaluator
#define ibitpermuteEvaluator TR::TreeEvaluator::bitpermuteEvaluator
#define lbitpermuteEvaluator TR::TreeEvaluator::bitpermuteEvaluator
#define PrefetchEvaluator TR::TreeEvaluator::PrefetchEvaluator


#include "il/OMROpcodes.hpp"

#define GENERATE_TREE_EVAL_TABLE(\
   opcode, \
   name, \
   prop1, \
   prop2, \
   prop3, \
   prop4, \
   dataType, \
   typeProps, \
   childProps, \
   swapChildrenOpcode, \
   reverseBranchOpcode, \
   boolCompareOpcode, \
   ifCompareOpcode, \
   enumValue, \
   ...) enumValue ## Evaluator,

   FOR_EACH_OPCODE(GENERATE_TREE_EVAL_TABLE)

#undef GENERATE_TREE_EVAL_TABLE
