/*******************************************************************************
 * Copyright (c) 2000, 2020 IBM Corp. and others
 *
 * This program and the accompanying materials are made available under
 * the terms of the Eclipse Public License 2.0 which accompanies this
 * distribution and is available at http://eclipse.org/legal/epl-2.0
 * or the Apache License, Version 2.0 which accompanies this distribution
 * and is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License, v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception [1] and GNU General Public
 * License, version 2 with the OpenJDK Assembly Exception [2].
 *
 * [1] https://www.gnu.org/software/classpath/license.html
 * [2] http://openjdk.java.net/legal/assembly-exception.html
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0 OR GPL-2.0 WITH Classpath-exception-2.0 OR LicenseRef-GPL-2.0 WITH Assembly-exception
 *******************************************************************************/

/*
 * This table is #included in a static table.
 * Only Function Pointers are allowed.
 */

#define BadILOpAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define aconstAMD64Evaluator TR::TreeEvaluator::aconstEvaluator
#define iconstAMD64Evaluator TR::TreeEvaluator::iconstEvaluator
#define lconstAMD64Evaluator TR::TreeEvaluator::lconstEvaluator
#define fconstAMD64Evaluator TR::TreeEvaluator::fconstEvaluator
#define dconstAMD64Evaluator TR::TreeEvaluator::dconstEvaluator
#define bconstAMD64Evaluator TR::TreeEvaluator::bconstEvaluator
#define sconstAMD64Evaluator TR::TreeEvaluator::sconstEvaluator
#define iloadAMD64Evaluator TR::TreeEvaluator::iloadEvaluator
#define floadAMD64Evaluator TR::TreeEvaluator::floadEvaluator
#define dloadAMD64Evaluator TR::TreeEvaluator::dloadEvaluator
#define aloadAMD64Evaluator TR::TreeEvaluator::aloadEvaluator
#define bloadAMD64Evaluator TR::TreeEvaluator::bloadEvaluator
#define sloadAMD64Evaluator TR::TreeEvaluator::sloadEvaluator
#define lloadAMD64Evaluator TR::TreeEvaluator::lloadEvaluator
#define irdbarAMD64Evaluator TR::TreeEvaluator::irdbarEvaluator
#define frdbarAMD64Evaluator TR::TreeEvaluator::frdbarEvaluator
#define drdbarAMD64Evaluator TR::TreeEvaluator::drdbarEvaluator
#define ardbarAMD64Evaluator TR::TreeEvaluator::ardbarEvaluator
#define brdbarAMD64Evaluator TR::TreeEvaluator::brdbarEvaluator
#define srdbarAMD64Evaluator TR::TreeEvaluator::srdbarEvaluator
#define lrdbarAMD64Evaluator TR::TreeEvaluator::lrdbarEvaluator
#define iloadiAMD64Evaluator TR::TreeEvaluator::iloadEvaluator
#define floadiAMD64Evaluator TR::TreeEvaluator::floadEvaluator
#define dloadiAMD64Evaluator TR::TreeEvaluator::dloadEvaluator
#define aloadiAMD64Evaluator TR::TreeEvaluator::aloadEvaluator
#define bloadiAMD64Evaluator TR::TreeEvaluator::bloadEvaluator
#define sloadiAMD64Evaluator TR::TreeEvaluator::sloadEvaluator
#define lloadiAMD64Evaluator TR::TreeEvaluator::lloadEvaluator
#define irdbariAMD64Evaluator TR::TreeEvaluator::irdbariEvaluator
#define frdbariAMD64Evaluator TR::TreeEvaluator::frdbariEvaluator
#define drdbariAMD64Evaluator TR::TreeEvaluator::drdbariEvaluator
#define ardbariAMD64Evaluator TR::TreeEvaluator::ardbariEvaluator
#define brdbariAMD64Evaluator TR::TreeEvaluator::brdbariEvaluator
#define srdbariAMD64Evaluator TR::TreeEvaluator::srdbariEvaluator
#define lrdbariAMD64Evaluator TR::TreeEvaluator::lrdbariEvaluator
#define istoreAMD64Evaluator TR::TreeEvaluator::istoreEvaluator
#define lstoreAMD64Evaluator TR::TreeEvaluator::lstoreEvaluator
#define fstoreAMD64Evaluator TR::TreeEvaluator::floatingPointStoreEvaluator
#define dstoreAMD64Evaluator TR::TreeEvaluator::floatingPointStoreEvaluator
#define astoreAMD64Evaluator TR::TreeEvaluator::lstoreEvaluator
#define bstoreAMD64Evaluator TR::TreeEvaluator::bstoreEvaluator
#define sstoreAMD64Evaluator TR::TreeEvaluator::sstoreEvaluator
#define iwrtbarAMD64Evaluator TR::TreeEvaluator::iwrtbarEvaluator
#define lwrtbarAMD64Evaluator TR::TreeEvaluator::lwrtbarEvaluator
#define fwrtbarAMD64Evaluator TR::TreeEvaluator::fwrtbarEvaluator
#define dwrtbarAMD64Evaluator TR::TreeEvaluator::dwrtbarEvaluator
#define awrtbarAMD64Evaluator TR::TreeEvaluator::awrtbarEvaluator
#define bwrtbarAMD64Evaluator TR::TreeEvaluator::bwrtbarEvaluator
#define swrtbarAMD64Evaluator TR::TreeEvaluator::swrtbarEvaluator
#define lstoreiAMD64Evaluator TR::TreeEvaluator::lstoreEvaluator
#define fstoreiAMD64Evaluator TR::TreeEvaluator::floatingPointStoreEvaluator
#define dstoreiAMD64Evaluator TR::TreeEvaluator::floatingPointStoreEvaluator
#define astoreiAMD64Evaluator TR::TreeEvaluator::lstoreEvaluator
#define bstoreiAMD64Evaluator TR::TreeEvaluator::bstoreEvaluator
#define sstoreiAMD64Evaluator TR::TreeEvaluator::sstoreEvaluator
#define istoreiAMD64Evaluator TR::TreeEvaluator::istoreEvaluator
#define lwrtbariAMD64Evaluator TR::TreeEvaluator::lwrtbariEvaluator
#define fwrtbariAMD64Evaluator TR::TreeEvaluator::fwrtbariEvaluator
#define dwrtbariAMD64Evaluator TR::TreeEvaluator::dwrtbariEvaluator
#define awrtbariAMD64Evaluator TR::TreeEvaluator::awrtbariEvaluator
#define bwrtbariAMD64Evaluator TR::TreeEvaluator::bwrtbariEvaluator
#define swrtbariAMD64Evaluator TR::TreeEvaluator::swrtbariEvaluator
#define iwrtbariAMD64Evaluator TR::TreeEvaluator::iwrtbariEvaluator
#define GotoAMD64Evaluator TR::TreeEvaluator::gotoEvaluator
#define ireturnAMD64Evaluator TR::TreeEvaluator::integerReturnEvaluator
#define lreturnAMD64Evaluator TR::TreeEvaluator::integerReturnEvaluator
#define freturnAMD64Evaluator TR::TreeEvaluator::fpReturnEvaluator
#define dreturnAMD64Evaluator TR::TreeEvaluator::fpReturnEvaluator
#define areturnAMD64Evaluator TR::TreeEvaluator::integerReturnEvaluator
#define ReturnAMD64Evaluator TR::TreeEvaluator::returnEvaluator
#define asynccheckAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define athrowAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define icallAMD64Evaluator TR::TreeEvaluator::directCallEvaluator
#define lcallAMD64Evaluator TR::TreeEvaluator::directCallEvaluator
#define fcallAMD64Evaluator TR::TreeEvaluator::directCallEvaluator
#define dcallAMD64Evaluator TR::TreeEvaluator::directCallEvaluator
#define acallAMD64Evaluator TR::TreeEvaluator::directCallEvaluator
#define callAMD64Evaluator TR::TreeEvaluator::directCallEvaluator
#define iaddAMD64Evaluator TR::TreeEvaluator::integerAddEvaluator
#define laddAMD64Evaluator TR::TreeEvaluator::integerAddEvaluator
#define faddAMD64Evaluator TR::TreeEvaluator::faddEvaluator
#define daddAMD64Evaluator TR::TreeEvaluator::daddEvaluator
#define baddAMD64Evaluator TR::TreeEvaluator::baddEvaluator
#define saddAMD64Evaluator TR::TreeEvaluator::saddEvaluator
#define isubAMD64Evaluator TR::TreeEvaluator::integerSubEvaluator
#define lsubAMD64Evaluator TR::TreeEvaluator::integerSubEvaluator
#define fsubAMD64Evaluator TR::TreeEvaluator::fsubEvaluator
#define dsubAMD64Evaluator TR::TreeEvaluator::dsubEvaluator
#define bsubAMD64Evaluator TR::TreeEvaluator::bsubEvaluator
#define ssubAMD64Evaluator TR::TreeEvaluator::ssubEvaluator
#define asubAMD64Evaluator TR::TreeEvaluator::integerSubEvaluator
#define imulAMD64Evaluator TR::TreeEvaluator::integerMulEvaluator
#define lmulAMD64Evaluator TR::TreeEvaluator::integerMulEvaluator
#define fmulAMD64Evaluator TR::TreeEvaluator::fmulEvaluator
#define dmulAMD64Evaluator TR::TreeEvaluator::dmulEvaluator
#define bmulAMD64Evaluator TR::TreeEvaluator::integerMulEvaluator
#define smulAMD64Evaluator TR::TreeEvaluator::integerMulEvaluator
#define idivAMD64Evaluator TR::TreeEvaluator::integerDivOrRemEvaluator
#define ldivAMD64Evaluator TR::TreeEvaluator::integerDivOrRemEvaluator
#define fdivAMD64Evaluator TR::TreeEvaluator::fdivEvaluator
#define ddivAMD64Evaluator TR::TreeEvaluator::ddivEvaluator
#define bdivAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define sdivAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iudivAMD64Evaluator TR::TreeEvaluator::integerDivOrRemEvaluator
#define ludivAMD64Evaluator TR::TreeEvaluator::integerDivOrRemEvaluator
#define iremAMD64Evaluator TR::TreeEvaluator::integerDivOrRemEvaluator
#define lremAMD64Evaluator TR::TreeEvaluator::integerDivOrRemEvaluator
#define fremAMD64Evaluator TR::TreeEvaluator::fpRemEvaluator
#define dremAMD64Evaluator TR::TreeEvaluator::fpRemEvaluator
#define bremAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define sremAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iuremAMD64Evaluator TR::TreeEvaluator::integerDivOrRemEvaluator
#define inegAMD64Evaluator TR::TreeEvaluator::integerNegEvaluator
#define lnegAMD64Evaluator TR::TreeEvaluator::integerNegEvaluator
#define fnegAMD64Evaluator TR::TreeEvaluator::fpUnaryMaskEvaluator
#define dnegAMD64Evaluator TR::TreeEvaluator::fpUnaryMaskEvaluator
#define bnegAMD64Evaluator TR::TreeEvaluator::bnegEvaluator
#define snegAMD64Evaluator TR::TreeEvaluator::snegEvaluator
#define iabsAMD64Evaluator TR::TreeEvaluator::integerAbsEvaluator
#define labsAMD64Evaluator TR::TreeEvaluator::integerAbsEvaluator
#define fabsAMD64Evaluator TR::TreeEvaluator::fpUnaryMaskEvaluator
#define dabsAMD64Evaluator TR::TreeEvaluator::fpUnaryMaskEvaluator
#define ishlAMD64Evaluator TR::TreeEvaluator::integerShlEvaluator
#define lshlAMD64Evaluator TR::TreeEvaluator::integerShlEvaluator
#define bshlAMD64Evaluator TR::TreeEvaluator::bshlEvaluator
#define sshlAMD64Evaluator TR::TreeEvaluator::sshlEvaluator
#define ishrAMD64Evaluator TR::TreeEvaluator::integerShrEvaluator
#define lshrAMD64Evaluator TR::TreeEvaluator::integerShrEvaluator
#define bshrAMD64Evaluator TR::TreeEvaluator::bshrEvaluator
#define sshrAMD64Evaluator TR::TreeEvaluator::sshrEvaluator
#define iushrAMD64Evaluator TR::TreeEvaluator::integerUshrEvaluator
#define lushrAMD64Evaluator TR::TreeEvaluator::integerUshrEvaluator
#define bushrAMD64Evaluator TR::TreeEvaluator::bushrEvaluator
#define sushrAMD64Evaluator TR::TreeEvaluator::sushrEvaluator
#define irolAMD64Evaluator TR::TreeEvaluator::integerRolEvaluator
#define lrolAMD64Evaluator TR::TreeEvaluator::integerRolEvaluator
#define iandAMD64Evaluator TR::TreeEvaluator::iandEvaluator
#define landAMD64Evaluator TR::TreeEvaluator::landEvaluator
#define bandAMD64Evaluator TR::TreeEvaluator::bandEvaluator
#define sandAMD64Evaluator TR::TreeEvaluator::sandEvaluator
#define iorAMD64Evaluator TR::TreeEvaluator::iorEvaluator
#define lorAMD64Evaluator TR::TreeEvaluator::lorEvaluator
#define borAMD64Evaluator TR::TreeEvaluator::borEvaluator
#define sorAMD64Evaluator TR::TreeEvaluator::sorEvaluator
#define ixorAMD64Evaluator TR::TreeEvaluator::ixorEvaluator
#define lxorAMD64Evaluator TR::TreeEvaluator::lxorEvaluator
#define bxorAMD64Evaluator TR::TreeEvaluator::bxorEvaluator
#define sxorAMD64Evaluator TR::TreeEvaluator::sxorEvaluator
#define i2lAMD64Evaluator TR::TreeEvaluator::i2lEvaluator
#define i2fAMD64Evaluator TR::TreeEvaluator::i2fEvaluator
#define i2dAMD64Evaluator TR::TreeEvaluator::i2dEvaluator
#define i2bAMD64Evaluator TR::TreeEvaluator::i2bEvaluator
#define i2sAMD64Evaluator TR::TreeEvaluator::i2bEvaluator
#define i2aAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define iu2lAMD64Evaluator TR::TreeEvaluator::iu2lEvaluator
#define iu2fAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define iu2dAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define iu2aAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define l2iAMD64Evaluator TR::TreeEvaluator::l2iEvaluator
#define l2fAMD64Evaluator TR::TreeEvaluator::l2fEvaluator
#define l2dAMD64Evaluator TR::TreeEvaluator::l2dEvaluator
#define l2bAMD64Evaluator TR::TreeEvaluator::l2iEvaluator
#define l2sAMD64Evaluator TR::TreeEvaluator::l2iEvaluator
#define l2aAMD64Evaluator TR::TreeEvaluator::l2aEvaluator
#define lu2fAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define lu2dAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define lu2aAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define f2iAMD64Evaluator TR::TreeEvaluator::f2iEvaluator
#define f2lAMD64Evaluator TR::TreeEvaluator::f2iEvaluator
#define f2dAMD64Evaluator TR::TreeEvaluator::f2dEvaluator
#define f2bAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define f2sAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define d2iAMD64Evaluator TR::TreeEvaluator::f2iEvaluator
#define d2lAMD64Evaluator TR::TreeEvaluator::f2iEvaluator
#define d2fAMD64Evaluator TR::TreeEvaluator::d2fEvaluator
#define d2bAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define d2sAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define b2iAMD64Evaluator TR::TreeEvaluator::b2iEvaluator
#define b2lAMD64Evaluator TR::TreeEvaluator::b2lEvaluator
#define b2fAMD64Evaluator TR::TreeEvaluator::i2fEvaluator
#define b2dAMD64Evaluator TR::TreeEvaluator::i2dEvaluator
#define b2sAMD64Evaluator TR::TreeEvaluator::b2sEvaluator
#define b2aAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define bu2iAMD64Evaluator TR::TreeEvaluator::bu2iEvaluator
#define bu2lAMD64Evaluator TR::TreeEvaluator::bu2lEvaluator
#define bu2fAMD64Evaluator TR::TreeEvaluator::i2fEvaluator
#define bu2dAMD64Evaluator TR::TreeEvaluator::i2dEvaluator
#define bu2sAMD64Evaluator TR::TreeEvaluator::bu2sEvaluator
#define bu2aAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define s2iAMD64Evaluator TR::TreeEvaluator::s2iEvaluator
#define s2lAMD64Evaluator TR::TreeEvaluator::s2lEvaluator
#define s2fAMD64Evaluator TR::TreeEvaluator::i2fEvaluator
#define s2dAMD64Evaluator TR::TreeEvaluator::i2dEvaluator
#define s2bAMD64Evaluator TR::TreeEvaluator::i2bEvaluator
#define s2aAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define su2iAMD64Evaluator TR::TreeEvaluator::su2iEvaluator
#define su2lAMD64Evaluator TR::TreeEvaluator::su2lEvaluator
#define su2fAMD64Evaluator TR::TreeEvaluator::i2fEvaluator
#define su2dAMD64Evaluator TR::TreeEvaluator::i2dEvaluator
#define su2aAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define a2iAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define a2lAMD64Evaluator TR::TreeEvaluator::a2lEvaluator
#define a2bAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define a2sAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define icmpeqAMD64Evaluator TR::TreeEvaluator::integerCmpeqEvaluator
#define icmpneAMD64Evaluator TR::TreeEvaluator::integerCmpneEvaluator
#define icmpltAMD64Evaluator TR::TreeEvaluator::integerCmpltEvaluator
#define icmpgeAMD64Evaluator TR::TreeEvaluator::integerCmpgeEvaluator
#define icmpgtAMD64Evaluator TR::TreeEvaluator::integerCmpgtEvaluator
#define icmpleAMD64Evaluator TR::TreeEvaluator::integerCmpleEvaluator
#define iucmpltAMD64Evaluator TR::TreeEvaluator::unsignedIntegerCmpltEvaluator
#define iucmpgeAMD64Evaluator TR::TreeEvaluator::unsignedIntegerCmpgeEvaluator
#define iucmpgtAMD64Evaluator TR::TreeEvaluator::unsignedIntegerCmpgtEvaluator
#define iucmpleAMD64Evaluator TR::TreeEvaluator::unsignedIntegerCmpleEvaluator
#define lcmpeqAMD64Evaluator TR::TreeEvaluator::integerCmpeqEvaluator
#define lcmpneAMD64Evaluator TR::TreeEvaluator::integerCmpneEvaluator
#define lcmpltAMD64Evaluator TR::TreeEvaluator::integerCmpltEvaluator
#define lcmpgeAMD64Evaluator TR::TreeEvaluator::integerCmpgeEvaluator
#define lcmpgtAMD64Evaluator TR::TreeEvaluator::integerCmpgtEvaluator
#define lcmpleAMD64Evaluator TR::TreeEvaluator::integerCmpleEvaluator
#define lucmpltAMD64Evaluator TR::TreeEvaluator::unsignedIntegerCmpltEvaluator
#define lucmpgeAMD64Evaluator TR::TreeEvaluator::unsignedIntegerCmpgeEvaluator
#define lucmpgtAMD64Evaluator TR::TreeEvaluator::unsignedIntegerCmpgtEvaluator
#define lucmpleAMD64Evaluator TR::TreeEvaluator::unsignedIntegerCmpleEvaluator
#define fcmpeqAMD64Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpneAMD64Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpltAMD64Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpgeAMD64Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpgtAMD64Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpleAMD64Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpequAMD64Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpneuAMD64Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpltuAMD64Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpgeuAMD64Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpgtuAMD64Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define fcmpleuAMD64Evaluator TR::TreeEvaluator::compareFloatAndSetEvaluator
#define dcmpeqAMD64Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpneAMD64Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpltAMD64Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpgeAMD64Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpgtAMD64Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpleAMD64Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpequAMD64Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpneuAMD64Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpltuAMD64Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpgeuAMD64Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpgtuAMD64Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define dcmpleuAMD64Evaluator TR::TreeEvaluator::compareDoubleAndSetEvaluator
#define acmpeqAMD64Evaluator TR::TreeEvaluator::integerCmpeqEvaluator
#define acmpneAMD64Evaluator TR::TreeEvaluator::integerCmpneEvaluator
#define acmpltAMD64Evaluator TR::TreeEvaluator::unsignedIntegerCmpltEvaluator
#define acmpgeAMD64Evaluator TR::TreeEvaluator::unsignedIntegerCmpgeEvaluator
#define acmpgtAMD64Evaluator TR::TreeEvaluator::unsignedIntegerCmpgtEvaluator
#define acmpleAMD64Evaluator TR::TreeEvaluator::unsignedIntegerCmpleEvaluator
#define bcmpeqAMD64Evaluator TR::TreeEvaluator::bcmpeqEvaluator
#define bcmpneAMD64Evaluator TR::TreeEvaluator::bcmpeqEvaluator
#define bcmpltAMD64Evaluator TR::TreeEvaluator::bcmpltEvaluator
#define bcmpgeAMD64Evaluator TR::TreeEvaluator::bcmpgeEvaluator
#define bcmpgtAMD64Evaluator TR::TreeEvaluator::bcmpgtEvaluator
#define bcmpleAMD64Evaluator TR::TreeEvaluator::bcmpleEvaluator
#define bucmpltAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define bucmpgeAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define bucmpgtAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define bucmpleAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define scmpeqAMD64Evaluator TR::TreeEvaluator::scmpeqEvaluator
#define scmpneAMD64Evaluator TR::TreeEvaluator::scmpeqEvaluator
#define scmpltAMD64Evaluator TR::TreeEvaluator::scmpltEvaluator
#define scmpgeAMD64Evaluator TR::TreeEvaluator::scmpgeEvaluator
#define scmpgtAMD64Evaluator TR::TreeEvaluator::scmpgtEvaluator
#define scmpleAMD64Evaluator TR::TreeEvaluator::scmpleEvaluator
#define sucmpltAMD64Evaluator TR::TreeEvaluator::sucmpltEvaluator
#define sucmpgeAMD64Evaluator TR::TreeEvaluator::sucmpgeEvaluator
#define sucmpgtAMD64Evaluator TR::TreeEvaluator::sucmpgtEvaluator
#define sucmpleAMD64Evaluator TR::TreeEvaluator::sucmpleEvaluator
#define lcmpAMD64Evaluator TR::TreeEvaluator::lcmpEvaluator
#define fcmplAMD64Evaluator TR::TreeEvaluator::compareFloatEvaluator
#define fcmpgAMD64Evaluator TR::TreeEvaluator::compareFloatEvaluator
#define dcmplAMD64Evaluator TR::TreeEvaluator::compareDoubleEvaluator
#define dcmpgAMD64Evaluator TR::TreeEvaluator::compareDoubleEvaluator
#define ificmpeqAMD64Evaluator TR::TreeEvaluator::integerIfCmpeqEvaluator
#define ificmpneAMD64Evaluator TR::TreeEvaluator::integerIfCmpneEvaluator
#define ificmpltAMD64Evaluator TR::TreeEvaluator::integerIfCmpltEvaluator
#define ificmpgeAMD64Evaluator TR::TreeEvaluator::integerIfCmpgeEvaluator
#define ificmpgtAMD64Evaluator TR::TreeEvaluator::integerIfCmpgtEvaluator
#define ificmpleAMD64Evaluator TR::TreeEvaluator::integerIfCmpleEvaluator
#define ifiucmpltAMD64Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpltEvaluator
#define ifiucmpgeAMD64Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpgeEvaluator
#define ifiucmpgtAMD64Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpgtEvaluator
#define ifiucmpleAMD64Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpleEvaluator
#define iflcmpeqAMD64Evaluator TR::TreeEvaluator::integerIfCmpeqEvaluator
#define iflcmpneAMD64Evaluator TR::TreeEvaluator::integerIfCmpneEvaluator
#define iflcmpltAMD64Evaluator TR::TreeEvaluator::integerIfCmpltEvaluator
#define iflcmpgeAMD64Evaluator TR::TreeEvaluator::integerIfCmpgeEvaluator
#define iflcmpgtAMD64Evaluator TR::TreeEvaluator::integerIfCmpgtEvaluator
#define iflcmpleAMD64Evaluator TR::TreeEvaluator::integerIfCmpleEvaluator
#define iflucmpltAMD64Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpltEvaluator
#define iflucmpgeAMD64Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpgeEvaluator
#define iflucmpgtAMD64Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpgtEvaluator
#define iflucmpleAMD64Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpleEvaluator
#define iffcmpeqAMD64Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpneAMD64Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpltAMD64Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpgeAMD64Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpgtAMD64Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpleAMD64Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpequAMD64Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpneuAMD64Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpltuAMD64Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpgeuAMD64Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpgtuAMD64Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define iffcmpleuAMD64Evaluator TR::TreeEvaluator::compareFloatAndBranchEvaluator
#define ifdcmpeqAMD64Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpneAMD64Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpltAMD64Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpgeAMD64Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpgtAMD64Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpleAMD64Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpequAMD64Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpneuAMD64Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpltuAMD64Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpgeuAMD64Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpgtuAMD64Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifdcmpleuAMD64Evaluator TR::TreeEvaluator::compareDoubleAndBranchEvaluator
#define ifacmpeqAMD64Evaluator TR::TreeEvaluator::integerIfCmpeqEvaluator
#define ifacmpneAMD64Evaluator TR::TreeEvaluator::integerIfCmpneEvaluator
#define ifacmpltAMD64Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpltEvaluator
#define ifacmpgeAMD64Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpgeEvaluator
#define ifacmpgtAMD64Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpgtEvaluator
#define ifacmpleAMD64Evaluator TR::TreeEvaluator::unsignedIntegerIfCmpleEvaluator
#define ifbcmpeqAMD64Evaluator TR::TreeEvaluator::ifbcmpeqEvaluator
#define ifbcmpneAMD64Evaluator TR::TreeEvaluator::ifbcmpeqEvaluator
#define ifbcmpltAMD64Evaluator TR::TreeEvaluator::ifbcmpltEvaluator
#define ifbcmpgeAMD64Evaluator TR::TreeEvaluator::ifbcmpgeEvaluator
#define ifbcmpgtAMD64Evaluator TR::TreeEvaluator::ifbcmpgtEvaluator
#define ifbcmpleAMD64Evaluator TR::TreeEvaluator::ifbcmpleEvaluator
#define ifbucmpltAMD64Evaluator TR::TreeEvaluator::ifbucmpltEvaluator
#define ifbucmpgeAMD64Evaluator TR::TreeEvaluator::ifbucmpgeEvaluator
#define ifbucmpgtAMD64Evaluator TR::TreeEvaluator::ifbucmpgtEvaluator
#define ifbucmpleAMD64Evaluator TR::TreeEvaluator::ifbucmpleEvaluator
#define ifscmpeqAMD64Evaluator TR::TreeEvaluator::ifscmpeqEvaluator
#define ifscmpneAMD64Evaluator TR::TreeEvaluator::ifscmpeqEvaluator
#define ifscmpltAMD64Evaluator TR::TreeEvaluator::ifscmpltEvaluator
#define ifscmpgeAMD64Evaluator TR::TreeEvaluator::ifscmpgeEvaluator
#define ifscmpgtAMD64Evaluator TR::TreeEvaluator::ifscmpgtEvaluator
#define ifscmpleAMD64Evaluator TR::TreeEvaluator::ifscmpleEvaluator
#define ifsucmpltAMD64Evaluator TR::TreeEvaluator::ifsucmpltEvaluator
#define ifsucmpgeAMD64Evaluator TR::TreeEvaluator::ifsucmpgeEvaluator
#define ifsucmpgtAMD64Evaluator TR::TreeEvaluator::ifsucmpgtEvaluator
#define ifsucmpleAMD64Evaluator TR::TreeEvaluator::ifsucmpleEvaluator
#define loadaddrAMD64Evaluator TR::TreeEvaluator::loadaddrEvaluator
#define ZEROCHKAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define callIfAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iRegLoadAMD64Evaluator TR::TreeEvaluator::integerRegLoadEvaluator
#define aRegLoadAMD64Evaluator TR::TreeEvaluator::aRegLoadEvaluator
#define lRegLoadAMD64Evaluator TR::TreeEvaluator::integerRegLoadEvaluator
#define fRegLoadAMD64Evaluator TR::TreeEvaluator::fRegLoadEvaluator
#define dRegLoadAMD64Evaluator TR::TreeEvaluator::dRegLoadEvaluator
#define sRegLoadAMD64Evaluator TR::TreeEvaluator::integerRegLoadEvaluator
#define bRegLoadAMD64Evaluator TR::TreeEvaluator::integerRegLoadEvaluator
#define iRegStoreAMD64Evaluator TR::TreeEvaluator::iRegStoreEvaluator
#define aRegStoreAMD64Evaluator TR::TreeEvaluator::iRegStoreEvaluator
#define lRegStoreAMD64Evaluator TR::TreeEvaluator::lRegStoreEvaluator
#define fRegStoreAMD64Evaluator TR::TreeEvaluator::fRegStoreEvaluator
#define dRegStoreAMD64Evaluator TR::TreeEvaluator::dRegStoreEvaluator
#define sRegStoreAMD64Evaluator TR::TreeEvaluator::iRegStoreEvaluator
#define bRegStoreAMD64Evaluator TR::TreeEvaluator::iRegStoreEvaluator
#define GlRegDepsAMD64Evaluator TR::TreeEvaluator::GlRegDepsEvaluator
#define iselectAMD64Evaluator TR::TreeEvaluator::iselectEvaluator
#define lselectAMD64Evaluator TR::TreeEvaluator::iselectEvaluator
#define bselectAMD64Evaluator TR::TreeEvaluator::iselectEvaluator
#define sselectAMD64Evaluator TR::TreeEvaluator::iselectEvaluator
#define aselectAMD64Evaluator TR::TreeEvaluator::iselectEvaluator
#define fselectAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define dselectAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define treetopAMD64Evaluator TR::TreeEvaluator::treetopEvaluator
#define MethodEnterHookAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define MethodExitHookAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define PassThroughAMD64Evaluator TR::TreeEvaluator::passThroughEvaluator
#define compressedRefsAMD64Evaluator TR::TreeEvaluator::compressedRefsEvaluator
#define BBStartAMD64Evaluator TR::TreeEvaluator::BBStartEvaluator
#define BBEndAMD64Evaluator TR::TreeEvaluator::BBEndEvaluator
#define viremAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define viminAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vimaxAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vigetelemAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define visetelemAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vimergelAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vimergehAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpeqAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpgtAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpgeAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpltAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpleAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpalleqAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallneAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallgtAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallgeAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallltAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpallleAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyeqAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyneAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanygtAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanygeAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyltAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vicmpanyleAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vnotAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vbitselectAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vpermAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vsplatsAMD64Evaluator TR::TreeEvaluator::SIMDsplatsEvaluator
#define vdmergelAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdmergehAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdsetelemAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdgetelemAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdselAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdremAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdmaddAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdnmsubAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdmsubAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdmaxAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdminAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpeqAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpneAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpgtAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpgeAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpltAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpleAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpalleqAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallneAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallgtAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallgeAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallltAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpallleAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyeqAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyneAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanygtAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanygeAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyltAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdcmpanyleAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdsqrtAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdlogAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vincAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vdecAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vnegAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcomAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vaddAMD64Evaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vsubAMD64Evaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vmulAMD64Evaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vdivAMD64Evaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vremAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vandAMD64Evaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vorAMD64Evaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vxorAMD64Evaluator TR::TreeEvaluator::FloatingPointAndVectorBinaryArithmeticEvaluator
#define vshlAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vushrAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vshrAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpeqAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpneAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpltAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vucmpltAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpgtAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vucmpgtAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpleAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vucmpleAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcmpgeAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vucmpgeAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vloadAMD64Evaluator TR::TreeEvaluator::SIMDloadEvaluator
#define vloadiAMD64Evaluator TR::TreeEvaluator::SIMDloadEvaluator
#define vstoreAMD64Evaluator TR::TreeEvaluator::SIMDstoreEvaluator
#define vstoreiAMD64Evaluator TR::TreeEvaluator::SIMDstoreEvaluator
#define vrandAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vreturnAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcallAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vcalliAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vselectAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define v2vAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vl2vdAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vconstAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define getvelemAMD64Evaluator TR::TreeEvaluator::SIMDgetvelemEvaluator
#define vsetelemAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define vbRegLoadAMD64Evaluator TR::TreeEvaluator::SIMDRegLoadEvaluator
#define vsRegLoadAMD64Evaluator TR::TreeEvaluator::SIMDRegLoadEvaluator
#define viRegLoadAMD64Evaluator TR::TreeEvaluator::SIMDRegLoadEvaluator
#define vlRegLoadAMD64Evaluator TR::TreeEvaluator::SIMDRegLoadEvaluator
#define vfRegLoadAMD64Evaluator TR::TreeEvaluator::SIMDRegLoadEvaluator
#define vdRegLoadAMD64Evaluator TR::TreeEvaluator::SIMDRegLoadEvaluator
#define vbRegStoreAMD64Evaluator TR::TreeEvaluator::SIMDRegStoreEvaluator
#define vsRegStoreAMD64Evaluator TR::TreeEvaluator::SIMDRegStoreEvaluator
#define viRegStoreAMD64Evaluator TR::TreeEvaluator::SIMDRegStoreEvaluator
#define vlRegStoreAMD64Evaluator TR::TreeEvaluator::SIMDRegStoreEvaluator
#define vfRegStoreAMD64Evaluator TR::TreeEvaluator::SIMDRegStoreEvaluator
#define vdRegStoreAMD64Evaluator TR::TreeEvaluator::SIMDRegStoreEvaluator
#define iuloadAMD64Evaluator TR::TreeEvaluator::iloadEvaluator
#define luloadAMD64Evaluator TR::TreeEvaluator::lloadEvaluator
#define buloadAMD64Evaluator TR::TreeEvaluator::bloadEvaluator
#define iuloadiAMD64Evaluator TR::TreeEvaluator::iloadEvaluator
#define luloadiAMD64Evaluator TR::TreeEvaluator::lloadEvaluator
#define buloadiAMD64Evaluator TR::TreeEvaluator::bloadEvaluator
#define iustoreAMD64Evaluator TR::TreeEvaluator::istoreEvaluator
#define lustoreAMD64Evaluator TR::TreeEvaluator::lstoreEvaluator
#define bustoreAMD64Evaluator TR::TreeEvaluator::bstoreEvaluator
#define iustoreiAMD64Evaluator TR::TreeEvaluator::istoreEvaluator
#define lustoreiAMD64Evaluator TR::TreeEvaluator::lstoreEvaluator
#define bustoreiAMD64Evaluator TR::TreeEvaluator::bstoreEvaluator
#define iuaddAMD64Evaluator TR::TreeEvaluator::integerAddEvaluator
#define luaddAMD64Evaluator TR::TreeEvaluator::integerAddEvaluator
#define buaddAMD64Evaluator TR::TreeEvaluator::baddEvaluator
#define iusubAMD64Evaluator TR::TreeEvaluator::integerSubEvaluator
#define lusubAMD64Evaluator TR::TreeEvaluator::integerSubEvaluator
#define busubAMD64Evaluator TR::TreeEvaluator::bsubEvaluator
#define iunegAMD64Evaluator TR::TreeEvaluator::integerNegEvaluator
#define lunegAMD64Evaluator TR::TreeEvaluator::integerNegEvaluator
#define f2iuAMD64Evaluator TR::TreeEvaluator::f2iEvaluator
#define f2luAMD64Evaluator TR::TreeEvaluator::f2iEvaluator
#define f2buAMD64Evaluator TR::TreeEvaluator::f2bEvaluator
#define f2cAMD64Evaluator TR::TreeEvaluator::f2cEvaluator
#define d2iuAMD64Evaluator TR::TreeEvaluator::f2iEvaluator
#define d2luAMD64Evaluator TR::TreeEvaluator::f2iEvaluator
#define d2buAMD64Evaluator TR::TreeEvaluator::d2bEvaluator
#define d2cAMD64Evaluator TR::TreeEvaluator::d2cEvaluator
#define iuRegLoadAMD64Evaluator TR::TreeEvaluator::integerRegLoadEvaluator
#define luRegLoadAMD64Evaluator TR::TreeEvaluator::integerRegLoadEvaluator
#define iuRegStoreAMD64Evaluator TR::TreeEvaluator::iRegStoreEvaluator
#define luRegStoreAMD64Evaluator TR::TreeEvaluator::lRegStoreEvaluator
#define cloadAMD64Evaluator TR::TreeEvaluator::sloadEvaluator
#define cloadiAMD64Evaluator TR::TreeEvaluator::sloadEvaluator
#define cstoreAMD64Evaluator TR::TreeEvaluator::cstoreEvaluator
#define cstoreiAMD64Evaluator TR::TreeEvaluator::cstoreEvaluator
#define monentAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define monexitAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define monexitfenceAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define tstartAMD64Evaluator TR::TreeEvaluator::tstartEvaluator
#define tfinishAMD64Evaluator TR::TreeEvaluator::tfinishEvaluator
#define tabortAMD64Evaluator TR::TreeEvaluator::tabortEvaluator
#define instanceofAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define checkcastAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define checkcastAndNULLCHKAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define NewAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define newvalueAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define newarrayAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define anewarrayAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define variableNewAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define variableNewArrayAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define multianewarrayAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define arraylengthAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define contigarraylengthAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define discontigarraylengthAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define icalliAMD64Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define lcalliAMD64Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define fcalliAMD64Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define dcalliAMD64Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define acalliAMD64Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define calliAMD64Evaluator TR::TreeEvaluator::indirectCallEvaluator
#define fenceAMD64Evaluator TR::TreeEvaluator::fenceEvaluator
#define luaddhAMD64Evaluator TR::TreeEvaluator::integerAddEvaluator
#define caddAMD64Evaluator TR::TreeEvaluator::caddEvaluator
#define aiaddAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define aiuaddAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define aladdAMD64Evaluator TR::TreeEvaluator::integerAddEvaluator
#define aluaddAMD64Evaluator TR::TreeEvaluator::integerAddEvaluator
#define lusubhAMD64Evaluator TR::TreeEvaluator::integerSubEvaluator
#define csubAMD64Evaluator TR::TreeEvaluator::csubEvaluator
#define imulhAMD64Evaluator TR::TreeEvaluator::integerMulhEvaluator
#define iumulhAMD64Evaluator TR::TreeEvaluator::integerMulhEvaluator
#define lmulhAMD64Evaluator TR::TreeEvaluator::integerMulhEvaluator
#define lumulhAMD64Evaluator TR::TreeEvaluator::integerMulhEvaluator
#define ibits2fAMD64Evaluator TR::TreeEvaluator::ibits2fEvaluator
#define fbits2iAMD64Evaluator TR::TreeEvaluator::fbits2iEvaluator
#define lbits2dAMD64Evaluator TR::TreeEvaluator::lbits2dEvaluator
#define dbits2lAMD64Evaluator TR::TreeEvaluator::dbits2lEvaluator
#define lookupAMD64Evaluator TR::TreeEvaluator::lookupEvaluator
#define trtLookupAMD64Evaluator TR::TreeEvaluator::NOPEvaluator
#define CaseAMD64Evaluator TR::TreeEvaluator::NOPEvaluator
#define tableAMD64Evaluator TR::TreeEvaluator::tableEvaluator
#define exceptionRangeFenceAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define dbgFenceAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define NULLCHKAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define ResolveCHKAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define ResolveAndNULLCHKAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define DIVCHKAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define OverflowCHKAMD64Evaluator TR::TreeEvaluator::overflowCHKEvaluator
#define UnsignedOverflowCHKAMD64Evaluator TR::TreeEvaluator::overflowCHKEvaluator
#define BNDCHKAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define ArrayCopyBNDCHKAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define BNDCHKwithSpineCHKAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define SpineCHKAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define ArrayStoreCHKAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define ArrayCHKAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define RetAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define arraycopyAMD64Evaluator TR::TreeEvaluator::arraycopyEvaluator
#define arraysetAMD64Evaluator TR::TreeEvaluator::arraysetEvaluator
#define arraytranslateAMD64Evaluator TR::TreeEvaluator::arraytranslateEvaluator
#define arraytranslateAndTestAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define long2StringAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define bitOpMemAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define bitOpMemNDAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define arraycmpAMD64Evaluator TR::TreeEvaluator::arraycmpEvaluator
#define arraycmpWithPadAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define allocationFenceAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define loadFenceAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define storeFenceAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define fullFenceAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define MergeNewAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define computeCCAMD64Evaluator TR::TreeEvaluator::computeCCEvaluator
#define butestAMD64Evaluator TR::TreeEvaluator::butestEvaluator
#define sutestAMD64Evaluator TR::TreeEvaluator::sutestEvaluator
#define bucmpAMD64Evaluator TR::TreeEvaluator::bucmpEvaluator
#define bcmpAMD64Evaluator TR::TreeEvaluator::bcmpEvaluator
#define sucmpAMD64Evaluator TR::TreeEvaluator::sucmpEvaluator
#define scmpAMD64Evaluator TR::TreeEvaluator::scmpEvaluator
#define iucmpAMD64Evaluator TR::TreeEvaluator::iucmpEvaluator
#define icmpAMD64Evaluator TR::TreeEvaluator::icmpEvaluator
#define lucmpAMD64Evaluator TR::TreeEvaluator::iucmpEvaluator
#define ificmpoAMD64Evaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define ificmpnoAMD64Evaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define iflcmpoAMD64Evaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define iflcmpnoAMD64Evaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define ificmnoAMD64Evaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define ificmnnoAMD64Evaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define iflcmnoAMD64Evaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define iflcmnnoAMD64Evaluator TR::TreeEvaluator::ifxcmpoEvaluator
#define iuaddcAMD64Evaluator TR::TreeEvaluator::integerAddEvaluator
#define luaddcAMD64Evaluator TR::TreeEvaluator::integerAddEvaluator
#define iusubbAMD64Evaluator TR::TreeEvaluator::integerSubEvaluator
#define lusubbAMD64Evaluator TR::TreeEvaluator::integerSubEvaluator
#define icmpsetAMD64Evaluator TR::TreeEvaluator::icmpsetEvaluator
#define lcmpsetAMD64Evaluator TR::TreeEvaluator::icmpsetEvaluator
#define bztestnsetAMD64Evaluator TR::TreeEvaluator::bztestnsetEvaluator
#define ibatomicorAMD64Evaluator TR::TreeEvaluator::atomicorEvaluator
#define isatomicorAMD64Evaluator TR::TreeEvaluator::atomicorEvaluator
#define iiatomicorAMD64Evaluator TR::TreeEvaluator::atomicorEvaluator
#define ilatomicorAMD64Evaluator TR::TreeEvaluator::atomicorEvaluator
#define dexpAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define branchAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define igotoAMD64Evaluator TR::TreeEvaluator::igotoEvaluator
#define bexpAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define buexpAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define sexpAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define cexpAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iexpAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iuexpAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define lexpAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define luexpAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fexpAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fuexpAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define duexpAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define ixfrsAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define lxfrsAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fxfrsAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dxfrsAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fintAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dintAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fnintAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dnintAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fsqrtAMD64Evaluator TR::TreeEvaluator::fpSqrtEvaluator
#define dsqrtAMD64Evaluator TR::TreeEvaluator::dsqrtEvaluator
#define getstackAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define deallocaAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define idozAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dcosAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dsinAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dtanAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dcoshAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dsinhAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dtanhAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dacosAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dasinAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define datanAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define datan2AMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dlogAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dfloorAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define ffloorAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dceilAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fceilAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define ibranchAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define mbranchAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define getpmAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define setpmAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define loadAutoOffsetAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define imaxAMD64Evaluator TR::TreeEvaluator::minmaxEvaluator
#define iumaxAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define lmaxAMD64Evaluator TR::TreeEvaluator::minmaxEvaluator
#define lumaxAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fmaxAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dmaxAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define iminAMD64Evaluator TR::TreeEvaluator::minmaxEvaluator
#define iuminAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define lminAMD64Evaluator TR::TreeEvaluator::minmaxEvaluator
#define luminAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define fminAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define dminAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define trtAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define trtSimpleAMD64Evaluator TR::TreeEvaluator::unImpOpEvaluator
#define ihbitAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define ilbitAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define inolzAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define inotzAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define ipopcntAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define lhbitAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define llbitAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define lnolzAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define lnotzAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define lpopcntAMD64Evaluator TR::TreeEvaluator::badILOpEvaluator
#define sbyteswapAMD64Evaluator TR::TreeEvaluator::sbyteswapEvaluator
#define ibyteswapAMD64Evaluator TR::TreeEvaluator::ibyteswapEvaluator
#define lbyteswapAMD64Evaluator TR::TreeEvaluator::ibyteswapEvaluator
#define bbitpermuteAMD64Evaluator TR::TreeEvaluator::bitpermuteEvaluator
#define sbitpermuteAMD64Evaluator TR::TreeEvaluator::bitpermuteEvaluator
#define ibitpermuteAMD64Evaluator TR::TreeEvaluator::bitpermuteEvaluator
#define lbitpermuteAMD64Evaluator TR::TreeEvaluator::bitpermuteEvaluator
#define PrefetchAMD64Evaluator TR::TreeEvaluator::PrefetchEvaluator


#include "il/OMROpcodes.hpp"

#define GENERATE_TREE_EVAL_TABLE(\
   opcode, \
   name, \
   prop1, \
   prop2, \
   prop3, \
   prop4, \
   dataType, \
   typeProps, \
   childProps, \
   swapChildrenOpcode, \
   reverseBranchOpcode, \
   boolCompareOpcode, \
   ifCompareOpcode, \
   enumValue, \
   ...) enumValue ## AMD64Evaluator,

   BadILOpAMD64Evaluator,
   FOR_EACH_OPCODE(GENERATE_TREE_EVAL_TABLE)

#undef GENERATE_TREE_EVAL_TABLE
